package com.cardif.satelite.callcenter.dao;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import com.cardif.satelite.model.AuditRegistroVehicular;

/*usuario_ modificacion: lmaron
 * fecha: 16/02/2014
 * Consulta: SELECT_AUDIT_VEHICULAR el registro id de la tabla de auditoria 
 * */
public interface AuditRegistroVehicularMapper {

  final String SELECT_PK = "SELECT * FROM dbo.AUDIT_REGISTRO_VEHICULAR WHERE ID_REGISTRO = #{idRegistro}";

  final String SELECT_AUDIT_VEHICULAR = "select distinct(id_registro)  from AUDIT_REGISTRO_VEHICULAR " + "where ID_REGISTRO=#{placa} and NOMBRE_TABLA='DIRECCION_PROPIETARIO_VEHICULO'";

  @Select(SELECT_AUDIT_VEHICULAR)
  @ResultMap(value = "BaseResultMap")
  AuditRegistroVehicular selectAudit(@Param("placa") String placa);

  @Select(SELECT_PK)
  @ResultMap(value = "BaseResultMap")
  AuditRegistroVehicular selectPK(@Param("idRegistro") String idRegistro);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.AUDIT_REGISTRO_VEHICULAR
   *
   * @mbggenerated Tue Feb 11 17:38:04 COT 2014
   */
  int insert(AuditRegistroVehicular record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.AUDIT_REGISTRO_VEHICULAR
   *
   * @mbggenerated Tue Feb 11 17:38:04 COT 2014
   */
  int updateByPrimaryKey(AuditRegistroVehicular record);
}