package com.cardif.satelite.cobranza.dao;

import java.util.ArrayList;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import com.cardif.satelite.model.AuditCobranza;
import com.cardif.satelite.model.AuditCobranzaExample;

public interface AuditCobranzaMapper {

  final String SELECT_AUDIT = "select TOP 30 * from dbo.AUDIT_COBRANZA " + "WHERE TIP_PROCESO = #{tipProceso} " + "AND VIA_COBRO = #{viaCobro} " + "order by FEC_EJECUCION DESC";

  @Select(SELECT_AUDIT)
  @ResultMap("BaseResultMap")
  ArrayList<AuditCobranza> consultar(@Param("tipProceso") String tipProceso, @Param("viaCobro") String viaCobro);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.AUDIT_COBRANZA
   *
   * @mbggenerated Mon Sep 16 12:09:54 COT 2013
   */
  int countByExample(AuditCobranzaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.AUDIT_COBRANZA
   *
   * @mbggenerated Mon Sep 16 12:09:54 COT 2013
   */
  int deleteByExample(AuditCobranzaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.AUDIT_COBRANZA
   *
   * @mbggenerated Mon Sep 16 12:09:54 COT 2013
   */
  int deleteByPrimaryKey(Long pk);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.AUDIT_COBRANZA
   *
   * @mbggenerated Mon Sep 16 12:09:54 COT 2013
   */
  int insert(AuditCobranza record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.AUDIT_COBRANZA
   *
   * @mbggenerated Mon Sep 16 12:09:54 COT 2013
   */
  int insertSelective(AuditCobranza record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.AUDIT_COBRANZA
   *
   * @mbggenerated Mon Sep 16 12:09:54 COT 2013
   */
  List<AuditCobranza> selectByExample(AuditCobranzaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.AUDIT_COBRANZA
   *
   * @mbggenerated Mon Sep 16 12:09:54 COT 2013
   */
  AuditCobranza selectByPrimaryKey(Long pk);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.AUDIT_COBRANZA
   *
   * @mbggenerated Mon Sep 16 12:09:54 COT 2013
   */
  int updateByExampleSelective(@Param("record") AuditCobranza record, @Param("example") AuditCobranzaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.AUDIT_COBRANZA
   *
   * @mbggenerated Mon Sep 16 12:09:54 COT 2013
   */
  int updateByExample(@Param("record") AuditCobranza record, @Param("example") AuditCobranzaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.AUDIT_COBRANZA
   *
   * @mbggenerated Mon Sep 16 12:09:54 COT 2013
   */
  int updateByPrimaryKeySelective(AuditCobranza record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.AUDIT_COBRANZA
   *
   * @mbggenerated Mon Sep 16 12:09:54 COT 2013
   */
  int updateByPrimaryKey(AuditCobranza record);
}