package com.cardif.satelite.cobranza.dao;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import com.cardif.satelite.cobranza.bean.ConsultaProceso;
import com.cardif.satelite.model.Proceso;
import com.cardif.satelite.model.ProcesoExample;

public interface ProcesoMapper {

  final String SELECT_PROCESOS = "select * from dbo.DATA_FLOW_TASK WHERE " + "datediff(mm,AUDIT_EXECUTION_START_TIME,getdate()) <= 6 AND "
      + "( AUDIT_PACKAGE_NAME='Banco CENCOSUD Envio - FW v1 0' OR AUDIT_PACKAGE_NAME='Banco CENCOSUD Respuesta - FW v1 0' ) " + "order by AUDIT_EXECUTION_START_TIME DESC";

  @Select(SELECT_PROCESOS)
  @ResultMap("ConsultaProceso")
  ArrayList<ConsultaProceso> consultar();

  ArrayList<ConsultaProceso> selectByFilter(Map<String, Object> mapa);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   * 
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  int countByExample(ProcesoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   * 
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  int deleteByExample(ProcesoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   * 
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  int deleteByPrimaryKey(Long processNumber);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   * 
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  int insert(Proceso record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   * 
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  int insertSelective(Proceso record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   * 
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  List<Proceso> selectByExample(ProcesoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   * 
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  Proceso selectByPrimaryKey(Long processNumber);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   * 
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  int updateByExampleSelective(@Param("record") Proceso record, @Param("example") ProcesoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   * 
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  int updateByExample(@Param("record") Proceso record, @Param("example") ProcesoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   * 
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  int updateByPrimaryKeySelective(Proceso record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   * 
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  int updateByPrimaryKey(Proceso record);
}