//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.13 at 04:28:19 PM COT 
//

package com.cardif.sunsystems.mapeo.impresionCheques;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="User">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SunSystemsContext">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BusinessUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BudgetCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Payload">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Ledger">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Line" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="LinkReference3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="TransactionAmount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="TransactionDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="TransactionReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "user", "sunSystemsContext", "payload" })
@XmlRootElement(name = "SSC")
public class SSC {

  @XmlElement(name = "User", required = true)
  protected SSC.User user;
  @XmlElement(name = "SunSystemsContext", required = true)
  protected SSC.SunSystemsContext sunSystemsContext;
  @XmlElement(name = "Payload", required = true)
  protected SSC.Payload payload;

  /**
   * Gets the value of the user property.
   * 
   * @return possible object is {@link SSC.User }
   * 
   */
  public SSC.User getUser() {
    return user;
  }

  /**
   * Sets the value of the user property.
   * 
   * @param value
   *          allowed object is {@link SSC.User }
   * 
   */
  public void setUser(SSC.User value) {
    this.user = value;
  }

  /**
   * Gets the value of the sunSystemsContext property.
   * 
   * @return possible object is {@link SSC.SunSystemsContext }
   * 
   */
  public SSC.SunSystemsContext getSunSystemsContext() {
    return sunSystemsContext;
  }

  /**
   * Sets the value of the sunSystemsContext property.
   * 
   * @param value
   *          allowed object is {@link SSC.SunSystemsContext }
   * 
   */
  public void setSunSystemsContext(SSC.SunSystemsContext value) {
    this.sunSystemsContext = value;
  }

  /**
   * Gets the value of the payload property.
   * 
   * @return possible object is {@link SSC.Payload }
   * 
   */
  public SSC.Payload getPayload() {
    return payload;
  }

  /**
   * Sets the value of the payload property.
   * 
   * @param value
   *          allowed object is {@link SSC.Payload }
   * 
   */
  public void setPayload(SSC.Payload value) {
    this.payload = value;
  }

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="Ledger">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                 &lt;sequence>
   *                   &lt;element name="Line" maxOccurs="unbounded">
   *                     &lt;complexType>
   *                       &lt;complexContent>
   *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                           &lt;sequence>
   *                             &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="LinkReference3" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="TransactionAmount" type="{http://www.w3.org/2001/XMLSchema}double"/>
   *                             &lt;element name="TransactionDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="TransactionReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                           &lt;/sequence>
   *                         &lt;/restriction>
   *                       &lt;/complexContent>
   *                     &lt;/complexType>
   *                   &lt;/element>
   *                 &lt;/sequence>
   *               &lt;/restriction>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "ledger" })
  public static class Payload {

    @XmlElement(name = "Ledger", required = true)
    protected SSC.Payload.Ledger ledger;

    /**
     * Gets the value of the ledger property.
     * 
     * @return possible object is {@link SSC.Payload.Ledger }
     * 
     */
    public SSC.Payload.Ledger getLedger() {
      return ledger;
    }

    /**
     * Sets the value of the ledger property.
     * 
     * @param value
     *          allowed object is {@link SSC.Payload.Ledger }
     * 
     */
    public void setLedger(SSC.Payload.Ledger value) {
      this.ledger = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Line" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="LinkReference3" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="TransactionAmount" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="TransactionDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="TransactionReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "line" })
    public static class Ledger {

      @XmlElement(name = "Line", required = true)
      protected List<SSC.Payload.Ledger.Line> line;

      /**
       * Gets the value of the line property.
       * 
       * <p>
       * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
       * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the line property.
       * 
       * <p>
       * For example, to add a new item, do as follows:
       * 
       * <pre>
       * getLine().add(newItem);
       * </pre>
       * 
       * 
       * <p>
       * Objects of the following type(s) are allowed in the list {@link SSC.Payload.Ledger.Line }
       * 
       * 
       */
      public List<SSC.Payload.Ledger.Line> getLine() {
        if (line == null) {
          line = new ArrayList<SSC.Payload.Ledger.Line>();
        }
        return this.line;
      }

      /**
       * <p>
       * Java class for anonymous complex type.
       * 
       * <p>
       * The following schema fragment specifies the expected content contained within this class.
       * 
       * <pre>
       * &lt;complexType>
       *   &lt;complexContent>
       *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *       &lt;sequence>
       *         &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="LinkReference3" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="TransactionAmount" type="{http://www.w3.org/2001/XMLSchema}double"/>
       *         &lt;element name="TransactionDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="TransactionReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *       &lt;/sequence>
       *     &lt;/restriction>
       *   &lt;/complexContent>
       * &lt;/complexType>
       * </pre>
       * 
       * 
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "", propOrder = { "currencyCode", "description", "linkReference3", "transactionAmount", "transactionDate", "transactionReference", "journalNumber", "journalLineNumber" })
      public static class Line {

        @XmlElement(name = "CurrencyCode", required = true)
        protected String currencyCode;
        @XmlElement(name = "Description", required = true)
        protected String description;
        @XmlElement(name = "LinkReference3", required = true)
        protected String linkReference3;
        @XmlElement(name = "TransactionAmount")
        protected double transactionAmount;
        @XmlElement(name = "TransactionDate", required = true)
        protected String transactionDate;
        @XmlElement(name = "TransactionReference", required = true)
        protected String transactionReference;
        @XmlElement(name = "JournalNumber", required = true)
        protected int journalNumber;
        @XmlElement(name = "JournalLineNumber", required = true)
        protected String journalLineNumber;

        /**
         * Gets the value of the currencyCode property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getCurrencyCode() {
          return currencyCode;
        }

        /**
         * Sets the value of the currencyCode property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setCurrencyCode(String value) {
          this.currencyCode = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getDescription() {
          return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setDescription(String value) {
          this.description = value;
        }

        /**
         * Gets the value of the linkReference3 property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getLinkReference3() {
          return linkReference3;
        }

        /**
         * Sets the value of the linkReference3 property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setLinkReference3(String value) {
          this.linkReference3 = value;
        }

        /**
         * Gets the value of the transactionAmount property.
         * 
         */
        public double getTransactionAmount() {
          return transactionAmount;
        }

        /**
         * Sets the value of the transactionAmount property.
         * 
         */
        public void setTransactionAmount(double value) {
          this.transactionAmount = value;
        }

        /**
         * Gets the value of the transactionDate property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getTransactionDate() {
          return transactionDate;
        }

        /**
         * Sets the value of the transactionDate property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setTransactionDate(String value) {
          this.transactionDate = value;
        }

        /**
         * Gets the value of the transactionReference property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getTransactionReference() {
          return transactionReference;
        }

        /**
         * Sets the value of the transactionReference property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setTransactionReference(String value) {
          this.transactionReference = value;
        }

        public int getJournalNumber() {
          return journalNumber;
        }

        public void setJournalNumber(int journalNumber) {
          this.journalNumber = journalNumber;
        }

        public String getJournalLineNumber() {
          return journalLineNumber;
        }

        public void setJournalLineNumber(String journalLineNumber) {
          this.journalLineNumber = journalLineNumber;
        }

      }

    }

  }

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="BusinessUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="BudgetCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "businessUnit", "budgetCode" })
  public static class SunSystemsContext {

    @XmlElement(name = "BusinessUnit", required = true)
    protected String businessUnit;
    @XmlElement(name = "BudgetCode", required = true)
    protected String budgetCode;

    /**
     * Gets the value of the businessUnit property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBusinessUnit() {
      return businessUnit;
    }

    /**
     * Sets the value of the businessUnit property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setBusinessUnit(String value) {
      this.businessUnit = value;
    }

    /**
     * Gets the value of the budgetCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBudgetCode() {
      return budgetCode;
    }

    /**
     * Sets the value of the budgetCode property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setBudgetCode(String value) {
      this.budgetCode = value;
    }

  }

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "name" })
  public static class User {

    @XmlElement(name = "Name", required = true)
    protected String name;

    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName() {
      return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setName(String value) {
      this.name = value;
    }

  }

}
