package com.cardif.satelite.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OpcionMenuPerfilExample implements Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.OPCION_MENU_PERFIL
   *
   * @mbggenerated Tue Jul 30 16:52:02 COT 2013
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.OPCION_MENU_PERFIL
   *
   * @mbggenerated Tue Jul 30 16:52:02 COT 2013
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.OPCION_MENU_PERFIL
   *
   * @mbggenerated Tue Jul 30 16:52:02 COT 2013
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OPCION_MENU_PERFIL
   *
   * @mbggenerated Tue Jul 30 16:52:02 COT 2013
   */
  public OpcionMenuPerfilExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OPCION_MENU_PERFIL
   *
   * @mbggenerated Tue Jul 30 16:52:02 COT 2013
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OPCION_MENU_PERFIL
   *
   * @mbggenerated Tue Jul 30 16:52:02 COT 2013
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OPCION_MENU_PERFIL
   *
   * @mbggenerated Tue Jul 30 16:52:02 COT 2013
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OPCION_MENU_PERFIL
   *
   * @mbggenerated Tue Jul 30 16:52:02 COT 2013
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OPCION_MENU_PERFIL
   *
   * @mbggenerated Tue Jul 30 16:52:02 COT 2013
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OPCION_MENU_PERFIL
   *
   * @mbggenerated Tue Jul 30 16:52:02 COT 2013
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OPCION_MENU_PERFIL
   *
   * @mbggenerated Tue Jul 30 16:52:02 COT 2013
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OPCION_MENU_PERFIL
   *
   * @mbggenerated Tue Jul 30 16:52:02 COT 2013
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OPCION_MENU_PERFIL
   *
   * @mbggenerated Tue Jul 30 16:52:02 COT 2013
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OPCION_MENU_PERFIL
   *
   * @mbggenerated Tue Jul 30 16:52:02 COT 2013
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.OPCION_MENU_PERFIL
   *
   * @mbggenerated Tue Jul 30 16:52:02 COT 2013
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andCodPerfilIsNull() {
      addCriterion("COD_PERFIL is null");
      return (Criteria) this;
    }

    public Criteria andCodPerfilIsNotNull() {
      addCriterion("COD_PERFIL is not null");
      return (Criteria) this;
    }

    public Criteria andCodPerfilEqualTo(Long value) {
      addCriterion("COD_PERFIL =", value, "codPerfil");
      return (Criteria) this;
    }

    public Criteria andCodPerfilNotEqualTo(Long value) {
      addCriterion("COD_PERFIL <>", value, "codPerfil");
      return (Criteria) this;
    }

    public Criteria andCodPerfilGreaterThan(Long value) {
      addCriterion("COD_PERFIL >", value, "codPerfil");
      return (Criteria) this;
    }

    public Criteria andCodPerfilGreaterThanOrEqualTo(Long value) {
      addCriterion("COD_PERFIL >=", value, "codPerfil");
      return (Criteria) this;
    }

    public Criteria andCodPerfilLessThan(Long value) {
      addCriterion("COD_PERFIL <", value, "codPerfil");
      return (Criteria) this;
    }

    public Criteria andCodPerfilLessThanOrEqualTo(Long value) {
      addCriterion("COD_PERFIL <=", value, "codPerfil");
      return (Criteria) this;
    }

    public Criteria andCodPerfilIn(List<Long> values) {
      addCriterion("COD_PERFIL in", values, "codPerfil");
      return (Criteria) this;
    }

    public Criteria andCodPerfilNotIn(List<Long> values) {
      addCriterion("COD_PERFIL not in", values, "codPerfil");
      return (Criteria) this;
    }

    public Criteria andCodPerfilBetween(Long value1, Long value2) {
      addCriterion("COD_PERFIL between", value1, value2, "codPerfil");
      return (Criteria) this;
    }

    public Criteria andCodPerfilNotBetween(Long value1, Long value2) {
      addCriterion("COD_PERFIL not between", value1, value2, "codPerfil");
      return (Criteria) this;
    }

    public Criteria andCodOpcionIsNull() {
      addCriterion("COD_OPCION is null");
      return (Criteria) this;
    }

    public Criteria andCodOpcionIsNotNull() {
      addCriterion("COD_OPCION is not null");
      return (Criteria) this;
    }

    public Criteria andCodOpcionEqualTo(Long value) {
      addCriterion("COD_OPCION =", value, "codOpcion");
      return (Criteria) this;
    }

    public Criteria andCodOpcionNotEqualTo(Long value) {
      addCriterion("COD_OPCION <>", value, "codOpcion");
      return (Criteria) this;
    }

    public Criteria andCodOpcionGreaterThan(Long value) {
      addCriterion("COD_OPCION >", value, "codOpcion");
      return (Criteria) this;
    }

    public Criteria andCodOpcionGreaterThanOrEqualTo(Long value) {
      addCriterion("COD_OPCION >=", value, "codOpcion");
      return (Criteria) this;
    }

    public Criteria andCodOpcionLessThan(Long value) {
      addCriterion("COD_OPCION <", value, "codOpcion");
      return (Criteria) this;
    }

    public Criteria andCodOpcionLessThanOrEqualTo(Long value) {
      addCriterion("COD_OPCION <=", value, "codOpcion");
      return (Criteria) this;
    }

    public Criteria andCodOpcionIn(List<Long> values) {
      addCriterion("COD_OPCION in", values, "codOpcion");
      return (Criteria) this;
    }

    public Criteria andCodOpcionNotIn(List<Long> values) {
      addCriterion("COD_OPCION not in", values, "codOpcion");
      return (Criteria) this;
    }

    public Criteria andCodOpcionBetween(Long value1, Long value2) {
      addCriterion("COD_OPCION between", value1, value2, "codOpcion");
      return (Criteria) this;
    }

    public Criteria andCodOpcionNotBetween(Long value1, Long value2) {
      addCriterion("COD_OPCION not between", value1, value2, "codOpcion");
      return (Criteria) this;
    }

    public Criteria andHabilitadoIsNull() {
      addCriterion("HABILITADO is null");
      return (Criteria) this;
    }

    public Criteria andHabilitadoIsNotNull() {
      addCriterion("HABILITADO is not null");
      return (Criteria) this;
    }

    public Criteria andHabilitadoEqualTo(Long value) {
      addCriterion("HABILITADO =", value, "habilitado");
      return (Criteria) this;
    }

    public Criteria andHabilitadoNotEqualTo(Long value) {
      addCriterion("HABILITADO <>", value, "habilitado");
      return (Criteria) this;
    }

    public Criteria andHabilitadoGreaterThan(Long value) {
      addCriterion("HABILITADO >", value, "habilitado");
      return (Criteria) this;
    }

    public Criteria andHabilitadoGreaterThanOrEqualTo(Long value) {
      addCriterion("HABILITADO >=", value, "habilitado");
      return (Criteria) this;
    }

    public Criteria andHabilitadoLessThan(Long value) {
      addCriterion("HABILITADO <", value, "habilitado");
      return (Criteria) this;
    }

    public Criteria andHabilitadoLessThanOrEqualTo(Long value) {
      addCriterion("HABILITADO <=", value, "habilitado");
      return (Criteria) this;
    }

    public Criteria andHabilitadoIn(List<Long> values) {
      addCriterion("HABILITADO in", values, "habilitado");
      return (Criteria) this;
    }

    public Criteria andHabilitadoNotIn(List<Long> values) {
      addCriterion("HABILITADO not in", values, "habilitado");
      return (Criteria) this;
    }

    public Criteria andHabilitadoBetween(Long value1, Long value2) {
      addCriterion("HABILITADO between", value1, value2, "habilitado");
      return (Criteria) this;
    }

    public Criteria andHabilitadoNotBetween(Long value1, Long value2) {
      addCriterion("HABILITADO not between", value1, value2, "habilitado");
      return (Criteria) this;
    }

    public Criteria andFecCreacionIsNull() {
      addCriterion("FEC_CREACION is null");
      return (Criteria) this;
    }

    public Criteria andFecCreacionIsNotNull() {
      addCriterion("FEC_CREACION is not null");
      return (Criteria) this;
    }

    public Criteria andFecCreacionEqualTo(Date value) {
      addCriterion("FEC_CREACION =", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionNotEqualTo(Date value) {
      addCriterion("FEC_CREACION <>", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionGreaterThan(Date value) {
      addCriterion("FEC_CREACION >", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionGreaterThanOrEqualTo(Date value) {
      addCriterion("FEC_CREACION >=", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionLessThan(Date value) {
      addCriterion("FEC_CREACION <", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionLessThanOrEqualTo(Date value) {
      addCriterion("FEC_CREACION <=", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionIn(List<Date> values) {
      addCriterion("FEC_CREACION in", values, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionNotIn(List<Date> values) {
      addCriterion("FEC_CREACION not in", values, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionBetween(Date value1, Date value2) {
      addCriterion("FEC_CREACION between", value1, value2, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionNotBetween(Date value1, Date value2) {
      addCriterion("FEC_CREACION not between", value1, value2, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionIsNull() {
      addCriterion("USU_CREACION is null");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionIsNotNull() {
      addCriterion("USU_CREACION is not null");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionEqualTo(String value) {
      addCriterion("USU_CREACION =", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionNotEqualTo(String value) {
      addCriterion("USU_CREACION <>", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionGreaterThan(String value) {
      addCriterion("USU_CREACION >", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionGreaterThanOrEqualTo(String value) {
      addCriterion("USU_CREACION >=", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionLessThan(String value) {
      addCriterion("USU_CREACION <", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionLessThanOrEqualTo(String value) {
      addCriterion("USU_CREACION <=", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionIn(List<String> values) {
      addCriterion("USU_CREACION in", values, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionNotIn(List<String> values) {
      addCriterion("USU_CREACION not in", values, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionBetween(String value1, String value2) {
      addCriterion("USU_CREACION between", value1, value2, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionNotBetween(String value1, String value2) {
      addCriterion("USU_CREACION not between", value1, value2, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionIsNull() {
      addCriterion("FEC_MODIFICACION is null");
      return (Criteria) this;
    }

    public Criteria andFecModificacionIsNotNull() {
      addCriterion("FEC_MODIFICACION is not null");
      return (Criteria) this;
    }

    public Criteria andFecModificacionEqualTo(Date value) {
      addCriterion("FEC_MODIFICACION =", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionNotEqualTo(Date value) {
      addCriterion("FEC_MODIFICACION <>", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionGreaterThan(Date value) {
      addCriterion("FEC_MODIFICACION >", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionGreaterThanOrEqualTo(Date value) {
      addCriterion("FEC_MODIFICACION >=", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionLessThan(Date value) {
      addCriterion("FEC_MODIFICACION <", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionLessThanOrEqualTo(Date value) {
      addCriterion("FEC_MODIFICACION <=", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionIn(List<Date> values) {
      addCriterion("FEC_MODIFICACION in", values, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionNotIn(List<Date> values) {
      addCriterion("FEC_MODIFICACION not in", values, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionBetween(Date value1, Date value2) {
      addCriterion("FEC_MODIFICACION between", value1, value2, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionNotBetween(Date value1, Date value2) {
      addCriterion("FEC_MODIFICACION not between", value1, value2, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionIsNull() {
      addCriterion("USU_MODIFICACION is null");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionIsNotNull() {
      addCriterion("USU_MODIFICACION is not null");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionEqualTo(String value) {
      addCriterion("USU_MODIFICACION =", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionNotEqualTo(String value) {
      addCriterion("USU_MODIFICACION <>", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionGreaterThan(String value) {
      addCriterion("USU_MODIFICACION >", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionGreaterThanOrEqualTo(String value) {
      addCriterion("USU_MODIFICACION >=", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionLessThan(String value) {
      addCriterion("USU_MODIFICACION <", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionLessThanOrEqualTo(String value) {
      addCriterion("USU_MODIFICACION <=", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionIn(List<String> values) {
      addCriterion("USU_MODIFICACION in", values, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionNotIn(List<String> values) {
      addCriterion("USU_MODIFICACION not in", values, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionBetween(String value1, String value2) {
      addCriterion("USU_MODIFICACION between", value1, value2, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionNotBetween(String value1, String value2) {
      addCriterion("USU_MODIFICACION not between", value1, value2, "usuModificacion");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.OPCION_MENU_PERFIL
   *
   * @mbggenerated do_not_delete_during_merge Tue Jul 30 16:52:02 COT 2013
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.OPCION_MENU_PERFIL
   *
   * @mbggenerated Tue Jul 30 16:52:02 COT 2013
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}