package com.cardif.satelite.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProcesoExample implements Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.DATA_FLOW_TASK
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.DATA_FLOW_TASK
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.DATA_FLOW_TASK
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public ProcesoExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DATA_FLOW_TASK
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.DATA_FLOW_TASK
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andProcessNumberIsNull() {
      addCriterion("PROCESS_NUMBER is null");
      return (Criteria) this;
    }

    public Criteria andProcessNumberIsNotNull() {
      addCriterion("PROCESS_NUMBER is not null");
      return (Criteria) this;
    }

    public Criteria andProcessNumberEqualTo(Long value) {
      addCriterion("PROCESS_NUMBER =", value, "processNumber");
      return (Criteria) this;
    }

    public Criteria andProcessNumberNotEqualTo(Long value) {
      addCriterion("PROCESS_NUMBER <>", value, "processNumber");
      return (Criteria) this;
    }

    public Criteria andProcessNumberGreaterThan(Long value) {
      addCriterion("PROCESS_NUMBER >", value, "processNumber");
      return (Criteria) this;
    }

    public Criteria andProcessNumberGreaterThanOrEqualTo(Long value) {
      addCriterion("PROCESS_NUMBER >=", value, "processNumber");
      return (Criteria) this;
    }

    public Criteria andProcessNumberLessThan(Long value) {
      addCriterion("PROCESS_NUMBER <", value, "processNumber");
      return (Criteria) this;
    }

    public Criteria andProcessNumberLessThanOrEqualTo(Long value) {
      addCriterion("PROCESS_NUMBER <=", value, "processNumber");
      return (Criteria) this;
    }

    public Criteria andProcessNumberIn(List<Long> values) {
      addCriterion("PROCESS_NUMBER in", values, "processNumber");
      return (Criteria) this;
    }

    public Criteria andProcessNumberNotIn(List<Long> values) {
      addCriterion("PROCESS_NUMBER not in", values, "processNumber");
      return (Criteria) this;
    }

    public Criteria andProcessNumberBetween(Long value1, Long value2) {
      addCriterion("PROCESS_NUMBER between", value1, value2, "processNumber");
      return (Criteria) this;
    }

    public Criteria andProcessNumberNotBetween(Long value1, Long value2) {
      addCriterion("PROCESS_NUMBER not between", value1, value2, "processNumber");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionInstanceGuidIsNull() {
      addCriterion("AUDIT_EXECUTION_INSTANCE_GUID is null");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionInstanceGuidIsNotNull() {
      addCriterion("AUDIT_EXECUTION_INSTANCE_GUID is not null");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionInstanceGuidEqualTo(String value) {
      addCriterion("AUDIT_EXECUTION_INSTANCE_GUID =", value, "auditExecutionInstanceGuid");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionInstanceGuidNotEqualTo(String value) {
      addCriterion("AUDIT_EXECUTION_INSTANCE_GUID <>", value, "auditExecutionInstanceGuid");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionInstanceGuidGreaterThan(String value) {
      addCriterion("AUDIT_EXECUTION_INSTANCE_GUID >", value, "auditExecutionInstanceGuid");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionInstanceGuidGreaterThanOrEqualTo(String value) {
      addCriterion("AUDIT_EXECUTION_INSTANCE_GUID >=", value, "auditExecutionInstanceGuid");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionInstanceGuidLessThan(String value) {
      addCriterion("AUDIT_EXECUTION_INSTANCE_GUID <", value, "auditExecutionInstanceGuid");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionInstanceGuidLessThanOrEqualTo(String value) {
      addCriterion("AUDIT_EXECUTION_INSTANCE_GUID <=", value, "auditExecutionInstanceGuid");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionInstanceGuidIn(List<String> values) {
      addCriterion("AUDIT_EXECUTION_INSTANCE_GUID in", values, "auditExecutionInstanceGuid");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionInstanceGuidNotIn(List<String> values) {
      addCriterion("AUDIT_EXECUTION_INSTANCE_GUID not in", values, "auditExecutionInstanceGuid");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionInstanceGuidBetween(String value1, String value2) {
      addCriterion("AUDIT_EXECUTION_INSTANCE_GUID between", value1, value2, "auditExecutionInstanceGuid");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionInstanceGuidNotBetween(String value1, String value2) {
      addCriterion("AUDIT_EXECUTION_INSTANCE_GUID not between", value1, value2, "auditExecutionInstanceGuid");
      return (Criteria) this;
    }

    public Criteria andAuditVersionIdIsNull() {
      addCriterion("AUDIT_VERSION_ID is null");
      return (Criteria) this;
    }

    public Criteria andAuditVersionIdIsNotNull() {
      addCriterion("AUDIT_VERSION_ID is not null");
      return (Criteria) this;
    }

    public Criteria andAuditVersionIdEqualTo(String value) {
      addCriterion("AUDIT_VERSION_ID =", value, "auditVersionId");
      return (Criteria) this;
    }

    public Criteria andAuditVersionIdNotEqualTo(String value) {
      addCriterion("AUDIT_VERSION_ID <>", value, "auditVersionId");
      return (Criteria) this;
    }

    public Criteria andAuditVersionIdGreaterThan(String value) {
      addCriterion("AUDIT_VERSION_ID >", value, "auditVersionId");
      return (Criteria) this;
    }

    public Criteria andAuditVersionIdGreaterThanOrEqualTo(String value) {
      addCriterion("AUDIT_VERSION_ID >=", value, "auditVersionId");
      return (Criteria) this;
    }

    public Criteria andAuditVersionIdLessThan(String value) {
      addCriterion("AUDIT_VERSION_ID <", value, "auditVersionId");
      return (Criteria) this;
    }

    public Criteria andAuditVersionIdLessThanOrEqualTo(String value) {
      addCriterion("AUDIT_VERSION_ID <=", value, "auditVersionId");
      return (Criteria) this;
    }

    public Criteria andAuditVersionIdIn(List<String> values) {
      addCriterion("AUDIT_VERSION_ID in", values, "auditVersionId");
      return (Criteria) this;
    }

    public Criteria andAuditVersionIdNotIn(List<String> values) {
      addCriterion("AUDIT_VERSION_ID not in", values, "auditVersionId");
      return (Criteria) this;
    }

    public Criteria andAuditVersionIdBetween(String value1, String value2) {
      addCriterion("AUDIT_VERSION_ID between", value1, value2, "auditVersionId");
      return (Criteria) this;
    }

    public Criteria andAuditVersionIdNotBetween(String value1, String value2) {
      addCriterion("AUDIT_VERSION_ID not between", value1, value2, "auditVersionId");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionStartTimeIsNull() {
      addCriterion("AUDIT_EXECUTION_START_TIME is null");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionStartTimeIsNotNull() {
      addCriterion("AUDIT_EXECUTION_START_TIME is not null");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionStartTimeEqualTo(Date value) {
      addCriterion("AUDIT_EXECUTION_START_TIME =", value, "auditExecutionStartTime");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionStartTimeNotEqualTo(Date value) {
      addCriterion("AUDIT_EXECUTION_START_TIME <>", value, "auditExecutionStartTime");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionStartTimeGreaterThan(Date value) {
      addCriterion("AUDIT_EXECUTION_START_TIME >", value, "auditExecutionStartTime");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionStartTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("AUDIT_EXECUTION_START_TIME >=", value, "auditExecutionStartTime");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionStartTimeLessThan(Date value) {
      addCriterion("AUDIT_EXECUTION_START_TIME <", value, "auditExecutionStartTime");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionStartTimeLessThanOrEqualTo(Date value) {
      addCriterion("AUDIT_EXECUTION_START_TIME <=", value, "auditExecutionStartTime");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionStartTimeIn(List<Date> values) {
      addCriterion("AUDIT_EXECUTION_START_TIME in", values, "auditExecutionStartTime");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionStartTimeNotIn(List<Date> values) {
      addCriterion("AUDIT_EXECUTION_START_TIME not in", values, "auditExecutionStartTime");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionStartTimeBetween(Date value1, Date value2) {
      addCriterion("AUDIT_EXECUTION_START_TIME between", value1, value2, "auditExecutionStartTime");
      return (Criteria) this;
    }

    public Criteria andAuditExecutionStartTimeNotBetween(Date value1, Date value2) {
      addCriterion("AUDIT_EXECUTION_START_TIME not between", value1, value2, "auditExecutionStartTime");
      return (Criteria) this;
    }

    public Criteria andAuditMachineNameIsNull() {
      addCriterion("AUDIT_MACHINE_NAME is null");
      return (Criteria) this;
    }

    public Criteria andAuditMachineNameIsNotNull() {
      addCriterion("AUDIT_MACHINE_NAME is not null");
      return (Criteria) this;
    }

    public Criteria andAuditMachineNameEqualTo(String value) {
      addCriterion("AUDIT_MACHINE_NAME =", value, "auditMachineName");
      return (Criteria) this;
    }

    public Criteria andAuditMachineNameNotEqualTo(String value) {
      addCriterion("AUDIT_MACHINE_NAME <>", value, "auditMachineName");
      return (Criteria) this;
    }

    public Criteria andAuditMachineNameGreaterThan(String value) {
      addCriterion("AUDIT_MACHINE_NAME >", value, "auditMachineName");
      return (Criteria) this;
    }

    public Criteria andAuditMachineNameGreaterThanOrEqualTo(String value) {
      addCriterion("AUDIT_MACHINE_NAME >=", value, "auditMachineName");
      return (Criteria) this;
    }

    public Criteria andAuditMachineNameLessThan(String value) {
      addCriterion("AUDIT_MACHINE_NAME <", value, "auditMachineName");
      return (Criteria) this;
    }

    public Criteria andAuditMachineNameLessThanOrEqualTo(String value) {
      addCriterion("AUDIT_MACHINE_NAME <=", value, "auditMachineName");
      return (Criteria) this;
    }

    public Criteria andAuditMachineNameIn(List<String> values) {
      addCriterion("AUDIT_MACHINE_NAME in", values, "auditMachineName");
      return (Criteria) this;
    }

    public Criteria andAuditMachineNameNotIn(List<String> values) {
      addCriterion("AUDIT_MACHINE_NAME not in", values, "auditMachineName");
      return (Criteria) this;
    }

    public Criteria andAuditMachineNameBetween(String value1, String value2) {
      addCriterion("AUDIT_MACHINE_NAME between", value1, value2, "auditMachineName");
      return (Criteria) this;
    }

    public Criteria andAuditMachineNameNotBetween(String value1, String value2) {
      addCriterion("AUDIT_MACHINE_NAME not between", value1, value2, "auditMachineName");
      return (Criteria) this;
    }

    public Criteria andAuditUserNameIsNull() {
      addCriterion("AUDIT_USER_NAME is null");
      return (Criteria) this;
    }

    public Criteria andAuditUserNameIsNotNull() {
      addCriterion("AUDIT_USER_NAME is not null");
      return (Criteria) this;
    }

    public Criteria andAuditUserNameEqualTo(String value) {
      addCriterion("AUDIT_USER_NAME =", value, "auditUserName");
      return (Criteria) this;
    }

    public Criteria andAuditUserNameNotEqualTo(String value) {
      addCriterion("AUDIT_USER_NAME <>", value, "auditUserName");
      return (Criteria) this;
    }

    public Criteria andAuditUserNameGreaterThan(String value) {
      addCriterion("AUDIT_USER_NAME >", value, "auditUserName");
      return (Criteria) this;
    }

    public Criteria andAuditUserNameGreaterThanOrEqualTo(String value) {
      addCriterion("AUDIT_USER_NAME >=", value, "auditUserName");
      return (Criteria) this;
    }

    public Criteria andAuditUserNameLessThan(String value) {
      addCriterion("AUDIT_USER_NAME <", value, "auditUserName");
      return (Criteria) this;
    }

    public Criteria andAuditUserNameLessThanOrEqualTo(String value) {
      addCriterion("AUDIT_USER_NAME <=", value, "auditUserName");
      return (Criteria) this;
    }

    public Criteria andAuditUserNameIn(List<String> values) {
      addCriterion("AUDIT_USER_NAME in", values, "auditUserName");
      return (Criteria) this;
    }

    public Criteria andAuditUserNameNotIn(List<String> values) {
      addCriterion("AUDIT_USER_NAME not in", values, "auditUserName");
      return (Criteria) this;
    }

    public Criteria andAuditUserNameBetween(String value1, String value2) {
      addCriterion("AUDIT_USER_NAME between", value1, value2, "auditUserName");
      return (Criteria) this;
    }

    public Criteria andAuditUserNameNotBetween(String value1, String value2) {
      addCriterion("AUDIT_USER_NAME not between", value1, value2, "auditUserName");
      return (Criteria) this;
    }

    public Criteria andAuditTaskNameIsNull() {
      addCriterion("AUDIT_TASK_NAME is null");
      return (Criteria) this;
    }

    public Criteria andAuditTaskNameIsNotNull() {
      addCriterion("AUDIT_TASK_NAME is not null");
      return (Criteria) this;
    }

    public Criteria andAuditTaskNameEqualTo(String value) {
      addCriterion("AUDIT_TASK_NAME =", value, "auditTaskName");
      return (Criteria) this;
    }

    public Criteria andAuditTaskNameNotEqualTo(String value) {
      addCriterion("AUDIT_TASK_NAME <>", value, "auditTaskName");
      return (Criteria) this;
    }

    public Criteria andAuditTaskNameGreaterThan(String value) {
      addCriterion("AUDIT_TASK_NAME >", value, "auditTaskName");
      return (Criteria) this;
    }

    public Criteria andAuditTaskNameGreaterThanOrEqualTo(String value) {
      addCriterion("AUDIT_TASK_NAME >=", value, "auditTaskName");
      return (Criteria) this;
    }

    public Criteria andAuditTaskNameLessThan(String value) {
      addCriterion("AUDIT_TASK_NAME <", value, "auditTaskName");
      return (Criteria) this;
    }

    public Criteria andAuditTaskNameLessThanOrEqualTo(String value) {
      addCriterion("AUDIT_TASK_NAME <=", value, "auditTaskName");
      return (Criteria) this;
    }

    public Criteria andAuditTaskNameIn(List<String> values) {
      addCriterion("AUDIT_TASK_NAME in", values, "auditTaskName");
      return (Criteria) this;
    }

    public Criteria andAuditTaskNameNotIn(List<String> values) {
      addCriterion("AUDIT_TASK_NAME not in", values, "auditTaskName");
      return (Criteria) this;
    }

    public Criteria andAuditTaskNameBetween(String value1, String value2) {
      addCriterion("AUDIT_TASK_NAME between", value1, value2, "auditTaskName");
      return (Criteria) this;
    }

    public Criteria andAuditTaskNameNotBetween(String value1, String value2) {
      addCriterion("AUDIT_TASK_NAME not between", value1, value2, "auditTaskName");
      return (Criteria) this;
    }

    public Criteria andAuditTaskIdIsNull() {
      addCriterion("AUDIT_TASK_ID is null");
      return (Criteria) this;
    }

    public Criteria andAuditTaskIdIsNotNull() {
      addCriterion("AUDIT_TASK_ID is not null");
      return (Criteria) this;
    }

    public Criteria andAuditTaskIdEqualTo(String value) {
      addCriterion("AUDIT_TASK_ID =", value, "auditTaskId");
      return (Criteria) this;
    }

    public Criteria andAuditTaskIdNotEqualTo(String value) {
      addCriterion("AUDIT_TASK_ID <>", value, "auditTaskId");
      return (Criteria) this;
    }

    public Criteria andAuditTaskIdGreaterThan(String value) {
      addCriterion("AUDIT_TASK_ID >", value, "auditTaskId");
      return (Criteria) this;
    }

    public Criteria andAuditTaskIdGreaterThanOrEqualTo(String value) {
      addCriterion("AUDIT_TASK_ID >=", value, "auditTaskId");
      return (Criteria) this;
    }

    public Criteria andAuditTaskIdLessThan(String value) {
      addCriterion("AUDIT_TASK_ID <", value, "auditTaskId");
      return (Criteria) this;
    }

    public Criteria andAuditTaskIdLessThanOrEqualTo(String value) {
      addCriterion("AUDIT_TASK_ID <=", value, "auditTaskId");
      return (Criteria) this;
    }

    public Criteria andAuditTaskIdIn(List<String> values) {
      addCriterion("AUDIT_TASK_ID in", values, "auditTaskId");
      return (Criteria) this;
    }

    public Criteria andAuditTaskIdNotIn(List<String> values) {
      addCriterion("AUDIT_TASK_ID not in", values, "auditTaskId");
      return (Criteria) this;
    }

    public Criteria andAuditTaskIdBetween(String value1, String value2) {
      addCriterion("AUDIT_TASK_ID between", value1, value2, "auditTaskId");
      return (Criteria) this;
    }

    public Criteria andAuditTaskIdNotBetween(String value1, String value2) {
      addCriterion("AUDIT_TASK_ID not between", value1, value2, "auditTaskId");
      return (Criteria) this;
    }

    public Criteria andAuditPackageIdIsNull() {
      addCriterion("AUDIT_PACKAGE_ID is null");
      return (Criteria) this;
    }

    public Criteria andAuditPackageIdIsNotNull() {
      addCriterion("AUDIT_PACKAGE_ID is not null");
      return (Criteria) this;
    }

    public Criteria andAuditPackageIdEqualTo(String value) {
      addCriterion("AUDIT_PACKAGE_ID =", value, "auditPackageId");
      return (Criteria) this;
    }

    public Criteria andAuditPackageIdNotEqualTo(String value) {
      addCriterion("AUDIT_PACKAGE_ID <>", value, "auditPackageId");
      return (Criteria) this;
    }

    public Criteria andAuditPackageIdGreaterThan(String value) {
      addCriterion("AUDIT_PACKAGE_ID >", value, "auditPackageId");
      return (Criteria) this;
    }

    public Criteria andAuditPackageIdGreaterThanOrEqualTo(String value) {
      addCriterion("AUDIT_PACKAGE_ID >=", value, "auditPackageId");
      return (Criteria) this;
    }

    public Criteria andAuditPackageIdLessThan(String value) {
      addCriterion("AUDIT_PACKAGE_ID <", value, "auditPackageId");
      return (Criteria) this;
    }

    public Criteria andAuditPackageIdLessThanOrEqualTo(String value) {
      addCriterion("AUDIT_PACKAGE_ID <=", value, "auditPackageId");
      return (Criteria) this;
    }

    public Criteria andAuditPackageIdIn(List<String> values) {
      addCriterion("AUDIT_PACKAGE_ID in", values, "auditPackageId");
      return (Criteria) this;
    }

    public Criteria andAuditPackageIdNotIn(List<String> values) {
      addCriterion("AUDIT_PACKAGE_ID not in", values, "auditPackageId");
      return (Criteria) this;
    }

    public Criteria andAuditPackageIdBetween(String value1, String value2) {
      addCriterion("AUDIT_PACKAGE_ID between", value1, value2, "auditPackageId");
      return (Criteria) this;
    }

    public Criteria andAuditPackageIdNotBetween(String value1, String value2) {
      addCriterion("AUDIT_PACKAGE_ID not between", value1, value2, "auditPackageId");
      return (Criteria) this;
    }

    public Criteria andAuditPackageNameIsNull() {
      addCriterion("AUDIT_PACKAGE_NAME is null");
      return (Criteria) this;
    }

    public Criteria andAuditPackageNameIsNotNull() {
      addCriterion("AUDIT_PACKAGE_NAME is not null");
      return (Criteria) this;
    }

    public Criteria andAuditPackageNameEqualTo(String value) {
      addCriterion("AUDIT_PACKAGE_NAME =", value, "auditPackageName");
      return (Criteria) this;
    }

    public Criteria andAuditPackageNameNotEqualTo(String value) {
      addCriterion("AUDIT_PACKAGE_NAME <>", value, "auditPackageName");
      return (Criteria) this;
    }

    public Criteria andAuditPackageNameGreaterThan(String value) {
      addCriterion("AUDIT_PACKAGE_NAME >", value, "auditPackageName");
      return (Criteria) this;
    }

    public Criteria andAuditPackageNameGreaterThanOrEqualTo(String value) {
      addCriterion("AUDIT_PACKAGE_NAME >=", value, "auditPackageName");
      return (Criteria) this;
    }

    public Criteria andAuditPackageNameLessThan(String value) {
      addCriterion("AUDIT_PACKAGE_NAME <", value, "auditPackageName");
      return (Criteria) this;
    }

    public Criteria andAuditPackageNameLessThanOrEqualTo(String value) {
      addCriterion("AUDIT_PACKAGE_NAME <=", value, "auditPackageName");
      return (Criteria) this;
    }

    public Criteria andAuditPackageNameIn(List<String> values) {
      addCriterion("AUDIT_PACKAGE_NAME in", values, "auditPackageName");
      return (Criteria) this;
    }

    public Criteria andAuditPackageNameNotIn(List<String> values) {
      addCriterion("AUDIT_PACKAGE_NAME not in", values, "auditPackageName");
      return (Criteria) this;
    }

    public Criteria andAuditPackageNameBetween(String value1, String value2) {
      addCriterion("AUDIT_PACKAGE_NAME between", value1, value2, "auditPackageName");
      return (Criteria) this;
    }

    public Criteria andAuditPackageNameNotBetween(String value1, String value2) {
      addCriterion("AUDIT_PACKAGE_NAME not between", value1, value2, "auditPackageName");
      return (Criteria) this;
    }

    public Criteria andExecutedQueryIsNull() {
      addCriterion("EXECUTED_QUERY is null");
      return (Criteria) this;
    }

    public Criteria andExecutedQueryIsNotNull() {
      addCriterion("EXECUTED_QUERY is not null");
      return (Criteria) this;
    }

    public Criteria andExecutedQueryEqualTo(String value) {
      addCriterion("EXECUTED_QUERY =", value, "executedQuery");
      return (Criteria) this;
    }

    public Criteria andExecutedQueryNotEqualTo(String value) {
      addCriterion("EXECUTED_QUERY <>", value, "executedQuery");
      return (Criteria) this;
    }

    public Criteria andExecutedQueryGreaterThan(String value) {
      addCriterion("EXECUTED_QUERY >", value, "executedQuery");
      return (Criteria) this;
    }

    public Criteria andExecutedQueryGreaterThanOrEqualTo(String value) {
      addCriterion("EXECUTED_QUERY >=", value, "executedQuery");
      return (Criteria) this;
    }

    public Criteria andExecutedQueryLessThan(String value) {
      addCriterion("EXECUTED_QUERY <", value, "executedQuery");
      return (Criteria) this;
    }

    public Criteria andExecutedQueryLessThanOrEqualTo(String value) {
      addCriterion("EXECUTED_QUERY <=", value, "executedQuery");
      return (Criteria) this;
    }

    public Criteria andExecutedQueryIn(List<String> values) {
      addCriterion("EXECUTED_QUERY in", values, "executedQuery");
      return (Criteria) this;
    }

    public Criteria andExecutedQueryNotIn(List<String> values) {
      addCriterion("EXECUTED_QUERY not in", values, "executedQuery");
      return (Criteria) this;
    }

    public Criteria andExecutedQueryBetween(String value1, String value2) {
      addCriterion("EXECUTED_QUERY between", value1, value2, "executedQuery");
      return (Criteria) this;
    }

    public Criteria andExecutedQueryNotBetween(String value1, String value2) {
      addCriterion("EXECUTED_QUERY not between", value1, value2, "executedQuery");
      return (Criteria) this;
    }

    public Criteria andFileNameFullIsNull() {
      addCriterion("FILE_NAME_FULL is null");
      return (Criteria) this;
    }

    public Criteria andFileNameFullIsNotNull() {
      addCriterion("FILE_NAME_FULL is not null");
      return (Criteria) this;
    }

    public Criteria andFileNameFullEqualTo(String value) {
      addCriterion("FILE_NAME_FULL =", value, "fileNameFull");
      return (Criteria) this;
    }

    public Criteria andFileNameFullNotEqualTo(String value) {
      addCriterion("FILE_NAME_FULL <>", value, "fileNameFull");
      return (Criteria) this;
    }

    public Criteria andFileNameFullGreaterThan(String value) {
      addCriterion("FILE_NAME_FULL >", value, "fileNameFull");
      return (Criteria) this;
    }

    public Criteria andFileNameFullGreaterThanOrEqualTo(String value) {
      addCriterion("FILE_NAME_FULL >=", value, "fileNameFull");
      return (Criteria) this;
    }

    public Criteria andFileNameFullLessThan(String value) {
      addCriterion("FILE_NAME_FULL <", value, "fileNameFull");
      return (Criteria) this;
    }

    public Criteria andFileNameFullLessThanOrEqualTo(String value) {
      addCriterion("FILE_NAME_FULL <=", value, "fileNameFull");
      return (Criteria) this;
    }

    public Criteria andFileNameFullLike(String value) {
      addCriterion("FILE_NAME_FULL like", value, "fileNameFull");
      return (Criteria) this;
    }

    public Criteria andFileNameFullNotLike(String value) {
      addCriterion("FILE_NAME_FULL not like", value, "fileNameFull");
      return (Criteria) this;
    }

    public Criteria andFileNameFullIn(List<String> values) {
      addCriterion("FILE_NAME_FULL in", values, "fileNameFull");
      return (Criteria) this;
    }

    public Criteria andFileNameFullNotIn(List<String> values) {
      addCriterion("FILE_NAME_FULL not in", values, "fileNameFull");
      return (Criteria) this;
    }

    public Criteria andFileNameFullBetween(String value1, String value2) {
      addCriterion("FILE_NAME_FULL between", value1, value2, "fileNameFull");
      return (Criteria) this;
    }

    public Criteria andFileNameFullNotBetween(String value1, String value2) {
      addCriterion("FILE_NAME_FULL not between", value1, value2, "fileNameFull");
      return (Criteria) this;
    }

    public Criteria andFileNameIsNull() {
      addCriterion("FILE_NAME is null");
      return (Criteria) this;
    }

    public Criteria andFileNameIsNotNull() {
      addCriterion("FILE_NAME is not null");
      return (Criteria) this;
    }

    public Criteria andFileNameEqualTo(String value) {
      addCriterion("FILE_NAME =", value, "fileName");
      return (Criteria) this;
    }

    public Criteria andFileNameNotEqualTo(String value) {
      addCriterion("FILE_NAME <>", value, "fileName");
      return (Criteria) this;
    }

    public Criteria andFileNameGreaterThan(String value) {
      addCriterion("FILE_NAME >", value, "fileName");
      return (Criteria) this;
    }

    public Criteria andFileNameGreaterThanOrEqualTo(String value) {
      addCriterion("FILE_NAME >=", value, "fileName");
      return (Criteria) this;
    }

    public Criteria andFileNameLessThan(String value) {
      addCriterion("FILE_NAME <", value, "fileName");
      return (Criteria) this;
    }

    public Criteria andFileNameLessThanOrEqualTo(String value) {
      addCriterion("FILE_NAME <=", value, "fileName");
      return (Criteria) this;
    }

    public Criteria andFileNameLike(String value) {
      addCriterion("FILE_NAME like", value, "fileName");
      return (Criteria) this;
    }

    public Criteria andFileNameNotLike(String value) {
      addCriterion("FILE_NAME not like", value, "fileName");
      return (Criteria) this;
    }

    public Criteria andFileNameIn(List<String> values) {
      addCriterion("FILE_NAME in", values, "fileName");
      return (Criteria) this;
    }

    public Criteria andFileNameNotIn(List<String> values) {
      addCriterion("FILE_NAME not in", values, "fileName");
      return (Criteria) this;
    }

    public Criteria andFileNameBetween(String value1, String value2) {
      addCriterion("FILE_NAME between", value1, value2, "fileName");
      return (Criteria) this;
    }

    public Criteria andFileNameNotBetween(String value1, String value2) {
      addCriterion("FILE_NAME not between", value1, value2, "fileName");
      return (Criteria) this;
    }

    public Criteria andFilePathIsNull() {
      addCriterion("FILE_PATH is null");
      return (Criteria) this;
    }

    public Criteria andFilePathIsNotNull() {
      addCriterion("FILE_PATH is not null");
      return (Criteria) this;
    }

    public Criteria andFilePathEqualTo(String value) {
      addCriterion("FILE_PATH =", value, "filePath");
      return (Criteria) this;
    }

    public Criteria andFilePathNotEqualTo(String value) {
      addCriterion("FILE_PATH <>", value, "filePath");
      return (Criteria) this;
    }

    public Criteria andFilePathGreaterThan(String value) {
      addCriterion("FILE_PATH >", value, "filePath");
      return (Criteria) this;
    }

    public Criteria andFilePathGreaterThanOrEqualTo(String value) {
      addCriterion("FILE_PATH >=", value, "filePath");
      return (Criteria) this;
    }

    public Criteria andFilePathLessThan(String value) {
      addCriterion("FILE_PATH <", value, "filePath");
      return (Criteria) this;
    }

    public Criteria andFilePathLessThanOrEqualTo(String value) {
      addCriterion("FILE_PATH <=", value, "filePath");
      return (Criteria) this;
    }

    public Criteria andFilePathLike(String value) {
      addCriterion("FILE_PATH like", value, "filePath");
      return (Criteria) this;
    }

    public Criteria andFilePathNotLike(String value) {
      addCriterion("FILE_PATH not like", value, "filePath");
      return (Criteria) this;
    }

    public Criteria andFilePathIn(List<String> values) {
      addCriterion("FILE_PATH in", values, "filePath");
      return (Criteria) this;
    }

    public Criteria andFilePathNotIn(List<String> values) {
      addCriterion("FILE_PATH not in", values, "filePath");
      return (Criteria) this;
    }

    public Criteria andFilePathBetween(String value1, String value2) {
      addCriterion("FILE_PATH between", value1, value2, "filePath");
      return (Criteria) this;
    }

    public Criteria andFilePathNotBetween(String value1, String value2) {
      addCriterion("FILE_PATH not between", value1, value2, "filePath");
      return (Criteria) this;
    }

    public Criteria andFileExtensionIsNull() {
      addCriterion("FILE_EXTENSION is null");
      return (Criteria) this;
    }

    public Criteria andFileExtensionIsNotNull() {
      addCriterion("FILE_EXTENSION is not null");
      return (Criteria) this;
    }

    public Criteria andFileExtensionEqualTo(String value) {
      addCriterion("FILE_EXTENSION =", value, "fileExtension");
      return (Criteria) this;
    }

    public Criteria andFileExtensionNotEqualTo(String value) {
      addCriterion("FILE_EXTENSION <>", value, "fileExtension");
      return (Criteria) this;
    }

    public Criteria andFileExtensionGreaterThan(String value) {
      addCriterion("FILE_EXTENSION >", value, "fileExtension");
      return (Criteria) this;
    }

    public Criteria andFileExtensionGreaterThanOrEqualTo(String value) {
      addCriterion("FILE_EXTENSION >=", value, "fileExtension");
      return (Criteria) this;
    }

    public Criteria andFileExtensionLessThan(String value) {
      addCriterion("FILE_EXTENSION <", value, "fileExtension");
      return (Criteria) this;
    }

    public Criteria andFileExtensionLessThanOrEqualTo(String value) {
      addCriterion("FILE_EXTENSION <=", value, "fileExtension");
      return (Criteria) this;
    }

    public Criteria andFileExtensionLike(String value) {
      addCriterion("FILE_EXTENSION like", value, "fileExtension");
      return (Criteria) this;
    }

    public Criteria andFileExtensionNotLike(String value) {
      addCriterion("FILE_EXTENSION not like", value, "fileExtension");
      return (Criteria) this;
    }

    public Criteria andFileExtensionIn(List<String> values) {
      addCriterion("FILE_EXTENSION in", values, "fileExtension");
      return (Criteria) this;
    }

    public Criteria andFileExtensionNotIn(List<String> values) {
      addCriterion("FILE_EXTENSION not in", values, "fileExtension");
      return (Criteria) this;
    }

    public Criteria andFileExtensionBetween(String value1, String value2) {
      addCriterion("FILE_EXTENSION between", value1, value2, "fileExtension");
      return (Criteria) this;
    }

    public Criteria andFileExtensionNotBetween(String value1, String value2) {
      addCriterion("FILE_EXTENSION not between", value1, value2, "fileExtension");
      return (Criteria) this;
    }

    public Criteria andExecutionEndTimeIsNull() {
      addCriterion("EXECUTION_END_TIME is null");
      return (Criteria) this;
    }

    public Criteria andExecutionEndTimeIsNotNull() {
      addCriterion("EXECUTION_END_TIME is not null");
      return (Criteria) this;
    }

    public Criteria andExecutionEndTimeEqualTo(Date value) {
      addCriterion("EXECUTION_END_TIME =", value, "executionEndTime");
      return (Criteria) this;
    }

    public Criteria andExecutionEndTimeNotEqualTo(Date value) {
      addCriterion("EXECUTION_END_TIME <>", value, "executionEndTime");
      return (Criteria) this;
    }

    public Criteria andExecutionEndTimeGreaterThan(Date value) {
      addCriterion("EXECUTION_END_TIME >", value, "executionEndTime");
      return (Criteria) this;
    }

    public Criteria andExecutionEndTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("EXECUTION_END_TIME >=", value, "executionEndTime");
      return (Criteria) this;
    }

    public Criteria andExecutionEndTimeLessThan(Date value) {
      addCriterion("EXECUTION_END_TIME <", value, "executionEndTime");
      return (Criteria) this;
    }

    public Criteria andExecutionEndTimeLessThanOrEqualTo(Date value) {
      addCriterion("EXECUTION_END_TIME <=", value, "executionEndTime");
      return (Criteria) this;
    }

    public Criteria andExecutionEndTimeIn(List<Date> values) {
      addCriterion("EXECUTION_END_TIME in", values, "executionEndTime");
      return (Criteria) this;
    }

    public Criteria andExecutionEndTimeNotIn(List<Date> values) {
      addCriterion("EXECUTION_END_TIME not in", values, "executionEndTime");
      return (Criteria) this;
    }

    public Criteria andExecutionEndTimeBetween(Date value1, Date value2) {
      addCriterion("EXECUTION_END_TIME between", value1, value2, "executionEndTime");
      return (Criteria) this;
    }

    public Criteria andExecutionEndTimeNotBetween(Date value1, Date value2) {
      addCriterion("EXECUTION_END_TIME not between", value1, value2, "executionEndTime");
      return (Criteria) this;
    }

    public Criteria andFlowTypeIsNull() {
      addCriterion("FLOW_TYPE is null");
      return (Criteria) this;
    }

    public Criteria andFlowTypeIsNotNull() {
      addCriterion("FLOW_TYPE is not null");
      return (Criteria) this;
    }

    public Criteria andFlowTypeEqualTo(String value) {
      addCriterion("FLOW_TYPE =", value, "flowType");
      return (Criteria) this;
    }

    public Criteria andFlowTypeNotEqualTo(String value) {
      addCriterion("FLOW_TYPE <>", value, "flowType");
      return (Criteria) this;
    }

    public Criteria andFlowTypeGreaterThan(String value) {
      addCriterion("FLOW_TYPE >", value, "flowType");
      return (Criteria) this;
    }

    public Criteria andFlowTypeGreaterThanOrEqualTo(String value) {
      addCriterion("FLOW_TYPE >=", value, "flowType");
      return (Criteria) this;
    }

    public Criteria andFlowTypeLessThan(String value) {
      addCriterion("FLOW_TYPE <", value, "flowType");
      return (Criteria) this;
    }

    public Criteria andFlowTypeLessThanOrEqualTo(String value) {
      addCriterion("FLOW_TYPE <=", value, "flowType");
      return (Criteria) this;
    }

    public Criteria andFlowTypeIn(List<String> values) {
      addCriterion("FLOW_TYPE in", values, "flowType");
      return (Criteria) this;
    }

    public Criteria andFlowTypeNotIn(List<String> values) {
      addCriterion("FLOW_TYPE not in", values, "flowType");
      return (Criteria) this;
    }

    public Criteria andFlowTypeBetween(String value1, String value2) {
      addCriterion("FLOW_TYPE between", value1, value2, "flowType");
      return (Criteria) this;
    }

    public Criteria andFlowTypeNotBetween(String value1, String value2) {
      addCriterion("FLOW_TYPE not between", value1, value2, "flowType");
      return (Criteria) this;
    }

    public Criteria andFlowStatusIsNull() {
      addCriterion("FLOW_STATUS is null");
      return (Criteria) this;
    }

    public Criteria andFlowStatusIsNotNull() {
      addCriterion("FLOW_STATUS is not null");
      return (Criteria) this;
    }

    public Criteria andFlowStatusEqualTo(String value) {
      addCriterion("FLOW_STATUS =", value, "flowStatus");
      return (Criteria) this;
    }

    public Criteria andFlowStatusNotEqualTo(String value) {
      addCriterion("FLOW_STATUS <>", value, "flowStatus");
      return (Criteria) this;
    }

    public Criteria andFlowStatusGreaterThan(String value) {
      addCriterion("FLOW_STATUS >", value, "flowStatus");
      return (Criteria) this;
    }

    public Criteria andFlowStatusGreaterThanOrEqualTo(String value) {
      addCriterion("FLOW_STATUS >=", value, "flowStatus");
      return (Criteria) this;
    }

    public Criteria andFlowStatusLessThan(String value) {
      addCriterion("FLOW_STATUS <", value, "flowStatus");
      return (Criteria) this;
    }

    public Criteria andFlowStatusLessThanOrEqualTo(String value) {
      addCriterion("FLOW_STATUS <=", value, "flowStatus");
      return (Criteria) this;
    }

    public Criteria andFlowStatusIn(List<String> values) {
      addCriterion("FLOW_STATUS in", values, "flowStatus");
      return (Criteria) this;
    }

    public Criteria andFlowStatusNotIn(List<String> values) {
      addCriterion("FLOW_STATUS not in", values, "flowStatus");
      return (Criteria) this;
    }

    public Criteria andFlowStatusBetween(String value1, String value2) {
      addCriterion("FLOW_STATUS between", value1, value2, "flowStatus");
      return (Criteria) this;
    }

    public Criteria andFlowStatusNotBetween(String value1, String value2) {
      addCriterion("FLOW_STATUS not between", value1, value2, "flowStatus");
      return (Criteria) this;
    }

    public Criteria andInboundFileErrorIsNull() {
      addCriterion("INBOUND_FILE_ERROR is null");
      return (Criteria) this;
    }

    public Criteria andInboundFileErrorIsNotNull() {
      addCriterion("INBOUND_FILE_ERROR is not null");
      return (Criteria) this;
    }

    public Criteria andInboundFileErrorEqualTo(String value) {
      addCriterion("INBOUND_FILE_ERROR =", value, "inboundFileError");
      return (Criteria) this;
    }

    public Criteria andInboundFileErrorNotEqualTo(String value) {
      addCriterion("INBOUND_FILE_ERROR <>", value, "inboundFileError");
      return (Criteria) this;
    }

    public Criteria andInboundFileErrorGreaterThan(String value) {
      addCriterion("INBOUND_FILE_ERROR >", value, "inboundFileError");
      return (Criteria) this;
    }

    public Criteria andInboundFileErrorGreaterThanOrEqualTo(String value) {
      addCriterion("INBOUND_FILE_ERROR >=", value, "inboundFileError");
      return (Criteria) this;
    }

    public Criteria andInboundFileErrorLessThan(String value) {
      addCriterion("INBOUND_FILE_ERROR <", value, "inboundFileError");
      return (Criteria) this;
    }

    public Criteria andInboundFileErrorLessThanOrEqualTo(String value) {
      addCriterion("INBOUND_FILE_ERROR <=", value, "inboundFileError");
      return (Criteria) this;
    }

    public Criteria andInboundFileErrorLike(String value) {
      addCriterion("INBOUND_FILE_ERROR like", value, "inboundFileError");
      return (Criteria) this;
    }

    public Criteria andInboundFileErrorNotLike(String value) {
      addCriterion("INBOUND_FILE_ERROR not like", value, "inboundFileError");
      return (Criteria) this;
    }

    public Criteria andInboundFileErrorIn(List<String> values) {
      addCriterion("INBOUND_FILE_ERROR in", values, "inboundFileError");
      return (Criteria) this;
    }

    public Criteria andInboundFileErrorNotIn(List<String> values) {
      addCriterion("INBOUND_FILE_ERROR not in", values, "inboundFileError");
      return (Criteria) this;
    }

    public Criteria andInboundFileErrorBetween(String value1, String value2) {
      addCriterion("INBOUND_FILE_ERROR between", value1, value2, "inboundFileError");
      return (Criteria) this;
    }

    public Criteria andInboundFileErrorNotBetween(String value1, String value2) {
      addCriterion("INBOUND_FILE_ERROR not between", value1, value2, "inboundFileError");
      return (Criteria) this;
    }

    public Criteria andTaskControlIdIsNull() {
      addCriterion("TASK_CONTROL_ID is null");
      return (Criteria) this;
    }

    public Criteria andTaskControlIdIsNotNull() {
      addCriterion("TASK_CONTROL_ID is not null");
      return (Criteria) this;
    }

    public Criteria andTaskControlIdEqualTo(String value) {
      addCriterion("TASK_CONTROL_ID =", value, "taskControlId");
      return (Criteria) this;
    }

    public Criteria andTaskControlIdNotEqualTo(String value) {
      addCriterion("TASK_CONTROL_ID <>", value, "taskControlId");
      return (Criteria) this;
    }

    public Criteria andTaskControlIdGreaterThan(String value) {
      addCriterion("TASK_CONTROL_ID >", value, "taskControlId");
      return (Criteria) this;
    }

    public Criteria andTaskControlIdGreaterThanOrEqualTo(String value) {
      addCriterion("TASK_CONTROL_ID >=", value, "taskControlId");
      return (Criteria) this;
    }

    public Criteria andTaskControlIdLessThan(String value) {
      addCriterion("TASK_CONTROL_ID <", value, "taskControlId");
      return (Criteria) this;
    }

    public Criteria andTaskControlIdLessThanOrEqualTo(String value) {
      addCriterion("TASK_CONTROL_ID <=", value, "taskControlId");
      return (Criteria) this;
    }

    public Criteria andTaskControlIdIn(List<String> values) {
      addCriterion("TASK_CONTROL_ID in", values, "taskControlId");
      return (Criteria) this;
    }

    public Criteria andTaskControlIdNotIn(List<String> values) {
      addCriterion("TASK_CONTROL_ID not in", values, "taskControlId");
      return (Criteria) this;
    }

    public Criteria andTaskControlIdBetween(String value1, String value2) {
      addCriterion("TASK_CONTROL_ID between", value1, value2, "taskControlId");
      return (Criteria) this;
    }

    public Criteria andTaskControlIdNotBetween(String value1, String value2) {
      addCriterion("TASK_CONTROL_ID not between", value1, value2, "taskControlId");
      return (Criteria) this;
    }

    public Criteria andErrorTimeIsNull() {
      addCriterion("ERROR_TIME is null");
      return (Criteria) this;
    }

    public Criteria andErrorTimeIsNotNull() {
      addCriterion("ERROR_TIME is not null");
      return (Criteria) this;
    }

    public Criteria andErrorTimeEqualTo(Date value) {
      addCriterion("ERROR_TIME =", value, "errorTime");
      return (Criteria) this;
    }

    public Criteria andErrorTimeNotEqualTo(Date value) {
      addCriterion("ERROR_TIME <>", value, "errorTime");
      return (Criteria) this;
    }

    public Criteria andErrorTimeGreaterThan(Date value) {
      addCriterion("ERROR_TIME >", value, "errorTime");
      return (Criteria) this;
    }

    public Criteria andErrorTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("ERROR_TIME >=", value, "errorTime");
      return (Criteria) this;
    }

    public Criteria andErrorTimeLessThan(Date value) {
      addCriterion("ERROR_TIME <", value, "errorTime");
      return (Criteria) this;
    }

    public Criteria andErrorTimeLessThanOrEqualTo(Date value) {
      addCriterion("ERROR_TIME <=", value, "errorTime");
      return (Criteria) this;
    }

    public Criteria andErrorTimeIn(List<Date> values) {
      addCriterion("ERROR_TIME in", values, "errorTime");
      return (Criteria) this;
    }

    public Criteria andErrorTimeNotIn(List<Date> values) {
      addCriterion("ERROR_TIME not in", values, "errorTime");
      return (Criteria) this;
    }

    public Criteria andErrorTimeBetween(Date value1, Date value2) {
      addCriterion("ERROR_TIME between", value1, value2, "errorTime");
      return (Criteria) this;
    }

    public Criteria andErrorTimeNotBetween(Date value1, Date value2) {
      addCriterion("ERROR_TIME not between", value1, value2, "errorTime");
      return (Criteria) this;
    }

    public Criteria andErrorDescriptionIsNull() {
      addCriterion("ERROR_DESCRIPTION is null");
      return (Criteria) this;
    }

    public Criteria andErrorDescriptionIsNotNull() {
      addCriterion("ERROR_DESCRIPTION is not null");
      return (Criteria) this;
    }

    public Criteria andErrorDescriptionEqualTo(String value) {
      addCriterion("ERROR_DESCRIPTION =", value, "errorDescription");
      return (Criteria) this;
    }

    public Criteria andErrorDescriptionNotEqualTo(String value) {
      addCriterion("ERROR_DESCRIPTION <>", value, "errorDescription");
      return (Criteria) this;
    }

    public Criteria andErrorDescriptionGreaterThan(String value) {
      addCriterion("ERROR_DESCRIPTION >", value, "errorDescription");
      return (Criteria) this;
    }

    public Criteria andErrorDescriptionGreaterThanOrEqualTo(String value) {
      addCriterion("ERROR_DESCRIPTION >=", value, "errorDescription");
      return (Criteria) this;
    }

    public Criteria andErrorDescriptionLessThan(String value) {
      addCriterion("ERROR_DESCRIPTION <", value, "errorDescription");
      return (Criteria) this;
    }

    public Criteria andErrorDescriptionLessThanOrEqualTo(String value) {
      addCriterion("ERROR_DESCRIPTION <=", value, "errorDescription");
      return (Criteria) this;
    }

    public Criteria andErrorDescriptionIn(List<String> values) {
      addCriterion("ERROR_DESCRIPTION in", values, "errorDescription");
      return (Criteria) this;
    }

    public Criteria andErrorDescriptionNotIn(List<String> values) {
      addCriterion("ERROR_DESCRIPTION not in", values, "errorDescription");
      return (Criteria) this;
    }

    public Criteria andErrorDescriptionBetween(String value1, String value2) {
      addCriterion("ERROR_DESCRIPTION between", value1, value2, "errorDescription");
      return (Criteria) this;
    }

    public Criteria andErrorDescriptionNotBetween(String value1, String value2) {
      addCriterion("ERROR_DESCRIPTION not between", value1, value2, "errorDescription");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.DATA_FLOW_TASK
   *
   * @mbggenerated do_not_delete_during_merge Tue Feb 19 16:10:33 COT 2013
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.DATA_FLOW_TASK
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}