package com.cardif.satelite.model;

import java.io.Serializable;
import java.util.Date;

public class Proceso implements Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.PROCESS_NUMBER
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private Long processNumber;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.AUDIT_EXECUTION_INSTANCE_GUID
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private String auditExecutionInstanceGuid;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.AUDIT_VERSION_ID
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private String auditVersionId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.AUDIT_EXECUTION_START_TIME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private Date auditExecutionStartTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.AUDIT_MACHINE_NAME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private String auditMachineName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.AUDIT_USER_NAME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private String auditUserName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.AUDIT_TASK_NAME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private String auditTaskName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.AUDIT_TASK_ID
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private String auditTaskId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.AUDIT_PACKAGE_ID
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private String auditPackageId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.AUDIT_PACKAGE_NAME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private String auditPackageName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.EXECUTED_QUERY
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private String executedQuery;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.FILE_NAME_FULL
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private String fileNameFull;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.FILE_NAME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private String fileName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.FILE_PATH
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private String filePath;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.FILE_EXTENSION
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private String fileExtension;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.EXECUTION_END_TIME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private Date executionEndTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.FLOW_TYPE
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private String flowType;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.FLOW_STATUS
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private String flowStatus;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.INBOUND_FILE_ERROR
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private String inboundFileError;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.TASK_CONTROL_ID
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private String taskControlId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.ERROR_TIME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private Date errorTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DATA_FLOW_TASK.ERROR_DESCRIPTION
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  private String errorDescription;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DATA_FLOW_TASK.PROCESS_NUMBER
   *
   * @return the value of dbo.DATA_FLOW_TASK.PROCESS_NUMBER
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public Long getProcessNumber() {
    return processNumber;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DATA_FLOW_TASK.PROCESS_NUMBER
   *
   * @param processNumber
   *          the value for dbo.DATA_FLOW_TASK.PROCESS_NUMBER
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setProcessNumber(Long processNumber) {
    this.processNumber = processNumber;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column
   * dbo.DATA_FLOW_TASK.AUDIT_EXECUTION_INSTANCE_GUID
   *
   * @return the value of dbo.DATA_FLOW_TASK.AUDIT_EXECUTION_INSTANCE_GUID
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public String getAuditExecutionInstanceGuid() {
    return auditExecutionInstanceGuid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column
   * dbo.DATA_FLOW_TASK.AUDIT_EXECUTION_INSTANCE_GUID
   *
   * @param auditExecutionInstanceGuid
   *          the value for dbo.DATA_FLOW_TASK.AUDIT_EXECUTION_INSTANCE_GUID
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setAuditExecutionInstanceGuid(String auditExecutionInstanceGuid) {
    this.auditExecutionInstanceGuid = auditExecutionInstanceGuid == null ? null : auditExecutionInstanceGuid.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DATA_FLOW_TASK.AUDIT_VERSION_ID
   *
   * @return the value of dbo.DATA_FLOW_TASK.AUDIT_VERSION_ID
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public String getAuditVersionId() {
    return auditVersionId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DATA_FLOW_TASK.AUDIT_VERSION_ID
   *
   * @param auditVersionId
   *          the value for dbo.DATA_FLOW_TASK.AUDIT_VERSION_ID
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setAuditVersionId(String auditVersionId) {
    this.auditVersionId = auditVersionId == null ? null : auditVersionId.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column
   * dbo.DATA_FLOW_TASK.AUDIT_EXECUTION_START_TIME
   *
   * @return the value of dbo.DATA_FLOW_TASK.AUDIT_EXECUTION_START_TIME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public Date getAuditExecutionStartTime() {
    return auditExecutionStartTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DATA_FLOW_TASK.AUDIT_EXECUTION_START_TIME
   *
   * @param auditExecutionStartTime
   *          the value for dbo.DATA_FLOW_TASK.AUDIT_EXECUTION_START_TIME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setAuditExecutionStartTime(Date auditExecutionStartTime) {
    this.auditExecutionStartTime = auditExecutionStartTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DATA_FLOW_TASK.AUDIT_MACHINE_NAME
   *
   * @return the value of dbo.DATA_FLOW_TASK.AUDIT_MACHINE_NAME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public String getAuditMachineName() {
    return auditMachineName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DATA_FLOW_TASK.AUDIT_MACHINE_NAME
   *
   * @param auditMachineName
   *          the value for dbo.DATA_FLOW_TASK.AUDIT_MACHINE_NAME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setAuditMachineName(String auditMachineName) {
    this.auditMachineName = auditMachineName == null ? null : auditMachineName.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DATA_FLOW_TASK.AUDIT_USER_NAME
   *
   * @return the value of dbo.DATA_FLOW_TASK.AUDIT_USER_NAME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public String getAuditUserName() {
    return auditUserName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DATA_FLOW_TASK.AUDIT_USER_NAME
   *
   * @param auditUserName
   *          the value for dbo.DATA_FLOW_TASK.AUDIT_USER_NAME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setAuditUserName(String auditUserName) {
    this.auditUserName = auditUserName == null ? null : auditUserName.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DATA_FLOW_TASK.AUDIT_TASK_NAME
   *
   * @return the value of dbo.DATA_FLOW_TASK.AUDIT_TASK_NAME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public String getAuditTaskName() {
    return auditTaskName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DATA_FLOW_TASK.AUDIT_TASK_NAME
   *
   * @param auditTaskName
   *          the value for dbo.DATA_FLOW_TASK.AUDIT_TASK_NAME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setAuditTaskName(String auditTaskName) {
    this.auditTaskName = auditTaskName == null ? null : auditTaskName.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DATA_FLOW_TASK.AUDIT_TASK_ID
   *
   * @return the value of dbo.DATA_FLOW_TASK.AUDIT_TASK_ID
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public String getAuditTaskId() {
    return auditTaskId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DATA_FLOW_TASK.AUDIT_TASK_ID
   *
   * @param auditTaskId
   *          the value for dbo.DATA_FLOW_TASK.AUDIT_TASK_ID
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setAuditTaskId(String auditTaskId) {
    this.auditTaskId = auditTaskId == null ? null : auditTaskId.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DATA_FLOW_TASK.AUDIT_PACKAGE_ID
   *
   * @return the value of dbo.DATA_FLOW_TASK.AUDIT_PACKAGE_ID
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public String getAuditPackageId() {
    return auditPackageId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DATA_FLOW_TASK.AUDIT_PACKAGE_ID
   *
   * @param auditPackageId
   *          the value for dbo.DATA_FLOW_TASK.AUDIT_PACKAGE_ID
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setAuditPackageId(String auditPackageId) {
    this.auditPackageId = auditPackageId == null ? null : auditPackageId.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DATA_FLOW_TASK.AUDIT_PACKAGE_NAME
   *
   * @return the value of dbo.DATA_FLOW_TASK.AUDIT_PACKAGE_NAME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public String getAuditPackageName() {
    return auditPackageName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DATA_FLOW_TASK.AUDIT_PACKAGE_NAME
   *
   * @param auditPackageName
   *          the value for dbo.DATA_FLOW_TASK.AUDIT_PACKAGE_NAME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setAuditPackageName(String auditPackageName) {
    this.auditPackageName = auditPackageName == null ? null : auditPackageName.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DATA_FLOW_TASK.EXECUTED_QUERY
   *
   * @return the value of dbo.DATA_FLOW_TASK.EXECUTED_QUERY
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public String getExecutedQuery() {
    return executedQuery;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DATA_FLOW_TASK.EXECUTED_QUERY
   *
   * @param executedQuery
   *          the value for dbo.DATA_FLOW_TASK.EXECUTED_QUERY
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setExecutedQuery(String executedQuery) {
    this.executedQuery = executedQuery == null ? null : executedQuery.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DATA_FLOW_TASK.FILE_NAME_FULL
   *
   * @return the value of dbo.DATA_FLOW_TASK.FILE_NAME_FULL
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public String getFileNameFull() {
    return fileNameFull;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DATA_FLOW_TASK.FILE_NAME_FULL
   *
   * @param fileNameFull
   *          the value for dbo.DATA_FLOW_TASK.FILE_NAME_FULL
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setFileNameFull(String fileNameFull) {
    this.fileNameFull = fileNameFull == null ? null : fileNameFull.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DATA_FLOW_TASK.FILE_NAME
   *
   * @return the value of dbo.DATA_FLOW_TASK.FILE_NAME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public String getFileName() {
    return fileName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DATA_FLOW_TASK.FILE_NAME
   *
   * @param fileName
   *          the value for dbo.DATA_FLOW_TASK.FILE_NAME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setFileName(String fileName) {
    this.fileName = fileName == null ? null : fileName.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DATA_FLOW_TASK.FILE_PATH
   *
   * @return the value of dbo.DATA_FLOW_TASK.FILE_PATH
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public String getFilePath() {
    return filePath;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DATA_FLOW_TASK.FILE_PATH
   *
   * @param filePath
   *          the value for dbo.DATA_FLOW_TASK.FILE_PATH
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setFilePath(String filePath) {
    this.filePath = filePath == null ? null : filePath.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DATA_FLOW_TASK.FILE_EXTENSION
   *
   * @return the value of dbo.DATA_FLOW_TASK.FILE_EXTENSION
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public String getFileExtension() {
    return fileExtension;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DATA_FLOW_TASK.FILE_EXTENSION
   *
   * @param fileExtension
   *          the value for dbo.DATA_FLOW_TASK.FILE_EXTENSION
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setFileExtension(String fileExtension) {
    this.fileExtension = fileExtension == null ? null : fileExtension.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DATA_FLOW_TASK.EXECUTION_END_TIME
   *
   * @return the value of dbo.DATA_FLOW_TASK.EXECUTION_END_TIME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public Date getExecutionEndTime() {
    return executionEndTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DATA_FLOW_TASK.EXECUTION_END_TIME
   *
   * @param executionEndTime
   *          the value for dbo.DATA_FLOW_TASK.EXECUTION_END_TIME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setExecutionEndTime(Date executionEndTime) {
    this.executionEndTime = executionEndTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DATA_FLOW_TASK.FLOW_TYPE
   *
   * @return the value of dbo.DATA_FLOW_TASK.FLOW_TYPE
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public String getFlowType() {
    return flowType;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DATA_FLOW_TASK.FLOW_TYPE
   *
   * @param flowType
   *          the value for dbo.DATA_FLOW_TASK.FLOW_TYPE
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setFlowType(String flowType) {
    this.flowType = flowType == null ? null : flowType.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DATA_FLOW_TASK.FLOW_STATUS
   *
   * @return the value of dbo.DATA_FLOW_TASK.FLOW_STATUS
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public String getFlowStatus() {
    return flowStatus;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DATA_FLOW_TASK.FLOW_STATUS
   *
   * @param flowStatus
   *          the value for dbo.DATA_FLOW_TASK.FLOW_STATUS
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setFlowStatus(String flowStatus) {
    this.flowStatus = flowStatus == null ? null : flowStatus.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DATA_FLOW_TASK.INBOUND_FILE_ERROR
   *
   * @return the value of dbo.DATA_FLOW_TASK.INBOUND_FILE_ERROR
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public String getInboundFileError() {
    return inboundFileError;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DATA_FLOW_TASK.INBOUND_FILE_ERROR
   *
   * @param inboundFileError
   *          the value for dbo.DATA_FLOW_TASK.INBOUND_FILE_ERROR
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setInboundFileError(String inboundFileError) {
    this.inboundFileError = inboundFileError == null ? null : inboundFileError.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DATA_FLOW_TASK.TASK_CONTROL_ID
   *
   * @return the value of dbo.DATA_FLOW_TASK.TASK_CONTROL_ID
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public String getTaskControlId() {
    return taskControlId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DATA_FLOW_TASK.TASK_CONTROL_ID
   *
   * @param taskControlId
   *          the value for dbo.DATA_FLOW_TASK.TASK_CONTROL_ID
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setTaskControlId(String taskControlId) {
    this.taskControlId = taskControlId == null ? null : taskControlId.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DATA_FLOW_TASK.ERROR_TIME
   *
   * @return the value of dbo.DATA_FLOW_TASK.ERROR_TIME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public Date getErrorTime() {
    return errorTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DATA_FLOW_TASK.ERROR_TIME
   *
   * @param errorTime
   *          the value for dbo.DATA_FLOW_TASK.ERROR_TIME
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setErrorTime(Date errorTime) {
    this.errorTime = errorTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DATA_FLOW_TASK.ERROR_DESCRIPTION
   *
   * @return the value of dbo.DATA_FLOW_TASK.ERROR_DESCRIPTION
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public String getErrorDescription() {
    return errorDescription;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DATA_FLOW_TASK.ERROR_DESCRIPTION
   *
   * @param errorDescription
   *          the value for dbo.DATA_FLOW_TASK.ERROR_DESCRIPTION
   *
   * @mbggenerated Tue Feb 19 16:10:33 COT 2013
   */
  public void setErrorDescription(String errorDescription) {
    this.errorDescription = errorDescription == null ? null : errorDescription.trim();
  }
}