package com.cardif.satelite.model;

import java.io.Serializable;

public class SiniRoboKey implements Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.SINI_ROBO.NRO_SINIESTRO
   *
   * @mbggenerated Thu Jul 17 14:22:08 COT 2014
   */
  private String nroSiniestro;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.SINI_ROBO.PK_ROBO
   *
   * @mbggenerated Thu Jul 17 14:22:08 COT 2014
   */
  private String pkRobo;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.SINI_ROBO.NRO_SINIESTRO
   *
   * @return the value of dbo.SINI_ROBO.NRO_SINIESTRO
   *
   * @mbggenerated Thu Jul 17 14:22:08 COT 2014
   */
  public String getNroSiniestro() {
    return nroSiniestro;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.SINI_ROBO.NRO_SINIESTRO
   *
   * @param nroSiniestro
   *          the value for dbo.SINI_ROBO.NRO_SINIESTRO
   *
   * @mbggenerated Thu Jul 17 14:22:08 COT 2014
   */
  public void setNroSiniestro(String nroSiniestro) {
    this.nroSiniestro = nroSiniestro == null ? null : nroSiniestro.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.SINI_ROBO.PK_ROBO
   *
   * @return the value of dbo.SINI_ROBO.PK_ROBO
   *
   * @mbggenerated Thu Jul 17 14:22:08 COT 2014
   */
  public String getPkRobo() {
    return pkRobo;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.SINI_ROBO.PK_ROBO
   *
   * @param pkRobo
   *          the value for dbo.SINI_ROBO.PK_ROBO
   *
   * @mbggenerated Thu Jul 17 14:22:08 COT 2014
   */
  public void setPkRobo(String pkRobo) {
    this.pkRobo = pkRobo == null ? null : pkRobo.trim();
  }
}