package com.cardif.satelite.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SusTramaInterbankExample implements Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  public SusTramaInterbankExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andCodTramaIsNull() {
      addCriterion("COD_TRAMA is null");
      return (Criteria) this;
    }

    public Criteria andCodTramaIsNotNull() {
      addCriterion("COD_TRAMA is not null");
      return (Criteria) this;
    }

    public Criteria andCodTramaEqualTo(Long value) {
      addCriterion("COD_TRAMA =", value, "codTrama");
      return (Criteria) this;
    }

    public Criteria andCodTramaNotEqualTo(Long value) {
      addCriterion("COD_TRAMA <>", value, "codTrama");
      return (Criteria) this;
    }

    public Criteria andCodTramaGreaterThan(Long value) {
      addCriterion("COD_TRAMA >", value, "codTrama");
      return (Criteria) this;
    }

    public Criteria andCodTramaGreaterThanOrEqualTo(Long value) {
      addCriterion("COD_TRAMA >=", value, "codTrama");
      return (Criteria) this;
    }

    public Criteria andCodTramaLessThan(Long value) {
      addCriterion("COD_TRAMA <", value, "codTrama");
      return (Criteria) this;
    }

    public Criteria andCodTramaLessThanOrEqualTo(Long value) {
      addCriterion("COD_TRAMA <=", value, "codTrama");
      return (Criteria) this;
    }

    public Criteria andCodTramaIn(List<Long> values) {
      addCriterion("COD_TRAMA in", values, "codTrama");
      return (Criteria) this;
    }

    public Criteria andCodTramaNotIn(List<Long> values) {
      addCriterion("COD_TRAMA not in", values, "codTrama");
      return (Criteria) this;
    }

    public Criteria andCodTramaBetween(Long value1, Long value2) {
      addCriterion("COD_TRAMA between", value1, value2, "codTrama");
      return (Criteria) this;
    }

    public Criteria andCodTramaNotBetween(Long value1, Long value2) {
      addCriterion("COD_TRAMA not between", value1, value2, "codTrama");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoIsNull() {
      addCriterion("NRO_CERTIFICADO is null");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoIsNotNull() {
      addCriterion("NRO_CERTIFICADO is not null");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoEqualTo(String value) {
      addCriterion("NRO_CERTIFICADO =", value, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoNotEqualTo(String value) {
      addCriterion("NRO_CERTIFICADO <>", value, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoGreaterThan(String value) {
      addCriterion("NRO_CERTIFICADO >", value, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoGreaterThanOrEqualTo(String value) {
      addCriterion("NRO_CERTIFICADO >=", value, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoLessThan(String value) {
      addCriterion("NRO_CERTIFICADO <", value, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoLessThanOrEqualTo(String value) {
      addCriterion("NRO_CERTIFICADO <=", value, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoLike(String value) {
      addCriterion("NRO_CERTIFICADO like", value, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoNotLike(String value) {
      addCriterion("NRO_CERTIFICADO not like", value, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoIn(List<String> values) {
      addCriterion("NRO_CERTIFICADO in", values, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoNotIn(List<String> values) {
      addCriterion("NRO_CERTIFICADO not in", values, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoBetween(String value1, String value2) {
      addCriterion("NRO_CERTIFICADO between", value1, value2, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoNotBetween(String value1, String value2) {
      addCriterion("NRO_CERTIFICADO not between", value1, value2, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andEstAnulacionIsNull() {
      addCriterion("EST_ANULACION is null");
      return (Criteria) this;
    }

    public Criteria andEstAnulacionIsNotNull() {
      addCriterion("EST_ANULACION is not null");
      return (Criteria) this;
    }

    public Criteria andEstAnulacionEqualTo(String value) {
      addCriterion("EST_ANULACION =", value, "estAnulacion");
      return (Criteria) this;
    }

    public Criteria andEstAnulacionNotEqualTo(String value) {
      addCriterion("EST_ANULACION <>", value, "estAnulacion");
      return (Criteria) this;
    }

    public Criteria andEstAnulacionGreaterThan(String value) {
      addCriterion("EST_ANULACION >", value, "estAnulacion");
      return (Criteria) this;
    }

    public Criteria andEstAnulacionGreaterThanOrEqualTo(String value) {
      addCriterion("EST_ANULACION >=", value, "estAnulacion");
      return (Criteria) this;
    }

    public Criteria andEstAnulacionLessThan(String value) {
      addCriterion("EST_ANULACION <", value, "estAnulacion");
      return (Criteria) this;
    }

    public Criteria andEstAnulacionLessThanOrEqualTo(String value) {
      addCriterion("EST_ANULACION <=", value, "estAnulacion");
      return (Criteria) this;
    }

    public Criteria andEstAnulacionLike(String value) {
      addCriterion("EST_ANULACION like", value, "estAnulacion");
      return (Criteria) this;
    }

    public Criteria andEstAnulacionNotLike(String value) {
      addCriterion("EST_ANULACION not like", value, "estAnulacion");
      return (Criteria) this;
    }

    public Criteria andEstAnulacionIn(List<String> values) {
      addCriterion("EST_ANULACION in", values, "estAnulacion");
      return (Criteria) this;
    }

    public Criteria andEstAnulacionNotIn(List<String> values) {
      addCriterion("EST_ANULACION not in", values, "estAnulacion");
      return (Criteria) this;
    }

    public Criteria andEstAnulacionBetween(String value1, String value2) {
      addCriterion("EST_ANULACION between", value1, value2, "estAnulacion");
      return (Criteria) this;
    }

    public Criteria andEstAnulacionNotBetween(String value1, String value2) {
      addCriterion("EST_ANULACION not between", value1, value2, "estAnulacion");
      return (Criteria) this;
    }

    public Criteria andNroCuotasIsNull() {
      addCriterion("NRO_CUOTAS is null");
      return (Criteria) this;
    }

    public Criteria andNroCuotasIsNotNull() {
      addCriterion("NRO_CUOTAS is not null");
      return (Criteria) this;
    }

    public Criteria andNroCuotasEqualTo(Long value) {
      addCriterion("NRO_CUOTAS =", value, "nroCuotas");
      return (Criteria) this;
    }

    public Criteria andNroCuotasNotEqualTo(Long value) {
      addCriterion("NRO_CUOTAS <>", value, "nroCuotas");
      return (Criteria) this;
    }

    public Criteria andNroCuotasGreaterThan(Long value) {
      addCriterion("NRO_CUOTAS >", value, "nroCuotas");
      return (Criteria) this;
    }

    public Criteria andNroCuotasGreaterThanOrEqualTo(Long value) {
      addCriterion("NRO_CUOTAS >=", value, "nroCuotas");
      return (Criteria) this;
    }

    public Criteria andNroCuotasLessThan(Long value) {
      addCriterion("NRO_CUOTAS <", value, "nroCuotas");
      return (Criteria) this;
    }

    public Criteria andNroCuotasLessThanOrEqualTo(Long value) {
      addCriterion("NRO_CUOTAS <=", value, "nroCuotas");
      return (Criteria) this;
    }

    public Criteria andNroCuotasIn(List<Long> values) {
      addCriterion("NRO_CUOTAS in", values, "nroCuotas");
      return (Criteria) this;
    }

    public Criteria andNroCuotasNotIn(List<Long> values) {
      addCriterion("NRO_CUOTAS not in", values, "nroCuotas");
      return (Criteria) this;
    }

    public Criteria andNroCuotasBetween(Long value1, Long value2) {
      addCriterion("NRO_CUOTAS between", value1, value2, "nroCuotas");
      return (Criteria) this;
    }

    public Criteria andNroCuotasNotBetween(Long value1, Long value2) {
      addCriterion("NRO_CUOTAS not between", value1, value2, "nroCuotas");
      return (Criteria) this;
    }

    public Criteria andTotDevolverIsNull() {
      addCriterion("TOT_DEVOLVER is null");
      return (Criteria) this;
    }

    public Criteria andTotDevolverIsNotNull() {
      addCriterion("TOT_DEVOLVER is not null");
      return (Criteria) this;
    }

    public Criteria andTotDevolverEqualTo(BigDecimal value) {
      addCriterion("TOT_DEVOLVER =", value, "totDevolver");
      return (Criteria) this;
    }

    public Criteria andTotDevolverNotEqualTo(BigDecimal value) {
      addCriterion("TOT_DEVOLVER <>", value, "totDevolver");
      return (Criteria) this;
    }

    public Criteria andTotDevolverGreaterThan(BigDecimal value) {
      addCriterion("TOT_DEVOLVER >", value, "totDevolver");
      return (Criteria) this;
    }

    public Criteria andTotDevolverGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("TOT_DEVOLVER >=", value, "totDevolver");
      return (Criteria) this;
    }

    public Criteria andTotDevolverLessThan(BigDecimal value) {
      addCriterion("TOT_DEVOLVER <", value, "totDevolver");
      return (Criteria) this;
    }

    public Criteria andTotDevolverLessThanOrEqualTo(BigDecimal value) {
      addCriterion("TOT_DEVOLVER <=", value, "totDevolver");
      return (Criteria) this;
    }

    public Criteria andTotDevolverIn(List<BigDecimal> values) {
      addCriterion("TOT_DEVOLVER in", values, "totDevolver");
      return (Criteria) this;
    }

    public Criteria andTotDevolverNotIn(List<BigDecimal> values) {
      addCriterion("TOT_DEVOLVER not in", values, "totDevolver");
      return (Criteria) this;
    }

    public Criteria andTotDevolverBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("TOT_DEVOLVER between", value1, value2, "totDevolver");
      return (Criteria) this;
    }

    public Criteria andTotDevolverNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("TOT_DEVOLVER not between", value1, value2, "totDevolver");
      return (Criteria) this;
    }

    public Criteria andFecSolAnulacionIsNull() {
      addCriterion("FEC_SOL_ANULACION is null");
      return (Criteria) this;
    }

    public Criteria andFecSolAnulacionIsNotNull() {
      addCriterion("FEC_SOL_ANULACION is not null");
      return (Criteria) this;
    }

    public Criteria andFecSolAnulacionEqualTo(Date value) {
      addCriterion("FEC_SOL_ANULACION =", value, "fecSolAnulacion");
      return (Criteria) this;
    }

    public Criteria andFecSolAnulacionNotEqualTo(Date value) {
      addCriterion("FEC_SOL_ANULACION <>", value, "fecSolAnulacion");
      return (Criteria) this;
    }

    public Criteria andFecSolAnulacionGreaterThan(Date value) {
      addCriterion("FEC_SOL_ANULACION >", value, "fecSolAnulacion");
      return (Criteria) this;
    }

    public Criteria andFecSolAnulacionGreaterThanOrEqualTo(Date value) {
      addCriterion("FEC_SOL_ANULACION >=", value, "fecSolAnulacion");
      return (Criteria) this;
    }

    public Criteria andFecSolAnulacionLessThan(Date value) {
      addCriterion("FEC_SOL_ANULACION <", value, "fecSolAnulacion");
      return (Criteria) this;
    }

    public Criteria andFecSolAnulacionLessThanOrEqualTo(Date value) {
      addCriterion("FEC_SOL_ANULACION <=", value, "fecSolAnulacion");
      return (Criteria) this;
    }

    public Criteria andFecSolAnulacionIn(List<Date> values) {
      addCriterion("FEC_SOL_ANULACION in", values, "fecSolAnulacion");
      return (Criteria) this;
    }

    public Criteria andFecSolAnulacionNotIn(List<Date> values) {
      addCriterion("FEC_SOL_ANULACION not in", values, "fecSolAnulacion");
      return (Criteria) this;
    }

    public Criteria andFecSolAnulacionBetween(Date value1, Date value2) {
      addCriterion("FEC_SOL_ANULACION between", value1, value2, "fecSolAnulacion");
      return (Criteria) this;
    }

    public Criteria andFecSolAnulacionNotBetween(Date value1, Date value2) {
      addCriterion("FEC_SOL_ANULACION not between", value1, value2, "fecSolAnulacion");
      return (Criteria) this;
    }

    public Criteria andProductoIsNull() {
      addCriterion("PRODUCTO is null");
      return (Criteria) this;
    }

    public Criteria andProductoIsNotNull() {
      addCriterion("PRODUCTO is not null");
      return (Criteria) this;
    }

    public Criteria andProductoEqualTo(String value) {
      addCriterion("PRODUCTO =", value, "producto");
      return (Criteria) this;
    }

    public Criteria andProductoNotEqualTo(String value) {
      addCriterion("PRODUCTO <>", value, "producto");
      return (Criteria) this;
    }

    public Criteria andProductoGreaterThan(String value) {
      addCriterion("PRODUCTO >", value, "producto");
      return (Criteria) this;
    }

    public Criteria andProductoGreaterThanOrEqualTo(String value) {
      addCriterion("PRODUCTO >=", value, "producto");
      return (Criteria) this;
    }

    public Criteria andProductoLessThan(String value) {
      addCriterion("PRODUCTO <", value, "producto");
      return (Criteria) this;
    }

    public Criteria andProductoLessThanOrEqualTo(String value) {
      addCriterion("PRODUCTO <=", value, "producto");
      return (Criteria) this;
    }

    public Criteria andProductoLike(String value) {
      addCriterion("PRODUCTO like", value, "producto");
      return (Criteria) this;
    }

    public Criteria andProductoNotLike(String value) {
      addCriterion("PRODUCTO not like", value, "producto");
      return (Criteria) this;
    }

    public Criteria andProductoIn(List<String> values) {
      addCriterion("PRODUCTO in", values, "producto");
      return (Criteria) this;
    }

    public Criteria andProductoNotIn(List<String> values) {
      addCriterion("PRODUCTO not in", values, "producto");
      return (Criteria) this;
    }

    public Criteria andProductoBetween(String value1, String value2) {
      addCriterion("PRODUCTO between", value1, value2, "producto");
      return (Criteria) this;
    }

    public Criteria andProductoNotBetween(String value1, String value2) {
      addCriterion("PRODUCTO not between", value1, value2, "producto");
      return (Criteria) this;
    }

    public Criteria andTipoPlanIsNull() {
      addCriterion("TIPO_PLAN is null");
      return (Criteria) this;
    }

    public Criteria andTipoPlanIsNotNull() {
      addCriterion("TIPO_PLAN is not null");
      return (Criteria) this;
    }

    public Criteria andTipoPlanEqualTo(String value) {
      addCriterion("TIPO_PLAN =", value, "tipoPlan");
      return (Criteria) this;
    }

    public Criteria andTipoPlanNotEqualTo(String value) {
      addCriterion("TIPO_PLAN <>", value, "tipoPlan");
      return (Criteria) this;
    }

    public Criteria andTipoPlanGreaterThan(String value) {
      addCriterion("TIPO_PLAN >", value, "tipoPlan");
      return (Criteria) this;
    }

    public Criteria andTipoPlanGreaterThanOrEqualTo(String value) {
      addCriterion("TIPO_PLAN >=", value, "tipoPlan");
      return (Criteria) this;
    }

    public Criteria andTipoPlanLessThan(String value) {
      addCriterion("TIPO_PLAN <", value, "tipoPlan");
      return (Criteria) this;
    }

    public Criteria andTipoPlanLessThanOrEqualTo(String value) {
      addCriterion("TIPO_PLAN <=", value, "tipoPlan");
      return (Criteria) this;
    }

    public Criteria andTipoPlanLike(String value) {
      addCriterion("TIPO_PLAN like", value, "tipoPlan");
      return (Criteria) this;
    }

    public Criteria andTipoPlanNotLike(String value) {
      addCriterion("TIPO_PLAN not like", value, "tipoPlan");
      return (Criteria) this;
    }

    public Criteria andTipoPlanIn(List<String> values) {
      addCriterion("TIPO_PLAN in", values, "tipoPlan");
      return (Criteria) this;
    }

    public Criteria andTipoPlanNotIn(List<String> values) {
      addCriterion("TIPO_PLAN not in", values, "tipoPlan");
      return (Criteria) this;
    }

    public Criteria andTipoPlanBetween(String value1, String value2) {
      addCriterion("TIPO_PLAN between", value1, value2, "tipoPlan");
      return (Criteria) this;
    }

    public Criteria andTipoPlanNotBetween(String value1, String value2) {
      addCriterion("TIPO_PLAN not between", value1, value2, "tipoPlan");
      return (Criteria) this;
    }

    public Criteria andCodOficinaIsNull() {
      addCriterion("COD_OFICINA is null");
      return (Criteria) this;
    }

    public Criteria andCodOficinaIsNotNull() {
      addCriterion("COD_OFICINA is not null");
      return (Criteria) this;
    }

    public Criteria andCodOficinaEqualTo(Long value) {
      addCriterion("COD_OFICINA =", value, "codOficina");
      return (Criteria) this;
    }

    public Criteria andCodOficinaNotEqualTo(Long value) {
      addCriterion("COD_OFICINA <>", value, "codOficina");
      return (Criteria) this;
    }

    public Criteria andCodOficinaGreaterThan(Long value) {
      addCriterion("COD_OFICINA >", value, "codOficina");
      return (Criteria) this;
    }

    public Criteria andCodOficinaGreaterThanOrEqualTo(Long value) {
      addCriterion("COD_OFICINA >=", value, "codOficina");
      return (Criteria) this;
    }

    public Criteria andCodOficinaLessThan(Long value) {
      addCriterion("COD_OFICINA <", value, "codOficina");
      return (Criteria) this;
    }

    public Criteria andCodOficinaLessThanOrEqualTo(Long value) {
      addCriterion("COD_OFICINA <=", value, "codOficina");
      return (Criteria) this;
    }

    public Criteria andCodOficinaIn(List<Long> values) {
      addCriterion("COD_OFICINA in", values, "codOficina");
      return (Criteria) this;
    }

    public Criteria andCodOficinaNotIn(List<Long> values) {
      addCriterion("COD_OFICINA not in", values, "codOficina");
      return (Criteria) this;
    }

    public Criteria andCodOficinaBetween(Long value1, Long value2) {
      addCriterion("COD_OFICINA between", value1, value2, "codOficina");
      return (Criteria) this;
    }

    public Criteria andCodOficinaNotBetween(Long value1, Long value2) {
      addCriterion("COD_OFICINA not between", value1, value2, "codOficina");
      return (Criteria) this;
    }

    public Criteria andCodVendedorIsNull() {
      addCriterion("COD_VENDEDOR is null");
      return (Criteria) this;
    }

    public Criteria andCodVendedorIsNotNull() {
      addCriterion("COD_VENDEDOR is not null");
      return (Criteria) this;
    }

    public Criteria andCodVendedorEqualTo(String value) {
      addCriterion("COD_VENDEDOR =", value, "codVendedor");
      return (Criteria) this;
    }

    public Criteria andCodVendedorNotEqualTo(String value) {
      addCriterion("COD_VENDEDOR <>", value, "codVendedor");
      return (Criteria) this;
    }

    public Criteria andCodVendedorGreaterThan(String value) {
      addCriterion("COD_VENDEDOR >", value, "codVendedor");
      return (Criteria) this;
    }

    public Criteria andCodVendedorGreaterThanOrEqualTo(String value) {
      addCriterion("COD_VENDEDOR >=", value, "codVendedor");
      return (Criteria) this;
    }

    public Criteria andCodVendedorLessThan(String value) {
      addCriterion("COD_VENDEDOR <", value, "codVendedor");
      return (Criteria) this;
    }

    public Criteria andCodVendedorLessThanOrEqualTo(String value) {
      addCriterion("COD_VENDEDOR <=", value, "codVendedor");
      return (Criteria) this;
    }

    public Criteria andCodVendedorLike(String value) {
      addCriterion("COD_VENDEDOR like", value, "codVendedor");
      return (Criteria) this;
    }

    public Criteria andCodVendedorNotLike(String value) {
      addCriterion("COD_VENDEDOR not like", value, "codVendedor");
      return (Criteria) this;
    }

    public Criteria andCodVendedorIn(List<String> values) {
      addCriterion("COD_VENDEDOR in", values, "codVendedor");
      return (Criteria) this;
    }

    public Criteria andCodVendedorNotIn(List<String> values) {
      addCriterion("COD_VENDEDOR not in", values, "codVendedor");
      return (Criteria) this;
    }

    public Criteria andCodVendedorBetween(String value1, String value2) {
      addCriterion("COD_VENDEDOR between", value1, value2, "codVendedor");
      return (Criteria) this;
    }

    public Criteria andCodVendedorNotBetween(String value1, String value2) {
      addCriterion("COD_VENDEDOR not between", value1, value2, "codVendedor");
      return (Criteria) this;
    }

    public Criteria andMedPagoIsNull() {
      addCriterion("MED_PAGO is null");
      return (Criteria) this;
    }

    public Criteria andMedPagoIsNotNull() {
      addCriterion("MED_PAGO is not null");
      return (Criteria) this;
    }

    public Criteria andMedPagoEqualTo(String value) {
      addCriterion("MED_PAGO =", value, "medPago");
      return (Criteria) this;
    }

    public Criteria andMedPagoNotEqualTo(String value) {
      addCriterion("MED_PAGO <>", value, "medPago");
      return (Criteria) this;
    }

    public Criteria andMedPagoGreaterThan(String value) {
      addCriterion("MED_PAGO >", value, "medPago");
      return (Criteria) this;
    }

    public Criteria andMedPagoGreaterThanOrEqualTo(String value) {
      addCriterion("MED_PAGO >=", value, "medPago");
      return (Criteria) this;
    }

    public Criteria andMedPagoLessThan(String value) {
      addCriterion("MED_PAGO <", value, "medPago");
      return (Criteria) this;
    }

    public Criteria andMedPagoLessThanOrEqualTo(String value) {
      addCriterion("MED_PAGO <=", value, "medPago");
      return (Criteria) this;
    }

    public Criteria andMedPagoLike(String value) {
      addCriterion("MED_PAGO like", value, "medPago");
      return (Criteria) this;
    }

    public Criteria andMedPagoNotLike(String value) {
      addCriterion("MED_PAGO not like", value, "medPago");
      return (Criteria) this;
    }

    public Criteria andMedPagoIn(List<String> values) {
      addCriterion("MED_PAGO in", values, "medPago");
      return (Criteria) this;
    }

    public Criteria andMedPagoNotIn(List<String> values) {
      addCriterion("MED_PAGO not in", values, "medPago");
      return (Criteria) this;
    }

    public Criteria andMedPagoBetween(String value1, String value2) {
      addCriterion("MED_PAGO between", value1, value2, "medPago");
      return (Criteria) this;
    }

    public Criteria andMedPagoNotBetween(String value1, String value2) {
      addCriterion("MED_PAGO not between", value1, value2, "medPago");
      return (Criteria) this;
    }

    public Criteria andEstCertificadoIsNull() {
      addCriterion("EST_CERTIFICADO is null");
      return (Criteria) this;
    }

    public Criteria andEstCertificadoIsNotNull() {
      addCriterion("EST_CERTIFICADO is not null");
      return (Criteria) this;
    }

    public Criteria andEstCertificadoEqualTo(Long value) {
      addCriterion("EST_CERTIFICADO =", value, "estCertificado");
      return (Criteria) this;
    }

    public Criteria andEstCertificadoNotEqualTo(Long value) {
      addCriterion("EST_CERTIFICADO <>", value, "estCertificado");
      return (Criteria) this;
    }

    public Criteria andEstCertificadoGreaterThan(Long value) {
      addCriterion("EST_CERTIFICADO >", value, "estCertificado");
      return (Criteria) this;
    }

    public Criteria andEstCertificadoGreaterThanOrEqualTo(Long value) {
      addCriterion("EST_CERTIFICADO >=", value, "estCertificado");
      return (Criteria) this;
    }

    public Criteria andEstCertificadoLessThan(Long value) {
      addCriterion("EST_CERTIFICADO <", value, "estCertificado");
      return (Criteria) this;
    }

    public Criteria andEstCertificadoLessThanOrEqualTo(Long value) {
      addCriterion("EST_CERTIFICADO <=", value, "estCertificado");
      return (Criteria) this;
    }

    public Criteria andEstCertificadoIn(List<Long> values) {
      addCriterion("EST_CERTIFICADO in", values, "estCertificado");
      return (Criteria) this;
    }

    public Criteria andEstCertificadoNotIn(List<Long> values) {
      addCriterion("EST_CERTIFICADO not in", values, "estCertificado");
      return (Criteria) this;
    }

    public Criteria andEstCertificadoBetween(Long value1, Long value2) {
      addCriterion("EST_CERTIFICADO between", value1, value2, "estCertificado");
      return (Criteria) this;
    }

    public Criteria andEstCertificadoNotBetween(Long value1, Long value2) {
      addCriterion("EST_CERTIFICADO not between", value1, value2, "estCertificado");
      return (Criteria) this;
    }

    public Criteria andPrimaIsNull() {
      addCriterion("PRIMA is null");
      return (Criteria) this;
    }

    public Criteria andPrimaIsNotNull() {
      addCriterion("PRIMA is not null");
      return (Criteria) this;
    }

    public Criteria andPrimaEqualTo(Long value) {
      addCriterion("PRIMA =", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaNotEqualTo(Long value) {
      addCriterion("PRIMA <>", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaGreaterThan(Long value) {
      addCriterion("PRIMA >", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaGreaterThanOrEqualTo(Long value) {
      addCriterion("PRIMA >=", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaLessThan(Long value) {
      addCriterion("PRIMA <", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaLessThanOrEqualTo(Long value) {
      addCriterion("PRIMA <=", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaIn(List<Long> values) {
      addCriterion("PRIMA in", values, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaNotIn(List<Long> values) {
      addCriterion("PRIMA not in", values, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaBetween(Long value1, Long value2) {
      addCriterion("PRIMA between", value1, value2, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaNotBetween(Long value1, Long value2) {
      addCriterion("PRIMA not between", value1, value2, "prima");
      return (Criteria) this;
    }

    public Criteria andMonPrimaIsNull() {
      addCriterion("MON_PRIMA is null");
      return (Criteria) this;
    }

    public Criteria andMonPrimaIsNotNull() {
      addCriterion("MON_PRIMA is not null");
      return (Criteria) this;
    }

    public Criteria andMonPrimaEqualTo(String value) {
      addCriterion("MON_PRIMA =", value, "monPrima");
      return (Criteria) this;
    }

    public Criteria andMonPrimaNotEqualTo(String value) {
      addCriterion("MON_PRIMA <>", value, "monPrima");
      return (Criteria) this;
    }

    public Criteria andMonPrimaGreaterThan(String value) {
      addCriterion("MON_PRIMA >", value, "monPrima");
      return (Criteria) this;
    }

    public Criteria andMonPrimaGreaterThanOrEqualTo(String value) {
      addCriterion("MON_PRIMA >=", value, "monPrima");
      return (Criteria) this;
    }

    public Criteria andMonPrimaLessThan(String value) {
      addCriterion("MON_PRIMA <", value, "monPrima");
      return (Criteria) this;
    }

    public Criteria andMonPrimaLessThanOrEqualTo(String value) {
      addCriterion("MON_PRIMA <=", value, "monPrima");
      return (Criteria) this;
    }

    public Criteria andMonPrimaLike(String value) {
      addCriterion("MON_PRIMA like", value, "monPrima");
      return (Criteria) this;
    }

    public Criteria andMonPrimaNotLike(String value) {
      addCriterion("MON_PRIMA not like", value, "monPrima");
      return (Criteria) this;
    }

    public Criteria andMonPrimaIn(List<String> values) {
      addCriterion("MON_PRIMA in", values, "monPrima");
      return (Criteria) this;
    }

    public Criteria andMonPrimaNotIn(List<String> values) {
      addCriterion("MON_PRIMA not in", values, "monPrima");
      return (Criteria) this;
    }

    public Criteria andMonPrimaBetween(String value1, String value2) {
      addCriterion("MON_PRIMA between", value1, value2, "monPrima");
      return (Criteria) this;
    }

    public Criteria andMonPrimaNotBetween(String value1, String value2) {
      addCriterion("MON_PRIMA not between", value1, value2, "monPrima");
      return (Criteria) this;
    }

    public Criteria andFecInicioVigenciaIsNull() {
      addCriterion("FEC_INICIO_VIGENCIA is null");
      return (Criteria) this;
    }

    public Criteria andFecInicioVigenciaIsNotNull() {
      addCriterion("FEC_INICIO_VIGENCIA is not null");
      return (Criteria) this;
    }

    public Criteria andFecInicioVigenciaEqualTo(Date value) {
      addCriterion("FEC_INICIO_VIGENCIA =", value, "fecInicioVigencia");
      return (Criteria) this;
    }

    public Criteria andFecInicioVigenciaNotEqualTo(Date value) {
      addCriterion("FEC_INICIO_VIGENCIA <>", value, "fecInicioVigencia");
      return (Criteria) this;
    }

    public Criteria andFecInicioVigenciaGreaterThan(Date value) {
      addCriterion("FEC_INICIO_VIGENCIA >", value, "fecInicioVigencia");
      return (Criteria) this;
    }

    public Criteria andFecInicioVigenciaGreaterThanOrEqualTo(Date value) {
      addCriterion("FEC_INICIO_VIGENCIA >=", value, "fecInicioVigencia");
      return (Criteria) this;
    }

    public Criteria andFecInicioVigenciaLessThan(Date value) {
      addCriterion("FEC_INICIO_VIGENCIA <", value, "fecInicioVigencia");
      return (Criteria) this;
    }

    public Criteria andFecInicioVigenciaLessThanOrEqualTo(Date value) {
      addCriterion("FEC_INICIO_VIGENCIA <=", value, "fecInicioVigencia");
      return (Criteria) this;
    }

    public Criteria andFecInicioVigenciaIn(List<Date> values) {
      addCriterion("FEC_INICIO_VIGENCIA in", values, "fecInicioVigencia");
      return (Criteria) this;
    }

    public Criteria andFecInicioVigenciaNotIn(List<Date> values) {
      addCriterion("FEC_INICIO_VIGENCIA not in", values, "fecInicioVigencia");
      return (Criteria) this;
    }

    public Criteria andFecInicioVigenciaBetween(Date value1, Date value2) {
      addCriterion("FEC_INICIO_VIGENCIA between", value1, value2, "fecInicioVigencia");
      return (Criteria) this;
    }

    public Criteria andFecInicioVigenciaNotBetween(Date value1, Date value2) {
      addCriterion("FEC_INICIO_VIGENCIA not between", value1, value2, "fecInicioVigencia");
      return (Criteria) this;
    }

    public Criteria andNom1CerIsNull() {
      addCriterion("NOM1_CER is null");
      return (Criteria) this;
    }

    public Criteria andNom1CerIsNotNull() {
      addCriterion("NOM1_CER is not null");
      return (Criteria) this;
    }

    public Criteria andNom1CerEqualTo(String value) {
      addCriterion("NOM1_CER =", value, "nom1Cer");
      return (Criteria) this;
    }

    public Criteria andNom1CerNotEqualTo(String value) {
      addCriterion("NOM1_CER <>", value, "nom1Cer");
      return (Criteria) this;
    }

    public Criteria andNom1CerGreaterThan(String value) {
      addCriterion("NOM1_CER >", value, "nom1Cer");
      return (Criteria) this;
    }

    public Criteria andNom1CerGreaterThanOrEqualTo(String value) {
      addCriterion("NOM1_CER >=", value, "nom1Cer");
      return (Criteria) this;
    }

    public Criteria andNom1CerLessThan(String value) {
      addCriterion("NOM1_CER <", value, "nom1Cer");
      return (Criteria) this;
    }

    public Criteria andNom1CerLessThanOrEqualTo(String value) {
      addCriterion("NOM1_CER <=", value, "nom1Cer");
      return (Criteria) this;
    }

    public Criteria andNom1CerLike(String value) {
      addCriterion("NOM1_CER like", value, "nom1Cer");
      return (Criteria) this;
    }

    public Criteria andNom1CerNotLike(String value) {
      addCriterion("NOM1_CER not like", value, "nom1Cer");
      return (Criteria) this;
    }

    public Criteria andNom1CerIn(List<String> values) {
      addCriterion("NOM1_CER in", values, "nom1Cer");
      return (Criteria) this;
    }

    public Criteria andNom1CerNotIn(List<String> values) {
      addCriterion("NOM1_CER not in", values, "nom1Cer");
      return (Criteria) this;
    }

    public Criteria andNom1CerBetween(String value1, String value2) {
      addCriterion("NOM1_CER between", value1, value2, "nom1Cer");
      return (Criteria) this;
    }

    public Criteria andNom1CerNotBetween(String value1, String value2) {
      addCriterion("NOM1_CER not between", value1, value2, "nom1Cer");
      return (Criteria) this;
    }

    public Criteria andNom2CerIsNull() {
      addCriterion("NOM2_CER is null");
      return (Criteria) this;
    }

    public Criteria andNom2CerIsNotNull() {
      addCriterion("NOM2_CER is not null");
      return (Criteria) this;
    }

    public Criteria andNom2CerEqualTo(String value) {
      addCriterion("NOM2_CER =", value, "nom2Cer");
      return (Criteria) this;
    }

    public Criteria andNom2CerNotEqualTo(String value) {
      addCriterion("NOM2_CER <>", value, "nom2Cer");
      return (Criteria) this;
    }

    public Criteria andNom2CerGreaterThan(String value) {
      addCriterion("NOM2_CER >", value, "nom2Cer");
      return (Criteria) this;
    }

    public Criteria andNom2CerGreaterThanOrEqualTo(String value) {
      addCriterion("NOM2_CER >=", value, "nom2Cer");
      return (Criteria) this;
    }

    public Criteria andNom2CerLessThan(String value) {
      addCriterion("NOM2_CER <", value, "nom2Cer");
      return (Criteria) this;
    }

    public Criteria andNom2CerLessThanOrEqualTo(String value) {
      addCriterion("NOM2_CER <=", value, "nom2Cer");
      return (Criteria) this;
    }

    public Criteria andNom2CerLike(String value) {
      addCriterion("NOM2_CER like", value, "nom2Cer");
      return (Criteria) this;
    }

    public Criteria andNom2CerNotLike(String value) {
      addCriterion("NOM2_CER not like", value, "nom2Cer");
      return (Criteria) this;
    }

    public Criteria andNom2CerIn(List<String> values) {
      addCriterion("NOM2_CER in", values, "nom2Cer");
      return (Criteria) this;
    }

    public Criteria andNom2CerNotIn(List<String> values) {
      addCriterion("NOM2_CER not in", values, "nom2Cer");
      return (Criteria) this;
    }

    public Criteria andNom2CerBetween(String value1, String value2) {
      addCriterion("NOM2_CER between", value1, value2, "nom2Cer");
      return (Criteria) this;
    }

    public Criteria andNom2CerNotBetween(String value1, String value2) {
      addCriterion("NOM2_CER not between", value1, value2, "nom2Cer");
      return (Criteria) this;
    }

    public Criteria andApe1CerIsNull() {
      addCriterion("APE1_CER is null");
      return (Criteria) this;
    }

    public Criteria andApe1CerIsNotNull() {
      addCriterion("APE1_CER is not null");
      return (Criteria) this;
    }

    public Criteria andApe1CerEqualTo(String value) {
      addCriterion("APE1_CER =", value, "ape1Cer");
      return (Criteria) this;
    }

    public Criteria andApe1CerNotEqualTo(String value) {
      addCriterion("APE1_CER <>", value, "ape1Cer");
      return (Criteria) this;
    }

    public Criteria andApe1CerGreaterThan(String value) {
      addCriterion("APE1_CER >", value, "ape1Cer");
      return (Criteria) this;
    }

    public Criteria andApe1CerGreaterThanOrEqualTo(String value) {
      addCriterion("APE1_CER >=", value, "ape1Cer");
      return (Criteria) this;
    }

    public Criteria andApe1CerLessThan(String value) {
      addCriterion("APE1_CER <", value, "ape1Cer");
      return (Criteria) this;
    }

    public Criteria andApe1CerLessThanOrEqualTo(String value) {
      addCriterion("APE1_CER <=", value, "ape1Cer");
      return (Criteria) this;
    }

    public Criteria andApe1CerLike(String value) {
      addCriterion("APE1_CER like", value, "ape1Cer");
      return (Criteria) this;
    }

    public Criteria andApe1CerNotLike(String value) {
      addCriterion("APE1_CER not like", value, "ape1Cer");
      return (Criteria) this;
    }

    public Criteria andApe1CerIn(List<String> values) {
      addCriterion("APE1_CER in", values, "ape1Cer");
      return (Criteria) this;
    }

    public Criteria andApe1CerNotIn(List<String> values) {
      addCriterion("APE1_CER not in", values, "ape1Cer");
      return (Criteria) this;
    }

    public Criteria andApe1CerBetween(String value1, String value2) {
      addCriterion("APE1_CER between", value1, value2, "ape1Cer");
      return (Criteria) this;
    }

    public Criteria andApe1CerNotBetween(String value1, String value2) {
      addCriterion("APE1_CER not between", value1, value2, "ape1Cer");
      return (Criteria) this;
    }

    public Criteria andApe2CerIsNull() {
      addCriterion("APE2_CER is null");
      return (Criteria) this;
    }

    public Criteria andApe2CerIsNotNull() {
      addCriterion("APE2_CER is not null");
      return (Criteria) this;
    }

    public Criteria andApe2CerEqualTo(String value) {
      addCriterion("APE2_CER =", value, "ape2Cer");
      return (Criteria) this;
    }

    public Criteria andApe2CerNotEqualTo(String value) {
      addCriterion("APE2_CER <>", value, "ape2Cer");
      return (Criteria) this;
    }

    public Criteria andApe2CerGreaterThan(String value) {
      addCriterion("APE2_CER >", value, "ape2Cer");
      return (Criteria) this;
    }

    public Criteria andApe2CerGreaterThanOrEqualTo(String value) {
      addCriterion("APE2_CER >=", value, "ape2Cer");
      return (Criteria) this;
    }

    public Criteria andApe2CerLessThan(String value) {
      addCriterion("APE2_CER <", value, "ape2Cer");
      return (Criteria) this;
    }

    public Criteria andApe2CerLessThanOrEqualTo(String value) {
      addCriterion("APE2_CER <=", value, "ape2Cer");
      return (Criteria) this;
    }

    public Criteria andApe2CerLike(String value) {
      addCriterion("APE2_CER like", value, "ape2Cer");
      return (Criteria) this;
    }

    public Criteria andApe2CerNotLike(String value) {
      addCriterion("APE2_CER not like", value, "ape2Cer");
      return (Criteria) this;
    }

    public Criteria andApe2CerIn(List<String> values) {
      addCriterion("APE2_CER in", values, "ape2Cer");
      return (Criteria) this;
    }

    public Criteria andApe2CerNotIn(List<String> values) {
      addCriterion("APE2_CER not in", values, "ape2Cer");
      return (Criteria) this;
    }

    public Criteria andApe2CerBetween(String value1, String value2) {
      addCriterion("APE2_CER between", value1, value2, "ape2Cer");
      return (Criteria) this;
    }

    public Criteria andApe2CerNotBetween(String value1, String value2) {
      addCriterion("APE2_CER not between", value1, value2, "ape2Cer");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoIsNull() {
      addCriterion("NRO_DOCUMENTO is null");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoIsNotNull() {
      addCriterion("NRO_DOCUMENTO is not null");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoEqualTo(String value) {
      addCriterion("NRO_DOCUMENTO =", value, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoNotEqualTo(String value) {
      addCriterion("NRO_DOCUMENTO <>", value, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoGreaterThan(String value) {
      addCriterion("NRO_DOCUMENTO >", value, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoGreaterThanOrEqualTo(String value) {
      addCriterion("NRO_DOCUMENTO >=", value, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoLessThan(String value) {
      addCriterion("NRO_DOCUMENTO <", value, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoLessThanOrEqualTo(String value) {
      addCriterion("NRO_DOCUMENTO <=", value, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoLike(String value) {
      addCriterion("NRO_DOCUMENTO like", value, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoNotLike(String value) {
      addCriterion("NRO_DOCUMENTO not like", value, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoIn(List<String> values) {
      addCriterion("NRO_DOCUMENTO in", values, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoNotIn(List<String> values) {
      addCriterion("NRO_DOCUMENTO not in", values, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoBetween(String value1, String value2) {
      addCriterion("NRO_DOCUMENTO between", value1, value2, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoNotBetween(String value1, String value2) {
      addCriterion("NRO_DOCUMENTO not between", value1, value2, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoIsNull() {
      addCriterion("TIP_DOCUMENTO is null");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoIsNotNull() {
      addCriterion("TIP_DOCUMENTO is not null");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoEqualTo(String value) {
      addCriterion("TIP_DOCUMENTO =", value, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoNotEqualTo(String value) {
      addCriterion("TIP_DOCUMENTO <>", value, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoGreaterThan(String value) {
      addCriterion("TIP_DOCUMENTO >", value, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoGreaterThanOrEqualTo(String value) {
      addCriterion("TIP_DOCUMENTO >=", value, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoLessThan(String value) {
      addCriterion("TIP_DOCUMENTO <", value, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoLessThanOrEqualTo(String value) {
      addCriterion("TIP_DOCUMENTO <=", value, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoLike(String value) {
      addCriterion("TIP_DOCUMENTO like", value, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoNotLike(String value) {
      addCriterion("TIP_DOCUMENTO not like", value, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoIn(List<String> values) {
      addCriterion("TIP_DOCUMENTO in", values, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoNotIn(List<String> values) {
      addCriterion("TIP_DOCUMENTO not in", values, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoBetween(String value1, String value2) {
      addCriterion("TIP_DOCUMENTO between", value1, value2, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoNotBetween(String value1, String value2) {
      addCriterion("TIP_DOCUMENTO not between", value1, value2, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andFinVigenciaIsNull() {
      addCriterion("FIN_VIGENCIA is null");
      return (Criteria) this;
    }

    public Criteria andFinVigenciaIsNotNull() {
      addCriterion("FIN_VIGENCIA is not null");
      return (Criteria) this;
    }

    public Criteria andFinVigenciaEqualTo(Date value) {
      addCriterion("FIN_VIGENCIA =", value, "finVigencia");
      return (Criteria) this;
    }

    public Criteria andFinVigenciaNotEqualTo(Date value) {
      addCriterion("FIN_VIGENCIA <>", value, "finVigencia");
      return (Criteria) this;
    }

    public Criteria andFinVigenciaGreaterThan(Date value) {
      addCriterion("FIN_VIGENCIA >", value, "finVigencia");
      return (Criteria) this;
    }

    public Criteria andFinVigenciaGreaterThanOrEqualTo(Date value) {
      addCriterion("FIN_VIGENCIA >=", value, "finVigencia");
      return (Criteria) this;
    }

    public Criteria andFinVigenciaLessThan(Date value) {
      addCriterion("FIN_VIGENCIA <", value, "finVigencia");
      return (Criteria) this;
    }

    public Criteria andFinVigenciaLessThanOrEqualTo(Date value) {
      addCriterion("FIN_VIGENCIA <=", value, "finVigencia");
      return (Criteria) this;
    }

    public Criteria andFinVigenciaIn(List<Date> values) {
      addCriterion("FIN_VIGENCIA in", values, "finVigencia");
      return (Criteria) this;
    }

    public Criteria andFinVigenciaNotIn(List<Date> values) {
      addCriterion("FIN_VIGENCIA not in", values, "finVigencia");
      return (Criteria) this;
    }

    public Criteria andFinVigenciaBetween(Date value1, Date value2) {
      addCriterion("FIN_VIGENCIA between", value1, value2, "finVigencia");
      return (Criteria) this;
    }

    public Criteria andFinVigenciaNotBetween(Date value1, Date value2) {
      addCriterion("FIN_VIGENCIA not between", value1, value2, "finVigencia");
      return (Criteria) this;
    }

    public Criteria andEstadoDocumentoIsNull() {
      addCriterion("ESTADO_DOCUMENTO is null");
      return (Criteria) this;
    }

    public Criteria andEstadoDocumentoIsNotNull() {
      addCriterion("ESTADO_DOCUMENTO is not null");
      return (Criteria) this;
    }

    public Criteria andEstadoDocumentoEqualTo(String value) {
      addCriterion("ESTADO_DOCUMENTO =", value, "estadoDocumento");
      return (Criteria) this;
    }

    public Criteria andEstadoDocumentoNotEqualTo(String value) {
      addCriterion("ESTADO_DOCUMENTO <>", value, "estadoDocumento");
      return (Criteria) this;
    }

    public Criteria andEstadoDocumentoGreaterThan(String value) {
      addCriterion("ESTADO_DOCUMENTO >", value, "estadoDocumento");
      return (Criteria) this;
    }

    public Criteria andEstadoDocumentoGreaterThanOrEqualTo(String value) {
      addCriterion("ESTADO_DOCUMENTO >=", value, "estadoDocumento");
      return (Criteria) this;
    }

    public Criteria andEstadoDocumentoLessThan(String value) {
      addCriterion("ESTADO_DOCUMENTO <", value, "estadoDocumento");
      return (Criteria) this;
    }

    public Criteria andEstadoDocumentoLessThanOrEqualTo(String value) {
      addCriterion("ESTADO_DOCUMENTO <=", value, "estadoDocumento");
      return (Criteria) this;
    }

    public Criteria andEstadoDocumentoLike(String value) {
      addCriterion("ESTADO_DOCUMENTO like", value, "estadoDocumento");
      return (Criteria) this;
    }

    public Criteria andEstadoDocumentoNotLike(String value) {
      addCriterion("ESTADO_DOCUMENTO not like", value, "estadoDocumento");
      return (Criteria) this;
    }

    public Criteria andEstadoDocumentoIn(List<String> values) {
      addCriterion("ESTADO_DOCUMENTO in", values, "estadoDocumento");
      return (Criteria) this;
    }

    public Criteria andEstadoDocumentoNotIn(List<String> values) {
      addCriterion("ESTADO_DOCUMENTO not in", values, "estadoDocumento");
      return (Criteria) this;
    }

    public Criteria andEstadoDocumentoBetween(String value1, String value2) {
      addCriterion("ESTADO_DOCUMENTO between", value1, value2, "estadoDocumento");
      return (Criteria) this;
    }

    public Criteria andEstadoDocumentoNotBetween(String value1, String value2) {
      addCriterion("ESTADO_DOCUMENTO not between", value1, value2, "estadoDocumento");
      return (Criteria) this;
    }

    public Criteria andMovAnulacionIsNull() {
      addCriterion("MOV_ANULACION is null");
      return (Criteria) this;
    }

    public Criteria andMovAnulacionIsNotNull() {
      addCriterion("MOV_ANULACION is not null");
      return (Criteria) this;
    }

    public Criteria andMovAnulacionEqualTo(Long value) {
      addCriterion("MOV_ANULACION =", value, "movAnulacion");
      return (Criteria) this;
    }

    public Criteria andMovAnulacionNotEqualTo(Long value) {
      addCriterion("MOV_ANULACION <>", value, "movAnulacion");
      return (Criteria) this;
    }

    public Criteria andMovAnulacionGreaterThan(Long value) {
      addCriterion("MOV_ANULACION >", value, "movAnulacion");
      return (Criteria) this;
    }

    public Criteria andMovAnulacionGreaterThanOrEqualTo(Long value) {
      addCriterion("MOV_ANULACION >=", value, "movAnulacion");
      return (Criteria) this;
    }

    public Criteria andMovAnulacionLessThan(Long value) {
      addCriterion("MOV_ANULACION <", value, "movAnulacion");
      return (Criteria) this;
    }

    public Criteria andMovAnulacionLessThanOrEqualTo(Long value) {
      addCriterion("MOV_ANULACION <=", value, "movAnulacion");
      return (Criteria) this;
    }

    public Criteria andMovAnulacionIn(List<Long> values) {
      addCriterion("MOV_ANULACION in", values, "movAnulacion");
      return (Criteria) this;
    }

    public Criteria andMovAnulacionNotIn(List<Long> values) {
      addCriterion("MOV_ANULACION not in", values, "movAnulacion");
      return (Criteria) this;
    }

    public Criteria andMovAnulacionBetween(Long value1, Long value2) {
      addCriterion("MOV_ANULACION between", value1, value2, "movAnulacion");
      return (Criteria) this;
    }

    public Criteria andMovAnulacionNotBetween(Long value1, Long value2) {
      addCriterion("MOV_ANULACION not between", value1, value2, "movAnulacion");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated do_not_delete_during_merge Mon Jun 23 12:11:49 COT 2014
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}