package com.cardif.satelite.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class TlmkBaseIBExample implements Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.TLMK_BASE_IB
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.TLMK_BASE_IB
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.TLMK_BASE_IB
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_IB
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  public TlmkBaseIBExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_IB
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_IB
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_IB
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_IB
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_IB
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_IB
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_IB
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_IB
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_IB
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_IB
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.TLMK_BASE_IB
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andPkIsNull() {
      addCriterion("PK is null");
      return (Criteria) this;
    }

    public Criteria andPkIsNotNull() {
      addCriterion("PK is not null");
      return (Criteria) this;
    }

    public Criteria andPkEqualTo(Long value) {
      addCriterion("PK =", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotEqualTo(Long value) {
      addCriterion("PK <>", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThan(Long value) {
      addCriterion("PK >", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThanOrEqualTo(Long value) {
      addCriterion("PK >=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThan(Long value) {
      addCriterion("PK <", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThanOrEqualTo(Long value) {
      addCriterion("PK <=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkIn(List<Long> values) {
      addCriterion("PK in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotIn(List<Long> values) {
      addCriterion("PK not in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkBetween(Long value1, Long value2) {
      addCriterion("PK between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotBetween(Long value1, Long value2) {
      addCriterion("PK not between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andCodBaseIsNull() {
      addCriterion("COD_BASE is null");
      return (Criteria) this;
    }

    public Criteria andCodBaseIsNotNull() {
      addCriterion("COD_BASE is not null");
      return (Criteria) this;
    }

    public Criteria andCodBaseEqualTo(Long value) {
      addCriterion("COD_BASE =", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseNotEqualTo(Long value) {
      addCriterion("COD_BASE <>", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseGreaterThan(Long value) {
      addCriterion("COD_BASE >", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseGreaterThanOrEqualTo(Long value) {
      addCriterion("COD_BASE >=", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseLessThan(Long value) {
      addCriterion("COD_BASE <", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseLessThanOrEqualTo(Long value) {
      addCriterion("COD_BASE <=", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseIn(List<Long> values) {
      addCriterion("COD_BASE in", values, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseNotIn(List<Long> values) {
      addCriterion("COD_BASE not in", values, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseBetween(Long value1, Long value2) {
      addCriterion("COD_BASE between", value1, value2, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseNotBetween(Long value1, Long value2) {
      addCriterion("COD_BASE not between", value1, value2, "codBase");
      return (Criteria) this;
    }

    public Criteria andTcVeaIsNull() {
      addCriterion("TC_VEA is null");
      return (Criteria) this;
    }

    public Criteria andTcVeaIsNotNull() {
      addCriterion("TC_VEA is not null");
      return (Criteria) this;
    }

    public Criteria andTcVeaEqualTo(String value) {
      addCriterion("TC_VEA =", value, "tcVea");
      return (Criteria) this;
    }

    public Criteria andTcVeaNotEqualTo(String value) {
      addCriterion("TC_VEA <>", value, "tcVea");
      return (Criteria) this;
    }

    public Criteria andTcVeaGreaterThan(String value) {
      addCriterion("TC_VEA >", value, "tcVea");
      return (Criteria) this;
    }

    public Criteria andTcVeaGreaterThanOrEqualTo(String value) {
      addCriterion("TC_VEA >=", value, "tcVea");
      return (Criteria) this;
    }

    public Criteria andTcVeaLessThan(String value) {
      addCriterion("TC_VEA <", value, "tcVea");
      return (Criteria) this;
    }

    public Criteria andTcVeaLessThanOrEqualTo(String value) {
      addCriterion("TC_VEA <=", value, "tcVea");
      return (Criteria) this;
    }

    public Criteria andTcVeaIn(List<String> values) {
      addCriterion("TC_VEA in", values, "tcVea");
      return (Criteria) this;
    }

    public Criteria andTcVeaNotIn(List<String> values) {
      addCriterion("TC_VEA not in", values, "tcVea");
      return (Criteria) this;
    }

    public Criteria andTcVeaBetween(String value1, String value2) {
      addCriterion("TC_VEA between", value1, value2, "tcVea");
      return (Criteria) this;
    }

    public Criteria andTcVeaNotBetween(String value1, String value2) {
      addCriterion("TC_VEA not between", value1, value2, "tcVea");
      return (Criteria) this;
    }

    public Criteria andTcVisaIsNull() {
      addCriterion("TC_VISA is null");
      return (Criteria) this;
    }

    public Criteria andTcVisaIsNotNull() {
      addCriterion("TC_VISA is not null");
      return (Criteria) this;
    }

    public Criteria andTcVisaEqualTo(String value) {
      addCriterion("TC_VISA =", value, "tcVisa");
      return (Criteria) this;
    }

    public Criteria andTcVisaNotEqualTo(String value) {
      addCriterion("TC_VISA <>", value, "tcVisa");
      return (Criteria) this;
    }

    public Criteria andTcVisaGreaterThan(String value) {
      addCriterion("TC_VISA >", value, "tcVisa");
      return (Criteria) this;
    }

    public Criteria andTcVisaGreaterThanOrEqualTo(String value) {
      addCriterion("TC_VISA >=", value, "tcVisa");
      return (Criteria) this;
    }

    public Criteria andTcVisaLessThan(String value) {
      addCriterion("TC_VISA <", value, "tcVisa");
      return (Criteria) this;
    }

    public Criteria andTcVisaLessThanOrEqualTo(String value) {
      addCriterion("TC_VISA <=", value, "tcVisa");
      return (Criteria) this;
    }

    public Criteria andTcVisaIn(List<String> values) {
      addCriterion("TC_VISA in", values, "tcVisa");
      return (Criteria) this;
    }

    public Criteria andTcVisaNotIn(List<String> values) {
      addCriterion("TC_VISA not in", values, "tcVisa");
      return (Criteria) this;
    }

    public Criteria andTcVisaBetween(String value1, String value2) {
      addCriterion("TC_VISA between", value1, value2, "tcVisa");
      return (Criteria) this;
    }

    public Criteria andTcVisaNotBetween(String value1, String value2) {
      addCriterion("TC_VISA not between", value1, value2, "tcVisa");
      return (Criteria) this;
    }

    public Criteria andTcAmexIsNull() {
      addCriterion("TC_AMEX is null");
      return (Criteria) this;
    }

    public Criteria andTcAmexIsNotNull() {
      addCriterion("TC_AMEX is not null");
      return (Criteria) this;
    }

    public Criteria andTcAmexEqualTo(String value) {
      addCriterion("TC_AMEX =", value, "tcAmex");
      return (Criteria) this;
    }

    public Criteria andTcAmexNotEqualTo(String value) {
      addCriterion("TC_AMEX <>", value, "tcAmex");
      return (Criteria) this;
    }

    public Criteria andTcAmexGreaterThan(String value) {
      addCriterion("TC_AMEX >", value, "tcAmex");
      return (Criteria) this;
    }

    public Criteria andTcAmexGreaterThanOrEqualTo(String value) {
      addCriterion("TC_AMEX >=", value, "tcAmex");
      return (Criteria) this;
    }

    public Criteria andTcAmexLessThan(String value) {
      addCriterion("TC_AMEX <", value, "tcAmex");
      return (Criteria) this;
    }

    public Criteria andTcAmexLessThanOrEqualTo(String value) {
      addCriterion("TC_AMEX <=", value, "tcAmex");
      return (Criteria) this;
    }

    public Criteria andTcAmexIn(List<String> values) {
      addCriterion("TC_AMEX in", values, "tcAmex");
      return (Criteria) this;
    }

    public Criteria andTcAmexNotIn(List<String> values) {
      addCriterion("TC_AMEX not in", values, "tcAmex");
      return (Criteria) this;
    }

    public Criteria andTcAmexBetween(String value1, String value2) {
      addCriterion("TC_AMEX between", value1, value2, "tcAmex");
      return (Criteria) this;
    }

    public Criteria andTcAmexNotBetween(String value1, String value2) {
      addCriterion("TC_AMEX not between", value1, value2, "tcAmex");
      return (Criteria) this;
    }

    public Criteria andTcMastercardIsNull() {
      addCriterion("TC_MASTERCARD is null");
      return (Criteria) this;
    }

    public Criteria andTcMastercardIsNotNull() {
      addCriterion("TC_MASTERCARD is not null");
      return (Criteria) this;
    }

    public Criteria andTcMastercardEqualTo(String value) {
      addCriterion("TC_MASTERCARD =", value, "tcMastercard");
      return (Criteria) this;
    }

    public Criteria andTcMastercardNotEqualTo(String value) {
      addCriterion("TC_MASTERCARD <>", value, "tcMastercard");
      return (Criteria) this;
    }

    public Criteria andTcMastercardGreaterThan(String value) {
      addCriterion("TC_MASTERCARD >", value, "tcMastercard");
      return (Criteria) this;
    }

    public Criteria andTcMastercardGreaterThanOrEqualTo(String value) {
      addCriterion("TC_MASTERCARD >=", value, "tcMastercard");
      return (Criteria) this;
    }

    public Criteria andTcMastercardLessThan(String value) {
      addCriterion("TC_MASTERCARD <", value, "tcMastercard");
      return (Criteria) this;
    }

    public Criteria andTcMastercardLessThanOrEqualTo(String value) {
      addCriterion("TC_MASTERCARD <=", value, "tcMastercard");
      return (Criteria) this;
    }

    public Criteria andTcMastercardIn(List<String> values) {
      addCriterion("TC_MASTERCARD in", values, "tcMastercard");
      return (Criteria) this;
    }

    public Criteria andTcMastercardNotIn(List<String> values) {
      addCriterion("TC_MASTERCARD not in", values, "tcMastercard");
      return (Criteria) this;
    }

    public Criteria andTcMastercardBetween(String value1, String value2) {
      addCriterion("TC_MASTERCARD between", value1, value2, "tcMastercard");
      return (Criteria) this;
    }

    public Criteria andTcMastercardNotBetween(String value1, String value2) {
      addCriterion("TC_MASTERCARD not between", value1, value2, "tcMastercard");
      return (Criteria) this;
    }

    public Criteria andTdIsNull() {
      addCriterion("TD is null");
      return (Criteria) this;
    }

    public Criteria andTdIsNotNull() {
      addCriterion("TD is not null");
      return (Criteria) this;
    }

    public Criteria andTdEqualTo(String value) {
      addCriterion("TD =", value, "td");
      return (Criteria) this;
    }

    public Criteria andTdNotEqualTo(String value) {
      addCriterion("TD <>", value, "td");
      return (Criteria) this;
    }

    public Criteria andTdGreaterThan(String value) {
      addCriterion("TD >", value, "td");
      return (Criteria) this;
    }

    public Criteria andTdGreaterThanOrEqualTo(String value) {
      addCriterion("TD >=", value, "td");
      return (Criteria) this;
    }

    public Criteria andTdLessThan(String value) {
      addCriterion("TD <", value, "td");
      return (Criteria) this;
    }

    public Criteria andTdLessThanOrEqualTo(String value) {
      addCriterion("TD <=", value, "td");
      return (Criteria) this;
    }

    public Criteria andTdIn(List<String> values) {
      addCriterion("TD in", values, "td");
      return (Criteria) this;
    }

    public Criteria andTdNotIn(List<String> values) {
      addCriterion("TD not in", values, "td");
      return (Criteria) this;
    }

    public Criteria andTdBetween(String value1, String value2) {
      addCriterion("TD between", value1, value2, "td");
      return (Criteria) this;
    }

    public Criteria andTdNotBetween(String value1, String value2) {
      addCriterion("TD not between", value1, value2, "td");
      return (Criteria) this;
    }

    public Criteria andTipdocIsNull() {
      addCriterion("TIPDOC is null");
      return (Criteria) this;
    }

    public Criteria andTipdocIsNotNull() {
      addCriterion("TIPDOC is not null");
      return (Criteria) this;
    }

    public Criteria andTipdocEqualTo(String value) {
      addCriterion("TIPDOC =", value, "tipdoc");
      return (Criteria) this;
    }

    public Criteria andTipdocNotEqualTo(String value) {
      addCriterion("TIPDOC <>", value, "tipdoc");
      return (Criteria) this;
    }

    public Criteria andTipdocGreaterThan(String value) {
      addCriterion("TIPDOC >", value, "tipdoc");
      return (Criteria) this;
    }

    public Criteria andTipdocGreaterThanOrEqualTo(String value) {
      addCriterion("TIPDOC >=", value, "tipdoc");
      return (Criteria) this;
    }

    public Criteria andTipdocLessThan(String value) {
      addCriterion("TIPDOC <", value, "tipdoc");
      return (Criteria) this;
    }

    public Criteria andTipdocLessThanOrEqualTo(String value) {
      addCriterion("TIPDOC <=", value, "tipdoc");
      return (Criteria) this;
    }

    public Criteria andTipdocIn(List<String> values) {
      addCriterion("TIPDOC in", values, "tipdoc");
      return (Criteria) this;
    }

    public Criteria andTipdocNotIn(List<String> values) {
      addCriterion("TIPDOC not in", values, "tipdoc");
      return (Criteria) this;
    }

    public Criteria andTipdocBetween(String value1, String value2) {
      addCriterion("TIPDOC between", value1, value2, "tipdoc");
      return (Criteria) this;
    }

    public Criteria andTipdocNotBetween(String value1, String value2) {
      addCriterion("TIPDOC not between", value1, value2, "tipdoc");
      return (Criteria) this;
    }

    public Criteria andCoddocIsNull() {
      addCriterion("CODDOC is null");
      return (Criteria) this;
    }

    public Criteria andCoddocIsNotNull() {
      addCriterion("CODDOC is not null");
      return (Criteria) this;
    }

    public Criteria andCoddocEqualTo(String value) {
      addCriterion("CODDOC =", value, "coddoc");
      return (Criteria) this;
    }

    public Criteria andCoddocNotEqualTo(String value) {
      addCriterion("CODDOC <>", value, "coddoc");
      return (Criteria) this;
    }

    public Criteria andCoddocGreaterThan(String value) {
      addCriterion("CODDOC >", value, "coddoc");
      return (Criteria) this;
    }

    public Criteria andCoddocGreaterThanOrEqualTo(String value) {
      addCriterion("CODDOC >=", value, "coddoc");
      return (Criteria) this;
    }

    public Criteria andCoddocLessThan(String value) {
      addCriterion("CODDOC <", value, "coddoc");
      return (Criteria) this;
    }

    public Criteria andCoddocLessThanOrEqualTo(String value) {
      addCriterion("CODDOC <=", value, "coddoc");
      return (Criteria) this;
    }

    public Criteria andCoddocIn(List<String> values) {
      addCriterion("CODDOC in", values, "coddoc");
      return (Criteria) this;
    }

    public Criteria andCoddocNotIn(List<String> values) {
      addCriterion("CODDOC not in", values, "coddoc");
      return (Criteria) this;
    }

    public Criteria andCoddocBetween(String value1, String value2) {
      addCriterion("CODDOC between", value1, value2, "coddoc");
      return (Criteria) this;
    }

    public Criteria andCoddocNotBetween(String value1, String value2) {
      addCriterion("CODDOC not between", value1, value2, "coddoc");
      return (Criteria) this;
    }

    public Criteria andNbrprimerperIsNull() {
      addCriterion("NBRPRIMERPER is null");
      return (Criteria) this;
    }

    public Criteria andNbrprimerperIsNotNull() {
      addCriterion("NBRPRIMERPER is not null");
      return (Criteria) this;
    }

    public Criteria andNbrprimerperEqualTo(String value) {
      addCriterion("NBRPRIMERPER =", value, "nbrprimerper");
      return (Criteria) this;
    }

    public Criteria andNbrprimerperNotEqualTo(String value) {
      addCriterion("NBRPRIMERPER <>", value, "nbrprimerper");
      return (Criteria) this;
    }

    public Criteria andNbrprimerperGreaterThan(String value) {
      addCriterion("NBRPRIMERPER >", value, "nbrprimerper");
      return (Criteria) this;
    }

    public Criteria andNbrprimerperGreaterThanOrEqualTo(String value) {
      addCriterion("NBRPRIMERPER >=", value, "nbrprimerper");
      return (Criteria) this;
    }

    public Criteria andNbrprimerperLessThan(String value) {
      addCriterion("NBRPRIMERPER <", value, "nbrprimerper");
      return (Criteria) this;
    }

    public Criteria andNbrprimerperLessThanOrEqualTo(String value) {
      addCriterion("NBRPRIMERPER <=", value, "nbrprimerper");
      return (Criteria) this;
    }

    public Criteria andNbrprimerperIn(List<String> values) {
      addCriterion("NBRPRIMERPER in", values, "nbrprimerper");
      return (Criteria) this;
    }

    public Criteria andNbrprimerperNotIn(List<String> values) {
      addCriterion("NBRPRIMERPER not in", values, "nbrprimerper");
      return (Criteria) this;
    }

    public Criteria andNbrprimerperBetween(String value1, String value2) {
      addCriterion("NBRPRIMERPER between", value1, value2, "nbrprimerper");
      return (Criteria) this;
    }

    public Criteria andNbrprimerperNotBetween(String value1, String value2) {
      addCriterion("NBRPRIMERPER not between", value1, value2, "nbrprimerper");
      return (Criteria) this;
    }

    public Criteria andNbrsegundoperIsNull() {
      addCriterion("NBRSEGUNDOPER is null");
      return (Criteria) this;
    }

    public Criteria andNbrsegundoperIsNotNull() {
      addCriterion("NBRSEGUNDOPER is not null");
      return (Criteria) this;
    }

    public Criteria andNbrsegundoperEqualTo(String value) {
      addCriterion("NBRSEGUNDOPER =", value, "nbrsegundoper");
      return (Criteria) this;
    }

    public Criteria andNbrsegundoperNotEqualTo(String value) {
      addCriterion("NBRSEGUNDOPER <>", value, "nbrsegundoper");
      return (Criteria) this;
    }

    public Criteria andNbrsegundoperGreaterThan(String value) {
      addCriterion("NBRSEGUNDOPER >", value, "nbrsegundoper");
      return (Criteria) this;
    }

    public Criteria andNbrsegundoperGreaterThanOrEqualTo(String value) {
      addCriterion("NBRSEGUNDOPER >=", value, "nbrsegundoper");
      return (Criteria) this;
    }

    public Criteria andNbrsegundoperLessThan(String value) {
      addCriterion("NBRSEGUNDOPER <", value, "nbrsegundoper");
      return (Criteria) this;
    }

    public Criteria andNbrsegundoperLessThanOrEqualTo(String value) {
      addCriterion("NBRSEGUNDOPER <=", value, "nbrsegundoper");
      return (Criteria) this;
    }

    public Criteria andNbrsegundoperIn(List<String> values) {
      addCriterion("NBRSEGUNDOPER in", values, "nbrsegundoper");
      return (Criteria) this;
    }

    public Criteria andNbrsegundoperNotIn(List<String> values) {
      addCriterion("NBRSEGUNDOPER not in", values, "nbrsegundoper");
      return (Criteria) this;
    }

    public Criteria andNbrsegundoperBetween(String value1, String value2) {
      addCriterion("NBRSEGUNDOPER between", value1, value2, "nbrsegundoper");
      return (Criteria) this;
    }

    public Criteria andNbrsegundoperNotBetween(String value1, String value2) {
      addCriterion("NBRSEGUNDOPER not between", value1, value2, "nbrsegundoper");
      return (Criteria) this;
    }

    public Criteria andApepatperIsNull() {
      addCriterion("APEPATPER is null");
      return (Criteria) this;
    }

    public Criteria andApepatperIsNotNull() {
      addCriterion("APEPATPER is not null");
      return (Criteria) this;
    }

    public Criteria andApepatperEqualTo(String value) {
      addCriterion("APEPATPER =", value, "apepatper");
      return (Criteria) this;
    }

    public Criteria andApepatperNotEqualTo(String value) {
      addCriterion("APEPATPER <>", value, "apepatper");
      return (Criteria) this;
    }

    public Criteria andApepatperGreaterThan(String value) {
      addCriterion("APEPATPER >", value, "apepatper");
      return (Criteria) this;
    }

    public Criteria andApepatperGreaterThanOrEqualTo(String value) {
      addCriterion("APEPATPER >=", value, "apepatper");
      return (Criteria) this;
    }

    public Criteria andApepatperLessThan(String value) {
      addCriterion("APEPATPER <", value, "apepatper");
      return (Criteria) this;
    }

    public Criteria andApepatperLessThanOrEqualTo(String value) {
      addCriterion("APEPATPER <=", value, "apepatper");
      return (Criteria) this;
    }

    public Criteria andApepatperIn(List<String> values) {
      addCriterion("APEPATPER in", values, "apepatper");
      return (Criteria) this;
    }

    public Criteria andApepatperNotIn(List<String> values) {
      addCriterion("APEPATPER not in", values, "apepatper");
      return (Criteria) this;
    }

    public Criteria andApepatperBetween(String value1, String value2) {
      addCriterion("APEPATPER between", value1, value2, "apepatper");
      return (Criteria) this;
    }

    public Criteria andApepatperNotBetween(String value1, String value2) {
      addCriterion("APEPATPER not between", value1, value2, "apepatper");
      return (Criteria) this;
    }

    public Criteria andApematperIsNull() {
      addCriterion("APEMATPER is null");
      return (Criteria) this;
    }

    public Criteria andApematperIsNotNull() {
      addCriterion("APEMATPER is not null");
      return (Criteria) this;
    }

    public Criteria andApematperEqualTo(String value) {
      addCriterion("APEMATPER =", value, "apematper");
      return (Criteria) this;
    }

    public Criteria andApematperNotEqualTo(String value) {
      addCriterion("APEMATPER <>", value, "apematper");
      return (Criteria) this;
    }

    public Criteria andApematperGreaterThan(String value) {
      addCriterion("APEMATPER >", value, "apematper");
      return (Criteria) this;
    }

    public Criteria andApematperGreaterThanOrEqualTo(String value) {
      addCriterion("APEMATPER >=", value, "apematper");
      return (Criteria) this;
    }

    public Criteria andApematperLessThan(String value) {
      addCriterion("APEMATPER <", value, "apematper");
      return (Criteria) this;
    }

    public Criteria andApematperLessThanOrEqualTo(String value) {
      addCriterion("APEMATPER <=", value, "apematper");
      return (Criteria) this;
    }

    public Criteria andApematperIn(List<String> values) {
      addCriterion("APEMATPER in", values, "apematper");
      return (Criteria) this;
    }

    public Criteria andApematperNotIn(List<String> values) {
      addCriterion("APEMATPER not in", values, "apematper");
      return (Criteria) this;
    }

    public Criteria andApematperBetween(String value1, String value2) {
      addCriterion("APEMATPER between", value1, value2, "apematper");
      return (Criteria) this;
    }

    public Criteria andApematperNotBetween(String value1, String value2) {
      addCriterion("APEMATPER not between", value1, value2, "apematper");
      return (Criteria) this;
    }

    public Criteria andSexoIsNull() {
      addCriterion("SEXO is null");
      return (Criteria) this;
    }

    public Criteria andSexoIsNotNull() {
      addCriterion("SEXO is not null");
      return (Criteria) this;
    }

    public Criteria andSexoEqualTo(String value) {
      addCriterion("SEXO =", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoNotEqualTo(String value) {
      addCriterion("SEXO <>", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoGreaterThan(String value) {
      addCriterion("SEXO >", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoGreaterThanOrEqualTo(String value) {
      addCriterion("SEXO >=", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoLessThan(String value) {
      addCriterion("SEXO <", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoLessThanOrEqualTo(String value) {
      addCriterion("SEXO <=", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoIn(List<String> values) {
      addCriterion("SEXO in", values, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoNotIn(List<String> values) {
      addCriterion("SEXO not in", values, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoBetween(String value1, String value2) {
      addCriterion("SEXO between", value1, value2, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoNotBetween(String value1, String value2) {
      addCriterion("SEXO not between", value1, value2, "sexo");
      return (Criteria) this;
    }

    public Criteria andEdadIsNull() {
      addCriterion("EDAD is null");
      return (Criteria) this;
    }

    public Criteria andEdadIsNotNull() {
      addCriterion("EDAD is not null");
      return (Criteria) this;
    }

    public Criteria andEdadEqualTo(String value) {
      addCriterion("EDAD =", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadNotEqualTo(String value) {
      addCriterion("EDAD <>", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadGreaterThan(String value) {
      addCriterion("EDAD >", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadGreaterThanOrEqualTo(String value) {
      addCriterion("EDAD >=", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadLessThan(String value) {
      addCriterion("EDAD <", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadLessThanOrEqualTo(String value) {
      addCriterion("EDAD <=", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadIn(List<String> values) {
      addCriterion("EDAD in", values, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadNotIn(List<String> values) {
      addCriterion("EDAD not in", values, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadBetween(String value1, String value2) {
      addCriterion("EDAD between", value1, value2, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadNotBetween(String value1, String value2) {
      addCriterion("EDAD not between", value1, value2, "edad");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelDomIsNull() {
      addCriterion("CODTELDEPARTAMENTO_TEL_DOM is null");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelDomIsNotNull() {
      addCriterion("CODTELDEPARTAMENTO_TEL_DOM is not null");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelDomEqualTo(String value) {
      addCriterion("CODTELDEPARTAMENTO_TEL_DOM =", value, "codteldepartamentoTelDom");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelDomNotEqualTo(String value) {
      addCriterion("CODTELDEPARTAMENTO_TEL_DOM <>", value, "codteldepartamentoTelDom");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelDomGreaterThan(String value) {
      addCriterion("CODTELDEPARTAMENTO_TEL_DOM >", value, "codteldepartamentoTelDom");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelDomGreaterThanOrEqualTo(String value) {
      addCriterion("CODTELDEPARTAMENTO_TEL_DOM >=", value, "codteldepartamentoTelDom");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelDomLessThan(String value) {
      addCriterion("CODTELDEPARTAMENTO_TEL_DOM <", value, "codteldepartamentoTelDom");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelDomLessThanOrEqualTo(String value) {
      addCriterion("CODTELDEPARTAMENTO_TEL_DOM <=", value, "codteldepartamentoTelDom");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelDomIn(List<String> values) {
      addCriterion("CODTELDEPARTAMENTO_TEL_DOM in", values, "codteldepartamentoTelDom");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelDomNotIn(List<String> values) {
      addCriterion("CODTELDEPARTAMENTO_TEL_DOM not in", values, "codteldepartamentoTelDom");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelDomBetween(String value1, String value2) {
      addCriterion("CODTELDEPARTAMENTO_TEL_DOM between", value1, value2, "codteldepartamentoTelDom");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelDomNotBetween(String value1, String value2) {
      addCriterion("CODTELDEPARTAMENTO_TEL_DOM not between", value1, value2, "codteldepartamentoTelDom");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelDomIsNull() {
      addCriterion("NUMTELEFONO_TEL_DOM is null");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelDomIsNotNull() {
      addCriterion("NUMTELEFONO_TEL_DOM is not null");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelDomEqualTo(String value) {
      addCriterion("NUMTELEFONO_TEL_DOM =", value, "numtelefonoTelDom");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelDomNotEqualTo(String value) {
      addCriterion("NUMTELEFONO_TEL_DOM <>", value, "numtelefonoTelDom");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelDomGreaterThan(String value) {
      addCriterion("NUMTELEFONO_TEL_DOM >", value, "numtelefonoTelDom");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelDomGreaterThanOrEqualTo(String value) {
      addCriterion("NUMTELEFONO_TEL_DOM >=", value, "numtelefonoTelDom");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelDomLessThan(String value) {
      addCriterion("NUMTELEFONO_TEL_DOM <", value, "numtelefonoTelDom");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelDomLessThanOrEqualTo(String value) {
      addCriterion("NUMTELEFONO_TEL_DOM <=", value, "numtelefonoTelDom");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelDomIn(List<String> values) {
      addCriterion("NUMTELEFONO_TEL_DOM in", values, "numtelefonoTelDom");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelDomNotIn(List<String> values) {
      addCriterion("NUMTELEFONO_TEL_DOM not in", values, "numtelefonoTelDom");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelDomBetween(String value1, String value2) {
      addCriterion("NUMTELEFONO_TEL_DOM between", value1, value2, "numtelefonoTelDom");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelDomNotBetween(String value1, String value2) {
      addCriterion("NUMTELEFONO_TEL_DOM not between", value1, value2, "numtelefonoTelDom");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelCelIsNull() {
      addCriterion("CODTELDEPARTAMENTO_TEL_CEL is null");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelCelIsNotNull() {
      addCriterion("CODTELDEPARTAMENTO_TEL_CEL is not null");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelCelEqualTo(String value) {
      addCriterion("CODTELDEPARTAMENTO_TEL_CEL =", value, "codteldepartamentoTelCel");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelCelNotEqualTo(String value) {
      addCriterion("CODTELDEPARTAMENTO_TEL_CEL <>", value, "codteldepartamentoTelCel");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelCelGreaterThan(String value) {
      addCriterion("CODTELDEPARTAMENTO_TEL_CEL >", value, "codteldepartamentoTelCel");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelCelGreaterThanOrEqualTo(String value) {
      addCriterion("CODTELDEPARTAMENTO_TEL_CEL >=", value, "codteldepartamentoTelCel");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelCelLessThan(String value) {
      addCriterion("CODTELDEPARTAMENTO_TEL_CEL <", value, "codteldepartamentoTelCel");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelCelLessThanOrEqualTo(String value) {
      addCriterion("CODTELDEPARTAMENTO_TEL_CEL <=", value, "codteldepartamentoTelCel");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelCelIn(List<String> values) {
      addCriterion("CODTELDEPARTAMENTO_TEL_CEL in", values, "codteldepartamentoTelCel");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelCelNotIn(List<String> values) {
      addCriterion("CODTELDEPARTAMENTO_TEL_CEL not in", values, "codteldepartamentoTelCel");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelCelBetween(String value1, String value2) {
      addCriterion("CODTELDEPARTAMENTO_TEL_CEL between", value1, value2, "codteldepartamentoTelCel");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelCelNotBetween(String value1, String value2) {
      addCriterion("CODTELDEPARTAMENTO_TEL_CEL not between", value1, value2, "codteldepartamentoTelCel");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelCelIsNull() {
      addCriterion("NUMTELEFONO_TEL_CEL is null");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelCelIsNotNull() {
      addCriterion("NUMTELEFONO_TEL_CEL is not null");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelCelEqualTo(String value) {
      addCriterion("NUMTELEFONO_TEL_CEL =", value, "numtelefonoTelCel");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelCelNotEqualTo(String value) {
      addCriterion("NUMTELEFONO_TEL_CEL <>", value, "numtelefonoTelCel");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelCelGreaterThan(String value) {
      addCriterion("NUMTELEFONO_TEL_CEL >", value, "numtelefonoTelCel");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelCelGreaterThanOrEqualTo(String value) {
      addCriterion("NUMTELEFONO_TEL_CEL >=", value, "numtelefonoTelCel");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelCelLessThan(String value) {
      addCriterion("NUMTELEFONO_TEL_CEL <", value, "numtelefonoTelCel");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelCelLessThanOrEqualTo(String value) {
      addCriterion("NUMTELEFONO_TEL_CEL <=", value, "numtelefonoTelCel");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelCelIn(List<String> values) {
      addCriterion("NUMTELEFONO_TEL_CEL in", values, "numtelefonoTelCel");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelCelNotIn(List<String> values) {
      addCriterion("NUMTELEFONO_TEL_CEL not in", values, "numtelefonoTelCel");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelCelBetween(String value1, String value2) {
      addCriterion("NUMTELEFONO_TEL_CEL between", value1, value2, "numtelefonoTelCel");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelCelNotBetween(String value1, String value2) {
      addCriterion("NUMTELEFONO_TEL_CEL not between", value1, value2, "numtelefonoTelCel");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelTrabajoIsNull() {
      addCriterion("CODTELDEPARTAMENTO_TEL_TRABAJO is null");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelTrabajoIsNotNull() {
      addCriterion("CODTELDEPARTAMENTO_TEL_TRABAJO is not null");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelTrabajoEqualTo(String value) {
      addCriterion("CODTELDEPARTAMENTO_TEL_TRABAJO =", value, "codteldepartamentoTelTrabajo");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelTrabajoNotEqualTo(String value) {
      addCriterion("CODTELDEPARTAMENTO_TEL_TRABAJO <>", value, "codteldepartamentoTelTrabajo");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelTrabajoGreaterThan(String value) {
      addCriterion("CODTELDEPARTAMENTO_TEL_TRABAJO >", value, "codteldepartamentoTelTrabajo");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelTrabajoGreaterThanOrEqualTo(String value) {
      addCriterion("CODTELDEPARTAMENTO_TEL_TRABAJO >=", value, "codteldepartamentoTelTrabajo");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelTrabajoLessThan(String value) {
      addCriterion("CODTELDEPARTAMENTO_TEL_TRABAJO <", value, "codteldepartamentoTelTrabajo");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelTrabajoLessThanOrEqualTo(String value) {
      addCriterion("CODTELDEPARTAMENTO_TEL_TRABAJO <=", value, "codteldepartamentoTelTrabajo");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelTrabajoIn(List<String> values) {
      addCriterion("CODTELDEPARTAMENTO_TEL_TRABAJO in", values, "codteldepartamentoTelTrabajo");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelTrabajoNotIn(List<String> values) {
      addCriterion("CODTELDEPARTAMENTO_TEL_TRABAJO not in", values, "codteldepartamentoTelTrabajo");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelTrabajoBetween(String value1, String value2) {
      addCriterion("CODTELDEPARTAMENTO_TEL_TRABAJO between", value1, value2, "codteldepartamentoTelTrabajo");
      return (Criteria) this;
    }

    public Criteria andCodteldepartamentoTelTrabajoNotBetween(String value1, String value2) {
      addCriterion("CODTELDEPARTAMENTO_TEL_TRABAJO not between", value1, value2, "codteldepartamentoTelTrabajo");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelTrabajoIsNull() {
      addCriterion("NUMTELEFONO_TEL_TRABAJO is null");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelTrabajoIsNotNull() {
      addCriterion("NUMTELEFONO_TEL_TRABAJO is not null");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelTrabajoEqualTo(String value) {
      addCriterion("NUMTELEFONO_TEL_TRABAJO =", value, "numtelefonoTelTrabajo");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelTrabajoNotEqualTo(String value) {
      addCriterion("NUMTELEFONO_TEL_TRABAJO <>", value, "numtelefonoTelTrabajo");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelTrabajoGreaterThan(String value) {
      addCriterion("NUMTELEFONO_TEL_TRABAJO >", value, "numtelefonoTelTrabajo");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelTrabajoGreaterThanOrEqualTo(String value) {
      addCriterion("NUMTELEFONO_TEL_TRABAJO >=", value, "numtelefonoTelTrabajo");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelTrabajoLessThan(String value) {
      addCriterion("NUMTELEFONO_TEL_TRABAJO <", value, "numtelefonoTelTrabajo");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelTrabajoLessThanOrEqualTo(String value) {
      addCriterion("NUMTELEFONO_TEL_TRABAJO <=", value, "numtelefonoTelTrabajo");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelTrabajoIn(List<String> values) {
      addCriterion("NUMTELEFONO_TEL_TRABAJO in", values, "numtelefonoTelTrabajo");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelTrabajoNotIn(List<String> values) {
      addCriterion("NUMTELEFONO_TEL_TRABAJO not in", values, "numtelefonoTelTrabajo");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelTrabajoBetween(String value1, String value2) {
      addCriterion("NUMTELEFONO_TEL_TRABAJO between", value1, value2, "numtelefonoTelTrabajo");
      return (Criteria) this;
    }

    public Criteria andNumtelefonoTelTrabajoNotBetween(String value1, String value2) {
      addCriterion("NUMTELEFONO_TEL_TRABAJO not between", value1, value2, "numtelefonoTelTrabajo");
      return (Criteria) this;
    }

    public Criteria andDesdireccionIsNull() {
      addCriterion("DESDIRECCION is null");
      return (Criteria) this;
    }

    public Criteria andDesdireccionIsNotNull() {
      addCriterion("DESDIRECCION is not null");
      return (Criteria) this;
    }

    public Criteria andDesdireccionEqualTo(String value) {
      addCriterion("DESDIRECCION =", value, "desdireccion");
      return (Criteria) this;
    }

    public Criteria andDesdireccionNotEqualTo(String value) {
      addCriterion("DESDIRECCION <>", value, "desdireccion");
      return (Criteria) this;
    }

    public Criteria andDesdireccionGreaterThan(String value) {
      addCriterion("DESDIRECCION >", value, "desdireccion");
      return (Criteria) this;
    }

    public Criteria andDesdireccionGreaterThanOrEqualTo(String value) {
      addCriterion("DESDIRECCION >=", value, "desdireccion");
      return (Criteria) this;
    }

    public Criteria andDesdireccionLessThan(String value) {
      addCriterion("DESDIRECCION <", value, "desdireccion");
      return (Criteria) this;
    }

    public Criteria andDesdireccionLessThanOrEqualTo(String value) {
      addCriterion("DESDIRECCION <=", value, "desdireccion");
      return (Criteria) this;
    }

    public Criteria andDesdireccionIn(List<String> values) {
      addCriterion("DESDIRECCION in", values, "desdireccion");
      return (Criteria) this;
    }

    public Criteria andDesdireccionNotIn(List<String> values) {
      addCriterion("DESDIRECCION not in", values, "desdireccion");
      return (Criteria) this;
    }

    public Criteria andDesdireccionBetween(String value1, String value2) {
      addCriterion("DESDIRECCION between", value1, value2, "desdireccion");
      return (Criteria) this;
    }

    public Criteria andDesdireccionNotBetween(String value1, String value2) {
      addCriterion("DESDIRECCION not between", value1, value2, "desdireccion");
      return (Criteria) this;
    }

    public Criteria andCodubigeoIsNull() {
      addCriterion("CODUBIGEO is null");
      return (Criteria) this;
    }

    public Criteria andCodubigeoIsNotNull() {
      addCriterion("CODUBIGEO is not null");
      return (Criteria) this;
    }

    public Criteria andCodubigeoEqualTo(String value) {
      addCriterion("CODUBIGEO =", value, "codubigeo");
      return (Criteria) this;
    }

    public Criteria andCodubigeoNotEqualTo(String value) {
      addCriterion("CODUBIGEO <>", value, "codubigeo");
      return (Criteria) this;
    }

    public Criteria andCodubigeoGreaterThan(String value) {
      addCriterion("CODUBIGEO >", value, "codubigeo");
      return (Criteria) this;
    }

    public Criteria andCodubigeoGreaterThanOrEqualTo(String value) {
      addCriterion("CODUBIGEO >=", value, "codubigeo");
      return (Criteria) this;
    }

    public Criteria andCodubigeoLessThan(String value) {
      addCriterion("CODUBIGEO <", value, "codubigeo");
      return (Criteria) this;
    }

    public Criteria andCodubigeoLessThanOrEqualTo(String value) {
      addCriterion("CODUBIGEO <=", value, "codubigeo");
      return (Criteria) this;
    }

    public Criteria andCodubigeoIn(List<String> values) {
      addCriterion("CODUBIGEO in", values, "codubigeo");
      return (Criteria) this;
    }

    public Criteria andCodubigeoNotIn(List<String> values) {
      addCriterion("CODUBIGEO not in", values, "codubigeo");
      return (Criteria) this;
    }

    public Criteria andCodubigeoBetween(String value1, String value2) {
      addCriterion("CODUBIGEO between", value1, value2, "codubigeo");
      return (Criteria) this;
    }

    public Criteria andCodubigeoNotBetween(String value1, String value2) {
      addCriterion("CODUBIGEO not between", value1, value2, "codubigeo");
      return (Criteria) this;
    }

    public Criteria andFlgProcedenciaIsNull() {
      addCriterion("FLG_PROCEDENCIA is null");
      return (Criteria) this;
    }

    public Criteria andFlgProcedenciaIsNotNull() {
      addCriterion("FLG_PROCEDENCIA is not null");
      return (Criteria) this;
    }

    public Criteria andFlgProcedenciaEqualTo(String value) {
      addCriterion("FLG_PROCEDENCIA =", value, "flgProcedencia");
      return (Criteria) this;
    }

    public Criteria andFlgProcedenciaNotEqualTo(String value) {
      addCriterion("FLG_PROCEDENCIA <>", value, "flgProcedencia");
      return (Criteria) this;
    }

    public Criteria andFlgProcedenciaGreaterThan(String value) {
      addCriterion("FLG_PROCEDENCIA >", value, "flgProcedencia");
      return (Criteria) this;
    }

    public Criteria andFlgProcedenciaGreaterThanOrEqualTo(String value) {
      addCriterion("FLG_PROCEDENCIA >=", value, "flgProcedencia");
      return (Criteria) this;
    }

    public Criteria andFlgProcedenciaLessThan(String value) {
      addCriterion("FLG_PROCEDENCIA <", value, "flgProcedencia");
      return (Criteria) this;
    }

    public Criteria andFlgProcedenciaLessThanOrEqualTo(String value) {
      addCriterion("FLG_PROCEDENCIA <=", value, "flgProcedencia");
      return (Criteria) this;
    }

    public Criteria andFlgProcedenciaIn(List<String> values) {
      addCriterion("FLG_PROCEDENCIA in", values, "flgProcedencia");
      return (Criteria) this;
    }

    public Criteria andFlgProcedenciaNotIn(List<String> values) {
      addCriterion("FLG_PROCEDENCIA not in", values, "flgProcedencia");
      return (Criteria) this;
    }

    public Criteria andFlgProcedenciaBetween(String value1, String value2) {
      addCriterion("FLG_PROCEDENCIA between", value1, value2, "flgProcedencia");
      return (Criteria) this;
    }

    public Criteria andFlgProcedenciaNotBetween(String value1, String value2) {
      addCriterion("FLG_PROCEDENCIA not between", value1, value2, "flgProcedencia");
      return (Criteria) this;
    }

    public Criteria andDescSegurosIsNull() {
      addCriterion("DESC_SEGUROS is null");
      return (Criteria) this;
    }

    public Criteria andDescSegurosIsNotNull() {
      addCriterion("DESC_SEGUROS is not null");
      return (Criteria) this;
    }

    public Criteria andDescSegurosEqualTo(String value) {
      addCriterion("DESC_SEGUROS =", value, "descSeguros");
      return (Criteria) this;
    }

    public Criteria andDescSegurosNotEqualTo(String value) {
      addCriterion("DESC_SEGUROS <>", value, "descSeguros");
      return (Criteria) this;
    }

    public Criteria andDescSegurosGreaterThan(String value) {
      addCriterion("DESC_SEGUROS >", value, "descSeguros");
      return (Criteria) this;
    }

    public Criteria andDescSegurosGreaterThanOrEqualTo(String value) {
      addCriterion("DESC_SEGUROS >=", value, "descSeguros");
      return (Criteria) this;
    }

    public Criteria andDescSegurosLessThan(String value) {
      addCriterion("DESC_SEGUROS <", value, "descSeguros");
      return (Criteria) this;
    }

    public Criteria andDescSegurosLessThanOrEqualTo(String value) {
      addCriterion("DESC_SEGUROS <=", value, "descSeguros");
      return (Criteria) this;
    }

    public Criteria andDescSegurosIn(List<String> values) {
      addCriterion("DESC_SEGUROS in", values, "descSeguros");
      return (Criteria) this;
    }

    public Criteria andDescSegurosNotIn(List<String> values) {
      addCriterion("DESC_SEGUROS not in", values, "descSeguros");
      return (Criteria) this;
    }

    public Criteria andDescSegurosBetween(String value1, String value2) {
      addCriterion("DESC_SEGUROS between", value1, value2, "descSeguros");
      return (Criteria) this;
    }

    public Criteria andDescSegurosNotBetween(String value1, String value2) {
      addCriterion("DESC_SEGUROS not between", value1, value2, "descSeguros");
      return (Criteria) this;
    }

    public Criteria andEstadoIsNull() {
      addCriterion("ESTADO is null");
      return (Criteria) this;
    }

    public Criteria andEstadoIsNotNull() {
      addCriterion("ESTADO is not null");
      return (Criteria) this;
    }

    public Criteria andEstadoEqualTo(String value) {
      addCriterion("ESTADO =", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoNotEqualTo(String value) {
      addCriterion("ESTADO <>", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoGreaterThan(String value) {
      addCriterion("ESTADO >", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoGreaterThanOrEqualTo(String value) {
      addCriterion("ESTADO >=", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoLessThan(String value) {
      addCriterion("ESTADO <", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoLessThanOrEqualTo(String value) {
      addCriterion("ESTADO <=", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoIn(List<String> values) {
      addCriterion("ESTADO in", values, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoNotIn(List<String> values) {
      addCriterion("ESTADO not in", values, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoBetween(String value1, String value2) {
      addCriterion("ESTADO between", value1, value2, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoNotBetween(String value1, String value2) {
      addCriterion("ESTADO not between", value1, value2, "estado");
      return (Criteria) this;
    }

    public Criteria andDesMensajeIsNull() {
      addCriterion("DES_MENSAJE is null");
      return (Criteria) this;
    }

    public Criteria andDesMensajeIsNotNull() {
      addCriterion("DES_MENSAJE is not null");
      return (Criteria) this;
    }

    public Criteria andDesMensajeEqualTo(String value) {
      addCriterion("DES_MENSAJE =", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeNotEqualTo(String value) {
      addCriterion("DES_MENSAJE <>", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeGreaterThan(String value) {
      addCriterion("DES_MENSAJE >", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeGreaterThanOrEqualTo(String value) {
      addCriterion("DES_MENSAJE >=", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeLessThan(String value) {
      addCriterion("DES_MENSAJE <", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeLessThanOrEqualTo(String value) {
      addCriterion("DES_MENSAJE <=", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeIn(List<String> values) {
      addCriterion("DES_MENSAJE in", values, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeNotIn(List<String> values) {
      addCriterion("DES_MENSAJE not in", values, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeBetween(String value1, String value2) {
      addCriterion("DES_MENSAJE between", value1, value2, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeNotBetween(String value1, String value2) {
      addCriterion("DES_MENSAJE not between", value1, value2, "desMensaje");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.TLMK_BASE_IB
   *
   * @mbggenerated do_not_delete_during_merge Thu May 29 11:16:51 COT 2014
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.TLMK_BASE_IB
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}