package com.cardif.satelite.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TlmkBaseBCExample implements Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.TLMK_BASE_BC
   *
   * @mbggenerated Thu Feb 06 17:15:58 COT 2014
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.TLMK_BASE_BC
   *
   * @mbggenerated Thu Feb 06 17:15:58 COT 2014
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.TLMK_BASE_BC
   *
   * @mbggenerated Thu Feb 06 17:15:58 COT 2014
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_BC
   *
   * @mbggenerated Thu Feb 06 17:15:58 COT 2014
   */
  public TlmkBaseBCExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_BC
   *
   * @mbggenerated Thu Feb 06 17:15:58 COT 2014
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_BC
   *
   * @mbggenerated Thu Feb 06 17:15:58 COT 2014
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_BC
   *
   * @mbggenerated Thu Feb 06 17:15:58 COT 2014
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_BC
   *
   * @mbggenerated Thu Feb 06 17:15:58 COT 2014
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_BC
   *
   * @mbggenerated Thu Feb 06 17:15:58 COT 2014
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_BC
   *
   * @mbggenerated Thu Feb 06 17:15:58 COT 2014
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_BC
   *
   * @mbggenerated Thu Feb 06 17:15:58 COT 2014
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_BC
   *
   * @mbggenerated Thu Feb 06 17:15:58 COT 2014
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_BC
   *
   * @mbggenerated Thu Feb 06 17:15:58 COT 2014
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_BC
   *
   * @mbggenerated Thu Feb 06 17:15:58 COT 2014
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.TLMK_BASE_BC
   *
   * @mbggenerated Thu Feb 06 17:15:58 COT 2014
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andPkIsNull() {
      addCriterion("PK is null");
      return (Criteria) this;
    }

    public Criteria andPkIsNotNull() {
      addCriterion("PK is not null");
      return (Criteria) this;
    }

    public Criteria andPkEqualTo(Long value) {
      addCriterion("PK =", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotEqualTo(Long value) {
      addCriterion("PK <>", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThan(Long value) {
      addCriterion("PK >", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThanOrEqualTo(Long value) {
      addCriterion("PK >=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThan(Long value) {
      addCriterion("PK <", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThanOrEqualTo(Long value) {
      addCriterion("PK <=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkIn(List<Long> values) {
      addCriterion("PK in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotIn(List<Long> values) {
      addCriterion("PK not in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkBetween(Long value1, Long value2) {
      addCriterion("PK between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotBetween(Long value1, Long value2) {
      addCriterion("PK not between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andCodBaseIsNull() {
      addCriterion("COD_BASE is null");
      return (Criteria) this;
    }

    public Criteria andCodBaseIsNotNull() {
      addCriterion("COD_BASE is not null");
      return (Criteria) this;
    }

    public Criteria andCodBaseEqualTo(Long value) {
      addCriterion("COD_BASE =", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseNotEqualTo(Long value) {
      addCriterion("COD_BASE <>", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseGreaterThan(Long value) {
      addCriterion("COD_BASE >", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseGreaterThanOrEqualTo(Long value) {
      addCriterion("COD_BASE >=", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseLessThan(Long value) {
      addCriterion("COD_BASE <", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseLessThanOrEqualTo(Long value) {
      addCriterion("COD_BASE <=", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseIn(List<Long> values) {
      addCriterion("COD_BASE in", values, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseNotIn(List<Long> values) {
      addCriterion("COD_BASE not in", values, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseBetween(Long value1, Long value2) {
      addCriterion("COD_BASE between", value1, value2, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseNotBetween(Long value1, Long value2) {
      addCriterion("COD_BASE not between", value1, value2, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodCampIsNull() {
      addCriterion("COD_CAMP is null");
      return (Criteria) this;
    }

    public Criteria andCodCampIsNotNull() {
      addCriterion("COD_CAMP is not null");
      return (Criteria) this;
    }

    public Criteria andCodCampEqualTo(String value) {
      addCriterion("COD_CAMP =", value, "codCamp");
      return (Criteria) this;
    }

    public Criteria andCodCampNotEqualTo(String value) {
      addCriterion("COD_CAMP <>", value, "codCamp");
      return (Criteria) this;
    }

    public Criteria andCodCampGreaterThan(String value) {
      addCriterion("COD_CAMP >", value, "codCamp");
      return (Criteria) this;
    }

    public Criteria andCodCampGreaterThanOrEqualTo(String value) {
      addCriterion("COD_CAMP >=", value, "codCamp");
      return (Criteria) this;
    }

    public Criteria andCodCampLessThan(String value) {
      addCriterion("COD_CAMP <", value, "codCamp");
      return (Criteria) this;
    }

    public Criteria andCodCampLessThanOrEqualTo(String value) {
      addCriterion("COD_CAMP <=", value, "codCamp");
      return (Criteria) this;
    }

    public Criteria andCodCampIn(List<String> values) {
      addCriterion("COD_CAMP in", values, "codCamp");
      return (Criteria) this;
    }

    public Criteria andCodCampNotIn(List<String> values) {
      addCriterion("COD_CAMP not in", values, "codCamp");
      return (Criteria) this;
    }

    public Criteria andCodCampBetween(String value1, String value2) {
      addCriterion("COD_CAMP between", value1, value2, "codCamp");
      return (Criteria) this;
    }

    public Criteria andCodCampNotBetween(String value1, String value2) {
      addCriterion("COD_CAMP not between", value1, value2, "codCamp");
      return (Criteria) this;
    }

    public Criteria andFecInicIsNull() {
      addCriterion("FEC_INIC is null");
      return (Criteria) this;
    }

    public Criteria andFecInicIsNotNull() {
      addCriterion("FEC_INIC is not null");
      return (Criteria) this;
    }

    public Criteria andFecInicEqualTo(String value) {
      addCriterion("FEC_INIC =", value, "fecInic");
      return (Criteria) this;
    }

    public Criteria andFecInicNotEqualTo(String value) {
      addCriterion("FEC_INIC <>", value, "fecInic");
      return (Criteria) this;
    }

    public Criteria andFecInicGreaterThan(String value) {
      addCriterion("FEC_INIC >", value, "fecInic");
      return (Criteria) this;
    }

    public Criteria andFecInicGreaterThanOrEqualTo(String value) {
      addCriterion("FEC_INIC >=", value, "fecInic");
      return (Criteria) this;
    }

    public Criteria andFecInicLessThan(String value) {
      addCriterion("FEC_INIC <", value, "fecInic");
      return (Criteria) this;
    }

    public Criteria andFecInicLessThanOrEqualTo(String value) {
      addCriterion("FEC_INIC <=", value, "fecInic");
      return (Criteria) this;
    }

    public Criteria andFecInicIn(List<String> values) {
      addCriterion("FEC_INIC in", values, "fecInic");
      return (Criteria) this;
    }

    public Criteria andFecInicNotIn(List<String> values) {
      addCriterion("FEC_INIC not in", values, "fecInic");
      return (Criteria) this;
    }

    public Criteria andFecInicBetween(String value1, String value2) {
      addCriterion("FEC_INIC between", value1, value2, "fecInic");
      return (Criteria) this;
    }

    public Criteria andFecInicNotBetween(String value1, String value2) {
      addCriterion("FEC_INIC not between", value1, value2, "fecInic");
      return (Criteria) this;
    }

    public Criteria andFecFinalIsNull() {
      addCriterion("FEC_FINAL is null");
      return (Criteria) this;
    }

    public Criteria andFecFinalIsNotNull() {
      addCriterion("FEC_FINAL is not null");
      return (Criteria) this;
    }

    public Criteria andFecFinalEqualTo(String value) {
      addCriterion("FEC_FINAL =", value, "fecFinal");
      return (Criteria) this;
    }

    public Criteria andFecFinalNotEqualTo(String value) {
      addCriterion("FEC_FINAL <>", value, "fecFinal");
      return (Criteria) this;
    }

    public Criteria andFecFinalGreaterThan(String value) {
      addCriterion("FEC_FINAL >", value, "fecFinal");
      return (Criteria) this;
    }

    public Criteria andFecFinalGreaterThanOrEqualTo(String value) {
      addCriterion("FEC_FINAL >=", value, "fecFinal");
      return (Criteria) this;
    }

    public Criteria andFecFinalLessThan(String value) {
      addCriterion("FEC_FINAL <", value, "fecFinal");
      return (Criteria) this;
    }

    public Criteria andFecFinalLessThanOrEqualTo(String value) {
      addCriterion("FEC_FINAL <=", value, "fecFinal");
      return (Criteria) this;
    }

    public Criteria andFecFinalIn(List<String> values) {
      addCriterion("FEC_FINAL in", values, "fecFinal");
      return (Criteria) this;
    }

    public Criteria andFecFinalNotIn(List<String> values) {
      addCriterion("FEC_FINAL not in", values, "fecFinal");
      return (Criteria) this;
    }

    public Criteria andFecFinalBetween(String value1, String value2) {
      addCriterion("FEC_FINAL between", value1, value2, "fecFinal");
      return (Criteria) this;
    }

    public Criteria andFecFinalNotBetween(String value1, String value2) {
      addCriterion("FEC_FINAL not between", value1, value2, "fecFinal");
      return (Criteria) this;
    }

    public Criteria andClienteIsNull() {
      addCriterion("CLIENTE is null");
      return (Criteria) this;
    }

    public Criteria andClienteIsNotNull() {
      addCriterion("CLIENTE is not null");
      return (Criteria) this;
    }

    public Criteria andClienteEqualTo(String value) {
      addCriterion("CLIENTE =", value, "cliente");
      return (Criteria) this;
    }

    public Criteria andClienteNotEqualTo(String value) {
      addCriterion("CLIENTE <>", value, "cliente");
      return (Criteria) this;
    }

    public Criteria andClienteGreaterThan(String value) {
      addCriterion("CLIENTE >", value, "cliente");
      return (Criteria) this;
    }

    public Criteria andClienteGreaterThanOrEqualTo(String value) {
      addCriterion("CLIENTE >=", value, "cliente");
      return (Criteria) this;
    }

    public Criteria andClienteLessThan(String value) {
      addCriterion("CLIENTE <", value, "cliente");
      return (Criteria) this;
    }

    public Criteria andClienteLessThanOrEqualTo(String value) {
      addCriterion("CLIENTE <=", value, "cliente");
      return (Criteria) this;
    }

    public Criteria andClienteIn(List<String> values) {
      addCriterion("CLIENTE in", values, "cliente");
      return (Criteria) this;
    }

    public Criteria andClienteNotIn(List<String> values) {
      addCriterion("CLIENTE not in", values, "cliente");
      return (Criteria) this;
    }

    public Criteria andClienteBetween(String value1, String value2) {
      addCriterion("CLIENTE between", value1, value2, "cliente");
      return (Criteria) this;
    }

    public Criteria andClienteNotBetween(String value1, String value2) {
      addCriterion("CLIENTE not between", value1, value2, "cliente");
      return (Criteria) this;
    }

    public Criteria andTdocumIsNull() {
      addCriterion("TDOCUM is null");
      return (Criteria) this;
    }

    public Criteria andTdocumIsNotNull() {
      addCriterion("TDOCUM is not null");
      return (Criteria) this;
    }

    public Criteria andTdocumEqualTo(String value) {
      addCriterion("TDOCUM =", value, "tdocum");
      return (Criteria) this;
    }

    public Criteria andTdocumNotEqualTo(String value) {
      addCriterion("TDOCUM <>", value, "tdocum");
      return (Criteria) this;
    }

    public Criteria andTdocumGreaterThan(String value) {
      addCriterion("TDOCUM >", value, "tdocum");
      return (Criteria) this;
    }

    public Criteria andTdocumGreaterThanOrEqualTo(String value) {
      addCriterion("TDOCUM >=", value, "tdocum");
      return (Criteria) this;
    }

    public Criteria andTdocumLessThan(String value) {
      addCriterion("TDOCUM <", value, "tdocum");
      return (Criteria) this;
    }

    public Criteria andTdocumLessThanOrEqualTo(String value) {
      addCriterion("TDOCUM <=", value, "tdocum");
      return (Criteria) this;
    }

    public Criteria andTdocumIn(List<String> values) {
      addCriterion("TDOCUM in", values, "tdocum");
      return (Criteria) this;
    }

    public Criteria andTdocumNotIn(List<String> values) {
      addCriterion("TDOCUM not in", values, "tdocum");
      return (Criteria) this;
    }

    public Criteria andTdocumBetween(String value1, String value2) {
      addCriterion("TDOCUM between", value1, value2, "tdocum");
      return (Criteria) this;
    }

    public Criteria andTdocumNotBetween(String value1, String value2) {
      addCriterion("TDOCUM not between", value1, value2, "tdocum");
      return (Criteria) this;
    }

    public Criteria andNdocIdentIsNull() {
      addCriterion("NDOC_IDENT is null");
      return (Criteria) this;
    }

    public Criteria andNdocIdentIsNotNull() {
      addCriterion("NDOC_IDENT is not null");
      return (Criteria) this;
    }

    public Criteria andNdocIdentEqualTo(String value) {
      addCriterion("NDOC_IDENT =", value, "ndocIdent");
      return (Criteria) this;
    }

    public Criteria andNdocIdentNotEqualTo(String value) {
      addCriterion("NDOC_IDENT <>", value, "ndocIdent");
      return (Criteria) this;
    }

    public Criteria andNdocIdentGreaterThan(String value) {
      addCriterion("NDOC_IDENT >", value, "ndocIdent");
      return (Criteria) this;
    }

    public Criteria andNdocIdentGreaterThanOrEqualTo(String value) {
      addCriterion("NDOC_IDENT >=", value, "ndocIdent");
      return (Criteria) this;
    }

    public Criteria andNdocIdentLessThan(String value) {
      addCriterion("NDOC_IDENT <", value, "ndocIdent");
      return (Criteria) this;
    }

    public Criteria andNdocIdentLessThanOrEqualTo(String value) {
      addCriterion("NDOC_IDENT <=", value, "ndocIdent");
      return (Criteria) this;
    }

    public Criteria andNdocIdentIn(List<String> values) {
      addCriterion("NDOC_IDENT in", values, "ndocIdent");
      return (Criteria) this;
    }

    public Criteria andNdocIdentNotIn(List<String> values) {
      addCriterion("NDOC_IDENT not in", values, "ndocIdent");
      return (Criteria) this;
    }

    public Criteria andNdocIdentBetween(String value1, String value2) {
      addCriterion("NDOC_IDENT between", value1, value2, "ndocIdent");
      return (Criteria) this;
    }

    public Criteria andNdocIdentNotBetween(String value1, String value2) {
      addCriterion("NDOC_IDENT not between", value1, value2, "ndocIdent");
      return (Criteria) this;
    }

    public Criteria andCodTrataIsNull() {
      addCriterion("COD_TRATA is null");
      return (Criteria) this;
    }

    public Criteria andCodTrataIsNotNull() {
      addCriterion("COD_TRATA is not null");
      return (Criteria) this;
    }

    public Criteria andCodTrataEqualTo(String value) {
      addCriterion("COD_TRATA =", value, "codTrata");
      return (Criteria) this;
    }

    public Criteria andCodTrataNotEqualTo(String value) {
      addCriterion("COD_TRATA <>", value, "codTrata");
      return (Criteria) this;
    }

    public Criteria andCodTrataGreaterThan(String value) {
      addCriterion("COD_TRATA >", value, "codTrata");
      return (Criteria) this;
    }

    public Criteria andCodTrataGreaterThanOrEqualTo(String value) {
      addCriterion("COD_TRATA >=", value, "codTrata");
      return (Criteria) this;
    }

    public Criteria andCodTrataLessThan(String value) {
      addCriterion("COD_TRATA <", value, "codTrata");
      return (Criteria) this;
    }

    public Criteria andCodTrataLessThanOrEqualTo(String value) {
      addCriterion("COD_TRATA <=", value, "codTrata");
      return (Criteria) this;
    }

    public Criteria andCodTrataIn(List<String> values) {
      addCriterion("COD_TRATA in", values, "codTrata");
      return (Criteria) this;
    }

    public Criteria andCodTrataNotIn(List<String> values) {
      addCriterion("COD_TRATA not in", values, "codTrata");
      return (Criteria) this;
    }

    public Criteria andCodTrataBetween(String value1, String value2) {
      addCriterion("COD_TRATA between", value1, value2, "codTrata");
      return (Criteria) this;
    }

    public Criteria andCodTrataNotBetween(String value1, String value2) {
      addCriterion("COD_TRATA not between", value1, value2, "codTrata");
      return (Criteria) this;
    }

    public Criteria andCodProveedorIsNull() {
      addCriterion("COD_PROVEEDOR is null");
      return (Criteria) this;
    }

    public Criteria andCodProveedorIsNotNull() {
      addCriterion("COD_PROVEEDOR is not null");
      return (Criteria) this;
    }

    public Criteria andCodProveedorEqualTo(String value) {
      addCriterion("COD_PROVEEDOR =", value, "codProveedor");
      return (Criteria) this;
    }

    public Criteria andCodProveedorNotEqualTo(String value) {
      addCriterion("COD_PROVEEDOR <>", value, "codProveedor");
      return (Criteria) this;
    }

    public Criteria andCodProveedorGreaterThan(String value) {
      addCriterion("COD_PROVEEDOR >", value, "codProveedor");
      return (Criteria) this;
    }

    public Criteria andCodProveedorGreaterThanOrEqualTo(String value) {
      addCriterion("COD_PROVEEDOR >=", value, "codProveedor");
      return (Criteria) this;
    }

    public Criteria andCodProveedorLessThan(String value) {
      addCriterion("COD_PROVEEDOR <", value, "codProveedor");
      return (Criteria) this;
    }

    public Criteria andCodProveedorLessThanOrEqualTo(String value) {
      addCriterion("COD_PROVEEDOR <=", value, "codProveedor");
      return (Criteria) this;
    }

    public Criteria andCodProveedorIn(List<String> values) {
      addCriterion("COD_PROVEEDOR in", values, "codProveedor");
      return (Criteria) this;
    }

    public Criteria andCodProveedorNotIn(List<String> values) {
      addCriterion("COD_PROVEEDOR not in", values, "codProveedor");
      return (Criteria) this;
    }

    public Criteria andCodProveedorBetween(String value1, String value2) {
      addCriterion("COD_PROVEEDOR between", value1, value2, "codProveedor");
      return (Criteria) this;
    }

    public Criteria andCodProveedorNotBetween(String value1, String value2) {
      addCriterion("COD_PROVEEDOR not between", value1, value2, "codProveedor");
      return (Criteria) this;
    }

    public Criteria andCodRptaIsNull() {
      addCriterion("COD_RPTA is null");
      return (Criteria) this;
    }

    public Criteria andCodRptaIsNotNull() {
      addCriterion("COD_RPTA is not null");
      return (Criteria) this;
    }

    public Criteria andCodRptaEqualTo(String value) {
      addCriterion("COD_RPTA =", value, "codRpta");
      return (Criteria) this;
    }

    public Criteria andCodRptaNotEqualTo(String value) {
      addCriterion("COD_RPTA <>", value, "codRpta");
      return (Criteria) this;
    }

    public Criteria andCodRptaGreaterThan(String value) {
      addCriterion("COD_RPTA >", value, "codRpta");
      return (Criteria) this;
    }

    public Criteria andCodRptaGreaterThanOrEqualTo(String value) {
      addCriterion("COD_RPTA >=", value, "codRpta");
      return (Criteria) this;
    }

    public Criteria andCodRptaLessThan(String value) {
      addCriterion("COD_RPTA <", value, "codRpta");
      return (Criteria) this;
    }

    public Criteria andCodRptaLessThanOrEqualTo(String value) {
      addCriterion("COD_RPTA <=", value, "codRpta");
      return (Criteria) this;
    }

    public Criteria andCodRptaIn(List<String> values) {
      addCriterion("COD_RPTA in", values, "codRpta");
      return (Criteria) this;
    }

    public Criteria andCodRptaNotIn(List<String> values) {
      addCriterion("COD_RPTA not in", values, "codRpta");
      return (Criteria) this;
    }

    public Criteria andCodRptaBetween(String value1, String value2) {
      addCriterion("COD_RPTA between", value1, value2, "codRpta");
      return (Criteria) this;
    }

    public Criteria andCodRptaNotBetween(String value1, String value2) {
      addCriterion("COD_RPTA not between", value1, value2, "codRpta");
      return (Criteria) this;
    }

    public Criteria andCodObsIsNull() {
      addCriterion("COD_OBS is null");
      return (Criteria) this;
    }

    public Criteria andCodObsIsNotNull() {
      addCriterion("COD_OBS is not null");
      return (Criteria) this;
    }

    public Criteria andCodObsEqualTo(String value) {
      addCriterion("COD_OBS =", value, "codObs");
      return (Criteria) this;
    }

    public Criteria andCodObsNotEqualTo(String value) {
      addCriterion("COD_OBS <>", value, "codObs");
      return (Criteria) this;
    }

    public Criteria andCodObsGreaterThan(String value) {
      addCriterion("COD_OBS >", value, "codObs");
      return (Criteria) this;
    }

    public Criteria andCodObsGreaterThanOrEqualTo(String value) {
      addCriterion("COD_OBS >=", value, "codObs");
      return (Criteria) this;
    }

    public Criteria andCodObsLessThan(String value) {
      addCriterion("COD_OBS <", value, "codObs");
      return (Criteria) this;
    }

    public Criteria andCodObsLessThanOrEqualTo(String value) {
      addCriterion("COD_OBS <=", value, "codObs");
      return (Criteria) this;
    }

    public Criteria andCodObsIn(List<String> values) {
      addCriterion("COD_OBS in", values, "codObs");
      return (Criteria) this;
    }

    public Criteria andCodObsNotIn(List<String> values) {
      addCriterion("COD_OBS not in", values, "codObs");
      return (Criteria) this;
    }

    public Criteria andCodObsBetween(String value1, String value2) {
      addCriterion("COD_OBS between", value1, value2, "codObs");
      return (Criteria) this;
    }

    public Criteria andCodObsNotBetween(String value1, String value2) {
      addCriterion("COD_OBS not between", value1, value2, "codObs");
      return (Criteria) this;
    }

    public Criteria andFenacimiIsNull() {
      addCriterion("FENACIMI is null");
      return (Criteria) this;
    }

    public Criteria andFenacimiIsNotNull() {
      addCriterion("FENACIMI is not null");
      return (Criteria) this;
    }

    public Criteria andFenacimiEqualTo(Date value) {
      addCriterion("FENACIMI =", value, "fenacimi");
      return (Criteria) this;
    }

    public Criteria andFenacimiNotEqualTo(Date value) {
      addCriterion("FENACIMI <>", value, "fenacimi");
      return (Criteria) this;
    }

    public Criteria andFenacimiGreaterThan(Date value) {
      addCriterion("FENACIMI >", value, "fenacimi");
      return (Criteria) this;
    }

    public Criteria andFenacimiGreaterThanOrEqualTo(Date value) {
      addCriterion("FENACIMI >=", value, "fenacimi");
      return (Criteria) this;
    }

    public Criteria andFenacimiLessThan(Date value) {
      addCriterion("FENACIMI <", value, "fenacimi");
      return (Criteria) this;
    }

    public Criteria andFenacimiLessThanOrEqualTo(Date value) {
      addCriterion("FENACIMI <=", value, "fenacimi");
      return (Criteria) this;
    }

    public Criteria andFenacimiIn(List<Date> values) {
      addCriterion("FENACIMI in", values, "fenacimi");
      return (Criteria) this;
    }

    public Criteria andFenacimiNotIn(List<Date> values) {
      addCriterion("FENACIMI not in", values, "fenacimi");
      return (Criteria) this;
    }

    public Criteria andFenacimiBetween(Date value1, Date value2) {
      addCriterion("FENACIMI between", value1, value2, "fenacimi");
      return (Criteria) this;
    }

    public Criteria andFenacimiNotBetween(Date value1, Date value2) {
      addCriterion("FENACIMI not between", value1, value2, "fenacimi");
      return (Criteria) this;
    }

    public Criteria andEdadIsNull() {
      addCriterion("EDAD is null");
      return (Criteria) this;
    }

    public Criteria andEdadIsNotNull() {
      addCriterion("EDAD is not null");
      return (Criteria) this;
    }

    public Criteria andEdadEqualTo(String value) {
      addCriterion("EDAD =", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadNotEqualTo(String value) {
      addCriterion("EDAD <>", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadGreaterThan(String value) {
      addCriterion("EDAD >", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadGreaterThanOrEqualTo(String value) {
      addCriterion("EDAD >=", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadLessThan(String value) {
      addCriterion("EDAD <", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadLessThanOrEqualTo(String value) {
      addCriterion("EDAD <=", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadIn(List<String> values) {
      addCriterion("EDAD in", values, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadNotIn(List<String> values) {
      addCriterion("EDAD not in", values, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadBetween(String value1, String value2) {
      addCriterion("EDAD between", value1, value2, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadNotBetween(String value1, String value2) {
      addCriterion("EDAD not between", value1, value2, "edad");
      return (Criteria) this;
    }

    public Criteria andSexoIsNull() {
      addCriterion("SEXO is null");
      return (Criteria) this;
    }

    public Criteria andSexoIsNotNull() {
      addCriterion("SEXO is not null");
      return (Criteria) this;
    }

    public Criteria andSexoEqualTo(String value) {
      addCriterion("SEXO =", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoNotEqualTo(String value) {
      addCriterion("SEXO <>", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoGreaterThan(String value) {
      addCriterion("SEXO >", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoGreaterThanOrEqualTo(String value) {
      addCriterion("SEXO >=", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoLessThan(String value) {
      addCriterion("SEXO <", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoLessThanOrEqualTo(String value) {
      addCriterion("SEXO <=", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoIn(List<String> values) {
      addCriterion("SEXO in", values, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoNotIn(List<String> values) {
      addCriterion("SEXO not in", values, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoBetween(String value1, String value2) {
      addCriterion("SEXO between", value1, value2, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoNotBetween(String value1, String value2) {
      addCriterion("SEXO not between", value1, value2, "sexo");
      return (Criteria) this;
    }

    public Criteria andEstCivilIsNull() {
      addCriterion("EST_CIVIL is null");
      return (Criteria) this;
    }

    public Criteria andEstCivilIsNotNull() {
      addCriterion("EST_CIVIL is not null");
      return (Criteria) this;
    }

    public Criteria andEstCivilEqualTo(String value) {
      addCriterion("EST_CIVIL =", value, "estCivil");
      return (Criteria) this;
    }

    public Criteria andEstCivilNotEqualTo(String value) {
      addCriterion("EST_CIVIL <>", value, "estCivil");
      return (Criteria) this;
    }

    public Criteria andEstCivilGreaterThan(String value) {
      addCriterion("EST_CIVIL >", value, "estCivil");
      return (Criteria) this;
    }

    public Criteria andEstCivilGreaterThanOrEqualTo(String value) {
      addCriterion("EST_CIVIL >=", value, "estCivil");
      return (Criteria) this;
    }

    public Criteria andEstCivilLessThan(String value) {
      addCriterion("EST_CIVIL <", value, "estCivil");
      return (Criteria) this;
    }

    public Criteria andEstCivilLessThanOrEqualTo(String value) {
      addCriterion("EST_CIVIL <=", value, "estCivil");
      return (Criteria) this;
    }

    public Criteria andEstCivilIn(List<String> values) {
      addCriterion("EST_CIVIL in", values, "estCivil");
      return (Criteria) this;
    }

    public Criteria andEstCivilNotIn(List<String> values) {
      addCriterion("EST_CIVIL not in", values, "estCivil");
      return (Criteria) this;
    }

    public Criteria andEstCivilBetween(String value1, String value2) {
      addCriterion("EST_CIVIL between", value1, value2, "estCivil");
      return (Criteria) this;
    }

    public Criteria andEstCivilNotBetween(String value1, String value2) {
      addCriterion("EST_CIVIL not between", value1, value2, "estCivil");
      return (Criteria) this;
    }

    public Criteria andPriapeIsNull() {
      addCriterion("PRIAPE is null");
      return (Criteria) this;
    }

    public Criteria andPriapeIsNotNull() {
      addCriterion("PRIAPE is not null");
      return (Criteria) this;
    }

    public Criteria andPriapeEqualTo(String value) {
      addCriterion("PRIAPE =", value, "priape");
      return (Criteria) this;
    }

    public Criteria andPriapeNotEqualTo(String value) {
      addCriterion("PRIAPE <>", value, "priape");
      return (Criteria) this;
    }

    public Criteria andPriapeGreaterThan(String value) {
      addCriterion("PRIAPE >", value, "priape");
      return (Criteria) this;
    }

    public Criteria andPriapeGreaterThanOrEqualTo(String value) {
      addCriterion("PRIAPE >=", value, "priape");
      return (Criteria) this;
    }

    public Criteria andPriapeLessThan(String value) {
      addCriterion("PRIAPE <", value, "priape");
      return (Criteria) this;
    }

    public Criteria andPriapeLessThanOrEqualTo(String value) {
      addCriterion("PRIAPE <=", value, "priape");
      return (Criteria) this;
    }

    public Criteria andPriapeIn(List<String> values) {
      addCriterion("PRIAPE in", values, "priape");
      return (Criteria) this;
    }

    public Criteria andPriapeNotIn(List<String> values) {
      addCriterion("PRIAPE not in", values, "priape");
      return (Criteria) this;
    }

    public Criteria andPriapeBetween(String value1, String value2) {
      addCriterion("PRIAPE between", value1, value2, "priape");
      return (Criteria) this;
    }

    public Criteria andPriapeNotBetween(String value1, String value2) {
      addCriterion("PRIAPE not between", value1, value2, "priape");
      return (Criteria) this;
    }

    public Criteria andSegapeIsNull() {
      addCriterion("SEGAPE is null");
      return (Criteria) this;
    }

    public Criteria andSegapeIsNotNull() {
      addCriterion("SEGAPE is not null");
      return (Criteria) this;
    }

    public Criteria andSegapeEqualTo(String value) {
      addCriterion("SEGAPE =", value, "segape");
      return (Criteria) this;
    }

    public Criteria andSegapeNotEqualTo(String value) {
      addCriterion("SEGAPE <>", value, "segape");
      return (Criteria) this;
    }

    public Criteria andSegapeGreaterThan(String value) {
      addCriterion("SEGAPE >", value, "segape");
      return (Criteria) this;
    }

    public Criteria andSegapeGreaterThanOrEqualTo(String value) {
      addCriterion("SEGAPE >=", value, "segape");
      return (Criteria) this;
    }

    public Criteria andSegapeLessThan(String value) {
      addCriterion("SEGAPE <", value, "segape");
      return (Criteria) this;
    }

    public Criteria andSegapeLessThanOrEqualTo(String value) {
      addCriterion("SEGAPE <=", value, "segape");
      return (Criteria) this;
    }

    public Criteria andSegapeIn(List<String> values) {
      addCriterion("SEGAPE in", values, "segape");
      return (Criteria) this;
    }

    public Criteria andSegapeNotIn(List<String> values) {
      addCriterion("SEGAPE not in", values, "segape");
      return (Criteria) this;
    }

    public Criteria andSegapeBetween(String value1, String value2) {
      addCriterion("SEGAPE between", value1, value2, "segape");
      return (Criteria) this;
    }

    public Criteria andSegapeNotBetween(String value1, String value2) {
      addCriterion("SEGAPE not between", value1, value2, "segape");
      return (Criteria) this;
    }

    public Criteria andNombresIsNull() {
      addCriterion("NOMBRES is null");
      return (Criteria) this;
    }

    public Criteria andNombresIsNotNull() {
      addCriterion("NOMBRES is not null");
      return (Criteria) this;
    }

    public Criteria andNombresEqualTo(String value) {
      addCriterion("NOMBRES =", value, "nombres");
      return (Criteria) this;
    }

    public Criteria andNombresNotEqualTo(String value) {
      addCriterion("NOMBRES <>", value, "nombres");
      return (Criteria) this;
    }

    public Criteria andNombresGreaterThan(String value) {
      addCriterion("NOMBRES >", value, "nombres");
      return (Criteria) this;
    }

    public Criteria andNombresGreaterThanOrEqualTo(String value) {
      addCriterion("NOMBRES >=", value, "nombres");
      return (Criteria) this;
    }

    public Criteria andNombresLessThan(String value) {
      addCriterion("NOMBRES <", value, "nombres");
      return (Criteria) this;
    }

    public Criteria andNombresLessThanOrEqualTo(String value) {
      addCriterion("NOMBRES <=", value, "nombres");
      return (Criteria) this;
    }

    public Criteria andNombresIn(List<String> values) {
      addCriterion("NOMBRES in", values, "nombres");
      return (Criteria) this;
    }

    public Criteria andNombresNotIn(List<String> values) {
      addCriterion("NOMBRES not in", values, "nombres");
      return (Criteria) this;
    }

    public Criteria andNombresBetween(String value1, String value2) {
      addCriterion("NOMBRES between", value1, value2, "nombres");
      return (Criteria) this;
    }

    public Criteria andNombresNotBetween(String value1, String value2) {
      addCriterion("NOMBRES not between", value1, value2, "nombres");
      return (Criteria) this;
    }

    public Criteria andDireccionIsNull() {
      addCriterion("DIRECCION is null");
      return (Criteria) this;
    }

    public Criteria andDireccionIsNotNull() {
      addCriterion("DIRECCION is not null");
      return (Criteria) this;
    }

    public Criteria andDireccionEqualTo(String value) {
      addCriterion("DIRECCION =", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionNotEqualTo(String value) {
      addCriterion("DIRECCION <>", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionGreaterThan(String value) {
      addCriterion("DIRECCION >", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionGreaterThanOrEqualTo(String value) {
      addCriterion("DIRECCION >=", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionLessThan(String value) {
      addCriterion("DIRECCION <", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionLessThanOrEqualTo(String value) {
      addCriterion("DIRECCION <=", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionIn(List<String> values) {
      addCriterion("DIRECCION in", values, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionNotIn(List<String> values) {
      addCriterion("DIRECCION not in", values, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionBetween(String value1, String value2) {
      addCriterion("DIRECCION between", value1, value2, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionNotBetween(String value1, String value2) {
      addCriterion("DIRECCION not between", value1, value2, "direccion");
      return (Criteria) this;
    }

    public Criteria andUbigeoIsNull() {
      addCriterion("UBIGEO is null");
      return (Criteria) this;
    }

    public Criteria andUbigeoIsNotNull() {
      addCriterion("UBIGEO is not null");
      return (Criteria) this;
    }

    public Criteria andUbigeoEqualTo(String value) {
      addCriterion("UBIGEO =", value, "ubigeo");
      return (Criteria) this;
    }

    public Criteria andUbigeoNotEqualTo(String value) {
      addCriterion("UBIGEO <>", value, "ubigeo");
      return (Criteria) this;
    }

    public Criteria andUbigeoGreaterThan(String value) {
      addCriterion("UBIGEO >", value, "ubigeo");
      return (Criteria) this;
    }

    public Criteria andUbigeoGreaterThanOrEqualTo(String value) {
      addCriterion("UBIGEO >=", value, "ubigeo");
      return (Criteria) this;
    }

    public Criteria andUbigeoLessThan(String value) {
      addCriterion("UBIGEO <", value, "ubigeo");
      return (Criteria) this;
    }

    public Criteria andUbigeoLessThanOrEqualTo(String value) {
      addCriterion("UBIGEO <=", value, "ubigeo");
      return (Criteria) this;
    }

    public Criteria andUbigeoIn(List<String> values) {
      addCriterion("UBIGEO in", values, "ubigeo");
      return (Criteria) this;
    }

    public Criteria andUbigeoNotIn(List<String> values) {
      addCriterion("UBIGEO not in", values, "ubigeo");
      return (Criteria) this;
    }

    public Criteria andUbigeoBetween(String value1, String value2) {
      addCriterion("UBIGEO between", value1, value2, "ubigeo");
      return (Criteria) this;
    }

    public Criteria andUbigeoNotBetween(String value1, String value2) {
      addCriterion("UBIGEO not between", value1, value2, "ubigeo");
      return (Criteria) this;
    }

    public Criteria andDistritoIsNull() {
      addCriterion("DISTRITO is null");
      return (Criteria) this;
    }

    public Criteria andDistritoIsNotNull() {
      addCriterion("DISTRITO is not null");
      return (Criteria) this;
    }

    public Criteria andDistritoEqualTo(String value) {
      addCriterion("DISTRITO =", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoNotEqualTo(String value) {
      addCriterion("DISTRITO <>", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoGreaterThan(String value) {
      addCriterion("DISTRITO >", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoGreaterThanOrEqualTo(String value) {
      addCriterion("DISTRITO >=", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoLessThan(String value) {
      addCriterion("DISTRITO <", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoLessThanOrEqualTo(String value) {
      addCriterion("DISTRITO <=", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoIn(List<String> values) {
      addCriterion("DISTRITO in", values, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoNotIn(List<String> values) {
      addCriterion("DISTRITO not in", values, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoBetween(String value1, String value2) {
      addCriterion("DISTRITO between", value1, value2, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoNotBetween(String value1, String value2) {
      addCriterion("DISTRITO not between", value1, value2, "distrito");
      return (Criteria) this;
    }

    public Criteria andProvinciaIsNull() {
      addCriterion("PROVINCIA is null");
      return (Criteria) this;
    }

    public Criteria andProvinciaIsNotNull() {
      addCriterion("PROVINCIA is not null");
      return (Criteria) this;
    }

    public Criteria andProvinciaEqualTo(String value) {
      addCriterion("PROVINCIA =", value, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaNotEqualTo(String value) {
      addCriterion("PROVINCIA <>", value, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaGreaterThan(String value) {
      addCriterion("PROVINCIA >", value, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaGreaterThanOrEqualTo(String value) {
      addCriterion("PROVINCIA >=", value, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaLessThan(String value) {
      addCriterion("PROVINCIA <", value, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaLessThanOrEqualTo(String value) {
      addCriterion("PROVINCIA <=", value, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaIn(List<String> values) {
      addCriterion("PROVINCIA in", values, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaNotIn(List<String> values) {
      addCriterion("PROVINCIA not in", values, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaBetween(String value1, String value2) {
      addCriterion("PROVINCIA between", value1, value2, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaNotBetween(String value1, String value2) {
      addCriterion("PROVINCIA not between", value1, value2, "provincia");
      return (Criteria) this;
    }

    public Criteria andDepartamentoIsNull() {
      addCriterion("DEPARTAMENTO is null");
      return (Criteria) this;
    }

    public Criteria andDepartamentoIsNotNull() {
      addCriterion("DEPARTAMENTO is not null");
      return (Criteria) this;
    }

    public Criteria andDepartamentoEqualTo(String value) {
      addCriterion("DEPARTAMENTO =", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoNotEqualTo(String value) {
      addCriterion("DEPARTAMENTO <>", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoGreaterThan(String value) {
      addCriterion("DEPARTAMENTO >", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoGreaterThanOrEqualTo(String value) {
      addCriterion("DEPARTAMENTO >=", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoLessThan(String value) {
      addCriterion("DEPARTAMENTO <", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoLessThanOrEqualTo(String value) {
      addCriterion("DEPARTAMENTO <=", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoIn(List<String> values) {
      addCriterion("DEPARTAMENTO in", values, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoNotIn(List<String> values) {
      addCriterion("DEPARTAMENTO not in", values, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoBetween(String value1, String value2) {
      addCriterion("DEPARTAMENTO between", value1, value2, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoNotBetween(String value1, String value2) {
      addCriterion("DEPARTAMENTO not between", value1, value2, "departamento");
      return (Criteria) this;
    }

    public Criteria andTiptel1IsNull() {
      addCriterion("TIPTEL1 is null");
      return (Criteria) this;
    }

    public Criteria andTiptel1IsNotNull() {
      addCriterion("TIPTEL1 is not null");
      return (Criteria) this;
    }

    public Criteria andTiptel1EqualTo(String value) {
      addCriterion("TIPTEL1 =", value, "tiptel1");
      return (Criteria) this;
    }

    public Criteria andTiptel1NotEqualTo(String value) {
      addCriterion("TIPTEL1 <>", value, "tiptel1");
      return (Criteria) this;
    }

    public Criteria andTiptel1GreaterThan(String value) {
      addCriterion("TIPTEL1 >", value, "tiptel1");
      return (Criteria) this;
    }

    public Criteria andTiptel1GreaterThanOrEqualTo(String value) {
      addCriterion("TIPTEL1 >=", value, "tiptel1");
      return (Criteria) this;
    }

    public Criteria andTiptel1LessThan(String value) {
      addCriterion("TIPTEL1 <", value, "tiptel1");
      return (Criteria) this;
    }

    public Criteria andTiptel1LessThanOrEqualTo(String value) {
      addCriterion("TIPTEL1 <=", value, "tiptel1");
      return (Criteria) this;
    }

    public Criteria andTiptel1In(List<String> values) {
      addCriterion("TIPTEL1 in", values, "tiptel1");
      return (Criteria) this;
    }

    public Criteria andTiptel1NotIn(List<String> values) {
      addCriterion("TIPTEL1 not in", values, "tiptel1");
      return (Criteria) this;
    }

    public Criteria andTiptel1Between(String value1, String value2) {
      addCriterion("TIPTEL1 between", value1, value2, "tiptel1");
      return (Criteria) this;
    }

    public Criteria andTiptel1NotBetween(String value1, String value2) {
      addCriterion("TIPTEL1 not between", value1, value2, "tiptel1");
      return (Criteria) this;
    }

    public Criteria andTiptel2IsNull() {
      addCriterion("TIPTEL2 is null");
      return (Criteria) this;
    }

    public Criteria andTiptel2IsNotNull() {
      addCriterion("TIPTEL2 is not null");
      return (Criteria) this;
    }

    public Criteria andTiptel2EqualTo(String value) {
      addCriterion("TIPTEL2 =", value, "tiptel2");
      return (Criteria) this;
    }

    public Criteria andTiptel2NotEqualTo(String value) {
      addCriterion("TIPTEL2 <>", value, "tiptel2");
      return (Criteria) this;
    }

    public Criteria andTiptel2GreaterThan(String value) {
      addCriterion("TIPTEL2 >", value, "tiptel2");
      return (Criteria) this;
    }

    public Criteria andTiptel2GreaterThanOrEqualTo(String value) {
      addCriterion("TIPTEL2 >=", value, "tiptel2");
      return (Criteria) this;
    }

    public Criteria andTiptel2LessThan(String value) {
      addCriterion("TIPTEL2 <", value, "tiptel2");
      return (Criteria) this;
    }

    public Criteria andTiptel2LessThanOrEqualTo(String value) {
      addCriterion("TIPTEL2 <=", value, "tiptel2");
      return (Criteria) this;
    }

    public Criteria andTiptel2In(List<String> values) {
      addCriterion("TIPTEL2 in", values, "tiptel2");
      return (Criteria) this;
    }

    public Criteria andTiptel2NotIn(List<String> values) {
      addCriterion("TIPTEL2 not in", values, "tiptel2");
      return (Criteria) this;
    }

    public Criteria andTiptel2Between(String value1, String value2) {
      addCriterion("TIPTEL2 between", value1, value2, "tiptel2");
      return (Criteria) this;
    }

    public Criteria andTiptel2NotBetween(String value1, String value2) {
      addCriterion("TIPTEL2 not between", value1, value2, "tiptel2");
      return (Criteria) this;
    }

    public Criteria andTiptel3IsNull() {
      addCriterion("TIPTEL3 is null");
      return (Criteria) this;
    }

    public Criteria andTiptel3IsNotNull() {
      addCriterion("TIPTEL3 is not null");
      return (Criteria) this;
    }

    public Criteria andTiptel3EqualTo(String value) {
      addCriterion("TIPTEL3 =", value, "tiptel3");
      return (Criteria) this;
    }

    public Criteria andTiptel3NotEqualTo(String value) {
      addCriterion("TIPTEL3 <>", value, "tiptel3");
      return (Criteria) this;
    }

    public Criteria andTiptel3GreaterThan(String value) {
      addCriterion("TIPTEL3 >", value, "tiptel3");
      return (Criteria) this;
    }

    public Criteria andTiptel3GreaterThanOrEqualTo(String value) {
      addCriterion("TIPTEL3 >=", value, "tiptel3");
      return (Criteria) this;
    }

    public Criteria andTiptel3LessThan(String value) {
      addCriterion("TIPTEL3 <", value, "tiptel3");
      return (Criteria) this;
    }

    public Criteria andTiptel3LessThanOrEqualTo(String value) {
      addCriterion("TIPTEL3 <=", value, "tiptel3");
      return (Criteria) this;
    }

    public Criteria andTiptel3In(List<String> values) {
      addCriterion("TIPTEL3 in", values, "tiptel3");
      return (Criteria) this;
    }

    public Criteria andTiptel3NotIn(List<String> values) {
      addCriterion("TIPTEL3 not in", values, "tiptel3");
      return (Criteria) this;
    }

    public Criteria andTiptel3Between(String value1, String value2) {
      addCriterion("TIPTEL3 between", value1, value2, "tiptel3");
      return (Criteria) this;
    }

    public Criteria andTiptel3NotBetween(String value1, String value2) {
      addCriterion("TIPTEL3 not between", value1, value2, "tiptel3");
      return (Criteria) this;
    }

    public Criteria andCodpostIsNull() {
      addCriterion("CODPOST is null");
      return (Criteria) this;
    }

    public Criteria andCodpostIsNotNull() {
      addCriterion("CODPOST is not null");
      return (Criteria) this;
    }

    public Criteria andCodpostEqualTo(String value) {
      addCriterion("CODPOST =", value, "codpost");
      return (Criteria) this;
    }

    public Criteria andCodpostNotEqualTo(String value) {
      addCriterion("CODPOST <>", value, "codpost");
      return (Criteria) this;
    }

    public Criteria andCodpostGreaterThan(String value) {
      addCriterion("CODPOST >", value, "codpost");
      return (Criteria) this;
    }

    public Criteria andCodpostGreaterThanOrEqualTo(String value) {
      addCriterion("CODPOST >=", value, "codpost");
      return (Criteria) this;
    }

    public Criteria andCodpostLessThan(String value) {
      addCriterion("CODPOST <", value, "codpost");
      return (Criteria) this;
    }

    public Criteria andCodpostLessThanOrEqualTo(String value) {
      addCriterion("CODPOST <=", value, "codpost");
      return (Criteria) this;
    }

    public Criteria andCodpostIn(List<String> values) {
      addCriterion("CODPOST in", values, "codpost");
      return (Criteria) this;
    }

    public Criteria andCodpostNotIn(List<String> values) {
      addCriterion("CODPOST not in", values, "codpost");
      return (Criteria) this;
    }

    public Criteria andCodpostBetween(String value1, String value2) {
      addCriterion("CODPOST between", value1, value2, "codpost");
      return (Criteria) this;
    }

    public Criteria andCodpostNotBetween(String value1, String value2) {
      addCriterion("CODPOST not between", value1, value2, "codpost");
      return (Criteria) this;
    }

    public Criteria andCodC01IsNull() {
      addCriterion("COD_C01 is null");
      return (Criteria) this;
    }

    public Criteria andCodC01IsNotNull() {
      addCriterion("COD_C01 is not null");
      return (Criteria) this;
    }

    public Criteria andCodC01EqualTo(String value) {
      addCriterion("COD_C01 =", value, "codC01");
      return (Criteria) this;
    }

    public Criteria andCodC01NotEqualTo(String value) {
      addCriterion("COD_C01 <>", value, "codC01");
      return (Criteria) this;
    }

    public Criteria andCodC01GreaterThan(String value) {
      addCriterion("COD_C01 >", value, "codC01");
      return (Criteria) this;
    }

    public Criteria andCodC01GreaterThanOrEqualTo(String value) {
      addCriterion("COD_C01 >=", value, "codC01");
      return (Criteria) this;
    }

    public Criteria andCodC01LessThan(String value) {
      addCriterion("COD_C01 <", value, "codC01");
      return (Criteria) this;
    }

    public Criteria andCodC01LessThanOrEqualTo(String value) {
      addCriterion("COD_C01 <=", value, "codC01");
      return (Criteria) this;
    }

    public Criteria andCodC01In(List<String> values) {
      addCriterion("COD_C01 in", values, "codC01");
      return (Criteria) this;
    }

    public Criteria andCodC01NotIn(List<String> values) {
      addCriterion("COD_C01 not in", values, "codC01");
      return (Criteria) this;
    }

    public Criteria andCodC01Between(String value1, String value2) {
      addCriterion("COD_C01 between", value1, value2, "codC01");
      return (Criteria) this;
    }

    public Criteria andCodC01NotBetween(String value1, String value2) {
      addCriterion("COD_C01 not between", value1, value2, "codC01");
      return (Criteria) this;
    }

    public Criteria andCodC02IsNull() {
      addCriterion("COD_C02 is null");
      return (Criteria) this;
    }

    public Criteria andCodC02IsNotNull() {
      addCriterion("COD_C02 is not null");
      return (Criteria) this;
    }

    public Criteria andCodC02EqualTo(String value) {
      addCriterion("COD_C02 =", value, "codC02");
      return (Criteria) this;
    }

    public Criteria andCodC02NotEqualTo(String value) {
      addCriterion("COD_C02 <>", value, "codC02");
      return (Criteria) this;
    }

    public Criteria andCodC02GreaterThan(String value) {
      addCriterion("COD_C02 >", value, "codC02");
      return (Criteria) this;
    }

    public Criteria andCodC02GreaterThanOrEqualTo(String value) {
      addCriterion("COD_C02 >=", value, "codC02");
      return (Criteria) this;
    }

    public Criteria andCodC02LessThan(String value) {
      addCriterion("COD_C02 <", value, "codC02");
      return (Criteria) this;
    }

    public Criteria andCodC02LessThanOrEqualTo(String value) {
      addCriterion("COD_C02 <=", value, "codC02");
      return (Criteria) this;
    }

    public Criteria andCodC02In(List<String> values) {
      addCriterion("COD_C02 in", values, "codC02");
      return (Criteria) this;
    }

    public Criteria andCodC02NotIn(List<String> values) {
      addCriterion("COD_C02 not in", values, "codC02");
      return (Criteria) this;
    }

    public Criteria andCodC02Between(String value1, String value2) {
      addCriterion("COD_C02 between", value1, value2, "codC02");
      return (Criteria) this;
    }

    public Criteria andCodC02NotBetween(String value1, String value2) {
      addCriterion("COD_C02 not between", value1, value2, "codC02");
      return (Criteria) this;
    }

    public Criteria andCodC03IsNull() {
      addCriterion("COD_C03 is null");
      return (Criteria) this;
    }

    public Criteria andCodC03IsNotNull() {
      addCriterion("COD_C03 is not null");
      return (Criteria) this;
    }

    public Criteria andCodC03EqualTo(String value) {
      addCriterion("COD_C03 =", value, "codC03");
      return (Criteria) this;
    }

    public Criteria andCodC03NotEqualTo(String value) {
      addCriterion("COD_C03 <>", value, "codC03");
      return (Criteria) this;
    }

    public Criteria andCodC03GreaterThan(String value) {
      addCriterion("COD_C03 >", value, "codC03");
      return (Criteria) this;
    }

    public Criteria andCodC03GreaterThanOrEqualTo(String value) {
      addCriterion("COD_C03 >=", value, "codC03");
      return (Criteria) this;
    }

    public Criteria andCodC03LessThan(String value) {
      addCriterion("COD_C03 <", value, "codC03");
      return (Criteria) this;
    }

    public Criteria andCodC03LessThanOrEqualTo(String value) {
      addCriterion("COD_C03 <=", value, "codC03");
      return (Criteria) this;
    }

    public Criteria andCodC03In(List<String> values) {
      addCriterion("COD_C03 in", values, "codC03");
      return (Criteria) this;
    }

    public Criteria andCodC03NotIn(List<String> values) {
      addCriterion("COD_C03 not in", values, "codC03");
      return (Criteria) this;
    }

    public Criteria andCodC03Between(String value1, String value2) {
      addCriterion("COD_C03 between", value1, value2, "codC03");
      return (Criteria) this;
    }

    public Criteria andCodC03NotBetween(String value1, String value2) {
      addCriterion("COD_C03 not between", value1, value2, "codC03");
      return (Criteria) this;
    }

    public Criteria andTelefo1IsNull() {
      addCriterion("TELEFO1 is null");
      return (Criteria) this;
    }

    public Criteria andTelefo1IsNotNull() {
      addCriterion("TELEFO1 is not null");
      return (Criteria) this;
    }

    public Criteria andTelefo1EqualTo(String value) {
      addCriterion("TELEFO1 =", value, "telefo1");
      return (Criteria) this;
    }

    public Criteria andTelefo1NotEqualTo(String value) {
      addCriterion("TELEFO1 <>", value, "telefo1");
      return (Criteria) this;
    }

    public Criteria andTelefo1GreaterThan(String value) {
      addCriterion("TELEFO1 >", value, "telefo1");
      return (Criteria) this;
    }

    public Criteria andTelefo1GreaterThanOrEqualTo(String value) {
      addCriterion("TELEFO1 >=", value, "telefo1");
      return (Criteria) this;
    }

    public Criteria andTelefo1LessThan(String value) {
      addCriterion("TELEFO1 <", value, "telefo1");
      return (Criteria) this;
    }

    public Criteria andTelefo1LessThanOrEqualTo(String value) {
      addCriterion("TELEFO1 <=", value, "telefo1");
      return (Criteria) this;
    }

    public Criteria andTelefo1In(List<String> values) {
      addCriterion("TELEFO1 in", values, "telefo1");
      return (Criteria) this;
    }

    public Criteria andTelefo1NotIn(List<String> values) {
      addCriterion("TELEFO1 not in", values, "telefo1");
      return (Criteria) this;
    }

    public Criteria andTelefo1Between(String value1, String value2) {
      addCriterion("TELEFO1 between", value1, value2, "telefo1");
      return (Criteria) this;
    }

    public Criteria andTelefo1NotBetween(String value1, String value2) {
      addCriterion("TELEFO1 not between", value1, value2, "telefo1");
      return (Criteria) this;
    }

    public Criteria andTelefo2IsNull() {
      addCriterion("TELEFO2 is null");
      return (Criteria) this;
    }

    public Criteria andTelefo2IsNotNull() {
      addCriterion("TELEFO2 is not null");
      return (Criteria) this;
    }

    public Criteria andTelefo2EqualTo(String value) {
      addCriterion("TELEFO2 =", value, "telefo2");
      return (Criteria) this;
    }

    public Criteria andTelefo2NotEqualTo(String value) {
      addCriterion("TELEFO2 <>", value, "telefo2");
      return (Criteria) this;
    }

    public Criteria andTelefo2GreaterThan(String value) {
      addCriterion("TELEFO2 >", value, "telefo2");
      return (Criteria) this;
    }

    public Criteria andTelefo2GreaterThanOrEqualTo(String value) {
      addCriterion("TELEFO2 >=", value, "telefo2");
      return (Criteria) this;
    }

    public Criteria andTelefo2LessThan(String value) {
      addCriterion("TELEFO2 <", value, "telefo2");
      return (Criteria) this;
    }

    public Criteria andTelefo2LessThanOrEqualTo(String value) {
      addCriterion("TELEFO2 <=", value, "telefo2");
      return (Criteria) this;
    }

    public Criteria andTelefo2In(List<String> values) {
      addCriterion("TELEFO2 in", values, "telefo2");
      return (Criteria) this;
    }

    public Criteria andTelefo2NotIn(List<String> values) {
      addCriterion("TELEFO2 not in", values, "telefo2");
      return (Criteria) this;
    }

    public Criteria andTelefo2Between(String value1, String value2) {
      addCriterion("TELEFO2 between", value1, value2, "telefo2");
      return (Criteria) this;
    }

    public Criteria andTelefo2NotBetween(String value1, String value2) {
      addCriterion("TELEFO2 not between", value1, value2, "telefo2");
      return (Criteria) this;
    }

    public Criteria andTelefo3IsNull() {
      addCriterion("TELEFO3 is null");
      return (Criteria) this;
    }

    public Criteria andTelefo3IsNotNull() {
      addCriterion("TELEFO3 is not null");
      return (Criteria) this;
    }

    public Criteria andTelefo3EqualTo(String value) {
      addCriterion("TELEFO3 =", value, "telefo3");
      return (Criteria) this;
    }

    public Criteria andTelefo3NotEqualTo(String value) {
      addCriterion("TELEFO3 <>", value, "telefo3");
      return (Criteria) this;
    }

    public Criteria andTelefo3GreaterThan(String value) {
      addCriterion("TELEFO3 >", value, "telefo3");
      return (Criteria) this;
    }

    public Criteria andTelefo3GreaterThanOrEqualTo(String value) {
      addCriterion("TELEFO3 >=", value, "telefo3");
      return (Criteria) this;
    }

    public Criteria andTelefo3LessThan(String value) {
      addCriterion("TELEFO3 <", value, "telefo3");
      return (Criteria) this;
    }

    public Criteria andTelefo3LessThanOrEqualTo(String value) {
      addCriterion("TELEFO3 <=", value, "telefo3");
      return (Criteria) this;
    }

    public Criteria andTelefo3In(List<String> values) {
      addCriterion("TELEFO3 in", values, "telefo3");
      return (Criteria) this;
    }

    public Criteria andTelefo3NotIn(List<String> values) {
      addCriterion("TELEFO3 not in", values, "telefo3");
      return (Criteria) this;
    }

    public Criteria andTelefo3Between(String value1, String value2) {
      addCriterion("TELEFO3 between", value1, value2, "telefo3");
      return (Criteria) this;
    }

    public Criteria andTelefo3NotBetween(String value1, String value2) {
      addCriterion("TELEFO3 not between", value1, value2, "telefo3");
      return (Criteria) this;
    }

    public Criteria andContratoAhorroIsNull() {
      addCriterion("CONTRATO_AHORRO is null");
      return (Criteria) this;
    }

    public Criteria andContratoAhorroIsNotNull() {
      addCriterion("CONTRATO_AHORRO is not null");
      return (Criteria) this;
    }

    public Criteria andContratoAhorroEqualTo(String value) {
      addCriterion("CONTRATO_AHORRO =", value, "contratoAhorro");
      return (Criteria) this;
    }

    public Criteria andContratoAhorroNotEqualTo(String value) {
      addCriterion("CONTRATO_AHORRO <>", value, "contratoAhorro");
      return (Criteria) this;
    }

    public Criteria andContratoAhorroGreaterThan(String value) {
      addCriterion("CONTRATO_AHORRO >", value, "contratoAhorro");
      return (Criteria) this;
    }

    public Criteria andContratoAhorroGreaterThanOrEqualTo(String value) {
      addCriterion("CONTRATO_AHORRO >=", value, "contratoAhorro");
      return (Criteria) this;
    }

    public Criteria andContratoAhorroLessThan(String value) {
      addCriterion("CONTRATO_AHORRO <", value, "contratoAhorro");
      return (Criteria) this;
    }

    public Criteria andContratoAhorroLessThanOrEqualTo(String value) {
      addCriterion("CONTRATO_AHORRO <=", value, "contratoAhorro");
      return (Criteria) this;
    }

    public Criteria andContratoAhorroIn(List<String> values) {
      addCriterion("CONTRATO_AHORRO in", values, "contratoAhorro");
      return (Criteria) this;
    }

    public Criteria andContratoAhorroNotIn(List<String> values) {
      addCriterion("CONTRATO_AHORRO not in", values, "contratoAhorro");
      return (Criteria) this;
    }

    public Criteria andContratoAhorroBetween(String value1, String value2) {
      addCriterion("CONTRATO_AHORRO between", value1, value2, "contratoAhorro");
      return (Criteria) this;
    }

    public Criteria andContratoAhorroNotBetween(String value1, String value2) {
      addCriterion("CONTRATO_AHORRO not between", value1, value2, "contratoAhorro");
      return (Criteria) this;
    }

    public Criteria andNTarjetaIsNull() {
      addCriterion("N_TARJETA is null");
      return (Criteria) this;
    }

    public Criteria andNTarjetaIsNotNull() {
      addCriterion("N_TARJETA is not null");
      return (Criteria) this;
    }

    public Criteria andNTarjetaEqualTo(String value) {
      addCriterion("N_TARJETA =", value, "nTarjeta");
      return (Criteria) this;
    }

    public Criteria andNTarjetaNotEqualTo(String value) {
      addCriterion("N_TARJETA <>", value, "nTarjeta");
      return (Criteria) this;
    }

    public Criteria andNTarjetaGreaterThan(String value) {
      addCriterion("N_TARJETA >", value, "nTarjeta");
      return (Criteria) this;
    }

    public Criteria andNTarjetaGreaterThanOrEqualTo(String value) {
      addCriterion("N_TARJETA >=", value, "nTarjeta");
      return (Criteria) this;
    }

    public Criteria andNTarjetaLessThan(String value) {
      addCriterion("N_TARJETA <", value, "nTarjeta");
      return (Criteria) this;
    }

    public Criteria andNTarjetaLessThanOrEqualTo(String value) {
      addCriterion("N_TARJETA <=", value, "nTarjeta");
      return (Criteria) this;
    }

    public Criteria andNTarjetaIn(List<String> values) {
      addCriterion("N_TARJETA in", values, "nTarjeta");
      return (Criteria) this;
    }

    public Criteria andNTarjetaNotIn(List<String> values) {
      addCriterion("N_TARJETA not in", values, "nTarjeta");
      return (Criteria) this;
    }

    public Criteria andNTarjetaBetween(String value1, String value2) {
      addCriterion("N_TARJETA between", value1, value2, "nTarjeta");
      return (Criteria) this;
    }

    public Criteria andNTarjetaNotBetween(String value1, String value2) {
      addCriterion("N_TARJETA not between", value1, value2, "nTarjeta");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoIsNull() {
      addCriterion("FECHA_VENCIMIENTO is null");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoIsNotNull() {
      addCriterion("FECHA_VENCIMIENTO is not null");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoEqualTo(Date value) {
      addCriterion("FECHA_VENCIMIENTO =", value, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoNotEqualTo(Date value) {
      addCriterion("FECHA_VENCIMIENTO <>", value, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoGreaterThan(Date value) {
      addCriterion("FECHA_VENCIMIENTO >", value, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoGreaterThanOrEqualTo(Date value) {
      addCriterion("FECHA_VENCIMIENTO >=", value, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoLessThan(Date value) {
      addCriterion("FECHA_VENCIMIENTO <", value, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoLessThanOrEqualTo(Date value) {
      addCriterion("FECHA_VENCIMIENTO <=", value, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoIn(List<Date> values) {
      addCriterion("FECHA_VENCIMIENTO in", values, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoNotIn(List<Date> values) {
      addCriterion("FECHA_VENCIMIENTO not in", values, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoBetween(Date value1, Date value2) {
      addCriterion("FECHA_VENCIMIENTO between", value1, value2, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoNotBetween(Date value1, Date value2) {
      addCriterion("FECHA_VENCIMIENTO not between", value1, value2, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andBinIsNull() {
      addCriterion("BIN is null");
      return (Criteria) this;
    }

    public Criteria andBinIsNotNull() {
      addCriterion("BIN is not null");
      return (Criteria) this;
    }

    public Criteria andBinEqualTo(String value) {
      addCriterion("BIN =", value, "bin");
      return (Criteria) this;
    }

    public Criteria andBinNotEqualTo(String value) {
      addCriterion("BIN <>", value, "bin");
      return (Criteria) this;
    }

    public Criteria andBinGreaterThan(String value) {
      addCriterion("BIN >", value, "bin");
      return (Criteria) this;
    }

    public Criteria andBinGreaterThanOrEqualTo(String value) {
      addCriterion("BIN >=", value, "bin");
      return (Criteria) this;
    }

    public Criteria andBinLessThan(String value) {
      addCriterion("BIN <", value, "bin");
      return (Criteria) this;
    }

    public Criteria andBinLessThanOrEqualTo(String value) {
      addCriterion("BIN <=", value, "bin");
      return (Criteria) this;
    }

    public Criteria andBinIn(List<String> values) {
      addCriterion("BIN in", values, "bin");
      return (Criteria) this;
    }

    public Criteria andBinNotIn(List<String> values) {
      addCriterion("BIN not in", values, "bin");
      return (Criteria) this;
    }

    public Criteria andBinBetween(String value1, String value2) {
      addCriterion("BIN between", value1, value2, "bin");
      return (Criteria) this;
    }

    public Criteria andBinNotBetween(String value1, String value2) {
      addCriterion("BIN not between", value1, value2, "bin");
      return (Criteria) this;
    }

    public Criteria andTarjetaIsNull() {
      addCriterion("TARJETA is null");
      return (Criteria) this;
    }

    public Criteria andTarjetaIsNotNull() {
      addCriterion("TARJETA is not null");
      return (Criteria) this;
    }

    public Criteria andTarjetaEqualTo(String value) {
      addCriterion("TARJETA =", value, "tarjeta");
      return (Criteria) this;
    }

    public Criteria andTarjetaNotEqualTo(String value) {
      addCriterion("TARJETA <>", value, "tarjeta");
      return (Criteria) this;
    }

    public Criteria andTarjetaGreaterThan(String value) {
      addCriterion("TARJETA >", value, "tarjeta");
      return (Criteria) this;
    }

    public Criteria andTarjetaGreaterThanOrEqualTo(String value) {
      addCriterion("TARJETA >=", value, "tarjeta");
      return (Criteria) this;
    }

    public Criteria andTarjetaLessThan(String value) {
      addCriterion("TARJETA <", value, "tarjeta");
      return (Criteria) this;
    }

    public Criteria andTarjetaLessThanOrEqualTo(String value) {
      addCriterion("TARJETA <=", value, "tarjeta");
      return (Criteria) this;
    }

    public Criteria andTarjetaIn(List<String> values) {
      addCriterion("TARJETA in", values, "tarjeta");
      return (Criteria) this;
    }

    public Criteria andTarjetaNotIn(List<String> values) {
      addCriterion("TARJETA not in", values, "tarjeta");
      return (Criteria) this;
    }

    public Criteria andTarjetaBetween(String value1, String value2) {
      addCriterion("TARJETA between", value1, value2, "tarjeta");
      return (Criteria) this;
    }

    public Criteria andTarjetaNotBetween(String value1, String value2) {
      addCriterion("TARJETA not between", value1, value2, "tarjeta");
      return (Criteria) this;
    }

    public Criteria andRscoreIsNull() {
      addCriterion("RSCORE is null");
      return (Criteria) this;
    }

    public Criteria andRscoreIsNotNull() {
      addCriterion("RSCORE is not null");
      return (Criteria) this;
    }

    public Criteria andRscoreEqualTo(String value) {
      addCriterion("RSCORE =", value, "rscore");
      return (Criteria) this;
    }

    public Criteria andRscoreNotEqualTo(String value) {
      addCriterion("RSCORE <>", value, "rscore");
      return (Criteria) this;
    }

    public Criteria andRscoreGreaterThan(String value) {
      addCriterion("RSCORE >", value, "rscore");
      return (Criteria) this;
    }

    public Criteria andRscoreGreaterThanOrEqualTo(String value) {
      addCriterion("RSCORE >=", value, "rscore");
      return (Criteria) this;
    }

    public Criteria andRscoreLessThan(String value) {
      addCriterion("RSCORE <", value, "rscore");
      return (Criteria) this;
    }

    public Criteria andRscoreLessThanOrEqualTo(String value) {
      addCriterion("RSCORE <=", value, "rscore");
      return (Criteria) this;
    }

    public Criteria andRscoreIn(List<String> values) {
      addCriterion("RSCORE in", values, "rscore");
      return (Criteria) this;
    }

    public Criteria andRscoreNotIn(List<String> values) {
      addCriterion("RSCORE not in", values, "rscore");
      return (Criteria) this;
    }

    public Criteria andRscoreBetween(String value1, String value2) {
      addCriterion("RSCORE between", value1, value2, "rscore");
      return (Criteria) this;
    }

    public Criteria andRscoreNotBetween(String value1, String value2) {
      addCriterion("RSCORE not between", value1, value2, "rscore");
      return (Criteria) this;
    }

    public Criteria andEstadoIsNull() {
      addCriterion("ESTADO is null");
      return (Criteria) this;
    }

    public Criteria andEstadoIsNotNull() {
      addCriterion("ESTADO is not null");
      return (Criteria) this;
    }

    public Criteria andEstadoEqualTo(String value) {
      addCriterion("ESTADO =", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoNotEqualTo(String value) {
      addCriterion("ESTADO <>", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoGreaterThan(String value) {
      addCriterion("ESTADO >", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoGreaterThanOrEqualTo(String value) {
      addCriterion("ESTADO >=", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoLessThan(String value) {
      addCriterion("ESTADO <", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoLessThanOrEqualTo(String value) {
      addCriterion("ESTADO <=", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoIn(List<String> values) {
      addCriterion("ESTADO in", values, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoNotIn(List<String> values) {
      addCriterion("ESTADO not in", values, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoBetween(String value1, String value2) {
      addCriterion("ESTADO between", value1, value2, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoNotBetween(String value1, String value2) {
      addCriterion("ESTADO not between", value1, value2, "estado");
      return (Criteria) this;
    }

    public Criteria andDesMensajeIsNull() {
      addCriterion("DES_MENSAJE is null");
      return (Criteria) this;
    }

    public Criteria andDesMensajeIsNotNull() {
      addCriterion("DES_MENSAJE is not null");
      return (Criteria) this;
    }

    public Criteria andDesMensajeEqualTo(String value) {
      addCriterion("DES_MENSAJE =", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeNotEqualTo(String value) {
      addCriterion("DES_MENSAJE <>", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeGreaterThan(String value) {
      addCriterion("DES_MENSAJE >", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeGreaterThanOrEqualTo(String value) {
      addCriterion("DES_MENSAJE >=", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeLessThan(String value) {
      addCriterion("DES_MENSAJE <", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeLessThanOrEqualTo(String value) {
      addCriterion("DES_MENSAJE <=", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeIn(List<String> values) {
      addCriterion("DES_MENSAJE in", values, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeNotIn(List<String> values) {
      addCriterion("DES_MENSAJE not in", values, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeBetween(String value1, String value2) {
      addCriterion("DES_MENSAJE between", value1, value2, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeNotBetween(String value1, String value2) {
      addCriterion("DES_MENSAJE not between", value1, value2, "desMensaje");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.TLMK_BASE_BC
   *
   * @mbggenerated do_not_delete_during_merge Thu Feb 06 17:15:58 COT 2014
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.TLMK_BASE_BC
   *
   * @mbggenerated Thu Feb 06 17:15:58 COT 2014
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}