package com.cardif.satelite.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TlmkBaseRPExample implements Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  public TlmkBaseRPExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andPkIsNull() {
      addCriterion("PK is null");
      return (Criteria) this;
    }

    public Criteria andPkIsNotNull() {
      addCriterion("PK is not null");
      return (Criteria) this;
    }

    public Criteria andPkEqualTo(Long value) {
      addCriterion("PK =", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotEqualTo(Long value) {
      addCriterion("PK <>", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThan(Long value) {
      addCriterion("PK >", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThanOrEqualTo(Long value) {
      addCriterion("PK >=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThan(Long value) {
      addCriterion("PK <", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThanOrEqualTo(Long value) {
      addCriterion("PK <=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkIn(List<Long> values) {
      addCriterion("PK in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotIn(List<Long> values) {
      addCriterion("PK not in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkBetween(Long value1, Long value2) {
      addCriterion("PK between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotBetween(Long value1, Long value2) {
      addCriterion("PK not between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andCodBaseIsNull() {
      addCriterion("COD_BASE is null");
      return (Criteria) this;
    }

    public Criteria andCodBaseIsNotNull() {
      addCriterion("COD_BASE is not null");
      return (Criteria) this;
    }

    public Criteria andCodBaseEqualTo(Long value) {
      addCriterion("COD_BASE =", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseNotEqualTo(Long value) {
      addCriterion("COD_BASE <>", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseGreaterThan(Long value) {
      addCriterion("COD_BASE >", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseGreaterThanOrEqualTo(Long value) {
      addCriterion("COD_BASE >=", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseLessThan(Long value) {
      addCriterion("COD_BASE <", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseLessThanOrEqualTo(Long value) {
      addCriterion("COD_BASE <=", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseIn(List<Long> values) {
      addCriterion("COD_BASE in", values, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseNotIn(List<Long> values) {
      addCriterion("COD_BASE not in", values, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseBetween(Long value1, Long value2) {
      addCriterion("COD_BASE between", value1, value2, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseNotBetween(Long value1, Long value2) {
      addCriterion("COD_BASE not between", value1, value2, "codBase");
      return (Criteria) this;
    }

    public Criteria andSecuenciaTlmkIsNull() {
      addCriterion("SECUENCIA_TLMK is null");
      return (Criteria) this;
    }

    public Criteria andSecuenciaTlmkIsNotNull() {
      addCriterion("SECUENCIA_TLMK is not null");
      return (Criteria) this;
    }

    public Criteria andSecuenciaTlmkEqualTo(String value) {
      addCriterion("SECUENCIA_TLMK =", value, "secuenciaTlmk");
      return (Criteria) this;
    }

    public Criteria andSecuenciaTlmkNotEqualTo(String value) {
      addCriterion("SECUENCIA_TLMK <>", value, "secuenciaTlmk");
      return (Criteria) this;
    }

    public Criteria andSecuenciaTlmkGreaterThan(String value) {
      addCriterion("SECUENCIA_TLMK >", value, "secuenciaTlmk");
      return (Criteria) this;
    }

    public Criteria andSecuenciaTlmkGreaterThanOrEqualTo(String value) {
      addCriterion("SECUENCIA_TLMK >=", value, "secuenciaTlmk");
      return (Criteria) this;
    }

    public Criteria andSecuenciaTlmkLessThan(String value) {
      addCriterion("SECUENCIA_TLMK <", value, "secuenciaTlmk");
      return (Criteria) this;
    }

    public Criteria andSecuenciaTlmkLessThanOrEqualTo(String value) {
      addCriterion("SECUENCIA_TLMK <=", value, "secuenciaTlmk");
      return (Criteria) this;
    }

    public Criteria andSecuenciaTlmkIn(List<String> values) {
      addCriterion("SECUENCIA_TLMK in", values, "secuenciaTlmk");
      return (Criteria) this;
    }

    public Criteria andSecuenciaTlmkNotIn(List<String> values) {
      addCriterion("SECUENCIA_TLMK not in", values, "secuenciaTlmk");
      return (Criteria) this;
    }

    public Criteria andSecuenciaTlmkBetween(String value1, String value2) {
      addCriterion("SECUENCIA_TLMK between", value1, value2, "secuenciaTlmk");
      return (Criteria) this;
    }

    public Criteria andSecuenciaTlmkNotBetween(String value1, String value2) {
      addCriterion("SECUENCIA_TLMK not between", value1, value2, "secuenciaTlmk");
      return (Criteria) this;
    }

    public Criteria andTargetIsNull() {
      addCriterion("TARGET is null");
      return (Criteria) this;
    }

    public Criteria andTargetIsNotNull() {
      addCriterion("TARGET is not null");
      return (Criteria) this;
    }

    public Criteria andTargetEqualTo(String value) {
      addCriterion("TARGET =", value, "target");
      return (Criteria) this;
    }

    public Criteria andTargetNotEqualTo(String value) {
      addCriterion("TARGET <>", value, "target");
      return (Criteria) this;
    }

    public Criteria andTargetGreaterThan(String value) {
      addCriterion("TARGET >", value, "target");
      return (Criteria) this;
    }

    public Criteria andTargetGreaterThanOrEqualTo(String value) {
      addCriterion("TARGET >=", value, "target");
      return (Criteria) this;
    }

    public Criteria andTargetLessThan(String value) {
      addCriterion("TARGET <", value, "target");
      return (Criteria) this;
    }

    public Criteria andTargetLessThanOrEqualTo(String value) {
      addCriterion("TARGET <=", value, "target");
      return (Criteria) this;
    }

    public Criteria andTargetIn(List<String> values) {
      addCriterion("TARGET in", values, "target");
      return (Criteria) this;
    }

    public Criteria andTargetNotIn(List<String> values) {
      addCriterion("TARGET not in", values, "target");
      return (Criteria) this;
    }

    public Criteria andTargetBetween(String value1, String value2) {
      addCriterion("TARGET between", value1, value2, "target");
      return (Criteria) this;
    }

    public Criteria andTargetNotBetween(String value1, String value2) {
      addCriterion("TARGET not between", value1, value2, "target");
      return (Criteria) this;
    }

    public Criteria andFueMaxIsNull() {
      addCriterion("FUE_MAX is null");
      return (Criteria) this;
    }

    public Criteria andFueMaxIsNotNull() {
      addCriterion("FUE_MAX is not null");
      return (Criteria) this;
    }

    public Criteria andFueMaxEqualTo(String value) {
      addCriterion("FUE_MAX =", value, "fueMax");
      return (Criteria) this;
    }

    public Criteria andFueMaxNotEqualTo(String value) {
      addCriterion("FUE_MAX <>", value, "fueMax");
      return (Criteria) this;
    }

    public Criteria andFueMaxGreaterThan(String value) {
      addCriterion("FUE_MAX >", value, "fueMax");
      return (Criteria) this;
    }

    public Criteria andFueMaxGreaterThanOrEqualTo(String value) {
      addCriterion("FUE_MAX >=", value, "fueMax");
      return (Criteria) this;
    }

    public Criteria andFueMaxLessThan(String value) {
      addCriterion("FUE_MAX <", value, "fueMax");
      return (Criteria) this;
    }

    public Criteria andFueMaxLessThanOrEqualTo(String value) {
      addCriterion("FUE_MAX <=", value, "fueMax");
      return (Criteria) this;
    }

    public Criteria andFueMaxIn(List<String> values) {
      addCriterion("FUE_MAX in", values, "fueMax");
      return (Criteria) this;
    }

    public Criteria andFueMaxNotIn(List<String> values) {
      addCriterion("FUE_MAX not in", values, "fueMax");
      return (Criteria) this;
    }

    public Criteria andFueMaxBetween(String value1, String value2) {
      addCriterion("FUE_MAX between", value1, value2, "fueMax");
      return (Criteria) this;
    }

    public Criteria andFueMaxNotBetween(String value1, String value2) {
      addCriterion("FUE_MAX not between", value1, value2, "fueMax");
      return (Criteria) this;
    }

    public Criteria andMarca1IsNull() {
      addCriterion("MARCA1 is null");
      return (Criteria) this;
    }

    public Criteria andMarca1IsNotNull() {
      addCriterion("MARCA1 is not null");
      return (Criteria) this;
    }

    public Criteria andMarca1EqualTo(String value) {
      addCriterion("MARCA1 =", value, "marca1");
      return (Criteria) this;
    }

    public Criteria andMarca1NotEqualTo(String value) {
      addCriterion("MARCA1 <>", value, "marca1");
      return (Criteria) this;
    }

    public Criteria andMarca1GreaterThan(String value) {
      addCriterion("MARCA1 >", value, "marca1");
      return (Criteria) this;
    }

    public Criteria andMarca1GreaterThanOrEqualTo(String value) {
      addCriterion("MARCA1 >=", value, "marca1");
      return (Criteria) this;
    }

    public Criteria andMarca1LessThan(String value) {
      addCriterion("MARCA1 <", value, "marca1");
      return (Criteria) this;
    }

    public Criteria andMarca1LessThanOrEqualTo(String value) {
      addCriterion("MARCA1 <=", value, "marca1");
      return (Criteria) this;
    }

    public Criteria andMarca1In(List<String> values) {
      addCriterion("MARCA1 in", values, "marca1");
      return (Criteria) this;
    }

    public Criteria andMarca1NotIn(List<String> values) {
      addCriterion("MARCA1 not in", values, "marca1");
      return (Criteria) this;
    }

    public Criteria andMarca1Between(String value1, String value2) {
      addCriterion("MARCA1 between", value1, value2, "marca1");
      return (Criteria) this;
    }

    public Criteria andMarca1NotBetween(String value1, String value2) {
      addCriterion("MARCA1 not between", value1, value2, "marca1");
      return (Criteria) this;
    }

    public Criteria andDocideEnlIsNull() {
      addCriterion("DOCIDE_ENL is null");
      return (Criteria) this;
    }

    public Criteria andDocideEnlIsNotNull() {
      addCriterion("DOCIDE_ENL is not null");
      return (Criteria) this;
    }

    public Criteria andDocideEnlEqualTo(String value) {
      addCriterion("DOCIDE_ENL =", value, "docideEnl");
      return (Criteria) this;
    }

    public Criteria andDocideEnlNotEqualTo(String value) {
      addCriterion("DOCIDE_ENL <>", value, "docideEnl");
      return (Criteria) this;
    }

    public Criteria andDocideEnlGreaterThan(String value) {
      addCriterion("DOCIDE_ENL >", value, "docideEnl");
      return (Criteria) this;
    }

    public Criteria andDocideEnlGreaterThanOrEqualTo(String value) {
      addCriterion("DOCIDE_ENL >=", value, "docideEnl");
      return (Criteria) this;
    }

    public Criteria andDocideEnlLessThan(String value) {
      addCriterion("DOCIDE_ENL <", value, "docideEnl");
      return (Criteria) this;
    }

    public Criteria andDocideEnlLessThanOrEqualTo(String value) {
      addCriterion("DOCIDE_ENL <=", value, "docideEnl");
      return (Criteria) this;
    }

    public Criteria andDocideEnlIn(List<String> values) {
      addCriterion("DOCIDE_ENL in", values, "docideEnl");
      return (Criteria) this;
    }

    public Criteria andDocideEnlNotIn(List<String> values) {
      addCriterion("DOCIDE_ENL not in", values, "docideEnl");
      return (Criteria) this;
    }

    public Criteria andDocideEnlBetween(String value1, String value2) {
      addCriterion("DOCIDE_ENL between", value1, value2, "docideEnl");
      return (Criteria) this;
    }

    public Criteria andDocideEnlNotBetween(String value1, String value2) {
      addCriterion("DOCIDE_ENL not between", value1, value2, "docideEnl");
      return (Criteria) this;
    }

    public Criteria andTipdocIsNull() {
      addCriterion("TIPDOC is null");
      return (Criteria) this;
    }

    public Criteria andTipdocIsNotNull() {
      addCriterion("TIPDOC is not null");
      return (Criteria) this;
    }

    public Criteria andTipdocEqualTo(String value) {
      addCriterion("TIPDOC =", value, "tipdoc");
      return (Criteria) this;
    }

    public Criteria andTipdocNotEqualTo(String value) {
      addCriterion("TIPDOC <>", value, "tipdoc");
      return (Criteria) this;
    }

    public Criteria andTipdocGreaterThan(String value) {
      addCriterion("TIPDOC >", value, "tipdoc");
      return (Criteria) this;
    }

    public Criteria andTipdocGreaterThanOrEqualTo(String value) {
      addCriterion("TIPDOC >=", value, "tipdoc");
      return (Criteria) this;
    }

    public Criteria andTipdocLessThan(String value) {
      addCriterion("TIPDOC <", value, "tipdoc");
      return (Criteria) this;
    }

    public Criteria andTipdocLessThanOrEqualTo(String value) {
      addCriterion("TIPDOC <=", value, "tipdoc");
      return (Criteria) this;
    }

    public Criteria andTipdocIn(List<String> values) {
      addCriterion("TIPDOC in", values, "tipdoc");
      return (Criteria) this;
    }

    public Criteria andTipdocNotIn(List<String> values) {
      addCriterion("TIPDOC not in", values, "tipdoc");
      return (Criteria) this;
    }

    public Criteria andTipdocBetween(String value1, String value2) {
      addCriterion("TIPDOC between", value1, value2, "tipdoc");
      return (Criteria) this;
    }

    public Criteria andTipdocNotBetween(String value1, String value2) {
      addCriterion("TIPDOC not between", value1, value2, "tipdoc");
      return (Criteria) this;
    }

    public Criteria andTipTarjetaIsNull() {
      addCriterion("TIP_TARJETA is null");
      return (Criteria) this;
    }

    public Criteria andTipTarjetaIsNotNull() {
      addCriterion("TIP_TARJETA is not null");
      return (Criteria) this;
    }

    public Criteria andTipTarjetaEqualTo(String value) {
      addCriterion("TIP_TARJETA =", value, "tipTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipTarjetaNotEqualTo(String value) {
      addCriterion("TIP_TARJETA <>", value, "tipTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipTarjetaGreaterThan(String value) {
      addCriterion("TIP_TARJETA >", value, "tipTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipTarjetaGreaterThanOrEqualTo(String value) {
      addCriterion("TIP_TARJETA >=", value, "tipTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipTarjetaLessThan(String value) {
      addCriterion("TIP_TARJETA <", value, "tipTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipTarjetaLessThanOrEqualTo(String value) {
      addCriterion("TIP_TARJETA <=", value, "tipTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipTarjetaIn(List<String> values) {
      addCriterion("TIP_TARJETA in", values, "tipTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipTarjetaNotIn(List<String> values) {
      addCriterion("TIP_TARJETA not in", values, "tipTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipTarjetaBetween(String value1, String value2) {
      addCriterion("TIP_TARJETA between", value1, value2, "tipTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipTarjetaNotBetween(String value1, String value2) {
      addCriterion("TIP_TARJETA not between", value1, value2, "tipTarjeta");
      return (Criteria) this;
    }

    public Criteria andRangoUtilizacionIsNull() {
      addCriterion("RANGO_UTILIZACION is null");
      return (Criteria) this;
    }

    public Criteria andRangoUtilizacionIsNotNull() {
      addCriterion("RANGO_UTILIZACION is not null");
      return (Criteria) this;
    }

    public Criteria andRangoUtilizacionEqualTo(String value) {
      addCriterion("RANGO_UTILIZACION =", value, "rangoUtilizacion");
      return (Criteria) this;
    }

    public Criteria andRangoUtilizacionNotEqualTo(String value) {
      addCriterion("RANGO_UTILIZACION <>", value, "rangoUtilizacion");
      return (Criteria) this;
    }

    public Criteria andRangoUtilizacionGreaterThan(String value) {
      addCriterion("RANGO_UTILIZACION >", value, "rangoUtilizacion");
      return (Criteria) this;
    }

    public Criteria andRangoUtilizacionGreaterThanOrEqualTo(String value) {
      addCriterion("RANGO_UTILIZACION >=", value, "rangoUtilizacion");
      return (Criteria) this;
    }

    public Criteria andRangoUtilizacionLessThan(String value) {
      addCriterion("RANGO_UTILIZACION <", value, "rangoUtilizacion");
      return (Criteria) this;
    }

    public Criteria andRangoUtilizacionLessThanOrEqualTo(String value) {
      addCriterion("RANGO_UTILIZACION <=", value, "rangoUtilizacion");
      return (Criteria) this;
    }

    public Criteria andRangoUtilizacionIn(List<String> values) {
      addCriterion("RANGO_UTILIZACION in", values, "rangoUtilizacion");
      return (Criteria) this;
    }

    public Criteria andRangoUtilizacionNotIn(List<String> values) {
      addCriterion("RANGO_UTILIZACION not in", values, "rangoUtilizacion");
      return (Criteria) this;
    }

    public Criteria andRangoUtilizacionBetween(String value1, String value2) {
      addCriterion("RANGO_UTILIZACION between", value1, value2, "rangoUtilizacion");
      return (Criteria) this;
    }

    public Criteria andRangoUtilizacionNotBetween(String value1, String value2) {
      addCriterion("RANGO_UTILIZACION not between", value1, value2, "rangoUtilizacion");
      return (Criteria) this;
    }

    public Criteria andRangoLineaRipleyIsNull() {
      addCriterion("RANGO_LINEA_RIPLEY is null");
      return (Criteria) this;
    }

    public Criteria andRangoLineaRipleyIsNotNull() {
      addCriterion("RANGO_LINEA_RIPLEY is not null");
      return (Criteria) this;
    }

    public Criteria andRangoLineaRipleyEqualTo(String value) {
      addCriterion("RANGO_LINEA_RIPLEY =", value, "rangoLineaRipley");
      return (Criteria) this;
    }

    public Criteria andRangoLineaRipleyNotEqualTo(String value) {
      addCriterion("RANGO_LINEA_RIPLEY <>", value, "rangoLineaRipley");
      return (Criteria) this;
    }

    public Criteria andRangoLineaRipleyGreaterThan(String value) {
      addCriterion("RANGO_LINEA_RIPLEY >", value, "rangoLineaRipley");
      return (Criteria) this;
    }

    public Criteria andRangoLineaRipleyGreaterThanOrEqualTo(String value) {
      addCriterion("RANGO_LINEA_RIPLEY >=", value, "rangoLineaRipley");
      return (Criteria) this;
    }

    public Criteria andRangoLineaRipleyLessThan(String value) {
      addCriterion("RANGO_LINEA_RIPLEY <", value, "rangoLineaRipley");
      return (Criteria) this;
    }

    public Criteria andRangoLineaRipleyLessThanOrEqualTo(String value) {
      addCriterion("RANGO_LINEA_RIPLEY <=", value, "rangoLineaRipley");
      return (Criteria) this;
    }

    public Criteria andRangoLineaRipleyIn(List<String> values) {
      addCriterion("RANGO_LINEA_RIPLEY in", values, "rangoLineaRipley");
      return (Criteria) this;
    }

    public Criteria andRangoLineaRipleyNotIn(List<String> values) {
      addCriterion("RANGO_LINEA_RIPLEY not in", values, "rangoLineaRipley");
      return (Criteria) this;
    }

    public Criteria andRangoLineaRipleyBetween(String value1, String value2) {
      addCriterion("RANGO_LINEA_RIPLEY between", value1, value2, "rangoLineaRipley");
      return (Criteria) this;
    }

    public Criteria andRangoLineaRipleyNotBetween(String value1, String value2) {
      addCriterion("RANGO_LINEA_RIPLEY not between", value1, value2, "rangoLineaRipley");
      return (Criteria) this;
    }

    public Criteria andRangoSaldosRipleyIsNull() {
      addCriterion("RANGO_SALDOS_RIPLEY is null");
      return (Criteria) this;
    }

    public Criteria andRangoSaldosRipleyIsNotNull() {
      addCriterion("RANGO_SALDOS_RIPLEY is not null");
      return (Criteria) this;
    }

    public Criteria andRangoSaldosRipleyEqualTo(String value) {
      addCriterion("RANGO_SALDOS_RIPLEY =", value, "rangoSaldosRipley");
      return (Criteria) this;
    }

    public Criteria andRangoSaldosRipleyNotEqualTo(String value) {
      addCriterion("RANGO_SALDOS_RIPLEY <>", value, "rangoSaldosRipley");
      return (Criteria) this;
    }

    public Criteria andRangoSaldosRipleyGreaterThan(String value) {
      addCriterion("RANGO_SALDOS_RIPLEY >", value, "rangoSaldosRipley");
      return (Criteria) this;
    }

    public Criteria andRangoSaldosRipleyGreaterThanOrEqualTo(String value) {
      addCriterion("RANGO_SALDOS_RIPLEY >=", value, "rangoSaldosRipley");
      return (Criteria) this;
    }

    public Criteria andRangoSaldosRipleyLessThan(String value) {
      addCriterion("RANGO_SALDOS_RIPLEY <", value, "rangoSaldosRipley");
      return (Criteria) this;
    }

    public Criteria andRangoSaldosRipleyLessThanOrEqualTo(String value) {
      addCriterion("RANGO_SALDOS_RIPLEY <=", value, "rangoSaldosRipley");
      return (Criteria) this;
    }

    public Criteria andRangoSaldosRipleyIn(List<String> values) {
      addCriterion("RANGO_SALDOS_RIPLEY in", values, "rangoSaldosRipley");
      return (Criteria) this;
    }

    public Criteria andRangoSaldosRipleyNotIn(List<String> values) {
      addCriterion("RANGO_SALDOS_RIPLEY not in", values, "rangoSaldosRipley");
      return (Criteria) this;
    }

    public Criteria andRangoSaldosRipleyBetween(String value1, String value2) {
      addCriterion("RANGO_SALDOS_RIPLEY between", value1, value2, "rangoSaldosRipley");
      return (Criteria) this;
    }

    public Criteria andRangoSaldosRipleyNotBetween(String value1, String value2) {
      addCriterion("RANGO_SALDOS_RIPLEY not between", value1, value2, "rangoSaldosRipley");
      return (Criteria) this;
    }

    public Criteria andRangoAntiguedadIsNull() {
      addCriterion("RANGO_ANTIGUEDAD is null");
      return (Criteria) this;
    }

    public Criteria andRangoAntiguedadIsNotNull() {
      addCriterion("RANGO_ANTIGUEDAD is not null");
      return (Criteria) this;
    }

    public Criteria andRangoAntiguedadEqualTo(String value) {
      addCriterion("RANGO_ANTIGUEDAD =", value, "rangoAntiguedad");
      return (Criteria) this;
    }

    public Criteria andRangoAntiguedadNotEqualTo(String value) {
      addCriterion("RANGO_ANTIGUEDAD <>", value, "rangoAntiguedad");
      return (Criteria) this;
    }

    public Criteria andRangoAntiguedadGreaterThan(String value) {
      addCriterion("RANGO_ANTIGUEDAD >", value, "rangoAntiguedad");
      return (Criteria) this;
    }

    public Criteria andRangoAntiguedadGreaterThanOrEqualTo(String value) {
      addCriterion("RANGO_ANTIGUEDAD >=", value, "rangoAntiguedad");
      return (Criteria) this;
    }

    public Criteria andRangoAntiguedadLessThan(String value) {
      addCriterion("RANGO_ANTIGUEDAD <", value, "rangoAntiguedad");
      return (Criteria) this;
    }

    public Criteria andRangoAntiguedadLessThanOrEqualTo(String value) {
      addCriterion("RANGO_ANTIGUEDAD <=", value, "rangoAntiguedad");
      return (Criteria) this;
    }

    public Criteria andRangoAntiguedadIn(List<String> values) {
      addCriterion("RANGO_ANTIGUEDAD in", values, "rangoAntiguedad");
      return (Criteria) this;
    }

    public Criteria andRangoAntiguedadNotIn(List<String> values) {
      addCriterion("RANGO_ANTIGUEDAD not in", values, "rangoAntiguedad");
      return (Criteria) this;
    }

    public Criteria andRangoAntiguedadBetween(String value1, String value2) {
      addCriterion("RANGO_ANTIGUEDAD between", value1, value2, "rangoAntiguedad");
      return (Criteria) this;
    }

    public Criteria andRangoAntiguedadNotBetween(String value1, String value2) {
      addCriterion("RANGO_ANTIGUEDAD not between", value1, value2, "rangoAntiguedad");
      return (Criteria) this;
    }

    public Criteria andRecenciaToIsNull() {
      addCriterion("RECENCIA_TO is null");
      return (Criteria) this;
    }

    public Criteria andRecenciaToIsNotNull() {
      addCriterion("RECENCIA_TO is not null");
      return (Criteria) this;
    }

    public Criteria andRecenciaToEqualTo(String value) {
      addCriterion("RECENCIA_TO =", value, "recenciaTo");
      return (Criteria) this;
    }

    public Criteria andRecenciaToNotEqualTo(String value) {
      addCriterion("RECENCIA_TO <>", value, "recenciaTo");
      return (Criteria) this;
    }

    public Criteria andRecenciaToGreaterThan(String value) {
      addCriterion("RECENCIA_TO >", value, "recenciaTo");
      return (Criteria) this;
    }

    public Criteria andRecenciaToGreaterThanOrEqualTo(String value) {
      addCriterion("RECENCIA_TO >=", value, "recenciaTo");
      return (Criteria) this;
    }

    public Criteria andRecenciaToLessThan(String value) {
      addCriterion("RECENCIA_TO <", value, "recenciaTo");
      return (Criteria) this;
    }

    public Criteria andRecenciaToLessThanOrEqualTo(String value) {
      addCriterion("RECENCIA_TO <=", value, "recenciaTo");
      return (Criteria) this;
    }

    public Criteria andRecenciaToIn(List<String> values) {
      addCriterion("RECENCIA_TO in", values, "recenciaTo");
      return (Criteria) this;
    }

    public Criteria andRecenciaToNotIn(List<String> values) {
      addCriterion("RECENCIA_TO not in", values, "recenciaTo");
      return (Criteria) this;
    }

    public Criteria andRecenciaToBetween(String value1, String value2) {
      addCriterion("RECENCIA_TO between", value1, value2, "recenciaTo");
      return (Criteria) this;
    }

    public Criteria andRecenciaToNotBetween(String value1, String value2) {
      addCriterion("RECENCIA_TO not between", value1, value2, "recenciaTo");
      return (Criteria) this;
    }

    public Criteria andFechaActIsNull() {
      addCriterion("FECHA_ACT is null");
      return (Criteria) this;
    }

    public Criteria andFechaActIsNotNull() {
      addCriterion("FECHA_ACT is not null");
      return (Criteria) this;
    }

    public Criteria andFechaActEqualTo(Date value) {
      addCriterion("FECHA_ACT =", value, "fechaAct");
      return (Criteria) this;
    }

    public Criteria andFechaActNotEqualTo(Date value) {
      addCriterion("FECHA_ACT <>", value, "fechaAct");
      return (Criteria) this;
    }

    public Criteria andFechaActGreaterThan(Date value) {
      addCriterion("FECHA_ACT >", value, "fechaAct");
      return (Criteria) this;
    }

    public Criteria andFechaActGreaterThanOrEqualTo(Date value) {
      addCriterion("FECHA_ACT >=", value, "fechaAct");
      return (Criteria) this;
    }

    public Criteria andFechaActLessThan(Date value) {
      addCriterion("FECHA_ACT <", value, "fechaAct");
      return (Criteria) this;
    }

    public Criteria andFechaActLessThanOrEqualTo(Date value) {
      addCriterion("FECHA_ACT <=", value, "fechaAct");
      return (Criteria) this;
    }

    public Criteria andFechaActIn(List<Date> values) {
      addCriterion("FECHA_ACT in", values, "fechaAct");
      return (Criteria) this;
    }

    public Criteria andFechaActNotIn(List<Date> values) {
      addCriterion("FECHA_ACT not in", values, "fechaAct");
      return (Criteria) this;
    }

    public Criteria andFechaActBetween(Date value1, Date value2) {
      addCriterion("FECHA_ACT between", value1, value2, "fechaAct");
      return (Criteria) this;
    }

    public Criteria andFechaActNotBetween(Date value1, Date value2) {
      addCriterion("FECHA_ACT not between", value1, value2, "fechaAct");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoIsNull() {
      addCriterion("FECHA_VENCIMIENTO is null");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoIsNotNull() {
      addCriterion("FECHA_VENCIMIENTO is not null");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoEqualTo(Date value) {
      addCriterion("FECHA_VENCIMIENTO =", value, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoNotEqualTo(Date value) {
      addCriterion("FECHA_VENCIMIENTO <>", value, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoGreaterThan(Date value) {
      addCriterion("FECHA_VENCIMIENTO >", value, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoGreaterThanOrEqualTo(Date value) {
      addCriterion("FECHA_VENCIMIENTO >=", value, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoLessThan(Date value) {
      addCriterion("FECHA_VENCIMIENTO <", value, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoLessThanOrEqualTo(Date value) {
      addCriterion("FECHA_VENCIMIENTO <=", value, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoIn(List<Date> values) {
      addCriterion("FECHA_VENCIMIENTO in", values, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoNotIn(List<Date> values) {
      addCriterion("FECHA_VENCIMIENTO not in", values, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoBetween(Date value1, Date value2) {
      addCriterion("FECHA_VENCIMIENTO between", value1, value2, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoNotBetween(Date value1, Date value2) {
      addCriterion("FECHA_VENCIMIENTO not between", value1, value2, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaEmbozadoIsNull() {
      addCriterion("FECHA_EMBOZADO is null");
      return (Criteria) this;
    }

    public Criteria andFechaEmbozadoIsNotNull() {
      addCriterion("FECHA_EMBOZADO is not null");
      return (Criteria) this;
    }

    public Criteria andFechaEmbozadoEqualTo(Date value) {
      addCriterion("FECHA_EMBOZADO =", value, "fechaEmbozado");
      return (Criteria) this;
    }

    public Criteria andFechaEmbozadoNotEqualTo(Date value) {
      addCriterion("FECHA_EMBOZADO <>", value, "fechaEmbozado");
      return (Criteria) this;
    }

    public Criteria andFechaEmbozadoGreaterThan(Date value) {
      addCriterion("FECHA_EMBOZADO >", value, "fechaEmbozado");
      return (Criteria) this;
    }

    public Criteria andFechaEmbozadoGreaterThanOrEqualTo(Date value) {
      addCriterion("FECHA_EMBOZADO >=", value, "fechaEmbozado");
      return (Criteria) this;
    }

    public Criteria andFechaEmbozadoLessThan(Date value) {
      addCriterion("FECHA_EMBOZADO <", value, "fechaEmbozado");
      return (Criteria) this;
    }

    public Criteria andFechaEmbozadoLessThanOrEqualTo(Date value) {
      addCriterion("FECHA_EMBOZADO <=", value, "fechaEmbozado");
      return (Criteria) this;
    }

    public Criteria andFechaEmbozadoIn(List<Date> values) {
      addCriterion("FECHA_EMBOZADO in", values, "fechaEmbozado");
      return (Criteria) this;
    }

    public Criteria andFechaEmbozadoNotIn(List<Date> values) {
      addCriterion("FECHA_EMBOZADO not in", values, "fechaEmbozado");
      return (Criteria) this;
    }

    public Criteria andFechaEmbozadoBetween(Date value1, Date value2) {
      addCriterion("FECHA_EMBOZADO between", value1, value2, "fechaEmbozado");
      return (Criteria) this;
    }

    public Criteria andFechaEmbozadoNotBetween(Date value1, Date value2) {
      addCriterion("FECHA_EMBOZADO not between", value1, value2, "fechaEmbozado");
      return (Criteria) this;
    }

    public Criteria andSexoIsNull() {
      addCriterion("SEXO is null");
      return (Criteria) this;
    }

    public Criteria andSexoIsNotNull() {
      addCriterion("SEXO is not null");
      return (Criteria) this;
    }

    public Criteria andSexoEqualTo(String value) {
      addCriterion("SEXO =", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoNotEqualTo(String value) {
      addCriterion("SEXO <>", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoGreaterThan(String value) {
      addCriterion("SEXO >", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoGreaterThanOrEqualTo(String value) {
      addCriterion("SEXO >=", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoLessThan(String value) {
      addCriterion("SEXO <", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoLessThanOrEqualTo(String value) {
      addCriterion("SEXO <=", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoIn(List<String> values) {
      addCriterion("SEXO in", values, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoNotIn(List<String> values) {
      addCriterion("SEXO not in", values, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoBetween(String value1, String value2) {
      addCriterion("SEXO between", value1, value2, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoNotBetween(String value1, String value2) {
      addCriterion("SEXO not between", value1, value2, "sexo");
      return (Criteria) this;
    }

    public Criteria andEdadIsNull() {
      addCriterion("EDAD is null");
      return (Criteria) this;
    }

    public Criteria andEdadIsNotNull() {
      addCriterion("EDAD is not null");
      return (Criteria) this;
    }

    public Criteria andEdadEqualTo(String value) {
      addCriterion("EDAD =", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadNotEqualTo(String value) {
      addCriterion("EDAD <>", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadGreaterThan(String value) {
      addCriterion("EDAD >", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadGreaterThanOrEqualTo(String value) {
      addCriterion("EDAD >=", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadLessThan(String value) {
      addCriterion("EDAD <", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadLessThanOrEqualTo(String value) {
      addCriterion("EDAD <=", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadIn(List<String> values) {
      addCriterion("EDAD in", values, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadNotIn(List<String> values) {
      addCriterion("EDAD not in", values, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadBetween(String value1, String value2) {
      addCriterion("EDAD between", value1, value2, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadNotBetween(String value1, String value2) {
      addCriterion("EDAD not between", value1, value2, "edad");
      return (Criteria) this;
    }

    public Criteria andNseIsNull() {
      addCriterion("NSE is null");
      return (Criteria) this;
    }

    public Criteria andNseIsNotNull() {
      addCriterion("NSE is not null");
      return (Criteria) this;
    }

    public Criteria andNseEqualTo(String value) {
      addCriterion("NSE =", value, "nse");
      return (Criteria) this;
    }

    public Criteria andNseNotEqualTo(String value) {
      addCriterion("NSE <>", value, "nse");
      return (Criteria) this;
    }

    public Criteria andNseGreaterThan(String value) {
      addCriterion("NSE >", value, "nse");
      return (Criteria) this;
    }

    public Criteria andNseGreaterThanOrEqualTo(String value) {
      addCriterion("NSE >=", value, "nse");
      return (Criteria) this;
    }

    public Criteria andNseLessThan(String value) {
      addCriterion("NSE <", value, "nse");
      return (Criteria) this;
    }

    public Criteria andNseLessThanOrEqualTo(String value) {
      addCriterion("NSE <=", value, "nse");
      return (Criteria) this;
    }

    public Criteria andNseIn(List<String> values) {
      addCriterion("NSE in", values, "nse");
      return (Criteria) this;
    }

    public Criteria andNseNotIn(List<String> values) {
      addCriterion("NSE not in", values, "nse");
      return (Criteria) this;
    }

    public Criteria andNseBetween(String value1, String value2) {
      addCriterion("NSE between", value1, value2, "nse");
      return (Criteria) this;
    }

    public Criteria andNseNotBetween(String value1, String value2) {
      addCriterion("NSE not between", value1, value2, "nse");
      return (Criteria) this;
    }

    public Criteria andNombresyapellidosIsNull() {
      addCriterion("NOMBRESYAPELLIDOS is null");
      return (Criteria) this;
    }

    public Criteria andNombresyapellidosIsNotNull() {
      addCriterion("NOMBRESYAPELLIDOS is not null");
      return (Criteria) this;
    }

    public Criteria andNombresyapellidosEqualTo(String value) {
      addCriterion("NOMBRESYAPELLIDOS =", value, "nombresyapellidos");
      return (Criteria) this;
    }

    public Criteria andNombresyapellidosNotEqualTo(String value) {
      addCriterion("NOMBRESYAPELLIDOS <>", value, "nombresyapellidos");
      return (Criteria) this;
    }

    public Criteria andNombresyapellidosGreaterThan(String value) {
      addCriterion("NOMBRESYAPELLIDOS >", value, "nombresyapellidos");
      return (Criteria) this;
    }

    public Criteria andNombresyapellidosGreaterThanOrEqualTo(String value) {
      addCriterion("NOMBRESYAPELLIDOS >=", value, "nombresyapellidos");
      return (Criteria) this;
    }

    public Criteria andNombresyapellidosLessThan(String value) {
      addCriterion("NOMBRESYAPELLIDOS <", value, "nombresyapellidos");
      return (Criteria) this;
    }

    public Criteria andNombresyapellidosLessThanOrEqualTo(String value) {
      addCriterion("NOMBRESYAPELLIDOS <=", value, "nombresyapellidos");
      return (Criteria) this;
    }

    public Criteria andNombresyapellidosIn(List<String> values) {
      addCriterion("NOMBRESYAPELLIDOS in", values, "nombresyapellidos");
      return (Criteria) this;
    }

    public Criteria andNombresyapellidosNotIn(List<String> values) {
      addCriterion("NOMBRESYAPELLIDOS not in", values, "nombresyapellidos");
      return (Criteria) this;
    }

    public Criteria andNombresyapellidosBetween(String value1, String value2) {
      addCriterion("NOMBRESYAPELLIDOS between", value1, value2, "nombresyapellidos");
      return (Criteria) this;
    }

    public Criteria andNombresyapellidosNotBetween(String value1, String value2) {
      addCriterion("NOMBRESYAPELLIDOS not between", value1, value2, "nombresyapellidos");
      return (Criteria) this;
    }

    public Criteria andOcupacionIsNull() {
      addCriterion("OCUPACION is null");
      return (Criteria) this;
    }

    public Criteria andOcupacionIsNotNull() {
      addCriterion("OCUPACION is not null");
      return (Criteria) this;
    }

    public Criteria andOcupacionEqualTo(String value) {
      addCriterion("OCUPACION =", value, "ocupacion");
      return (Criteria) this;
    }

    public Criteria andOcupacionNotEqualTo(String value) {
      addCriterion("OCUPACION <>", value, "ocupacion");
      return (Criteria) this;
    }

    public Criteria andOcupacionGreaterThan(String value) {
      addCriterion("OCUPACION >", value, "ocupacion");
      return (Criteria) this;
    }

    public Criteria andOcupacionGreaterThanOrEqualTo(String value) {
      addCriterion("OCUPACION >=", value, "ocupacion");
      return (Criteria) this;
    }

    public Criteria andOcupacionLessThan(String value) {
      addCriterion("OCUPACION <", value, "ocupacion");
      return (Criteria) this;
    }

    public Criteria andOcupacionLessThanOrEqualTo(String value) {
      addCriterion("OCUPACION <=", value, "ocupacion");
      return (Criteria) this;
    }

    public Criteria andOcupacionIn(List<String> values) {
      addCriterion("OCUPACION in", values, "ocupacion");
      return (Criteria) this;
    }

    public Criteria andOcupacionNotIn(List<String> values) {
      addCriterion("OCUPACION not in", values, "ocupacion");
      return (Criteria) this;
    }

    public Criteria andOcupacionBetween(String value1, String value2) {
      addCriterion("OCUPACION between", value1, value2, "ocupacion");
      return (Criteria) this;
    }

    public Criteria andOcupacionNotBetween(String value1, String value2) {
      addCriterion("OCUPACION not between", value1, value2, "ocupacion");
      return (Criteria) this;
    }

    public Criteria andDireccionIsNull() {
      addCriterion("DIRECCION is null");
      return (Criteria) this;
    }

    public Criteria andDireccionIsNotNull() {
      addCriterion("DIRECCION is not null");
      return (Criteria) this;
    }

    public Criteria andDireccionEqualTo(String value) {
      addCriterion("DIRECCION =", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionNotEqualTo(String value) {
      addCriterion("DIRECCION <>", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionGreaterThan(String value) {
      addCriterion("DIRECCION >", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionGreaterThanOrEqualTo(String value) {
      addCriterion("DIRECCION >=", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionLessThan(String value) {
      addCriterion("DIRECCION <", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionLessThanOrEqualTo(String value) {
      addCriterion("DIRECCION <=", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionIn(List<String> values) {
      addCriterion("DIRECCION in", values, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionNotIn(List<String> values) {
      addCriterion("DIRECCION not in", values, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionBetween(String value1, String value2) {
      addCriterion("DIRECCION between", value1, value2, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionNotBetween(String value1, String value2) {
      addCriterion("DIRECCION not between", value1, value2, "direccion");
      return (Criteria) this;
    }

    public Criteria andDistritoIsNull() {
      addCriterion("DISTRITO is null");
      return (Criteria) this;
    }

    public Criteria andDistritoIsNotNull() {
      addCriterion("DISTRITO is not null");
      return (Criteria) this;
    }

    public Criteria andDistritoEqualTo(String value) {
      addCriterion("DISTRITO =", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoNotEqualTo(String value) {
      addCriterion("DISTRITO <>", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoGreaterThan(String value) {
      addCriterion("DISTRITO >", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoGreaterThanOrEqualTo(String value) {
      addCriterion("DISTRITO >=", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoLessThan(String value) {
      addCriterion("DISTRITO <", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoLessThanOrEqualTo(String value) {
      addCriterion("DISTRITO <=", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoIn(List<String> values) {
      addCriterion("DISTRITO in", values, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoNotIn(List<String> values) {
      addCriterion("DISTRITO not in", values, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoBetween(String value1, String value2) {
      addCriterion("DISTRITO between", value1, value2, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoNotBetween(String value1, String value2) {
      addCriterion("DISTRITO not between", value1, value2, "distrito");
      return (Criteria) this;
    }

    public Criteria andDepartamentoIsNull() {
      addCriterion("DEPARTAMENTO is null");
      return (Criteria) this;
    }

    public Criteria andDepartamentoIsNotNull() {
      addCriterion("DEPARTAMENTO is not null");
      return (Criteria) this;
    }

    public Criteria andDepartamentoEqualTo(String value) {
      addCriterion("DEPARTAMENTO =", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoNotEqualTo(String value) {
      addCriterion("DEPARTAMENTO <>", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoGreaterThan(String value) {
      addCriterion("DEPARTAMENTO >", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoGreaterThanOrEqualTo(String value) {
      addCriterion("DEPARTAMENTO >=", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoLessThan(String value) {
      addCriterion("DEPARTAMENTO <", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoLessThanOrEqualTo(String value) {
      addCriterion("DEPARTAMENTO <=", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoIn(List<String> values) {
      addCriterion("DEPARTAMENTO in", values, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoNotIn(List<String> values) {
      addCriterion("DEPARTAMENTO not in", values, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoBetween(String value1, String value2) {
      addCriterion("DEPARTAMENTO between", value1, value2, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoNotBetween(String value1, String value2) {
      addCriterion("DEPARTAMENTO not between", value1, value2, "departamento");
      return (Criteria) this;
    }

    public Criteria andFonoEmpleador1IsNull() {
      addCriterion("FONO_EMPLEADOR_1 is null");
      return (Criteria) this;
    }

    public Criteria andFonoEmpleador1IsNotNull() {
      addCriterion("FONO_EMPLEADOR_1 is not null");
      return (Criteria) this;
    }

    public Criteria andFonoEmpleador1EqualTo(String value) {
      addCriterion("FONO_EMPLEADOR_1 =", value, "fonoEmpleador1");
      return (Criteria) this;
    }

    public Criteria andFonoEmpleador1NotEqualTo(String value) {
      addCriterion("FONO_EMPLEADOR_1 <>", value, "fonoEmpleador1");
      return (Criteria) this;
    }

    public Criteria andFonoEmpleador1GreaterThan(String value) {
      addCriterion("FONO_EMPLEADOR_1 >", value, "fonoEmpleador1");
      return (Criteria) this;
    }

    public Criteria andFonoEmpleador1GreaterThanOrEqualTo(String value) {
      addCriterion("FONO_EMPLEADOR_1 >=", value, "fonoEmpleador1");
      return (Criteria) this;
    }

    public Criteria andFonoEmpleador1LessThan(String value) {
      addCriterion("FONO_EMPLEADOR_1 <", value, "fonoEmpleador1");
      return (Criteria) this;
    }

    public Criteria andFonoEmpleador1LessThanOrEqualTo(String value) {
      addCriterion("FONO_EMPLEADOR_1 <=", value, "fonoEmpleador1");
      return (Criteria) this;
    }

    public Criteria andFonoEmpleador1In(List<String> values) {
      addCriterion("FONO_EMPLEADOR_1 in", values, "fonoEmpleador1");
      return (Criteria) this;
    }

    public Criteria andFonoEmpleador1NotIn(List<String> values) {
      addCriterion("FONO_EMPLEADOR_1 not in", values, "fonoEmpleador1");
      return (Criteria) this;
    }

    public Criteria andFonoEmpleador1Between(String value1, String value2) {
      addCriterion("FONO_EMPLEADOR_1 between", value1, value2, "fonoEmpleador1");
      return (Criteria) this;
    }

    public Criteria andFonoEmpleador1NotBetween(String value1, String value2) {
      addCriterion("FONO_EMPLEADOR_1 not between", value1, value2, "fonoEmpleador1");
      return (Criteria) this;
    }

    public Criteria andFonoCliente1IsNull() {
      addCriterion("FONO_CLIENTE_1 is null");
      return (Criteria) this;
    }

    public Criteria andFonoCliente1IsNotNull() {
      addCriterion("FONO_CLIENTE_1 is not null");
      return (Criteria) this;
    }

    public Criteria andFonoCliente1EqualTo(String value) {
      addCriterion("FONO_CLIENTE_1 =", value, "fonoCliente1");
      return (Criteria) this;
    }

    public Criteria andFonoCliente1NotEqualTo(String value) {
      addCriterion("FONO_CLIENTE_1 <>", value, "fonoCliente1");
      return (Criteria) this;
    }

    public Criteria andFonoCliente1GreaterThan(String value) {
      addCriterion("FONO_CLIENTE_1 >", value, "fonoCliente1");
      return (Criteria) this;
    }

    public Criteria andFonoCliente1GreaterThanOrEqualTo(String value) {
      addCriterion("FONO_CLIENTE_1 >=", value, "fonoCliente1");
      return (Criteria) this;
    }

    public Criteria andFonoCliente1LessThan(String value) {
      addCriterion("FONO_CLIENTE_1 <", value, "fonoCliente1");
      return (Criteria) this;
    }

    public Criteria andFonoCliente1LessThanOrEqualTo(String value) {
      addCriterion("FONO_CLIENTE_1 <=", value, "fonoCliente1");
      return (Criteria) this;
    }

    public Criteria andFonoCliente1In(List<String> values) {
      addCriterion("FONO_CLIENTE_1 in", values, "fonoCliente1");
      return (Criteria) this;
    }

    public Criteria andFonoCliente1NotIn(List<String> values) {
      addCriterion("FONO_CLIENTE_1 not in", values, "fonoCliente1");
      return (Criteria) this;
    }

    public Criteria andFonoCliente1Between(String value1, String value2) {
      addCriterion("FONO_CLIENTE_1 between", value1, value2, "fonoCliente1");
      return (Criteria) this;
    }

    public Criteria andFonoCliente1NotBetween(String value1, String value2) {
      addCriterion("FONO_CLIENTE_1 not between", value1, value2, "fonoCliente1");
      return (Criteria) this;
    }

    public Criteria andFonoCliente2IsNull() {
      addCriterion("FONO_CLIENTE_2 is null");
      return (Criteria) this;
    }

    public Criteria andFonoCliente2IsNotNull() {
      addCriterion("FONO_CLIENTE_2 is not null");
      return (Criteria) this;
    }

    public Criteria andFonoCliente2EqualTo(String value) {
      addCriterion("FONO_CLIENTE_2 =", value, "fonoCliente2");
      return (Criteria) this;
    }

    public Criteria andFonoCliente2NotEqualTo(String value) {
      addCriterion("FONO_CLIENTE_2 <>", value, "fonoCliente2");
      return (Criteria) this;
    }

    public Criteria andFonoCliente2GreaterThan(String value) {
      addCriterion("FONO_CLIENTE_2 >", value, "fonoCliente2");
      return (Criteria) this;
    }

    public Criteria andFonoCliente2GreaterThanOrEqualTo(String value) {
      addCriterion("FONO_CLIENTE_2 >=", value, "fonoCliente2");
      return (Criteria) this;
    }

    public Criteria andFonoCliente2LessThan(String value) {
      addCriterion("FONO_CLIENTE_2 <", value, "fonoCliente2");
      return (Criteria) this;
    }

    public Criteria andFonoCliente2LessThanOrEqualTo(String value) {
      addCriterion("FONO_CLIENTE_2 <=", value, "fonoCliente2");
      return (Criteria) this;
    }

    public Criteria andFonoCliente2In(List<String> values) {
      addCriterion("FONO_CLIENTE_2 in", values, "fonoCliente2");
      return (Criteria) this;
    }

    public Criteria andFonoCliente2NotIn(List<String> values) {
      addCriterion("FONO_CLIENTE_2 not in", values, "fonoCliente2");
      return (Criteria) this;
    }

    public Criteria andFonoCliente2Between(String value1, String value2) {
      addCriterion("FONO_CLIENTE_2 between", value1, value2, "fonoCliente2");
      return (Criteria) this;
    }

    public Criteria andFonoCliente2NotBetween(String value1, String value2) {
      addCriterion("FONO_CLIENTE_2 not between", value1, value2, "fonoCliente2");
      return (Criteria) this;
    }

    public Criteria andCelular0IsNull() {
      addCriterion("CELULAR_0 is null");
      return (Criteria) this;
    }

    public Criteria andCelular0IsNotNull() {
      addCriterion("CELULAR_0 is not null");
      return (Criteria) this;
    }

    public Criteria andCelular0EqualTo(String value) {
      addCriterion("CELULAR_0 =", value, "celular0");
      return (Criteria) this;
    }

    public Criteria andCelular0NotEqualTo(String value) {
      addCriterion("CELULAR_0 <>", value, "celular0");
      return (Criteria) this;
    }

    public Criteria andCelular0GreaterThan(String value) {
      addCriterion("CELULAR_0 >", value, "celular0");
      return (Criteria) this;
    }

    public Criteria andCelular0GreaterThanOrEqualTo(String value) {
      addCriterion("CELULAR_0 >=", value, "celular0");
      return (Criteria) this;
    }

    public Criteria andCelular0LessThan(String value) {
      addCriterion("CELULAR_0 <", value, "celular0");
      return (Criteria) this;
    }

    public Criteria andCelular0LessThanOrEqualTo(String value) {
      addCriterion("CELULAR_0 <=", value, "celular0");
      return (Criteria) this;
    }

    public Criteria andCelular0In(List<String> values) {
      addCriterion("CELULAR_0 in", values, "celular0");
      return (Criteria) this;
    }

    public Criteria andCelular0NotIn(List<String> values) {
      addCriterion("CELULAR_0 not in", values, "celular0");
      return (Criteria) this;
    }

    public Criteria andCelular0Between(String value1, String value2) {
      addCriterion("CELULAR_0 between", value1, value2, "celular0");
      return (Criteria) this;
    }

    public Criteria andCelular0NotBetween(String value1, String value2) {
      addCriterion("CELULAR_0 not between", value1, value2, "celular0");
      return (Criteria) this;
    }

    public Criteria andCelular1IsNull() {
      addCriterion("CELULAR_1 is null");
      return (Criteria) this;
    }

    public Criteria andCelular1IsNotNull() {
      addCriterion("CELULAR_1 is not null");
      return (Criteria) this;
    }

    public Criteria andCelular1EqualTo(String value) {
      addCriterion("CELULAR_1 =", value, "celular1");
      return (Criteria) this;
    }

    public Criteria andCelular1NotEqualTo(String value) {
      addCriterion("CELULAR_1 <>", value, "celular1");
      return (Criteria) this;
    }

    public Criteria andCelular1GreaterThan(String value) {
      addCriterion("CELULAR_1 >", value, "celular1");
      return (Criteria) this;
    }

    public Criteria andCelular1GreaterThanOrEqualTo(String value) {
      addCriterion("CELULAR_1 >=", value, "celular1");
      return (Criteria) this;
    }

    public Criteria andCelular1LessThan(String value) {
      addCriterion("CELULAR_1 <", value, "celular1");
      return (Criteria) this;
    }

    public Criteria andCelular1LessThanOrEqualTo(String value) {
      addCriterion("CELULAR_1 <=", value, "celular1");
      return (Criteria) this;
    }

    public Criteria andCelular1In(List<String> values) {
      addCriterion("CELULAR_1 in", values, "celular1");
      return (Criteria) this;
    }

    public Criteria andCelular1NotIn(List<String> values) {
      addCriterion("CELULAR_1 not in", values, "celular1");
      return (Criteria) this;
    }

    public Criteria andCelular1Between(String value1, String value2) {
      addCriterion("CELULAR_1 between", value1, value2, "celular1");
      return (Criteria) this;
    }

    public Criteria andCelular1NotBetween(String value1, String value2) {
      addCriterion("CELULAR_1 not between", value1, value2, "celular1");
      return (Criteria) this;
    }

    public Criteria andOficinaIsNull() {
      addCriterion("OFICINA is null");
      return (Criteria) this;
    }

    public Criteria andOficinaIsNotNull() {
      addCriterion("OFICINA is not null");
      return (Criteria) this;
    }

    public Criteria andOficinaEqualTo(String value) {
      addCriterion("OFICINA =", value, "oficina");
      return (Criteria) this;
    }

    public Criteria andOficinaNotEqualTo(String value) {
      addCriterion("OFICINA <>", value, "oficina");
      return (Criteria) this;
    }

    public Criteria andOficinaGreaterThan(String value) {
      addCriterion("OFICINA >", value, "oficina");
      return (Criteria) this;
    }

    public Criteria andOficinaGreaterThanOrEqualTo(String value) {
      addCriterion("OFICINA >=", value, "oficina");
      return (Criteria) this;
    }

    public Criteria andOficinaLessThan(String value) {
      addCriterion("OFICINA <", value, "oficina");
      return (Criteria) this;
    }

    public Criteria andOficinaLessThanOrEqualTo(String value) {
      addCriterion("OFICINA <=", value, "oficina");
      return (Criteria) this;
    }

    public Criteria andOficinaIn(List<String> values) {
      addCriterion("OFICINA in", values, "oficina");
      return (Criteria) this;
    }

    public Criteria andOficinaNotIn(List<String> values) {
      addCriterion("OFICINA not in", values, "oficina");
      return (Criteria) this;
    }

    public Criteria andOficinaBetween(String value1, String value2) {
      addCriterion("OFICINA between", value1, value2, "oficina");
      return (Criteria) this;
    }

    public Criteria andOficinaNotBetween(String value1, String value2) {
      addCriterion("OFICINA not between", value1, value2, "oficina");
      return (Criteria) this;
    }

    public Criteria andCasaIsNull() {
      addCriterion("CASA is null");
      return (Criteria) this;
    }

    public Criteria andCasaIsNotNull() {
      addCriterion("CASA is not null");
      return (Criteria) this;
    }

    public Criteria andCasaEqualTo(String value) {
      addCriterion("CASA =", value, "casa");
      return (Criteria) this;
    }

    public Criteria andCasaNotEqualTo(String value) {
      addCriterion("CASA <>", value, "casa");
      return (Criteria) this;
    }

    public Criteria andCasaGreaterThan(String value) {
      addCriterion("CASA >", value, "casa");
      return (Criteria) this;
    }

    public Criteria andCasaGreaterThanOrEqualTo(String value) {
      addCriterion("CASA >=", value, "casa");
      return (Criteria) this;
    }

    public Criteria andCasaLessThan(String value) {
      addCriterion("CASA <", value, "casa");
      return (Criteria) this;
    }

    public Criteria andCasaLessThanOrEqualTo(String value) {
      addCriterion("CASA <=", value, "casa");
      return (Criteria) this;
    }

    public Criteria andCasaIn(List<String> values) {
      addCriterion("CASA in", values, "casa");
      return (Criteria) this;
    }

    public Criteria andCasaNotIn(List<String> values) {
      addCriterion("CASA not in", values, "casa");
      return (Criteria) this;
    }

    public Criteria andCasaBetween(String value1, String value2) {
      addCriterion("CASA between", value1, value2, "casa");
      return (Criteria) this;
    }

    public Criteria andCasaNotBetween(String value1, String value2) {
      addCriterion("CASA not between", value1, value2, "casa");
      return (Criteria) this;
    }

    public Criteria andCel1IsNull() {
      addCriterion("CEL1 is null");
      return (Criteria) this;
    }

    public Criteria andCel1IsNotNull() {
      addCriterion("CEL1 is not null");
      return (Criteria) this;
    }

    public Criteria andCel1EqualTo(String value) {
      addCriterion("CEL1 =", value, "cel1");
      return (Criteria) this;
    }

    public Criteria andCel1NotEqualTo(String value) {
      addCriterion("CEL1 <>", value, "cel1");
      return (Criteria) this;
    }

    public Criteria andCel1GreaterThan(String value) {
      addCriterion("CEL1 >", value, "cel1");
      return (Criteria) this;
    }

    public Criteria andCel1GreaterThanOrEqualTo(String value) {
      addCriterion("CEL1 >=", value, "cel1");
      return (Criteria) this;
    }

    public Criteria andCel1LessThan(String value) {
      addCriterion("CEL1 <", value, "cel1");
      return (Criteria) this;
    }

    public Criteria andCel1LessThanOrEqualTo(String value) {
      addCriterion("CEL1 <=", value, "cel1");
      return (Criteria) this;
    }

    public Criteria andCel1In(List<String> values) {
      addCriterion("CEL1 in", values, "cel1");
      return (Criteria) this;
    }

    public Criteria andCel1NotIn(List<String> values) {
      addCriterion("CEL1 not in", values, "cel1");
      return (Criteria) this;
    }

    public Criteria andCel1Between(String value1, String value2) {
      addCriterion("CEL1 between", value1, value2, "cel1");
      return (Criteria) this;
    }

    public Criteria andCel1NotBetween(String value1, String value2) {
      addCriterion("CEL1 not between", value1, value2, "cel1");
      return (Criteria) this;
    }

    public Criteria andCel2IsNull() {
      addCriterion("CEL2 is null");
      return (Criteria) this;
    }

    public Criteria andCel2IsNotNull() {
      addCriterion("CEL2 is not null");
      return (Criteria) this;
    }

    public Criteria andCel2EqualTo(String value) {
      addCriterion("CEL2 =", value, "cel2");
      return (Criteria) this;
    }

    public Criteria andCel2NotEqualTo(String value) {
      addCriterion("CEL2 <>", value, "cel2");
      return (Criteria) this;
    }

    public Criteria andCel2GreaterThan(String value) {
      addCriterion("CEL2 >", value, "cel2");
      return (Criteria) this;
    }

    public Criteria andCel2GreaterThanOrEqualTo(String value) {
      addCriterion("CEL2 >=", value, "cel2");
      return (Criteria) this;
    }

    public Criteria andCel2LessThan(String value) {
      addCriterion("CEL2 <", value, "cel2");
      return (Criteria) this;
    }

    public Criteria andCel2LessThanOrEqualTo(String value) {
      addCriterion("CEL2 <=", value, "cel2");
      return (Criteria) this;
    }

    public Criteria andCel2In(List<String> values) {
      addCriterion("CEL2 in", values, "cel2");
      return (Criteria) this;
    }

    public Criteria andCel2NotIn(List<String> values) {
      addCriterion("CEL2 not in", values, "cel2");
      return (Criteria) this;
    }

    public Criteria andCel2Between(String value1, String value2) {
      addCriterion("CEL2 between", value1, value2, "cel2");
      return (Criteria) this;
    }

    public Criteria andCel2NotBetween(String value1, String value2) {
      addCriterion("CEL2 not between", value1, value2, "cel2");
      return (Criteria) this;
    }

    public Criteria andCel3IsNull() {
      addCriterion("CEL3 is null");
      return (Criteria) this;
    }

    public Criteria andCel3IsNotNull() {
      addCriterion("CEL3 is not null");
      return (Criteria) this;
    }

    public Criteria andCel3EqualTo(String value) {
      addCriterion("CEL3 =", value, "cel3");
      return (Criteria) this;
    }

    public Criteria andCel3NotEqualTo(String value) {
      addCriterion("CEL3 <>", value, "cel3");
      return (Criteria) this;
    }

    public Criteria andCel3GreaterThan(String value) {
      addCriterion("CEL3 >", value, "cel3");
      return (Criteria) this;
    }

    public Criteria andCel3GreaterThanOrEqualTo(String value) {
      addCriterion("CEL3 >=", value, "cel3");
      return (Criteria) this;
    }

    public Criteria andCel3LessThan(String value) {
      addCriterion("CEL3 <", value, "cel3");
      return (Criteria) this;
    }

    public Criteria andCel3LessThanOrEqualTo(String value) {
      addCriterion("CEL3 <=", value, "cel3");
      return (Criteria) this;
    }

    public Criteria andCel3In(List<String> values) {
      addCriterion("CEL3 in", values, "cel3");
      return (Criteria) this;
    }

    public Criteria andCel3NotIn(List<String> values) {
      addCriterion("CEL3 not in", values, "cel3");
      return (Criteria) this;
    }

    public Criteria andCel3Between(String value1, String value2) {
      addCriterion("CEL3 between", value1, value2, "cel3");
      return (Criteria) this;
    }

    public Criteria andCel3NotBetween(String value1, String value2) {
      addCriterion("CEL3 not between", value1, value2, "cel3");
      return (Criteria) this;
    }

    public Criteria andCel4IsNull() {
      addCriterion("CEL4 is null");
      return (Criteria) this;
    }

    public Criteria andCel4IsNotNull() {
      addCriterion("CEL4 is not null");
      return (Criteria) this;
    }

    public Criteria andCel4EqualTo(String value) {
      addCriterion("CEL4 =", value, "cel4");
      return (Criteria) this;
    }

    public Criteria andCel4NotEqualTo(String value) {
      addCriterion("CEL4 <>", value, "cel4");
      return (Criteria) this;
    }

    public Criteria andCel4GreaterThan(String value) {
      addCriterion("CEL4 >", value, "cel4");
      return (Criteria) this;
    }

    public Criteria andCel4GreaterThanOrEqualTo(String value) {
      addCriterion("CEL4 >=", value, "cel4");
      return (Criteria) this;
    }

    public Criteria andCel4LessThan(String value) {
      addCriterion("CEL4 <", value, "cel4");
      return (Criteria) this;
    }

    public Criteria andCel4LessThanOrEqualTo(String value) {
      addCriterion("CEL4 <=", value, "cel4");
      return (Criteria) this;
    }

    public Criteria andCel4In(List<String> values) {
      addCriterion("CEL4 in", values, "cel4");
      return (Criteria) this;
    }

    public Criteria andCel4NotIn(List<String> values) {
      addCriterion("CEL4 not in", values, "cel4");
      return (Criteria) this;
    }

    public Criteria andCel4Between(String value1, String value2) {
      addCriterion("CEL4 between", value1, value2, "cel4");
      return (Criteria) this;
    }

    public Criteria andCel4NotBetween(String value1, String value2) {
      addCriterion("CEL4 not between", value1, value2, "cel4");
      return (Criteria) this;
    }

    public Criteria andCel5IsNull() {
      addCriterion("CEL5 is null");
      return (Criteria) this;
    }

    public Criteria andCel5IsNotNull() {
      addCriterion("CEL5 is not null");
      return (Criteria) this;
    }

    public Criteria andCel5EqualTo(String value) {
      addCriterion("CEL5 =", value, "cel5");
      return (Criteria) this;
    }

    public Criteria andCel5NotEqualTo(String value) {
      addCriterion("CEL5 <>", value, "cel5");
      return (Criteria) this;
    }

    public Criteria andCel5GreaterThan(String value) {
      addCriterion("CEL5 >", value, "cel5");
      return (Criteria) this;
    }

    public Criteria andCel5GreaterThanOrEqualTo(String value) {
      addCriterion("CEL5 >=", value, "cel5");
      return (Criteria) this;
    }

    public Criteria andCel5LessThan(String value) {
      addCriterion("CEL5 <", value, "cel5");
      return (Criteria) this;
    }

    public Criteria andCel5LessThanOrEqualTo(String value) {
      addCriterion("CEL5 <=", value, "cel5");
      return (Criteria) this;
    }

    public Criteria andCel5In(List<String> values) {
      addCriterion("CEL5 in", values, "cel5");
      return (Criteria) this;
    }

    public Criteria andCel5NotIn(List<String> values) {
      addCriterion("CEL5 not in", values, "cel5");
      return (Criteria) this;
    }

    public Criteria andCel5Between(String value1, String value2) {
      addCriterion("CEL5 between", value1, value2, "cel5");
      return (Criteria) this;
    }

    public Criteria andCel5NotBetween(String value1, String value2) {
      addCriterion("CEL5 not between", value1, value2, "cel5");
      return (Criteria) this;
    }

    public Criteria andEstadoIsNull() {
      addCriterion("ESTADO is null");
      return (Criteria) this;
    }

    public Criteria andEstadoIsNotNull() {
      addCriterion("ESTADO is not null");
      return (Criteria) this;
    }

    public Criteria andEstadoEqualTo(String value) {
      addCriterion("ESTADO =", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoNotEqualTo(String value) {
      addCriterion("ESTADO <>", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoGreaterThan(String value) {
      addCriterion("ESTADO >", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoGreaterThanOrEqualTo(String value) {
      addCriterion("ESTADO >=", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoLessThan(String value) {
      addCriterion("ESTADO <", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoLessThanOrEqualTo(String value) {
      addCriterion("ESTADO <=", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoIn(List<String> values) {
      addCriterion("ESTADO in", values, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoNotIn(List<String> values) {
      addCriterion("ESTADO not in", values, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoBetween(String value1, String value2) {
      addCriterion("ESTADO between", value1, value2, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoNotBetween(String value1, String value2) {
      addCriterion("ESTADO not between", value1, value2, "estado");
      return (Criteria) this;
    }

    public Criteria andDesMensajeIsNull() {
      addCriterion("DES_MENSAJE is null");
      return (Criteria) this;
    }

    public Criteria andDesMensajeIsNotNull() {
      addCriterion("DES_MENSAJE is not null");
      return (Criteria) this;
    }

    public Criteria andDesMensajeEqualTo(String value) {
      addCriterion("DES_MENSAJE =", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeNotEqualTo(String value) {
      addCriterion("DES_MENSAJE <>", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeGreaterThan(String value) {
      addCriterion("DES_MENSAJE >", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeGreaterThanOrEqualTo(String value) {
      addCriterion("DES_MENSAJE >=", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeLessThan(String value) {
      addCriterion("DES_MENSAJE <", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeLessThanOrEqualTo(String value) {
      addCriterion("DES_MENSAJE <=", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeIn(List<String> values) {
      addCriterion("DES_MENSAJE in", values, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeNotIn(List<String> values) {
      addCriterion("DES_MENSAJE not in", values, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeBetween(String value1, String value2) {
      addCriterion("DES_MENSAJE between", value1, value2, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeNotBetween(String value1, String value2) {
      addCriterion("DES_MENSAJE not between", value1, value2, "desMensaje");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated do_not_delete_during_merge Wed Jan 22 12:45:18 COT 2014
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}