package com.cardif.satelite.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TlmkBaseCabeceraExample implements Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:28:39 COT 2014
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:28:39 COT 2014
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:28:39 COT 2014
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:28:39 COT 2014
   */
  public TlmkBaseCabeceraExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:28:39 COT 2014
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:28:39 COT 2014
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:28:39 COT 2014
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:28:39 COT 2014
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:28:39 COT 2014
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:28:39 COT 2014
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:28:39 COT 2014
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:28:39 COT 2014
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:28:39 COT 2014
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:28:39 COT 2014
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:28:39 COT 2014
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andCodBaseIsNull() {
      addCriterion("COD_BASE is null");
      return (Criteria) this;
    }

    public Criteria andCodBaseIsNotNull() {
      addCriterion("COD_BASE is not null");
      return (Criteria) this;
    }

    public Criteria andCodBaseEqualTo(Long value) {
      addCriterion("COD_BASE =", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseNotEqualTo(Long value) {
      addCriterion("COD_BASE <>", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseGreaterThan(Long value) {
      addCriterion("COD_BASE >", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseGreaterThanOrEqualTo(Long value) {
      addCriterion("COD_BASE >=", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseLessThan(Long value) {
      addCriterion("COD_BASE <", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseLessThanOrEqualTo(Long value) {
      addCriterion("COD_BASE <=", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseIn(List<Long> values) {
      addCriterion("COD_BASE in", values, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseNotIn(List<Long> values) {
      addCriterion("COD_BASE not in", values, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseBetween(Long value1, Long value2) {
      addCriterion("COD_BASE between", value1, value2, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseNotBetween(Long value1, Long value2) {
      addCriterion("COD_BASE not between", value1, value2, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodSocioIsNull() {
      addCriterion("COD_SOCIO is null");
      return (Criteria) this;
    }

    public Criteria andCodSocioIsNotNull() {
      addCriterion("COD_SOCIO is not null");
      return (Criteria) this;
    }

    public Criteria andCodSocioEqualTo(String value) {
      addCriterion("COD_SOCIO =", value, "codSocio");
      return (Criteria) this;
    }

    public Criteria andCodSocioNotEqualTo(String value) {
      addCriterion("COD_SOCIO <>", value, "codSocio");
      return (Criteria) this;
    }

    public Criteria andCodSocioGreaterThan(String value) {
      addCriterion("COD_SOCIO >", value, "codSocio");
      return (Criteria) this;
    }

    public Criteria andCodSocioGreaterThanOrEqualTo(String value) {
      addCriterion("COD_SOCIO >=", value, "codSocio");
      return (Criteria) this;
    }

    public Criteria andCodSocioLessThan(String value) {
      addCriterion("COD_SOCIO <", value, "codSocio");
      return (Criteria) this;
    }

    public Criteria andCodSocioLessThanOrEqualTo(String value) {
      addCriterion("COD_SOCIO <=", value, "codSocio");
      return (Criteria) this;
    }

    public Criteria andCodSocioIn(List<String> values) {
      addCriterion("COD_SOCIO in", values, "codSocio");
      return (Criteria) this;
    }

    public Criteria andCodSocioNotIn(List<String> values) {
      addCriterion("COD_SOCIO not in", values, "codSocio");
      return (Criteria) this;
    }

    public Criteria andCodSocioBetween(String value1, String value2) {
      addCriterion("COD_SOCIO between", value1, value2, "codSocio");
      return (Criteria) this;
    }

    public Criteria andCodSocioNotBetween(String value1, String value2) {
      addCriterion("COD_SOCIO not between", value1, value2, "codSocio");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosIsNull() {
      addCriterion("NUM_REGISTROS is null");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosIsNotNull() {
      addCriterion("NUM_REGISTROS is not null");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosEqualTo(Long value) {
      addCriterion("NUM_REGISTROS =", value, "numRegistros");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosNotEqualTo(Long value) {
      addCriterion("NUM_REGISTROS <>", value, "numRegistros");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosGreaterThan(Long value) {
      addCriterion("NUM_REGISTROS >", value, "numRegistros");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosGreaterThanOrEqualTo(Long value) {
      addCriterion("NUM_REGISTROS >=", value, "numRegistros");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosLessThan(Long value) {
      addCriterion("NUM_REGISTROS <", value, "numRegistros");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosLessThanOrEqualTo(Long value) {
      addCriterion("NUM_REGISTROS <=", value, "numRegistros");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosIn(List<Long> values) {
      addCriterion("NUM_REGISTROS in", values, "numRegistros");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosNotIn(List<Long> values) {
      addCriterion("NUM_REGISTROS not in", values, "numRegistros");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosBetween(Long value1, Long value2) {
      addCriterion("NUM_REGISTROS between", value1, value2, "numRegistros");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosNotBetween(Long value1, Long value2) {
      addCriterion("NUM_REGISTROS not between", value1, value2, "numRegistros");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberIsNull() {
      addCriterion("SEQUENCE_FILE_NUMBER is null");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberIsNotNull() {
      addCriterion("SEQUENCE_FILE_NUMBER is not null");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberEqualTo(Long value) {
      addCriterion("SEQUENCE_FILE_NUMBER =", value, "sequenceFileNumber");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberNotEqualTo(Long value) {
      addCriterion("SEQUENCE_FILE_NUMBER <>", value, "sequenceFileNumber");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberGreaterThan(Long value) {
      addCriterion("SEQUENCE_FILE_NUMBER >", value, "sequenceFileNumber");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberGreaterThanOrEqualTo(Long value) {
      addCriterion("SEQUENCE_FILE_NUMBER >=", value, "sequenceFileNumber");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberLessThan(Long value) {
      addCriterion("SEQUENCE_FILE_NUMBER <", value, "sequenceFileNumber");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberLessThanOrEqualTo(Long value) {
      addCriterion("SEQUENCE_FILE_NUMBER <=", value, "sequenceFileNumber");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberIn(List<Long> values) {
      addCriterion("SEQUENCE_FILE_NUMBER in", values, "sequenceFileNumber");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberNotIn(List<Long> values) {
      addCriterion("SEQUENCE_FILE_NUMBER not in", values, "sequenceFileNumber");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberBetween(Long value1, Long value2) {
      addCriterion("SEQUENCE_FILE_NUMBER between", value1, value2, "sequenceFileNumber");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberNotBetween(Long value1, Long value2) {
      addCriterion("SEQUENCE_FILE_NUMBER not between", value1, value2, "sequenceFileNumber");
      return (Criteria) this;
    }

    public Criteria andProductosIsNull() {
      addCriterion("PRODUCTOS is null");
      return (Criteria) this;
    }

    public Criteria andProductosIsNotNull() {
      addCriterion("PRODUCTOS is not null");
      return (Criteria) this;
    }

    public Criteria andProductosEqualTo(String value) {
      addCriterion("PRODUCTOS =", value, "productos");
      return (Criteria) this;
    }

    public Criteria andProductosNotEqualTo(String value) {
      addCriterion("PRODUCTOS <>", value, "productos");
      return (Criteria) this;
    }

    public Criteria andProductosGreaterThan(String value) {
      addCriterion("PRODUCTOS >", value, "productos");
      return (Criteria) this;
    }

    public Criteria andProductosGreaterThanOrEqualTo(String value) {
      addCriterion("PRODUCTOS >=", value, "productos");
      return (Criteria) this;
    }

    public Criteria andProductosLessThan(String value) {
      addCriterion("PRODUCTOS <", value, "productos");
      return (Criteria) this;
    }

    public Criteria andProductosLessThanOrEqualTo(String value) {
      addCriterion("PRODUCTOS <=", value, "productos");
      return (Criteria) this;
    }

    public Criteria andProductosIn(List<String> values) {
      addCriterion("PRODUCTOS in", values, "productos");
      return (Criteria) this;
    }

    public Criteria andProductosNotIn(List<String> values) {
      addCriterion("PRODUCTOS not in", values, "productos");
      return (Criteria) this;
    }

    public Criteria andProductosBetween(String value1, String value2) {
      addCriterion("PRODUCTOS between", value1, value2, "productos");
      return (Criteria) this;
    }

    public Criteria andProductosNotBetween(String value1, String value2) {
      addCriterion("PRODUCTOS not between", value1, value2, "productos");
      return (Criteria) this;
    }

    public Criteria andNumMesDescansoIsNull() {
      addCriterion("NUM_MES_DESCANSO is null");
      return (Criteria) this;
    }

    public Criteria andNumMesDescansoIsNotNull() {
      addCriterion("NUM_MES_DESCANSO is not null");
      return (Criteria) this;
    }

    public Criteria andNumMesDescansoEqualTo(Integer value) {
      addCriterion("NUM_MES_DESCANSO =", value, "numMesDescanso");
      return (Criteria) this;
    }

    public Criteria andNumMesDescansoNotEqualTo(Integer value) {
      addCriterion("NUM_MES_DESCANSO <>", value, "numMesDescanso");
      return (Criteria) this;
    }

    public Criteria andNumMesDescansoGreaterThan(Integer value) {
      addCriterion("NUM_MES_DESCANSO >", value, "numMesDescanso");
      return (Criteria) this;
    }

    public Criteria andNumMesDescansoGreaterThanOrEqualTo(Integer value) {
      addCriterion("NUM_MES_DESCANSO >=", value, "numMesDescanso");
      return (Criteria) this;
    }

    public Criteria andNumMesDescansoLessThan(Integer value) {
      addCriterion("NUM_MES_DESCANSO <", value, "numMesDescanso");
      return (Criteria) this;
    }

    public Criteria andNumMesDescansoLessThanOrEqualTo(Integer value) {
      addCriterion("NUM_MES_DESCANSO <=", value, "numMesDescanso");
      return (Criteria) this;
    }

    public Criteria andNumMesDescansoIn(List<Integer> values) {
      addCriterion("NUM_MES_DESCANSO in", values, "numMesDescanso");
      return (Criteria) this;
    }

    public Criteria andNumMesDescansoNotIn(List<Integer> values) {
      addCriterion("NUM_MES_DESCANSO not in", values, "numMesDescanso");
      return (Criteria) this;
    }

    public Criteria andNumMesDescansoBetween(Integer value1, Integer value2) {
      addCriterion("NUM_MES_DESCANSO between", value1, value2, "numMesDescanso");
      return (Criteria) this;
    }

    public Criteria andNumMesDescansoNotBetween(Integer value1, Integer value2) {
      addCriterion("NUM_MES_DESCANSO not between", value1, value2, "numMesDescanso");
      return (Criteria) this;
    }

    public Criteria andNumMesVencimientoIsNull() {
      addCriterion("NUM_MES_VENCIMIENTO is null");
      return (Criteria) this;
    }

    public Criteria andNumMesVencimientoIsNotNull() {
      addCriterion("NUM_MES_VENCIMIENTO is not null");
      return (Criteria) this;
    }

    public Criteria andNumMesVencimientoEqualTo(Integer value) {
      addCriterion("NUM_MES_VENCIMIENTO =", value, "numMesVencimiento");
      return (Criteria) this;
    }

    public Criteria andNumMesVencimientoNotEqualTo(Integer value) {
      addCriterion("NUM_MES_VENCIMIENTO <>", value, "numMesVencimiento");
      return (Criteria) this;
    }

    public Criteria andNumMesVencimientoGreaterThan(Integer value) {
      addCriterion("NUM_MES_VENCIMIENTO >", value, "numMesVencimiento");
      return (Criteria) this;
    }

    public Criteria andNumMesVencimientoGreaterThanOrEqualTo(Integer value) {
      addCriterion("NUM_MES_VENCIMIENTO >=", value, "numMesVencimiento");
      return (Criteria) this;
    }

    public Criteria andNumMesVencimientoLessThan(Integer value) {
      addCriterion("NUM_MES_VENCIMIENTO <", value, "numMesVencimiento");
      return (Criteria) this;
    }

    public Criteria andNumMesVencimientoLessThanOrEqualTo(Integer value) {
      addCriterion("NUM_MES_VENCIMIENTO <=", value, "numMesVencimiento");
      return (Criteria) this;
    }

    public Criteria andNumMesVencimientoIn(List<Integer> values) {
      addCriterion("NUM_MES_VENCIMIENTO in", values, "numMesVencimiento");
      return (Criteria) this;
    }

    public Criteria andNumMesVencimientoNotIn(List<Integer> values) {
      addCriterion("NUM_MES_VENCIMIENTO not in", values, "numMesVencimiento");
      return (Criteria) this;
    }

    public Criteria andNumMesVencimientoBetween(Integer value1, Integer value2) {
      addCriterion("NUM_MES_VENCIMIENTO between", value1, value2, "numMesVencimiento");
      return (Criteria) this;
    }

    public Criteria andNumMesVencimientoNotBetween(Integer value1, Integer value2) {
      addCriterion("NUM_MES_VENCIMIENTO not between", value1, value2, "numMesVencimiento");
      return (Criteria) this;
    }

    public Criteria andEstadoIsNull() {
      addCriterion("ESTADO is null");
      return (Criteria) this;
    }

    public Criteria andEstadoIsNotNull() {
      addCriterion("ESTADO is not null");
      return (Criteria) this;
    }

    public Criteria andEstadoEqualTo(String value) {
      addCriterion("ESTADO =", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoNotEqualTo(String value) {
      addCriterion("ESTADO <>", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoGreaterThan(String value) {
      addCriterion("ESTADO >", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoGreaterThanOrEqualTo(String value) {
      addCriterion("ESTADO >=", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoLessThan(String value) {
      addCriterion("ESTADO <", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoLessThanOrEqualTo(String value) {
      addCriterion("ESTADO <=", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoIn(List<String> values) {
      addCriterion("ESTADO in", values, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoNotIn(List<String> values) {
      addCriterion("ESTADO not in", values, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoBetween(String value1, String value2) {
      addCriterion("ESTADO between", value1, value2, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoNotBetween(String value1, String value2) {
      addCriterion("ESTADO not between", value1, value2, "estado");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionIsNull() {
      addCriterion("USU_CREACION is null");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionIsNotNull() {
      addCriterion("USU_CREACION is not null");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionEqualTo(String value) {
      addCriterion("USU_CREACION =", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionNotEqualTo(String value) {
      addCriterion("USU_CREACION <>", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionGreaterThan(String value) {
      addCriterion("USU_CREACION >", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionGreaterThanOrEqualTo(String value) {
      addCriterion("USU_CREACION >=", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionLessThan(String value) {
      addCriterion("USU_CREACION <", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionLessThanOrEqualTo(String value) {
      addCriterion("USU_CREACION <=", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionIn(List<String> values) {
      addCriterion("USU_CREACION in", values, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionNotIn(List<String> values) {
      addCriterion("USU_CREACION not in", values, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionBetween(String value1, String value2) {
      addCriterion("USU_CREACION between", value1, value2, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionNotBetween(String value1, String value2) {
      addCriterion("USU_CREACION not between", value1, value2, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionIsNull() {
      addCriterion("FEC_CREACION is null");
      return (Criteria) this;
    }

    public Criteria andFecCreacionIsNotNull() {
      addCriterion("FEC_CREACION is not null");
      return (Criteria) this;
    }

    public Criteria andFecCreacionEqualTo(Date value) {
      addCriterion("FEC_CREACION =", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionNotEqualTo(Date value) {
      addCriterion("FEC_CREACION <>", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionGreaterThan(Date value) {
      addCriterion("FEC_CREACION >", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionGreaterThanOrEqualTo(Date value) {
      addCriterion("FEC_CREACION >=", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionLessThan(Date value) {
      addCriterion("FEC_CREACION <", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionLessThanOrEqualTo(Date value) {
      addCriterion("FEC_CREACION <=", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionIn(List<Date> values) {
      addCriterion("FEC_CREACION in", values, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionNotIn(List<Date> values) {
      addCriterion("FEC_CREACION not in", values, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionBetween(Date value1, Date value2) {
      addCriterion("FEC_CREACION between", value1, value2, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionNotBetween(Date value1, Date value2) {
      addCriterion("FEC_CREACION not between", value1, value2, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionIsNull() {
      addCriterion("USU_MODIFICACION is null");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionIsNotNull() {
      addCriterion("USU_MODIFICACION is not null");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionEqualTo(String value) {
      addCriterion("USU_MODIFICACION =", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionNotEqualTo(String value) {
      addCriterion("USU_MODIFICACION <>", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionGreaterThan(String value) {
      addCriterion("USU_MODIFICACION >", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionGreaterThanOrEqualTo(String value) {
      addCriterion("USU_MODIFICACION >=", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionLessThan(String value) {
      addCriterion("USU_MODIFICACION <", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionLessThanOrEqualTo(String value) {
      addCriterion("USU_MODIFICACION <=", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionIn(List<String> values) {
      addCriterion("USU_MODIFICACION in", values, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionNotIn(List<String> values) {
      addCriterion("USU_MODIFICACION not in", values, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionBetween(String value1, String value2) {
      addCriterion("USU_MODIFICACION between", value1, value2, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionNotBetween(String value1, String value2) {
      addCriterion("USU_MODIFICACION not between", value1, value2, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionIsNull() {
      addCriterion("FEC_MODIFICACION is null");
      return (Criteria) this;
    }

    public Criteria andFecModificacionIsNotNull() {
      addCriterion("FEC_MODIFICACION is not null");
      return (Criteria) this;
    }

    public Criteria andFecModificacionEqualTo(Date value) {
      addCriterion("FEC_MODIFICACION =", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionNotEqualTo(Date value) {
      addCriterion("FEC_MODIFICACION <>", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionGreaterThan(Date value) {
      addCriterion("FEC_MODIFICACION >", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionGreaterThanOrEqualTo(Date value) {
      addCriterion("FEC_MODIFICACION >=", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionLessThan(Date value) {
      addCriterion("FEC_MODIFICACION <", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionLessThanOrEqualTo(Date value) {
      addCriterion("FEC_MODIFICACION <=", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionIn(List<Date> values) {
      addCriterion("FEC_MODIFICACION in", values, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionNotIn(List<Date> values) {
      addCriterion("FEC_MODIFICACION not in", values, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionBetween(Date value1, Date value2) {
      addCriterion("FEC_MODIFICACION between", value1, value2, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionNotBetween(Date value1, Date value2) {
      addCriterion("FEC_MODIFICACION not between", value1, value2, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andMaxEdadIsNull() {
      addCriterion("MAX_EDAD is null");
      return (Criteria) this;
    }

    public Criteria andMaxEdadIsNotNull() {
      addCriterion("MAX_EDAD is not null");
      return (Criteria) this;
    }

    public Criteria andMaxEdadEqualTo(Integer value) {
      addCriterion("MAX_EDAD =", value, "maxEdad");
      return (Criteria) this;
    }

    public Criteria andMaxEdadNotEqualTo(Integer value) {
      addCriterion("MAX_EDAD <>", value, "maxEdad");
      return (Criteria) this;
    }

    public Criteria andMaxEdadGreaterThan(Integer value) {
      addCriterion("MAX_EDAD >", value, "maxEdad");
      return (Criteria) this;
    }

    public Criteria andMaxEdadGreaterThanOrEqualTo(Integer value) {
      addCriterion("MAX_EDAD >=", value, "maxEdad");
      return (Criteria) this;
    }

    public Criteria andMaxEdadLessThan(Integer value) {
      addCriterion("MAX_EDAD <", value, "maxEdad");
      return (Criteria) this;
    }

    public Criteria andMaxEdadLessThanOrEqualTo(Integer value) {
      addCriterion("MAX_EDAD <=", value, "maxEdad");
      return (Criteria) this;
    }

    public Criteria andMaxEdadIn(List<Integer> values) {
      addCriterion("MAX_EDAD in", values, "maxEdad");
      return (Criteria) this;
    }

    public Criteria andMaxEdadNotIn(List<Integer> values) {
      addCriterion("MAX_EDAD not in", values, "maxEdad");
      return (Criteria) this;
    }

    public Criteria andMaxEdadBetween(Integer value1, Integer value2) {
      addCriterion("MAX_EDAD between", value1, value2, "maxEdad");
      return (Criteria) this;
    }

    public Criteria andMaxEdadNotBetween(Integer value1, Integer value2) {
      addCriterion("MAX_EDAD not between", value1, value2, "maxEdad");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated do_not_delete_during_merge Thu May 29 11:28:39 COT 2014
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:28:39 COT 2014
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}