package com.cardif.satelite.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TlmkBaseSBExample implements Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.TLMK_BASE_SB
   *
   * @mbggenerated Thu Feb 06 11:39:53 COT 2014
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.TLMK_BASE_SB
   *
   * @mbggenerated Thu Feb 06 11:39:53 COT 2014
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.TLMK_BASE_SB
   *
   * @mbggenerated Thu Feb 06 11:39:53 COT 2014
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_SB
   *
   * @mbggenerated Thu Feb 06 11:39:53 COT 2014
   */
  public TlmkBaseSBExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_SB
   *
   * @mbggenerated Thu Feb 06 11:39:53 COT 2014
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_SB
   *
   * @mbggenerated Thu Feb 06 11:39:53 COT 2014
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_SB
   *
   * @mbggenerated Thu Feb 06 11:39:53 COT 2014
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_SB
   *
   * @mbggenerated Thu Feb 06 11:39:53 COT 2014
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_SB
   *
   * @mbggenerated Thu Feb 06 11:39:53 COT 2014
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_SB
   *
   * @mbggenerated Thu Feb 06 11:39:53 COT 2014
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_SB
   *
   * @mbggenerated Thu Feb 06 11:39:53 COT 2014
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_SB
   *
   * @mbggenerated Thu Feb 06 11:39:53 COT 2014
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_SB
   *
   * @mbggenerated Thu Feb 06 11:39:53 COT 2014
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_SB
   *
   * @mbggenerated Thu Feb 06 11:39:53 COT 2014
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.TLMK_BASE_SB
   *
   * @mbggenerated Thu Feb 06 11:39:53 COT 2014
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andPkIsNull() {
      addCriterion("PK is null");
      return (Criteria) this;
    }

    public Criteria andPkIsNotNull() {
      addCriterion("PK is not null");
      return (Criteria) this;
    }

    public Criteria andPkEqualTo(Long value) {
      addCriterion("PK =", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotEqualTo(Long value) {
      addCriterion("PK <>", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThan(Long value) {
      addCriterion("PK >", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThanOrEqualTo(Long value) {
      addCriterion("PK >=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThan(Long value) {
      addCriterion("PK <", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThanOrEqualTo(Long value) {
      addCriterion("PK <=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkIn(List<Long> values) {
      addCriterion("PK in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotIn(List<Long> values) {
      addCriterion("PK not in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkBetween(Long value1, Long value2) {
      addCriterion("PK between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotBetween(Long value1, Long value2) {
      addCriterion("PK not between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andCodBaseIsNull() {
      addCriterion("COD_BASE is null");
      return (Criteria) this;
    }

    public Criteria andCodBaseIsNotNull() {
      addCriterion("COD_BASE is not null");
      return (Criteria) this;
    }

    public Criteria andCodBaseEqualTo(Long value) {
      addCriterion("COD_BASE =", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseNotEqualTo(Long value) {
      addCriterion("COD_BASE <>", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseGreaterThan(Long value) {
      addCriterion("COD_BASE >", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseGreaterThanOrEqualTo(Long value) {
      addCriterion("COD_BASE >=", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseLessThan(Long value) {
      addCriterion("COD_BASE <", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseLessThanOrEqualTo(Long value) {
      addCriterion("COD_BASE <=", value, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseIn(List<Long> values) {
      addCriterion("COD_BASE in", values, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseNotIn(List<Long> values) {
      addCriterion("COD_BASE not in", values, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseBetween(Long value1, Long value2) {
      addCriterion("COD_BASE between", value1, value2, "codBase");
      return (Criteria) this;
    }

    public Criteria andCodBaseNotBetween(Long value1, Long value2) {
      addCriterion("COD_BASE not between", value1, value2, "codBase");
      return (Criteria) this;
    }

    public Criteria andClienteIdIsNull() {
      addCriterion("CLIENTE_ID is null");
      return (Criteria) this;
    }

    public Criteria andClienteIdIsNotNull() {
      addCriterion("CLIENTE_ID is not null");
      return (Criteria) this;
    }

    public Criteria andClienteIdEqualTo(String value) {
      addCriterion("CLIENTE_ID =", value, "clienteId");
      return (Criteria) this;
    }

    public Criteria andClienteIdNotEqualTo(String value) {
      addCriterion("CLIENTE_ID <>", value, "clienteId");
      return (Criteria) this;
    }

    public Criteria andClienteIdGreaterThan(String value) {
      addCriterion("CLIENTE_ID >", value, "clienteId");
      return (Criteria) this;
    }

    public Criteria andClienteIdGreaterThanOrEqualTo(String value) {
      addCriterion("CLIENTE_ID >=", value, "clienteId");
      return (Criteria) this;
    }

    public Criteria andClienteIdLessThan(String value) {
      addCriterion("CLIENTE_ID <", value, "clienteId");
      return (Criteria) this;
    }

    public Criteria andClienteIdLessThanOrEqualTo(String value) {
      addCriterion("CLIENTE_ID <=", value, "clienteId");
      return (Criteria) this;
    }

    public Criteria andClienteIdIn(List<String> values) {
      addCriterion("CLIENTE_ID in", values, "clienteId");
      return (Criteria) this;
    }

    public Criteria andClienteIdNotIn(List<String> values) {
      addCriterion("CLIENTE_ID not in", values, "clienteId");
      return (Criteria) this;
    }

    public Criteria andClienteIdBetween(String value1, String value2) {
      addCriterion("CLIENTE_ID between", value1, value2, "clienteId");
      return (Criteria) this;
    }

    public Criteria andClienteIdNotBetween(String value1, String value2) {
      addCriterion("CLIENTE_ID not between", value1, value2, "clienteId");
      return (Criteria) this;
    }

    public Criteria andNroDocIsNull() {
      addCriterion("NRO_DOC is null");
      return (Criteria) this;
    }

    public Criteria andNroDocIsNotNull() {
      addCriterion("NRO_DOC is not null");
      return (Criteria) this;
    }

    public Criteria andNroDocEqualTo(String value) {
      addCriterion("NRO_DOC =", value, "nroDoc");
      return (Criteria) this;
    }

    public Criteria andNroDocNotEqualTo(String value) {
      addCriterion("NRO_DOC <>", value, "nroDoc");
      return (Criteria) this;
    }

    public Criteria andNroDocGreaterThan(String value) {
      addCriterion("NRO_DOC >", value, "nroDoc");
      return (Criteria) this;
    }

    public Criteria andNroDocGreaterThanOrEqualTo(String value) {
      addCriterion("NRO_DOC >=", value, "nroDoc");
      return (Criteria) this;
    }

    public Criteria andNroDocLessThan(String value) {
      addCriterion("NRO_DOC <", value, "nroDoc");
      return (Criteria) this;
    }

    public Criteria andNroDocLessThanOrEqualTo(String value) {
      addCriterion("NRO_DOC <=", value, "nroDoc");
      return (Criteria) this;
    }

    public Criteria andNroDocIn(List<String> values) {
      addCriterion("NRO_DOC in", values, "nroDoc");
      return (Criteria) this;
    }

    public Criteria andNroDocNotIn(List<String> values) {
      addCriterion("NRO_DOC not in", values, "nroDoc");
      return (Criteria) this;
    }

    public Criteria andNroDocBetween(String value1, String value2) {
      addCriterion("NRO_DOC between", value1, value2, "nroDoc");
      return (Criteria) this;
    }

    public Criteria andNroDocNotBetween(String value1, String value2) {
      addCriterion("NRO_DOC not between", value1, value2, "nroDoc");
      return (Criteria) this;
    }

    public Criteria andTipoDocumentoIsNull() {
      addCriterion("TIPO_DOCUMENTO is null");
      return (Criteria) this;
    }

    public Criteria andTipoDocumentoIsNotNull() {
      addCriterion("TIPO_DOCUMENTO is not null");
      return (Criteria) this;
    }

    public Criteria andTipoDocumentoEqualTo(String value) {
      addCriterion("TIPO_DOCUMENTO =", value, "tipoDocumento");
      return (Criteria) this;
    }

    public Criteria andTipoDocumentoNotEqualTo(String value) {
      addCriterion("TIPO_DOCUMENTO <>", value, "tipoDocumento");
      return (Criteria) this;
    }

    public Criteria andTipoDocumentoGreaterThan(String value) {
      addCriterion("TIPO_DOCUMENTO >", value, "tipoDocumento");
      return (Criteria) this;
    }

    public Criteria andTipoDocumentoGreaterThanOrEqualTo(String value) {
      addCriterion("TIPO_DOCUMENTO >=", value, "tipoDocumento");
      return (Criteria) this;
    }

    public Criteria andTipoDocumentoLessThan(String value) {
      addCriterion("TIPO_DOCUMENTO <", value, "tipoDocumento");
      return (Criteria) this;
    }

    public Criteria andTipoDocumentoLessThanOrEqualTo(String value) {
      addCriterion("TIPO_DOCUMENTO <=", value, "tipoDocumento");
      return (Criteria) this;
    }

    public Criteria andTipoDocumentoIn(List<String> values) {
      addCriterion("TIPO_DOCUMENTO in", values, "tipoDocumento");
      return (Criteria) this;
    }

    public Criteria andTipoDocumentoNotIn(List<String> values) {
      addCriterion("TIPO_DOCUMENTO not in", values, "tipoDocumento");
      return (Criteria) this;
    }

    public Criteria andTipoDocumentoBetween(String value1, String value2) {
      addCriterion("TIPO_DOCUMENTO between", value1, value2, "tipoDocumento");
      return (Criteria) this;
    }

    public Criteria andTipoDocumentoNotBetween(String value1, String value2) {
      addCriterion("TIPO_DOCUMENTO not between", value1, value2, "tipoDocumento");
      return (Criteria) this;
    }

    public Criteria andApellidoPaternoIsNull() {
      addCriterion("APELLIDO_PATERNO is null");
      return (Criteria) this;
    }

    public Criteria andApellidoPaternoIsNotNull() {
      addCriterion("APELLIDO_PATERNO is not null");
      return (Criteria) this;
    }

    public Criteria andApellidoPaternoEqualTo(String value) {
      addCriterion("APELLIDO_PATERNO =", value, "apellidoPaterno");
      return (Criteria) this;
    }

    public Criteria andApellidoPaternoNotEqualTo(String value) {
      addCriterion("APELLIDO_PATERNO <>", value, "apellidoPaterno");
      return (Criteria) this;
    }

    public Criteria andApellidoPaternoGreaterThan(String value) {
      addCriterion("APELLIDO_PATERNO >", value, "apellidoPaterno");
      return (Criteria) this;
    }

    public Criteria andApellidoPaternoGreaterThanOrEqualTo(String value) {
      addCriterion("APELLIDO_PATERNO >=", value, "apellidoPaterno");
      return (Criteria) this;
    }

    public Criteria andApellidoPaternoLessThan(String value) {
      addCriterion("APELLIDO_PATERNO <", value, "apellidoPaterno");
      return (Criteria) this;
    }

    public Criteria andApellidoPaternoLessThanOrEqualTo(String value) {
      addCriterion("APELLIDO_PATERNO <=", value, "apellidoPaterno");
      return (Criteria) this;
    }

    public Criteria andApellidoPaternoIn(List<String> values) {
      addCriterion("APELLIDO_PATERNO in", values, "apellidoPaterno");
      return (Criteria) this;
    }

    public Criteria andApellidoPaternoNotIn(List<String> values) {
      addCriterion("APELLIDO_PATERNO not in", values, "apellidoPaterno");
      return (Criteria) this;
    }

    public Criteria andApellidoPaternoBetween(String value1, String value2) {
      addCriterion("APELLIDO_PATERNO between", value1, value2, "apellidoPaterno");
      return (Criteria) this;
    }

    public Criteria andApellidoPaternoNotBetween(String value1, String value2) {
      addCriterion("APELLIDO_PATERNO not between", value1, value2, "apellidoPaterno");
      return (Criteria) this;
    }

    public Criteria andApellidoMaternoIsNull() {
      addCriterion("APELLIDO_MATERNO is null");
      return (Criteria) this;
    }

    public Criteria andApellidoMaternoIsNotNull() {
      addCriterion("APELLIDO_MATERNO is not null");
      return (Criteria) this;
    }

    public Criteria andApellidoMaternoEqualTo(String value) {
      addCriterion("APELLIDO_MATERNO =", value, "apellidoMaterno");
      return (Criteria) this;
    }

    public Criteria andApellidoMaternoNotEqualTo(String value) {
      addCriterion("APELLIDO_MATERNO <>", value, "apellidoMaterno");
      return (Criteria) this;
    }

    public Criteria andApellidoMaternoGreaterThan(String value) {
      addCriterion("APELLIDO_MATERNO >", value, "apellidoMaterno");
      return (Criteria) this;
    }

    public Criteria andApellidoMaternoGreaterThanOrEqualTo(String value) {
      addCriterion("APELLIDO_MATERNO >=", value, "apellidoMaterno");
      return (Criteria) this;
    }

    public Criteria andApellidoMaternoLessThan(String value) {
      addCriterion("APELLIDO_MATERNO <", value, "apellidoMaterno");
      return (Criteria) this;
    }

    public Criteria andApellidoMaternoLessThanOrEqualTo(String value) {
      addCriterion("APELLIDO_MATERNO <=", value, "apellidoMaterno");
      return (Criteria) this;
    }

    public Criteria andApellidoMaternoIn(List<String> values) {
      addCriterion("APELLIDO_MATERNO in", values, "apellidoMaterno");
      return (Criteria) this;
    }

    public Criteria andApellidoMaternoNotIn(List<String> values) {
      addCriterion("APELLIDO_MATERNO not in", values, "apellidoMaterno");
      return (Criteria) this;
    }

    public Criteria andApellidoMaternoBetween(String value1, String value2) {
      addCriterion("APELLIDO_MATERNO between", value1, value2, "apellidoMaterno");
      return (Criteria) this;
    }

    public Criteria andApellidoMaternoNotBetween(String value1, String value2) {
      addCriterion("APELLIDO_MATERNO not between", value1, value2, "apellidoMaterno");
      return (Criteria) this;
    }

    public Criteria andPrimerNombreIsNull() {
      addCriterion("PRIMER_NOMBRE is null");
      return (Criteria) this;
    }

    public Criteria andPrimerNombreIsNotNull() {
      addCriterion("PRIMER_NOMBRE is not null");
      return (Criteria) this;
    }

    public Criteria andPrimerNombreEqualTo(String value) {
      addCriterion("PRIMER_NOMBRE =", value, "primerNombre");
      return (Criteria) this;
    }

    public Criteria andPrimerNombreNotEqualTo(String value) {
      addCriterion("PRIMER_NOMBRE <>", value, "primerNombre");
      return (Criteria) this;
    }

    public Criteria andPrimerNombreGreaterThan(String value) {
      addCriterion("PRIMER_NOMBRE >", value, "primerNombre");
      return (Criteria) this;
    }

    public Criteria andPrimerNombreGreaterThanOrEqualTo(String value) {
      addCriterion("PRIMER_NOMBRE >=", value, "primerNombre");
      return (Criteria) this;
    }

    public Criteria andPrimerNombreLessThan(String value) {
      addCriterion("PRIMER_NOMBRE <", value, "primerNombre");
      return (Criteria) this;
    }

    public Criteria andPrimerNombreLessThanOrEqualTo(String value) {
      addCriterion("PRIMER_NOMBRE <=", value, "primerNombre");
      return (Criteria) this;
    }

    public Criteria andPrimerNombreIn(List<String> values) {
      addCriterion("PRIMER_NOMBRE in", values, "primerNombre");
      return (Criteria) this;
    }

    public Criteria andPrimerNombreNotIn(List<String> values) {
      addCriterion("PRIMER_NOMBRE not in", values, "primerNombre");
      return (Criteria) this;
    }

    public Criteria andPrimerNombreBetween(String value1, String value2) {
      addCriterion("PRIMER_NOMBRE between", value1, value2, "primerNombre");
      return (Criteria) this;
    }

    public Criteria andPrimerNombreNotBetween(String value1, String value2) {
      addCriterion("PRIMER_NOMBRE not between", value1, value2, "primerNombre");
      return (Criteria) this;
    }

    public Criteria andSegundoNombreIsNull() {
      addCriterion("SEGUNDO_NOMBRE is null");
      return (Criteria) this;
    }

    public Criteria andSegundoNombreIsNotNull() {
      addCriterion("SEGUNDO_NOMBRE is not null");
      return (Criteria) this;
    }

    public Criteria andSegundoNombreEqualTo(String value) {
      addCriterion("SEGUNDO_NOMBRE =", value, "segundoNombre");
      return (Criteria) this;
    }

    public Criteria andSegundoNombreNotEqualTo(String value) {
      addCriterion("SEGUNDO_NOMBRE <>", value, "segundoNombre");
      return (Criteria) this;
    }

    public Criteria andSegundoNombreGreaterThan(String value) {
      addCriterion("SEGUNDO_NOMBRE >", value, "segundoNombre");
      return (Criteria) this;
    }

    public Criteria andSegundoNombreGreaterThanOrEqualTo(String value) {
      addCriterion("SEGUNDO_NOMBRE >=", value, "segundoNombre");
      return (Criteria) this;
    }

    public Criteria andSegundoNombreLessThan(String value) {
      addCriterion("SEGUNDO_NOMBRE <", value, "segundoNombre");
      return (Criteria) this;
    }

    public Criteria andSegundoNombreLessThanOrEqualTo(String value) {
      addCriterion("SEGUNDO_NOMBRE <=", value, "segundoNombre");
      return (Criteria) this;
    }

    public Criteria andSegundoNombreIn(List<String> values) {
      addCriterion("SEGUNDO_NOMBRE in", values, "segundoNombre");
      return (Criteria) this;
    }

    public Criteria andSegundoNombreNotIn(List<String> values) {
      addCriterion("SEGUNDO_NOMBRE not in", values, "segundoNombre");
      return (Criteria) this;
    }

    public Criteria andSegundoNombreBetween(String value1, String value2) {
      addCriterion("SEGUNDO_NOMBRE between", value1, value2, "segundoNombre");
      return (Criteria) this;
    }

    public Criteria andSegundoNombreNotBetween(String value1, String value2) {
      addCriterion("SEGUNDO_NOMBRE not between", value1, value2, "segundoNombre");
      return (Criteria) this;
    }

    public Criteria andFechaNacimientoIsNull() {
      addCriterion("FECHA_NACIMIENTO is null");
      return (Criteria) this;
    }

    public Criteria andFechaNacimientoIsNotNull() {
      addCriterion("FECHA_NACIMIENTO is not null");
      return (Criteria) this;
    }

    public Criteria andFechaNacimientoEqualTo(Date value) {
      addCriterion("FECHA_NACIMIENTO =", value, "fechaNacimiento");
      return (Criteria) this;
    }

    public Criteria andFechaNacimientoNotEqualTo(Date value) {
      addCriterion("FECHA_NACIMIENTO <>", value, "fechaNacimiento");
      return (Criteria) this;
    }

    public Criteria andFechaNacimientoGreaterThan(Date value) {
      addCriterion("FECHA_NACIMIENTO >", value, "fechaNacimiento");
      return (Criteria) this;
    }

    public Criteria andFechaNacimientoGreaterThanOrEqualTo(Date value) {
      addCriterion("FECHA_NACIMIENTO >=", value, "fechaNacimiento");
      return (Criteria) this;
    }

    public Criteria andFechaNacimientoLessThan(Date value) {
      addCriterion("FECHA_NACIMIENTO <", value, "fechaNacimiento");
      return (Criteria) this;
    }

    public Criteria andFechaNacimientoLessThanOrEqualTo(Date value) {
      addCriterion("FECHA_NACIMIENTO <=", value, "fechaNacimiento");
      return (Criteria) this;
    }

    public Criteria andFechaNacimientoIn(List<Date> values) {
      addCriterion("FECHA_NACIMIENTO in", values, "fechaNacimiento");
      return (Criteria) this;
    }

    public Criteria andFechaNacimientoNotIn(List<Date> values) {
      addCriterion("FECHA_NACIMIENTO not in", values, "fechaNacimiento");
      return (Criteria) this;
    }

    public Criteria andFechaNacimientoBetween(Date value1, Date value2) {
      addCriterion("FECHA_NACIMIENTO between", value1, value2, "fechaNacimiento");
      return (Criteria) this;
    }

    public Criteria andFechaNacimientoNotBetween(Date value1, Date value2) {
      addCriterion("FECHA_NACIMIENTO not between", value1, value2, "fechaNacimiento");
      return (Criteria) this;
    }

    public Criteria andEdadIsNull() {
      addCriterion("EDAD is null");
      return (Criteria) this;
    }

    public Criteria andEdadIsNotNull() {
      addCriterion("EDAD is not null");
      return (Criteria) this;
    }

    public Criteria andEdadEqualTo(String value) {
      addCriterion("EDAD =", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadNotEqualTo(String value) {
      addCriterion("EDAD <>", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadGreaterThan(String value) {
      addCriterion("EDAD >", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadGreaterThanOrEqualTo(String value) {
      addCriterion("EDAD >=", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadLessThan(String value) {
      addCriterion("EDAD <", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadLessThanOrEqualTo(String value) {
      addCriterion("EDAD <=", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadIn(List<String> values) {
      addCriterion("EDAD in", values, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadNotIn(List<String> values) {
      addCriterion("EDAD not in", values, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadBetween(String value1, String value2) {
      addCriterion("EDAD between", value1, value2, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadNotBetween(String value1, String value2) {
      addCriterion("EDAD not between", value1, value2, "edad");
      return (Criteria) this;
    }

    public Criteria andSexoIsNull() {
      addCriterion("SEXO is null");
      return (Criteria) this;
    }

    public Criteria andSexoIsNotNull() {
      addCriterion("SEXO is not null");
      return (Criteria) this;
    }

    public Criteria andSexoEqualTo(String value) {
      addCriterion("SEXO =", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoNotEqualTo(String value) {
      addCriterion("SEXO <>", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoGreaterThan(String value) {
      addCriterion("SEXO >", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoGreaterThanOrEqualTo(String value) {
      addCriterion("SEXO >=", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoLessThan(String value) {
      addCriterion("SEXO <", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoLessThanOrEqualTo(String value) {
      addCriterion("SEXO <=", value, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoIn(List<String> values) {
      addCriterion("SEXO in", values, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoNotIn(List<String> values) {
      addCriterion("SEXO not in", values, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoBetween(String value1, String value2) {
      addCriterion("SEXO between", value1, value2, "sexo");
      return (Criteria) this;
    }

    public Criteria andSexoNotBetween(String value1, String value2) {
      addCriterion("SEXO not between", value1, value2, "sexo");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilIsNull() {
      addCriterion("ESTADO_CIVIL is null");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilIsNotNull() {
      addCriterion("ESTADO_CIVIL is not null");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilEqualTo(String value) {
      addCriterion("ESTADO_CIVIL =", value, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilNotEqualTo(String value) {
      addCriterion("ESTADO_CIVIL <>", value, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilGreaterThan(String value) {
      addCriterion("ESTADO_CIVIL >", value, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilGreaterThanOrEqualTo(String value) {
      addCriterion("ESTADO_CIVIL >=", value, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilLessThan(String value) {
      addCriterion("ESTADO_CIVIL <", value, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilLessThanOrEqualTo(String value) {
      addCriterion("ESTADO_CIVIL <=", value, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilIn(List<String> values) {
      addCriterion("ESTADO_CIVIL in", values, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilNotIn(List<String> values) {
      addCriterion("ESTADO_CIVIL not in", values, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilBetween(String value1, String value2) {
      addCriterion("ESTADO_CIVIL between", value1, value2, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilNotBetween(String value1, String value2) {
      addCriterion("ESTADO_CIVIL not between", value1, value2, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andNacionalidadIsNull() {
      addCriterion("NACIONALIDAD is null");
      return (Criteria) this;
    }

    public Criteria andNacionalidadIsNotNull() {
      addCriterion("NACIONALIDAD is not null");
      return (Criteria) this;
    }

    public Criteria andNacionalidadEqualTo(String value) {
      addCriterion("NACIONALIDAD =", value, "nacionalidad");
      return (Criteria) this;
    }

    public Criteria andNacionalidadNotEqualTo(String value) {
      addCriterion("NACIONALIDAD <>", value, "nacionalidad");
      return (Criteria) this;
    }

    public Criteria andNacionalidadGreaterThan(String value) {
      addCriterion("NACIONALIDAD >", value, "nacionalidad");
      return (Criteria) this;
    }

    public Criteria andNacionalidadGreaterThanOrEqualTo(String value) {
      addCriterion("NACIONALIDAD >=", value, "nacionalidad");
      return (Criteria) this;
    }

    public Criteria andNacionalidadLessThan(String value) {
      addCriterion("NACIONALIDAD <", value, "nacionalidad");
      return (Criteria) this;
    }

    public Criteria andNacionalidadLessThanOrEqualTo(String value) {
      addCriterion("NACIONALIDAD <=", value, "nacionalidad");
      return (Criteria) this;
    }

    public Criteria andNacionalidadIn(List<String> values) {
      addCriterion("NACIONALIDAD in", values, "nacionalidad");
      return (Criteria) this;
    }

    public Criteria andNacionalidadNotIn(List<String> values) {
      addCriterion("NACIONALIDAD not in", values, "nacionalidad");
      return (Criteria) this;
    }

    public Criteria andNacionalidadBetween(String value1, String value2) {
      addCriterion("NACIONALIDAD between", value1, value2, "nacionalidad");
      return (Criteria) this;
    }

    public Criteria andNacionalidadNotBetween(String value1, String value2) {
      addCriterion("NACIONALIDAD not between", value1, value2, "nacionalidad");
      return (Criteria) this;
    }

    public Criteria andDireccionIsNull() {
      addCriterion("DIRECCION is null");
      return (Criteria) this;
    }

    public Criteria andDireccionIsNotNull() {
      addCriterion("DIRECCION is not null");
      return (Criteria) this;
    }

    public Criteria andDireccionEqualTo(String value) {
      addCriterion("DIRECCION =", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionNotEqualTo(String value) {
      addCriterion("DIRECCION <>", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionGreaterThan(String value) {
      addCriterion("DIRECCION >", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionGreaterThanOrEqualTo(String value) {
      addCriterion("DIRECCION >=", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionLessThan(String value) {
      addCriterion("DIRECCION <", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionLessThanOrEqualTo(String value) {
      addCriterion("DIRECCION <=", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionIn(List<String> values) {
      addCriterion("DIRECCION in", values, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionNotIn(List<String> values) {
      addCriterion("DIRECCION not in", values, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionBetween(String value1, String value2) {
      addCriterion("DIRECCION between", value1, value2, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionNotBetween(String value1, String value2) {
      addCriterion("DIRECCION not between", value1, value2, "direccion");
      return (Criteria) this;
    }

    public Criteria andDepartamentoIsNull() {
      addCriterion("DEPARTAMENTO is null");
      return (Criteria) this;
    }

    public Criteria andDepartamentoIsNotNull() {
      addCriterion("DEPARTAMENTO is not null");
      return (Criteria) this;
    }

    public Criteria andDepartamentoEqualTo(String value) {
      addCriterion("DEPARTAMENTO =", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoNotEqualTo(String value) {
      addCriterion("DEPARTAMENTO <>", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoGreaterThan(String value) {
      addCriterion("DEPARTAMENTO >", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoGreaterThanOrEqualTo(String value) {
      addCriterion("DEPARTAMENTO >=", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoLessThan(String value) {
      addCriterion("DEPARTAMENTO <", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoLessThanOrEqualTo(String value) {
      addCriterion("DEPARTAMENTO <=", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoIn(List<String> values) {
      addCriterion("DEPARTAMENTO in", values, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoNotIn(List<String> values) {
      addCriterion("DEPARTAMENTO not in", values, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoBetween(String value1, String value2) {
      addCriterion("DEPARTAMENTO between", value1, value2, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoNotBetween(String value1, String value2) {
      addCriterion("DEPARTAMENTO not between", value1, value2, "departamento");
      return (Criteria) this;
    }

    public Criteria andProvinciaIsNull() {
      addCriterion("PROVINCIA is null");
      return (Criteria) this;
    }

    public Criteria andProvinciaIsNotNull() {
      addCriterion("PROVINCIA is not null");
      return (Criteria) this;
    }

    public Criteria andProvinciaEqualTo(String value) {
      addCriterion("PROVINCIA =", value, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaNotEqualTo(String value) {
      addCriterion("PROVINCIA <>", value, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaGreaterThan(String value) {
      addCriterion("PROVINCIA >", value, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaGreaterThanOrEqualTo(String value) {
      addCriterion("PROVINCIA >=", value, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaLessThan(String value) {
      addCriterion("PROVINCIA <", value, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaLessThanOrEqualTo(String value) {
      addCriterion("PROVINCIA <=", value, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaIn(List<String> values) {
      addCriterion("PROVINCIA in", values, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaNotIn(List<String> values) {
      addCriterion("PROVINCIA not in", values, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaBetween(String value1, String value2) {
      addCriterion("PROVINCIA between", value1, value2, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaNotBetween(String value1, String value2) {
      addCriterion("PROVINCIA not between", value1, value2, "provincia");
      return (Criteria) this;
    }

    public Criteria andDistritoIsNull() {
      addCriterion("DISTRITO is null");
      return (Criteria) this;
    }

    public Criteria andDistritoIsNotNull() {
      addCriterion("DISTRITO is not null");
      return (Criteria) this;
    }

    public Criteria andDistritoEqualTo(String value) {
      addCriterion("DISTRITO =", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoNotEqualTo(String value) {
      addCriterion("DISTRITO <>", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoGreaterThan(String value) {
      addCriterion("DISTRITO >", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoGreaterThanOrEqualTo(String value) {
      addCriterion("DISTRITO >=", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoLessThan(String value) {
      addCriterion("DISTRITO <", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoLessThanOrEqualTo(String value) {
      addCriterion("DISTRITO <=", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoIn(List<String> values) {
      addCriterion("DISTRITO in", values, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoNotIn(List<String> values) {
      addCriterion("DISTRITO not in", values, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoBetween(String value1, String value2) {
      addCriterion("DISTRITO between", value1, value2, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoNotBetween(String value1, String value2) {
      addCriterion("DISTRITO not between", value1, value2, "distrito");
      return (Criteria) this;
    }

    public Criteria andUbigeoIsNull() {
      addCriterion("UBIGEO is null");
      return (Criteria) this;
    }

    public Criteria andUbigeoIsNotNull() {
      addCriterion("UBIGEO is not null");
      return (Criteria) this;
    }

    public Criteria andUbigeoEqualTo(String value) {
      addCriterion("UBIGEO =", value, "ubigeo");
      return (Criteria) this;
    }

    public Criteria andUbigeoNotEqualTo(String value) {
      addCriterion("UBIGEO <>", value, "ubigeo");
      return (Criteria) this;
    }

    public Criteria andUbigeoGreaterThan(String value) {
      addCriterion("UBIGEO >", value, "ubigeo");
      return (Criteria) this;
    }

    public Criteria andUbigeoGreaterThanOrEqualTo(String value) {
      addCriterion("UBIGEO >=", value, "ubigeo");
      return (Criteria) this;
    }

    public Criteria andUbigeoLessThan(String value) {
      addCriterion("UBIGEO <", value, "ubigeo");
      return (Criteria) this;
    }

    public Criteria andUbigeoLessThanOrEqualTo(String value) {
      addCriterion("UBIGEO <=", value, "ubigeo");
      return (Criteria) this;
    }

    public Criteria andUbigeoIn(List<String> values) {
      addCriterion("UBIGEO in", values, "ubigeo");
      return (Criteria) this;
    }

    public Criteria andUbigeoNotIn(List<String> values) {
      addCriterion("UBIGEO not in", values, "ubigeo");
      return (Criteria) this;
    }

    public Criteria andUbigeoBetween(String value1, String value2) {
      addCriterion("UBIGEO between", value1, value2, "ubigeo");
      return (Criteria) this;
    }

    public Criteria andUbigeoNotBetween(String value1, String value2) {
      addCriterion("UBIGEO not between", value1, value2, "ubigeo");
      return (Criteria) this;
    }

    public Criteria andTelfDomicilioIsNull() {
      addCriterion("TELF_DOMICILIO is null");
      return (Criteria) this;
    }

    public Criteria andTelfDomicilioIsNotNull() {
      addCriterion("TELF_DOMICILIO is not null");
      return (Criteria) this;
    }

    public Criteria andTelfDomicilioEqualTo(String value) {
      addCriterion("TELF_DOMICILIO =", value, "telfDomicilio");
      return (Criteria) this;
    }

    public Criteria andTelfDomicilioNotEqualTo(String value) {
      addCriterion("TELF_DOMICILIO <>", value, "telfDomicilio");
      return (Criteria) this;
    }

    public Criteria andTelfDomicilioGreaterThan(String value) {
      addCriterion("TELF_DOMICILIO >", value, "telfDomicilio");
      return (Criteria) this;
    }

    public Criteria andTelfDomicilioGreaterThanOrEqualTo(String value) {
      addCriterion("TELF_DOMICILIO >=", value, "telfDomicilio");
      return (Criteria) this;
    }

    public Criteria andTelfDomicilioLessThan(String value) {
      addCriterion("TELF_DOMICILIO <", value, "telfDomicilio");
      return (Criteria) this;
    }

    public Criteria andTelfDomicilioLessThanOrEqualTo(String value) {
      addCriterion("TELF_DOMICILIO <=", value, "telfDomicilio");
      return (Criteria) this;
    }

    public Criteria andTelfDomicilioIn(List<String> values) {
      addCriterion("TELF_DOMICILIO in", values, "telfDomicilio");
      return (Criteria) this;
    }

    public Criteria andTelfDomicilioNotIn(List<String> values) {
      addCriterion("TELF_DOMICILIO not in", values, "telfDomicilio");
      return (Criteria) this;
    }

    public Criteria andTelfDomicilioBetween(String value1, String value2) {
      addCriterion("TELF_DOMICILIO between", value1, value2, "telfDomicilio");
      return (Criteria) this;
    }

    public Criteria andTelfDomicilioNotBetween(String value1, String value2) {
      addCriterion("TELF_DOMICILIO not between", value1, value2, "telfDomicilio");
      return (Criteria) this;
    }

    public Criteria andTelefCorrespondenciaIsNull() {
      addCriterion("TELEF_CORRESPONDENCIA is null");
      return (Criteria) this;
    }

    public Criteria andTelefCorrespondenciaIsNotNull() {
      addCriterion("TELEF_CORRESPONDENCIA is not null");
      return (Criteria) this;
    }

    public Criteria andTelefCorrespondenciaEqualTo(String value) {
      addCriterion("TELEF_CORRESPONDENCIA =", value, "telefCorrespondencia");
      return (Criteria) this;
    }

    public Criteria andTelefCorrespondenciaNotEqualTo(String value) {
      addCriterion("TELEF_CORRESPONDENCIA <>", value, "telefCorrespondencia");
      return (Criteria) this;
    }

    public Criteria andTelefCorrespondenciaGreaterThan(String value) {
      addCriterion("TELEF_CORRESPONDENCIA >", value, "telefCorrespondencia");
      return (Criteria) this;
    }

    public Criteria andTelefCorrespondenciaGreaterThanOrEqualTo(String value) {
      addCriterion("TELEF_CORRESPONDENCIA >=", value, "telefCorrespondencia");
      return (Criteria) this;
    }

    public Criteria andTelefCorrespondenciaLessThan(String value) {
      addCriterion("TELEF_CORRESPONDENCIA <", value, "telefCorrespondencia");
      return (Criteria) this;
    }

    public Criteria andTelefCorrespondenciaLessThanOrEqualTo(String value) {
      addCriterion("TELEF_CORRESPONDENCIA <=", value, "telefCorrespondencia");
      return (Criteria) this;
    }

    public Criteria andTelefCorrespondenciaIn(List<String> values) {
      addCriterion("TELEF_CORRESPONDENCIA in", values, "telefCorrespondencia");
      return (Criteria) this;
    }

    public Criteria andTelefCorrespondenciaNotIn(List<String> values) {
      addCriterion("TELEF_CORRESPONDENCIA not in", values, "telefCorrespondencia");
      return (Criteria) this;
    }

    public Criteria andTelefCorrespondenciaBetween(String value1, String value2) {
      addCriterion("TELEF_CORRESPONDENCIA between", value1, value2, "telefCorrespondencia");
      return (Criteria) this;
    }

    public Criteria andTelefCorrespondenciaNotBetween(String value1, String value2) {
      addCriterion("TELEF_CORRESPONDENCIA not between", value1, value2, "telefCorrespondencia");
      return (Criteria) this;
    }

    public Criteria andTelfVisaIsNull() {
      addCriterion("TELF_VISA is null");
      return (Criteria) this;
    }

    public Criteria andTelfVisaIsNotNull() {
      addCriterion("TELF_VISA is not null");
      return (Criteria) this;
    }

    public Criteria andTelfVisaEqualTo(String value) {
      addCriterion("TELF_VISA =", value, "telfVisa");
      return (Criteria) this;
    }

    public Criteria andTelfVisaNotEqualTo(String value) {
      addCriterion("TELF_VISA <>", value, "telfVisa");
      return (Criteria) this;
    }

    public Criteria andTelfVisaGreaterThan(String value) {
      addCriterion("TELF_VISA >", value, "telfVisa");
      return (Criteria) this;
    }

    public Criteria andTelfVisaGreaterThanOrEqualTo(String value) {
      addCriterion("TELF_VISA >=", value, "telfVisa");
      return (Criteria) this;
    }

    public Criteria andTelfVisaLessThan(String value) {
      addCriterion("TELF_VISA <", value, "telfVisa");
      return (Criteria) this;
    }

    public Criteria andTelfVisaLessThanOrEqualTo(String value) {
      addCriterion("TELF_VISA <=", value, "telfVisa");
      return (Criteria) this;
    }

    public Criteria andTelfVisaIn(List<String> values) {
      addCriterion("TELF_VISA in", values, "telfVisa");
      return (Criteria) this;
    }

    public Criteria andTelfVisaNotIn(List<String> values) {
      addCriterion("TELF_VISA not in", values, "telfVisa");
      return (Criteria) this;
    }

    public Criteria andTelfVisaBetween(String value1, String value2) {
      addCriterion("TELF_VISA between", value1, value2, "telfVisa");
      return (Criteria) this;
    }

    public Criteria andTelfVisaNotBetween(String value1, String value2) {
      addCriterion("TELF_VISA not between", value1, value2, "telfVisa");
      return (Criteria) this;
    }

    public Criteria andTelfCasaIsNull() {
      addCriterion("TELF_CASA is null");
      return (Criteria) this;
    }

    public Criteria andTelfCasaIsNotNull() {
      addCriterion("TELF_CASA is not null");
      return (Criteria) this;
    }

    public Criteria andTelfCasaEqualTo(String value) {
      addCriterion("TELF_CASA =", value, "telfCasa");
      return (Criteria) this;
    }

    public Criteria andTelfCasaNotEqualTo(String value) {
      addCriterion("TELF_CASA <>", value, "telfCasa");
      return (Criteria) this;
    }

    public Criteria andTelfCasaGreaterThan(String value) {
      addCriterion("TELF_CASA >", value, "telfCasa");
      return (Criteria) this;
    }

    public Criteria andTelfCasaGreaterThanOrEqualTo(String value) {
      addCriterion("TELF_CASA >=", value, "telfCasa");
      return (Criteria) this;
    }

    public Criteria andTelfCasaLessThan(String value) {
      addCriterion("TELF_CASA <", value, "telfCasa");
      return (Criteria) this;
    }

    public Criteria andTelfCasaLessThanOrEqualTo(String value) {
      addCriterion("TELF_CASA <=", value, "telfCasa");
      return (Criteria) this;
    }

    public Criteria andTelfCasaIn(List<String> values) {
      addCriterion("TELF_CASA in", values, "telfCasa");
      return (Criteria) this;
    }

    public Criteria andTelfCasaNotIn(List<String> values) {
      addCriterion("TELF_CASA not in", values, "telfCasa");
      return (Criteria) this;
    }

    public Criteria andTelfCasaBetween(String value1, String value2) {
      addCriterion("TELF_CASA between", value1, value2, "telfCasa");
      return (Criteria) this;
    }

    public Criteria andTelfCasaNotBetween(String value1, String value2) {
      addCriterion("TELF_CASA not between", value1, value2, "telfCasa");
      return (Criteria) this;
    }

    public Criteria andTelfRetailIsNull() {
      addCriterion("TELF_RETAIL is null");
      return (Criteria) this;
    }

    public Criteria andTelfRetailIsNotNull() {
      addCriterion("TELF_RETAIL is not null");
      return (Criteria) this;
    }

    public Criteria andTelfRetailEqualTo(String value) {
      addCriterion("TELF_RETAIL =", value, "telfRetail");
      return (Criteria) this;
    }

    public Criteria andTelfRetailNotEqualTo(String value) {
      addCriterion("TELF_RETAIL <>", value, "telfRetail");
      return (Criteria) this;
    }

    public Criteria andTelfRetailGreaterThan(String value) {
      addCriterion("TELF_RETAIL >", value, "telfRetail");
      return (Criteria) this;
    }

    public Criteria andTelfRetailGreaterThanOrEqualTo(String value) {
      addCriterion("TELF_RETAIL >=", value, "telfRetail");
      return (Criteria) this;
    }

    public Criteria andTelfRetailLessThan(String value) {
      addCriterion("TELF_RETAIL <", value, "telfRetail");
      return (Criteria) this;
    }

    public Criteria andTelfRetailLessThanOrEqualTo(String value) {
      addCriterion("TELF_RETAIL <=", value, "telfRetail");
      return (Criteria) this;
    }

    public Criteria andTelfRetailIn(List<String> values) {
      addCriterion("TELF_RETAIL in", values, "telfRetail");
      return (Criteria) this;
    }

    public Criteria andTelfRetailNotIn(List<String> values) {
      addCriterion("TELF_RETAIL not in", values, "telfRetail");
      return (Criteria) this;
    }

    public Criteria andTelfRetailBetween(String value1, String value2) {
      addCriterion("TELF_RETAIL between", value1, value2, "telfRetail");
      return (Criteria) this;
    }

    public Criteria andTelfRetailNotBetween(String value1, String value2) {
      addCriterion("TELF_RETAIL not between", value1, value2, "telfRetail");
      return (Criteria) this;
    }

    public Criteria andTelfLimaIsNull() {
      addCriterion("TELF_LIMA is null");
      return (Criteria) this;
    }

    public Criteria andTelfLimaIsNotNull() {
      addCriterion("TELF_LIMA is not null");
      return (Criteria) this;
    }

    public Criteria andTelfLimaEqualTo(String value) {
      addCriterion("TELF_LIMA =", value, "telfLima");
      return (Criteria) this;
    }

    public Criteria andTelfLimaNotEqualTo(String value) {
      addCriterion("TELF_LIMA <>", value, "telfLima");
      return (Criteria) this;
    }

    public Criteria andTelfLimaGreaterThan(String value) {
      addCriterion("TELF_LIMA >", value, "telfLima");
      return (Criteria) this;
    }

    public Criteria andTelfLimaGreaterThanOrEqualTo(String value) {
      addCriterion("TELF_LIMA >=", value, "telfLima");
      return (Criteria) this;
    }

    public Criteria andTelfLimaLessThan(String value) {
      addCriterion("TELF_LIMA <", value, "telfLima");
      return (Criteria) this;
    }

    public Criteria andTelfLimaLessThanOrEqualTo(String value) {
      addCriterion("TELF_LIMA <=", value, "telfLima");
      return (Criteria) this;
    }

    public Criteria andTelfLimaIn(List<String> values) {
      addCriterion("TELF_LIMA in", values, "telfLima");
      return (Criteria) this;
    }

    public Criteria andTelfLimaNotIn(List<String> values) {
      addCriterion("TELF_LIMA not in", values, "telfLima");
      return (Criteria) this;
    }

    public Criteria andTelfLimaBetween(String value1, String value2) {
      addCriterion("TELF_LIMA between", value1, value2, "telfLima");
      return (Criteria) this;
    }

    public Criteria andTelfLimaNotBetween(String value1, String value2) {
      addCriterion("TELF_LIMA not between", value1, value2, "telfLima");
      return (Criteria) this;
    }

    public Criteria andTelfProvinciaIsNull() {
      addCriterion("TELF_PROVINCIA is null");
      return (Criteria) this;
    }

    public Criteria andTelfProvinciaIsNotNull() {
      addCriterion("TELF_PROVINCIA is not null");
      return (Criteria) this;
    }

    public Criteria andTelfProvinciaEqualTo(String value) {
      addCriterion("TELF_PROVINCIA =", value, "telfProvincia");
      return (Criteria) this;
    }

    public Criteria andTelfProvinciaNotEqualTo(String value) {
      addCriterion("TELF_PROVINCIA <>", value, "telfProvincia");
      return (Criteria) this;
    }

    public Criteria andTelfProvinciaGreaterThan(String value) {
      addCriterion("TELF_PROVINCIA >", value, "telfProvincia");
      return (Criteria) this;
    }

    public Criteria andTelfProvinciaGreaterThanOrEqualTo(String value) {
      addCriterion("TELF_PROVINCIA >=", value, "telfProvincia");
      return (Criteria) this;
    }

    public Criteria andTelfProvinciaLessThan(String value) {
      addCriterion("TELF_PROVINCIA <", value, "telfProvincia");
      return (Criteria) this;
    }

    public Criteria andTelfProvinciaLessThanOrEqualTo(String value) {
      addCriterion("TELF_PROVINCIA <=", value, "telfProvincia");
      return (Criteria) this;
    }

    public Criteria andTelfProvinciaIn(List<String> values) {
      addCriterion("TELF_PROVINCIA in", values, "telfProvincia");
      return (Criteria) this;
    }

    public Criteria andTelfProvinciaNotIn(List<String> values) {
      addCriterion("TELF_PROVINCIA not in", values, "telfProvincia");
      return (Criteria) this;
    }

    public Criteria andTelfProvinciaBetween(String value1, String value2) {
      addCriterion("TELF_PROVINCIA between", value1, value2, "telfProvincia");
      return (Criteria) this;
    }

    public Criteria andTelfProvinciaNotBetween(String value1, String value2) {
      addCriterion("TELF_PROVINCIA not between", value1, value2, "telfProvincia");
      return (Criteria) this;
    }

    public Criteria andTelfTrabajoIsNull() {
      addCriterion("TELF_TRABAJO is null");
      return (Criteria) this;
    }

    public Criteria andTelfTrabajoIsNotNull() {
      addCriterion("TELF_TRABAJO is not null");
      return (Criteria) this;
    }

    public Criteria andTelfTrabajoEqualTo(String value) {
      addCriterion("TELF_TRABAJO =", value, "telfTrabajo");
      return (Criteria) this;
    }

    public Criteria andTelfTrabajoNotEqualTo(String value) {
      addCriterion("TELF_TRABAJO <>", value, "telfTrabajo");
      return (Criteria) this;
    }

    public Criteria andTelfTrabajoGreaterThan(String value) {
      addCriterion("TELF_TRABAJO >", value, "telfTrabajo");
      return (Criteria) this;
    }

    public Criteria andTelfTrabajoGreaterThanOrEqualTo(String value) {
      addCriterion("TELF_TRABAJO >=", value, "telfTrabajo");
      return (Criteria) this;
    }

    public Criteria andTelfTrabajoLessThan(String value) {
      addCriterion("TELF_TRABAJO <", value, "telfTrabajo");
      return (Criteria) this;
    }

    public Criteria andTelfTrabajoLessThanOrEqualTo(String value) {
      addCriterion("TELF_TRABAJO <=", value, "telfTrabajo");
      return (Criteria) this;
    }

    public Criteria andTelfTrabajoIn(List<String> values) {
      addCriterion("TELF_TRABAJO in", values, "telfTrabajo");
      return (Criteria) this;
    }

    public Criteria andTelfTrabajoNotIn(List<String> values) {
      addCriterion("TELF_TRABAJO not in", values, "telfTrabajo");
      return (Criteria) this;
    }

    public Criteria andTelfTrabajoBetween(String value1, String value2) {
      addCriterion("TELF_TRABAJO between", value1, value2, "telfTrabajo");
      return (Criteria) this;
    }

    public Criteria andTelfTrabajoNotBetween(String value1, String value2) {
      addCriterion("TELF_TRABAJO not between", value1, value2, "telfTrabajo");
      return (Criteria) this;
    }

    public Criteria andNroCuentaIsNull() {
      addCriterion("NRO_CUENTA is null");
      return (Criteria) this;
    }

    public Criteria andNroCuentaIsNotNull() {
      addCriterion("NRO_CUENTA is not null");
      return (Criteria) this;
    }

    public Criteria andNroCuentaEqualTo(String value) {
      addCriterion("NRO_CUENTA =", value, "nroCuenta");
      return (Criteria) this;
    }

    public Criteria andNroCuentaNotEqualTo(String value) {
      addCriterion("NRO_CUENTA <>", value, "nroCuenta");
      return (Criteria) this;
    }

    public Criteria andNroCuentaGreaterThan(String value) {
      addCriterion("NRO_CUENTA >", value, "nroCuenta");
      return (Criteria) this;
    }

    public Criteria andNroCuentaGreaterThanOrEqualTo(String value) {
      addCriterion("NRO_CUENTA >=", value, "nroCuenta");
      return (Criteria) this;
    }

    public Criteria andNroCuentaLessThan(String value) {
      addCriterion("NRO_CUENTA <", value, "nroCuenta");
      return (Criteria) this;
    }

    public Criteria andNroCuentaLessThanOrEqualTo(String value) {
      addCriterion("NRO_CUENTA <=", value, "nroCuenta");
      return (Criteria) this;
    }

    public Criteria andNroCuentaIn(List<String> values) {
      addCriterion("NRO_CUENTA in", values, "nroCuenta");
      return (Criteria) this;
    }

    public Criteria andNroCuentaNotIn(List<String> values) {
      addCriterion("NRO_CUENTA not in", values, "nroCuenta");
      return (Criteria) this;
    }

    public Criteria andNroCuentaBetween(String value1, String value2) {
      addCriterion("NRO_CUENTA between", value1, value2, "nroCuenta");
      return (Criteria) this;
    }

    public Criteria andNroCuentaNotBetween(String value1, String value2) {
      addCriterion("NRO_CUENTA not between", value1, value2, "nroCuenta");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaIsNull() {
      addCriterion("NRO_TARJETA is null");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaIsNotNull() {
      addCriterion("NRO_TARJETA is not null");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaEqualTo(String value) {
      addCriterion("NRO_TARJETA =", value, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaNotEqualTo(String value) {
      addCriterion("NRO_TARJETA <>", value, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaGreaterThan(String value) {
      addCriterion("NRO_TARJETA >", value, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaGreaterThanOrEqualTo(String value) {
      addCriterion("NRO_TARJETA >=", value, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaLessThan(String value) {
      addCriterion("NRO_TARJETA <", value, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaLessThanOrEqualTo(String value) {
      addCriterion("NRO_TARJETA <=", value, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaIn(List<String> values) {
      addCriterion("NRO_TARJETA in", values, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaNotIn(List<String> values) {
      addCriterion("NRO_TARJETA not in", values, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaBetween(String value1, String value2) {
      addCriterion("NRO_TARJETA between", value1, value2, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaNotBetween(String value1, String value2) {
      addCriterion("NRO_TARJETA not between", value1, value2, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaIsNull() {
      addCriterion("TIPO_TARJETA is null");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaIsNotNull() {
      addCriterion("TIPO_TARJETA is not null");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaEqualTo(String value) {
      addCriterion("TIPO_TARJETA =", value, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaNotEqualTo(String value) {
      addCriterion("TIPO_TARJETA <>", value, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaGreaterThan(String value) {
      addCriterion("TIPO_TARJETA >", value, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaGreaterThanOrEqualTo(String value) {
      addCriterion("TIPO_TARJETA >=", value, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaLessThan(String value) {
      addCriterion("TIPO_TARJETA <", value, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaLessThanOrEqualTo(String value) {
      addCriterion("TIPO_TARJETA <=", value, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaIn(List<String> values) {
      addCriterion("TIPO_TARJETA in", values, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaNotIn(List<String> values) {
      addCriterion("TIPO_TARJETA not in", values, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaBetween(String value1, String value2) {
      addCriterion("TIPO_TARJETA between", value1, value2, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaNotBetween(String value1, String value2) {
      addCriterion("TIPO_TARJETA not between", value1, value2, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoPenIsNull() {
      addCriterion("LIMITE_CREDITO_PEN is null");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoPenIsNotNull() {
      addCriterion("LIMITE_CREDITO_PEN is not null");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoPenEqualTo(String value) {
      addCriterion("LIMITE_CREDITO_PEN =", value, "limiteCreditoPen");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoPenNotEqualTo(String value) {
      addCriterion("LIMITE_CREDITO_PEN <>", value, "limiteCreditoPen");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoPenGreaterThan(String value) {
      addCriterion("LIMITE_CREDITO_PEN >", value, "limiteCreditoPen");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoPenGreaterThanOrEqualTo(String value) {
      addCriterion("LIMITE_CREDITO_PEN >=", value, "limiteCreditoPen");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoPenLessThan(String value) {
      addCriterion("LIMITE_CREDITO_PEN <", value, "limiteCreditoPen");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoPenLessThanOrEqualTo(String value) {
      addCriterion("LIMITE_CREDITO_PEN <=", value, "limiteCreditoPen");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoPenIn(List<String> values) {
      addCriterion("LIMITE_CREDITO_PEN in", values, "limiteCreditoPen");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoPenNotIn(List<String> values) {
      addCriterion("LIMITE_CREDITO_PEN not in", values, "limiteCreditoPen");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoPenBetween(String value1, String value2) {
      addCriterion("LIMITE_CREDITO_PEN between", value1, value2, "limiteCreditoPen");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoPenNotBetween(String value1, String value2) {
      addCriterion("LIMITE_CREDITO_PEN not between", value1, value2, "limiteCreditoPen");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoDolaresIsNull() {
      addCriterion("LIMITE_CREDITO_DOLARES is null");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoDolaresIsNotNull() {
      addCriterion("LIMITE_CREDITO_DOLARES is not null");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoDolaresEqualTo(String value) {
      addCriterion("LIMITE_CREDITO_DOLARES =", value, "limiteCreditoDolares");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoDolaresNotEqualTo(String value) {
      addCriterion("LIMITE_CREDITO_DOLARES <>", value, "limiteCreditoDolares");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoDolaresGreaterThan(String value) {
      addCriterion("LIMITE_CREDITO_DOLARES >", value, "limiteCreditoDolares");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoDolaresGreaterThanOrEqualTo(String value) {
      addCriterion("LIMITE_CREDITO_DOLARES >=", value, "limiteCreditoDolares");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoDolaresLessThan(String value) {
      addCriterion("LIMITE_CREDITO_DOLARES <", value, "limiteCreditoDolares");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoDolaresLessThanOrEqualTo(String value) {
      addCriterion("LIMITE_CREDITO_DOLARES <=", value, "limiteCreditoDolares");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoDolaresIn(List<String> values) {
      addCriterion("LIMITE_CREDITO_DOLARES in", values, "limiteCreditoDolares");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoDolaresNotIn(List<String> values) {
      addCriterion("LIMITE_CREDITO_DOLARES not in", values, "limiteCreditoDolares");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoDolaresBetween(String value1, String value2) {
      addCriterion("LIMITE_CREDITO_DOLARES between", value1, value2, "limiteCreditoDolares");
      return (Criteria) this;
    }

    public Criteria andLimiteCreditoDolaresNotBetween(String value1, String value2) {
      addCriterion("LIMITE_CREDITO_DOLARES not between", value1, value2, "limiteCreditoDolares");
      return (Criteria) this;
    }

    public Criteria andCodCicloIsNull() {
      addCriterion("COD_CICLO is null");
      return (Criteria) this;
    }

    public Criteria andCodCicloIsNotNull() {
      addCriterion("COD_CICLO is not null");
      return (Criteria) this;
    }

    public Criteria andCodCicloEqualTo(String value) {
      addCriterion("COD_CICLO =", value, "codCiclo");
      return (Criteria) this;
    }

    public Criteria andCodCicloNotEqualTo(String value) {
      addCriterion("COD_CICLO <>", value, "codCiclo");
      return (Criteria) this;
    }

    public Criteria andCodCicloGreaterThan(String value) {
      addCriterion("COD_CICLO >", value, "codCiclo");
      return (Criteria) this;
    }

    public Criteria andCodCicloGreaterThanOrEqualTo(String value) {
      addCriterion("COD_CICLO >=", value, "codCiclo");
      return (Criteria) this;
    }

    public Criteria andCodCicloLessThan(String value) {
      addCriterion("COD_CICLO <", value, "codCiclo");
      return (Criteria) this;
    }

    public Criteria andCodCicloLessThanOrEqualTo(String value) {
      addCriterion("COD_CICLO <=", value, "codCiclo");
      return (Criteria) this;
    }

    public Criteria andCodCicloIn(List<String> values) {
      addCriterion("COD_CICLO in", values, "codCiclo");
      return (Criteria) this;
    }

    public Criteria andCodCicloNotIn(List<String> values) {
      addCriterion("COD_CICLO not in", values, "codCiclo");
      return (Criteria) this;
    }

    public Criteria andCodCicloBetween(String value1, String value2) {
      addCriterion("COD_CICLO between", value1, value2, "codCiclo");
      return (Criteria) this;
    }

    public Criteria andCodCicloNotBetween(String value1, String value2) {
      addCriterion("COD_CICLO not between", value1, value2, "codCiclo");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoIsNull() {
      addCriterion("FECHA_VENCIMIENTO is null");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoIsNotNull() {
      addCriterion("FECHA_VENCIMIENTO is not null");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoEqualTo(Date value) {
      addCriterion("FECHA_VENCIMIENTO =", value, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoNotEqualTo(Date value) {
      addCriterion("FECHA_VENCIMIENTO <>", value, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoGreaterThan(Date value) {
      addCriterion("FECHA_VENCIMIENTO >", value, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoGreaterThanOrEqualTo(Date value) {
      addCriterion("FECHA_VENCIMIENTO >=", value, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoLessThan(Date value) {
      addCriterion("FECHA_VENCIMIENTO <", value, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoLessThanOrEqualTo(Date value) {
      addCriterion("FECHA_VENCIMIENTO <=", value, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoIn(List<Date> values) {
      addCriterion("FECHA_VENCIMIENTO in", values, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoNotIn(List<Date> values) {
      addCriterion("FECHA_VENCIMIENTO not in", values, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoBetween(Date value1, Date value2) {
      addCriterion("FECHA_VENCIMIENTO between", value1, value2, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andFechaVencimientoNotBetween(Date value1, Date value2) {
      addCriterion("FECHA_VENCIMIENTO not between", value1, value2, "fechaVencimiento");
      return (Criteria) this;
    }

    public Criteria andClientethIsNull() {
      addCriterion("CLIENTETH is null");
      return (Criteria) this;
    }

    public Criteria andClientethIsNotNull() {
      addCriterion("CLIENTETH is not null");
      return (Criteria) this;
    }

    public Criteria andClientethEqualTo(String value) {
      addCriterion("CLIENTETH =", value, "clienteth");
      return (Criteria) this;
    }

    public Criteria andClientethNotEqualTo(String value) {
      addCriterion("CLIENTETH <>", value, "clienteth");
      return (Criteria) this;
    }

    public Criteria andClientethGreaterThan(String value) {
      addCriterion("CLIENTETH >", value, "clienteth");
      return (Criteria) this;
    }

    public Criteria andClientethGreaterThanOrEqualTo(String value) {
      addCriterion("CLIENTETH >=", value, "clienteth");
      return (Criteria) this;
    }

    public Criteria andClientethLessThan(String value) {
      addCriterion("CLIENTETH <", value, "clienteth");
      return (Criteria) this;
    }

    public Criteria andClientethLessThanOrEqualTo(String value) {
      addCriterion("CLIENTETH <=", value, "clienteth");
      return (Criteria) this;
    }

    public Criteria andClientethIn(List<String> values) {
      addCriterion("CLIENTETH in", values, "clienteth");
      return (Criteria) this;
    }

    public Criteria andClientethNotIn(List<String> values) {
      addCriterion("CLIENTETH not in", values, "clienteth");
      return (Criteria) this;
    }

    public Criteria andClientethBetween(String value1, String value2) {
      addCriterion("CLIENTETH between", value1, value2, "clienteth");
      return (Criteria) this;
    }

    public Criteria andClientethNotBetween(String value1, String value2) {
      addCriterion("CLIENTETH not between", value1, value2, "clienteth");
      return (Criteria) this;
    }

    public Criteria andComentario1CardifIsNull() {
      addCriterion("COMENTARIO1_CARDIF is null");
      return (Criteria) this;
    }

    public Criteria andComentario1CardifIsNotNull() {
      addCriterion("COMENTARIO1_CARDIF is not null");
      return (Criteria) this;
    }

    public Criteria andComentario1CardifEqualTo(String value) {
      addCriterion("COMENTARIO1_CARDIF =", value, "comentario1Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario1CardifNotEqualTo(String value) {
      addCriterion("COMENTARIO1_CARDIF <>", value, "comentario1Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario1CardifGreaterThan(String value) {
      addCriterion("COMENTARIO1_CARDIF >", value, "comentario1Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario1CardifGreaterThanOrEqualTo(String value) {
      addCriterion("COMENTARIO1_CARDIF >=", value, "comentario1Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario1CardifLessThan(String value) {
      addCriterion("COMENTARIO1_CARDIF <", value, "comentario1Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario1CardifLessThanOrEqualTo(String value) {
      addCriterion("COMENTARIO1_CARDIF <=", value, "comentario1Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario1CardifIn(List<String> values) {
      addCriterion("COMENTARIO1_CARDIF in", values, "comentario1Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario1CardifNotIn(List<String> values) {
      addCriterion("COMENTARIO1_CARDIF not in", values, "comentario1Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario1CardifBetween(String value1, String value2) {
      addCriterion("COMENTARIO1_CARDIF between", value1, value2, "comentario1Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario1CardifNotBetween(String value1, String value2) {
      addCriterion("COMENTARIO1_CARDIF not between", value1, value2, "comentario1Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario2CardifIsNull() {
      addCriterion("COMENTARIO2_CARDIF is null");
      return (Criteria) this;
    }

    public Criteria andComentario2CardifIsNotNull() {
      addCriterion("COMENTARIO2_CARDIF is not null");
      return (Criteria) this;
    }

    public Criteria andComentario2CardifEqualTo(String value) {
      addCriterion("COMENTARIO2_CARDIF =", value, "comentario2Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario2CardifNotEqualTo(String value) {
      addCriterion("COMENTARIO2_CARDIF <>", value, "comentario2Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario2CardifGreaterThan(String value) {
      addCriterion("COMENTARIO2_CARDIF >", value, "comentario2Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario2CardifGreaterThanOrEqualTo(String value) {
      addCriterion("COMENTARIO2_CARDIF >=", value, "comentario2Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario2CardifLessThan(String value) {
      addCriterion("COMENTARIO2_CARDIF <", value, "comentario2Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario2CardifLessThanOrEqualTo(String value) {
      addCriterion("COMENTARIO2_CARDIF <=", value, "comentario2Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario2CardifIn(List<String> values) {
      addCriterion("COMENTARIO2_CARDIF in", values, "comentario2Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario2CardifNotIn(List<String> values) {
      addCriterion("COMENTARIO2_CARDIF not in", values, "comentario2Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario2CardifBetween(String value1, String value2) {
      addCriterion("COMENTARIO2_CARDIF between", value1, value2, "comentario2Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario2CardifNotBetween(String value1, String value2) {
      addCriterion("COMENTARIO2_CARDIF not between", value1, value2, "comentario2Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario3CardifIsNull() {
      addCriterion("COMENTARIO3_CARDIF is null");
      return (Criteria) this;
    }

    public Criteria andComentario3CardifIsNotNull() {
      addCriterion("COMENTARIO3_CARDIF is not null");
      return (Criteria) this;
    }

    public Criteria andComentario3CardifEqualTo(String value) {
      addCriterion("COMENTARIO3_CARDIF =", value, "comentario3Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario3CardifNotEqualTo(String value) {
      addCriterion("COMENTARIO3_CARDIF <>", value, "comentario3Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario3CardifGreaterThan(String value) {
      addCriterion("COMENTARIO3_CARDIF >", value, "comentario3Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario3CardifGreaterThanOrEqualTo(String value) {
      addCriterion("COMENTARIO3_CARDIF >=", value, "comentario3Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario3CardifLessThan(String value) {
      addCriterion("COMENTARIO3_CARDIF <", value, "comentario3Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario3CardifLessThanOrEqualTo(String value) {
      addCriterion("COMENTARIO3_CARDIF <=", value, "comentario3Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario3CardifIn(List<String> values) {
      addCriterion("COMENTARIO3_CARDIF in", values, "comentario3Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario3CardifNotIn(List<String> values) {
      addCriterion("COMENTARIO3_CARDIF not in", values, "comentario3Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario3CardifBetween(String value1, String value2) {
      addCriterion("COMENTARIO3_CARDIF between", value1, value2, "comentario3Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario3CardifNotBetween(String value1, String value2) {
      addCriterion("COMENTARIO3_CARDIF not between", value1, value2, "comentario3Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario4CardifIsNull() {
      addCriterion("COMENTARIO4_CARDIF is null");
      return (Criteria) this;
    }

    public Criteria andComentario4CardifIsNotNull() {
      addCriterion("COMENTARIO4_CARDIF is not null");
      return (Criteria) this;
    }

    public Criteria andComentario4CardifEqualTo(String value) {
      addCriterion("COMENTARIO4_CARDIF =", value, "comentario4Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario4CardifNotEqualTo(String value) {
      addCriterion("COMENTARIO4_CARDIF <>", value, "comentario4Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario4CardifGreaterThan(String value) {
      addCriterion("COMENTARIO4_CARDIF >", value, "comentario4Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario4CardifGreaterThanOrEqualTo(String value) {
      addCriterion("COMENTARIO4_CARDIF >=", value, "comentario4Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario4CardifLessThan(String value) {
      addCriterion("COMENTARIO4_CARDIF <", value, "comentario4Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario4CardifLessThanOrEqualTo(String value) {
      addCriterion("COMENTARIO4_CARDIF <=", value, "comentario4Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario4CardifIn(List<String> values) {
      addCriterion("COMENTARIO4_CARDIF in", values, "comentario4Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario4CardifNotIn(List<String> values) {
      addCriterion("COMENTARIO4_CARDIF not in", values, "comentario4Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario4CardifBetween(String value1, String value2) {
      addCriterion("COMENTARIO4_CARDIF between", value1, value2, "comentario4Cardif");
      return (Criteria) this;
    }

    public Criteria andComentario4CardifNotBetween(String value1, String value2) {
      addCriterion("COMENTARIO4_CARDIF not between", value1, value2, "comentario4Cardif");
      return (Criteria) this;
    }

    public Criteria andEstadoIsNull() {
      addCriterion("ESTADO is null");
      return (Criteria) this;
    }

    public Criteria andEstadoIsNotNull() {
      addCriterion("ESTADO is not null");
      return (Criteria) this;
    }

    public Criteria andEstadoEqualTo(String value) {
      addCriterion("ESTADO =", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoNotEqualTo(String value) {
      addCriterion("ESTADO <>", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoGreaterThan(String value) {
      addCriterion("ESTADO >", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoGreaterThanOrEqualTo(String value) {
      addCriterion("ESTADO >=", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoLessThan(String value) {
      addCriterion("ESTADO <", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoLessThanOrEqualTo(String value) {
      addCriterion("ESTADO <=", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoIn(List<String> values) {
      addCriterion("ESTADO in", values, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoNotIn(List<String> values) {
      addCriterion("ESTADO not in", values, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoBetween(String value1, String value2) {
      addCriterion("ESTADO between", value1, value2, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoNotBetween(String value1, String value2) {
      addCriterion("ESTADO not between", value1, value2, "estado");
      return (Criteria) this;
    }

    public Criteria andDesMensajeIsNull() {
      addCriterion("DES_MENSAJE is null");
      return (Criteria) this;
    }

    public Criteria andDesMensajeIsNotNull() {
      addCriterion("DES_MENSAJE is not null");
      return (Criteria) this;
    }

    public Criteria andDesMensajeEqualTo(String value) {
      addCriterion("DES_MENSAJE =", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeNotEqualTo(String value) {
      addCriterion("DES_MENSAJE <>", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeGreaterThan(String value) {
      addCriterion("DES_MENSAJE >", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeGreaterThanOrEqualTo(String value) {
      addCriterion("DES_MENSAJE >=", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeLessThan(String value) {
      addCriterion("DES_MENSAJE <", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeLessThanOrEqualTo(String value) {
      addCriterion("DES_MENSAJE <=", value, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeIn(List<String> values) {
      addCriterion("DES_MENSAJE in", values, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeNotIn(List<String> values) {
      addCriterion("DES_MENSAJE not in", values, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeBetween(String value1, String value2) {
      addCriterion("DES_MENSAJE between", value1, value2, "desMensaje");
      return (Criteria) this;
    }

    public Criteria andDesMensajeNotBetween(String value1, String value2) {
      addCriterion("DES_MENSAJE not between", value1, value2, "desMensaje");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.TLMK_BASE_SB
   *
   * @mbggenerated do_not_delete_during_merge Thu Feb 06 11:39:53 COT 2014
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.TLMK_BASE_SB
   *
   * @mbggenerated Thu Feb 06 11:39:53 COT 2014
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}