package com.cardif.satelite.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TstVentas implements Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.pk
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Long pk;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.CorrelativoRegistro
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Long correlativoregistro;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.FechaEmision
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Date fechaemision;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.FechaVencimiento
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Date fechavencimiento;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.TipoComprobante
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Long tipocomprobante;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.NroSerie
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Long nroserie;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.CorrelativoSerie
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Long correlativoserie;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.TipoDocCliente
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String tipodoccliente;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.NumeroDocCliente
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String numerodoccliente;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.NombresRazonSocial
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String nombresrazonsocial;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.ValorFactExport
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private BigDecimal valorfactexport;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.BaseImponible
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private BigDecimal baseimponible;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.ImporteExonerado
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private BigDecimal importeexonerado;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.ImporteInafecto
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private BigDecimal importeinafecto;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.ISC
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private BigDecimal isc;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.IGV
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private BigDecimal igv;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.OtrosImportes
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private BigDecimal otrosimportes;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.ImporteTotal
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private BigDecimal importetotal;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.TipoCambio
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private BigDecimal tipocambio;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.FechaEmisionRef
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Date fechaemisionref;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.TipoComprobanteRef
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Long tipocomprobanteref;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.SerieComprobanteRef
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Long seriecomprobanteref;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.CorrelativoSerieOrig
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Long correlativoserieorig;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.Modificable
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String modificable;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.OpenItem
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String openitem;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.OpenItemRef
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String openitemref;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.NumeroPoliza
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String numeropoliza;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.Producto
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String producto;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.Estado
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String estado;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.OBSERVACIONES
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String observaciones;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.ASTERISCO
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String asterisco;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.CADENA1
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String cadena1;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.CADENA2
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String cadena2;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.CADENA3
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String cadena3;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.CADENA4
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String cadena4;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.CADENA5
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String cadena5;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.NUMERICO1
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Long numerico1;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.NUMERICO2
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Long numerico2;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.NUMERICO3
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Long numerico3;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.NUMERICO4
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Long numerico4;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.NUMERICO5
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Long numerico5;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.FECHA1
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Date fecha1;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.FECHA2
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Date fecha2;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.FECHA3
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Date fecha3;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.FECHA4
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Date fecha4;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.FECHA5
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Date fecha5;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.CONSECUTIVO
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Integer consecutivo;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.NUMER1
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private BigDecimal numer1;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.NUMER2
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private BigDecimal numer2;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.NUMER3
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private BigDecimal numer3;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.NUMER4
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private BigDecimal numer4;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.NUMER5
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private BigDecimal numer5;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.TEXTO1
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String texto1;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.TEXTO2
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String texto2;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.TEXTO3
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String texto3;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.TEXTO4
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String texto4;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.TEXTO5
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String texto5;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.FEC_CREACION
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Date fecCreacion;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.USU_CREACION
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String usuCreacion;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.FEC_MODIFICACION
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private Date fecModificacion;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.TST_VENTAS.USU_MODIFICACION
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  private String usuModificacion;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.pk
   *
   * @return the value of dbo.TST_VENTAS.pk
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Long getPk() {
    return pk;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.pk
   *
   * @param pk
   *          the value for dbo.TST_VENTAS.pk
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setPk(Long pk) {
    this.pk = pk;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.CorrelativoRegistro
   *
   * @return the value of dbo.TST_VENTAS.CorrelativoRegistro
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Long getCorrelativoregistro() {
    return correlativoregistro;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.CorrelativoRegistro
   *
   * @param correlativoregistro
   *          the value for dbo.TST_VENTAS.CorrelativoRegistro
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setCorrelativoregistro(Long correlativoregistro) {
    this.correlativoregistro = correlativoregistro;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.FechaEmision
   *
   * @return the value of dbo.TST_VENTAS.FechaEmision
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Date getFechaemision() {
    return fechaemision;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.FechaEmision
   *
   * @param fechaemision
   *          the value for dbo.TST_VENTAS.FechaEmision
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setFechaemision(Date fechaemision) {
    this.fechaemision = fechaemision;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.FechaVencimiento
   *
   * @return the value of dbo.TST_VENTAS.FechaVencimiento
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Date getFechavencimiento() {
    return fechavencimiento;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.FechaVencimiento
   *
   * @param fechavencimiento
   *          the value for dbo.TST_VENTAS.FechaVencimiento
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setFechavencimiento(Date fechavencimiento) {
    this.fechavencimiento = fechavencimiento;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.TipoComprobante
   *
   * @return the value of dbo.TST_VENTAS.TipoComprobante
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Long getTipocomprobante() {
    return tipocomprobante;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.TipoComprobante
   *
   * @param tipocomprobante
   *          the value for dbo.TST_VENTAS.TipoComprobante
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setTipocomprobante(Long tipocomprobante) {
    this.tipocomprobante = tipocomprobante;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.NroSerie
   *
   * @return the value of dbo.TST_VENTAS.NroSerie
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Long getNroserie() {
    return nroserie;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.NroSerie
   *
   * @param nroserie
   *          the value for dbo.TST_VENTAS.NroSerie
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setNroserie(Long nroserie) {
    this.nroserie = nroserie;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.CorrelativoSerie
   *
   * @return the value of dbo.TST_VENTAS.CorrelativoSerie
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Long getCorrelativoserie() {
    return correlativoserie;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.CorrelativoSerie
   *
   * @param correlativoserie
   *          the value for dbo.TST_VENTAS.CorrelativoSerie
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setCorrelativoserie(Long correlativoserie) {
    this.correlativoserie = correlativoserie;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.TipoDocCliente
   *
   * @return the value of dbo.TST_VENTAS.TipoDocCliente
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getTipodoccliente() {
    return tipodoccliente;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.TipoDocCliente
   *
   * @param tipodoccliente
   *          the value for dbo.TST_VENTAS.TipoDocCliente
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setTipodoccliente(String tipodoccliente) {
    this.tipodoccliente = tipodoccliente == null ? null : tipodoccliente.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.NumeroDocCliente
   *
   * @return the value of dbo.TST_VENTAS.NumeroDocCliente
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getNumerodoccliente() {
    return numerodoccliente;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.NumeroDocCliente
   *
   * @param numerodoccliente
   *          the value for dbo.TST_VENTAS.NumeroDocCliente
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setNumerodoccliente(String numerodoccliente) {
    this.numerodoccliente = numerodoccliente == null ? null : numerodoccliente.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.NombresRazonSocial
   *
   * @return the value of dbo.TST_VENTAS.NombresRazonSocial
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getNombresrazonsocial() {
    return nombresrazonsocial;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.NombresRazonSocial
   *
   * @param nombresrazonsocial
   *          the value for dbo.TST_VENTAS.NombresRazonSocial
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setNombresrazonsocial(String nombresrazonsocial) {
    this.nombresrazonsocial = nombresrazonsocial == null ? null : nombresrazonsocial.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.ValorFactExport
   *
   * @return the value of dbo.TST_VENTAS.ValorFactExport
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public BigDecimal getValorfactexport() {
    return valorfactexport;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.ValorFactExport
   *
   * @param valorfactexport
   *          the value for dbo.TST_VENTAS.ValorFactExport
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setValorfactexport(BigDecimal valorfactexport) {
    this.valorfactexport = valorfactexport;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.BaseImponible
   *
   * @return the value of dbo.TST_VENTAS.BaseImponible
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public BigDecimal getBaseimponible() {
    return baseimponible;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.BaseImponible
   *
   * @param baseimponible
   *          the value for dbo.TST_VENTAS.BaseImponible
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setBaseimponible(BigDecimal baseimponible) {
    this.baseimponible = baseimponible;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.ImporteExonerado
   *
   * @return the value of dbo.TST_VENTAS.ImporteExonerado
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public BigDecimal getImporteexonerado() {
    return importeexonerado;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.ImporteExonerado
   *
   * @param importeexonerado
   *          the value for dbo.TST_VENTAS.ImporteExonerado
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setImporteexonerado(BigDecimal importeexonerado) {
    this.importeexonerado = importeexonerado;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.ImporteInafecto
   *
   * @return the value of dbo.TST_VENTAS.ImporteInafecto
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public BigDecimal getImporteinafecto() {
    return importeinafecto;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.ImporteInafecto
   *
   * @param importeinafecto
   *          the value for dbo.TST_VENTAS.ImporteInafecto
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setImporteinafecto(BigDecimal importeinafecto) {
    this.importeinafecto = importeinafecto;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.ISC
   *
   * @return the value of dbo.TST_VENTAS.ISC
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public BigDecimal getIsc() {
    return isc;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.ISC
   *
   * @param isc
   *          the value for dbo.TST_VENTAS.ISC
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setIsc(BigDecimal isc) {
    this.isc = isc;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.IGV
   *
   * @return the value of dbo.TST_VENTAS.IGV
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public BigDecimal getIgv() {
    return igv;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.IGV
   *
   * @param igv
   *          the value for dbo.TST_VENTAS.IGV
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setIgv(BigDecimal igv) {
    this.igv = igv;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.OtrosImportes
   *
   * @return the value of dbo.TST_VENTAS.OtrosImportes
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public BigDecimal getOtrosimportes() {
    return otrosimportes;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.OtrosImportes
   *
   * @param otrosimportes
   *          the value for dbo.TST_VENTAS.OtrosImportes
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setOtrosimportes(BigDecimal otrosimportes) {
    this.otrosimportes = otrosimportes;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.ImporteTotal
   *
   * @return the value of dbo.TST_VENTAS.ImporteTotal
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public BigDecimal getImportetotal() {
    return importetotal;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.ImporteTotal
   *
   * @param importetotal
   *          the value for dbo.TST_VENTAS.ImporteTotal
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setImportetotal(BigDecimal importetotal) {
    this.importetotal = importetotal;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.TipoCambio
   *
   * @return the value of dbo.TST_VENTAS.TipoCambio
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public BigDecimal getTipocambio() {
    return tipocambio;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.TipoCambio
   *
   * @param tipocambio
   *          the value for dbo.TST_VENTAS.TipoCambio
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setTipocambio(BigDecimal tipocambio) {
    this.tipocambio = tipocambio;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.FechaEmisionRef
   *
   * @return the value of dbo.TST_VENTAS.FechaEmisionRef
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Date getFechaemisionref() {
    return fechaemisionref;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.FechaEmisionRef
   *
   * @param fechaemisionref
   *          the value for dbo.TST_VENTAS.FechaEmisionRef
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setFechaemisionref(Date fechaemisionref) {
    this.fechaemisionref = fechaemisionref;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.TipoComprobanteRef
   *
   * @return the value of dbo.TST_VENTAS.TipoComprobanteRef
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Long getTipocomprobanteref() {
    return tipocomprobanteref;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.TipoComprobanteRef
   *
   * @param tipocomprobanteref
   *          the value for dbo.TST_VENTAS.TipoComprobanteRef
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setTipocomprobanteref(Long tipocomprobanteref) {
    this.tipocomprobanteref = tipocomprobanteref;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.SerieComprobanteRef
   *
   * @return the value of dbo.TST_VENTAS.SerieComprobanteRef
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Long getSeriecomprobanteref() {
    return seriecomprobanteref;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.SerieComprobanteRef
   *
   * @param seriecomprobanteref
   *          the value for dbo.TST_VENTAS.SerieComprobanteRef
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setSeriecomprobanteref(Long seriecomprobanteref) {
    this.seriecomprobanteref = seriecomprobanteref;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.CorrelativoSerieOrig
   *
   * @return the value of dbo.TST_VENTAS.CorrelativoSerieOrig
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Long getCorrelativoserieorig() {
    return correlativoserieorig;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.CorrelativoSerieOrig
   *
   * @param correlativoserieorig
   *          the value for dbo.TST_VENTAS.CorrelativoSerieOrig
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setCorrelativoserieorig(Long correlativoserieorig) {
    this.correlativoserieorig = correlativoserieorig;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.Modificable
   *
   * @return the value of dbo.TST_VENTAS.Modificable
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getModificable() {
    return modificable;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.Modificable
   *
   * @param modificable
   *          the value for dbo.TST_VENTAS.Modificable
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setModificable(String modificable) {
    this.modificable = modificable == null ? null : modificable.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.OpenItem
   *
   * @return the value of dbo.TST_VENTAS.OpenItem
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getOpenitem() {
    return openitem;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.OpenItem
   *
   * @param openitem
   *          the value for dbo.TST_VENTAS.OpenItem
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setOpenitem(String openitem) {
    this.openitem = openitem == null ? null : openitem.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.OpenItemRef
   *
   * @return the value of dbo.TST_VENTAS.OpenItemRef
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getOpenitemref() {
    return openitemref;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.OpenItemRef
   *
   * @param openitemref
   *          the value for dbo.TST_VENTAS.OpenItemRef
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setOpenitemref(String openitemref) {
    this.openitemref = openitemref == null ? null : openitemref.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.NumeroPoliza
   *
   * @return the value of dbo.TST_VENTAS.NumeroPoliza
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getNumeropoliza() {
    return numeropoliza;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.NumeroPoliza
   *
   * @param numeropoliza
   *          the value for dbo.TST_VENTAS.NumeroPoliza
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setNumeropoliza(String numeropoliza) {
    this.numeropoliza = numeropoliza == null ? null : numeropoliza.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.Producto
   *
   * @return the value of dbo.TST_VENTAS.Producto
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getProducto() {
    return producto;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.Producto
   *
   * @param producto
   *          the value for dbo.TST_VENTAS.Producto
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setProducto(String producto) {
    this.producto = producto == null ? null : producto.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.Estado
   *
   * @return the value of dbo.TST_VENTAS.Estado
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getEstado() {
    return estado;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.Estado
   *
   * @param estado
   *          the value for dbo.TST_VENTAS.Estado
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setEstado(String estado) {
    this.estado = estado == null ? null : estado.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.OBSERVACIONES
   *
   * @return the value of dbo.TST_VENTAS.OBSERVACIONES
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getObservaciones() {
    return observaciones;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.OBSERVACIONES
   *
   * @param observaciones
   *          the value for dbo.TST_VENTAS.OBSERVACIONES
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setObservaciones(String observaciones) {
    this.observaciones = observaciones == null ? null : observaciones.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.ASTERISCO
   *
   * @return the value of dbo.TST_VENTAS.ASTERISCO
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getAsterisco() {
    return asterisco;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.ASTERISCO
   *
   * @param asterisco
   *          the value for dbo.TST_VENTAS.ASTERISCO
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setAsterisco(String asterisco) {
    this.asterisco = asterisco == null ? null : asterisco.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.CADENA1
   *
   * @return the value of dbo.TST_VENTAS.CADENA1
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getCadena1() {
    return cadena1;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.CADENA1
   *
   * @param cadena1
   *          the value for dbo.TST_VENTAS.CADENA1
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setCadena1(String cadena1) {
    this.cadena1 = cadena1 == null ? null : cadena1.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.CADENA2
   *
   * @return the value of dbo.TST_VENTAS.CADENA2
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getCadena2() {
    return cadena2;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.CADENA2
   *
   * @param cadena2
   *          the value for dbo.TST_VENTAS.CADENA2
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setCadena2(String cadena2) {
    this.cadena2 = cadena2 == null ? null : cadena2.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.CADENA3
   *
   * @return the value of dbo.TST_VENTAS.CADENA3
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getCadena3() {
    return cadena3;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.CADENA3
   *
   * @param cadena3
   *          the value for dbo.TST_VENTAS.CADENA3
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setCadena3(String cadena3) {
    this.cadena3 = cadena3 == null ? null : cadena3.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.CADENA4
   *
   * @return the value of dbo.TST_VENTAS.CADENA4
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getCadena4() {
    return cadena4;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.CADENA4
   *
   * @param cadena4
   *          the value for dbo.TST_VENTAS.CADENA4
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setCadena4(String cadena4) {
    this.cadena4 = cadena4 == null ? null : cadena4.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.CADENA5
   *
   * @return the value of dbo.TST_VENTAS.CADENA5
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getCadena5() {
    return cadena5;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.CADENA5
   *
   * @param cadena5
   *          the value for dbo.TST_VENTAS.CADENA5
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setCadena5(String cadena5) {
    this.cadena5 = cadena5 == null ? null : cadena5.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.NUMERICO1
   *
   * @return the value of dbo.TST_VENTAS.NUMERICO1
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Long getNumerico1() {
    return numerico1;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.NUMERICO1
   *
   * @param numerico1
   *          the value for dbo.TST_VENTAS.NUMERICO1
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setNumerico1(Long numerico1) {
    this.numerico1 = numerico1;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.NUMERICO2
   *
   * @return the value of dbo.TST_VENTAS.NUMERICO2
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Long getNumerico2() {
    return numerico2;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.NUMERICO2
   *
   * @param numerico2
   *          the value for dbo.TST_VENTAS.NUMERICO2
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setNumerico2(Long numerico2) {
    this.numerico2 = numerico2;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.NUMERICO3
   *
   * @return the value of dbo.TST_VENTAS.NUMERICO3
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Long getNumerico3() {
    return numerico3;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.NUMERICO3
   *
   * @param numerico3
   *          the value for dbo.TST_VENTAS.NUMERICO3
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setNumerico3(Long numerico3) {
    this.numerico3 = numerico3;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.NUMERICO4
   *
   * @return the value of dbo.TST_VENTAS.NUMERICO4
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Long getNumerico4() {
    return numerico4;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.NUMERICO4
   *
   * @param numerico4
   *          the value for dbo.TST_VENTAS.NUMERICO4
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setNumerico4(Long numerico4) {
    this.numerico4 = numerico4;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.NUMERICO5
   *
   * @return the value of dbo.TST_VENTAS.NUMERICO5
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Long getNumerico5() {
    return numerico5;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.NUMERICO5
   *
   * @param numerico5
   *          the value for dbo.TST_VENTAS.NUMERICO5
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setNumerico5(Long numerico5) {
    this.numerico5 = numerico5;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.FECHA1
   *
   * @return the value of dbo.TST_VENTAS.FECHA1
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Date getFecha1() {
    return fecha1;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.FECHA1
   *
   * @param fecha1
   *          the value for dbo.TST_VENTAS.FECHA1
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setFecha1(Date fecha1) {
    this.fecha1 = fecha1;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.FECHA2
   *
   * @return the value of dbo.TST_VENTAS.FECHA2
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Date getFecha2() {
    return fecha2;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.FECHA2
   *
   * @param fecha2
   *          the value for dbo.TST_VENTAS.FECHA2
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setFecha2(Date fecha2) {
    this.fecha2 = fecha2;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.FECHA3
   *
   * @return the value of dbo.TST_VENTAS.FECHA3
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Date getFecha3() {
    return fecha3;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.FECHA3
   *
   * @param fecha3
   *          the value for dbo.TST_VENTAS.FECHA3
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setFecha3(Date fecha3) {
    this.fecha3 = fecha3;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.FECHA4
   *
   * @return the value of dbo.TST_VENTAS.FECHA4
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Date getFecha4() {
    return fecha4;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.FECHA4
   *
   * @param fecha4
   *          the value for dbo.TST_VENTAS.FECHA4
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setFecha4(Date fecha4) {
    this.fecha4 = fecha4;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.FECHA5
   *
   * @return the value of dbo.TST_VENTAS.FECHA5
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Date getFecha5() {
    return fecha5;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.FECHA5
   *
   * @param fecha5
   *          the value for dbo.TST_VENTAS.FECHA5
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setFecha5(Date fecha5) {
    this.fecha5 = fecha5;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.CONSECUTIVO
   *
   * @return the value of dbo.TST_VENTAS.CONSECUTIVO
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Integer getConsecutivo() {
    return consecutivo;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.CONSECUTIVO
   *
   * @param consecutivo
   *          the value for dbo.TST_VENTAS.CONSECUTIVO
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setConsecutivo(Integer consecutivo) {
    this.consecutivo = consecutivo;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.NUMER1
   *
   * @return the value of dbo.TST_VENTAS.NUMER1
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public BigDecimal getNumer1() {
    return numer1;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.NUMER1
   *
   * @param numer1
   *          the value for dbo.TST_VENTAS.NUMER1
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setNumer1(BigDecimal numer1) {
    this.numer1 = numer1;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.NUMER2
   *
   * @return the value of dbo.TST_VENTAS.NUMER2
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public BigDecimal getNumer2() {
    return numer2;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.NUMER2
   *
   * @param numer2
   *          the value for dbo.TST_VENTAS.NUMER2
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setNumer2(BigDecimal numer2) {
    this.numer2 = numer2;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.NUMER3
   *
   * @return the value of dbo.TST_VENTAS.NUMER3
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public BigDecimal getNumer3() {
    return numer3;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.NUMER3
   *
   * @param numer3
   *          the value for dbo.TST_VENTAS.NUMER3
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setNumer3(BigDecimal numer3) {
    this.numer3 = numer3;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.NUMER4
   *
   * @return the value of dbo.TST_VENTAS.NUMER4
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public BigDecimal getNumer4() {
    return numer4;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.NUMER4
   *
   * @param numer4
   *          the value for dbo.TST_VENTAS.NUMER4
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setNumer4(BigDecimal numer4) {
    this.numer4 = numer4;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.NUMER5
   *
   * @return the value of dbo.TST_VENTAS.NUMER5
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public BigDecimal getNumer5() {
    return numer5;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.NUMER5
   *
   * @param numer5
   *          the value for dbo.TST_VENTAS.NUMER5
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setNumer5(BigDecimal numer5) {
    this.numer5 = numer5;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.TEXTO1
   *
   * @return the value of dbo.TST_VENTAS.TEXTO1
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getTexto1() {
    return texto1;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.TEXTO1
   *
   * @param texto1
   *          the value for dbo.TST_VENTAS.TEXTO1
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setTexto1(String texto1) {
    this.texto1 = texto1 == null ? null : texto1.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.TEXTO2
   *
   * @return the value of dbo.TST_VENTAS.TEXTO2
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getTexto2() {
    return texto2;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.TEXTO2
   *
   * @param texto2
   *          the value for dbo.TST_VENTAS.TEXTO2
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setTexto2(String texto2) {
    this.texto2 = texto2 == null ? null : texto2.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.TEXTO3
   *
   * @return the value of dbo.TST_VENTAS.TEXTO3
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getTexto3() {
    return texto3;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.TEXTO3
   *
   * @param texto3
   *          the value for dbo.TST_VENTAS.TEXTO3
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setTexto3(String texto3) {
    this.texto3 = texto3 == null ? null : texto3.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.TEXTO4
   *
   * @return the value of dbo.TST_VENTAS.TEXTO4
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getTexto4() {
    return texto4;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.TEXTO4
   *
   * @param texto4
   *          the value for dbo.TST_VENTAS.TEXTO4
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setTexto4(String texto4) {
    this.texto4 = texto4 == null ? null : texto4.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.TEXTO5
   *
   * @return the value of dbo.TST_VENTAS.TEXTO5
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getTexto5() {
    return texto5;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.TEXTO5
   *
   * @param texto5
   *          the value for dbo.TST_VENTAS.TEXTO5
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setTexto5(String texto5) {
    this.texto5 = texto5 == null ? null : texto5.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.FEC_CREACION
   *
   * @return the value of dbo.TST_VENTAS.FEC_CREACION
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Date getFecCreacion() {
    return fecCreacion;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.FEC_CREACION
   *
   * @param fecCreacion
   *          the value for dbo.TST_VENTAS.FEC_CREACION
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setFecCreacion(Date fecCreacion) {
    this.fecCreacion = fecCreacion;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.USU_CREACION
   *
   * @return the value of dbo.TST_VENTAS.USU_CREACION
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getUsuCreacion() {
    return usuCreacion;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.USU_CREACION
   *
   * @param usuCreacion
   *          the value for dbo.TST_VENTAS.USU_CREACION
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setUsuCreacion(String usuCreacion) {
    this.usuCreacion = usuCreacion == null ? null : usuCreacion.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.FEC_MODIFICACION
   *
   * @return the value of dbo.TST_VENTAS.FEC_MODIFICACION
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public Date getFecModificacion() {
    return fecModificacion;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.FEC_MODIFICACION
   *
   * @param fecModificacion
   *          the value for dbo.TST_VENTAS.FEC_MODIFICACION
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setFecModificacion(Date fecModificacion) {
    this.fecModificacion = fecModificacion;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.TST_VENTAS.USU_MODIFICACION
   *
   * @return the value of dbo.TST_VENTAS.USU_MODIFICACION
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public String getUsuModificacion() {
    return usuModificacion;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.TST_VENTAS.USU_MODIFICACION
   *
   * @param usuModificacion
   *          the value for dbo.TST_VENTAS.USU_MODIFICACION
   *
   * @mbggenerated Thu Aug 08 17:52:27 COT 2013
   */
  public void setUsuModificacion(String usuModificacion) {
    this.usuModificacion = usuModificacion == null ? null : usuModificacion.trim();
  }
}