package com.cardif.satelite.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VentaSoatEmplExample implements Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.POLIZA_SOAT_EMPL
   *
   * @mbggenerated Wed Sep 24 17:41:29 COT 2014
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.POLIZA_SOAT_EMPL
   *
   * @mbggenerated Wed Sep 24 17:41:29 COT 2014
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.POLIZA_SOAT_EMPL
   *
   * @mbggenerated Wed Sep 24 17:41:29 COT 2014
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.POLIZA_SOAT_EMPL
   *
   * @mbggenerated Wed Sep 24 17:41:29 COT 2014
   */
  public VentaSoatEmplExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.POLIZA_SOAT_EMPL
   *
   * @mbggenerated Wed Sep 24 17:41:29 COT 2014
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.POLIZA_SOAT_EMPL
   *
   * @mbggenerated Wed Sep 24 17:41:29 COT 2014
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.POLIZA_SOAT_EMPL
   *
   * @mbggenerated Wed Sep 24 17:41:29 COT 2014
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.POLIZA_SOAT_EMPL
   *
   * @mbggenerated Wed Sep 24 17:41:29 COT 2014
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.POLIZA_SOAT_EMPL
   *
   * @mbggenerated Wed Sep 24 17:41:29 COT 2014
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.POLIZA_SOAT_EMPL
   *
   * @mbggenerated Wed Sep 24 17:41:29 COT 2014
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.POLIZA_SOAT_EMPL
   *
   * @mbggenerated Wed Sep 24 17:41:29 COT 2014
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.POLIZA_SOAT_EMPL
   *
   * @mbggenerated Wed Sep 24 17:41:29 COT 2014
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.POLIZA_SOAT_EMPL
   *
   * @mbggenerated Wed Sep 24 17:41:29 COT 2014
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.POLIZA_SOAT_EMPL
   *
   * @mbggenerated Wed Sep 24 17:41:29 COT 2014
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.POLIZA_SOAT_EMPL
   *
   * @mbggenerated Wed Sep 24 17:41:29 COT 2014
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andNroPolizaIsNull() {
      addCriterion("NRO_POLIZA is null");
      return (Criteria) this;
    }

    public Criteria andNroPolizaIsNotNull() {
      addCriterion("NRO_POLIZA is not null");
      return (Criteria) this;
    }

    public Criteria andNroPolizaEqualTo(String value) {
      addCriterion("NRO_POLIZA =", value, "nroPoliza");
      return (Criteria) this;
    }

    public Criteria andNroPolizaNotEqualTo(String value) {
      addCriterion("NRO_POLIZA <>", value, "nroPoliza");
      return (Criteria) this;
    }

    public Criteria andNroPolizaGreaterThan(String value) {
      addCriterion("NRO_POLIZA >", value, "nroPoliza");
      return (Criteria) this;
    }

    public Criteria andNroPolizaGreaterThanOrEqualTo(String value) {
      addCriterion("NRO_POLIZA >=", value, "nroPoliza");
      return (Criteria) this;
    }

    public Criteria andNroPolizaLessThan(String value) {
      addCriterion("NRO_POLIZA <", value, "nroPoliza");
      return (Criteria) this;
    }

    public Criteria andNroPolizaLessThanOrEqualTo(String value) {
      addCriterion("NRO_POLIZA <=", value, "nroPoliza");
      return (Criteria) this;
    }

    public Criteria andNroPolizaIn(List<String> values) {
      addCriterion("NRO_POLIZA in", values, "nroPoliza");
      return (Criteria) this;
    }

    public Criteria andNroPolizaNotIn(List<String> values) {
      addCriterion("NRO_POLIZA not in", values, "nroPoliza");
      return (Criteria) this;
    }

    public Criteria andNroPolizaBetween(String value1, String value2) {
      addCriterion("NRO_POLIZA between", value1, value2, "nroPoliza");
      return (Criteria) this;
    }

    public Criteria andNroPolizaNotBetween(String value1, String value2) {
      addCriterion("NRO_POLIZA not between", value1, value2, "nroPoliza");
      return (Criteria) this;
    }

    public Criteria andPlacaIsNull() {
      addCriterion("PLACA is null");
      return (Criteria) this;
    }

    public Criteria andPlacaIsNotNull() {
      addCriterion("PLACA is not null");
      return (Criteria) this;
    }

    public Criteria andPlacaEqualTo(String value) {
      addCriterion("PLACA =", value, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaNotEqualTo(String value) {
      addCriterion("PLACA <>", value, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaGreaterThan(String value) {
      addCriterion("PLACA >", value, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaGreaterThanOrEqualTo(String value) {
      addCriterion("PLACA >=", value, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaLessThan(String value) {
      addCriterion("PLACA <", value, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaLessThanOrEqualTo(String value) {
      addCriterion("PLACA <=", value, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaIn(List<String> values) {
      addCriterion("PLACA in", values, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaNotIn(List<String> values) {
      addCriterion("PLACA not in", values, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaBetween(String value1, String value2) {
      addCriterion("PLACA between", value1, value2, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaNotBetween(String value1, String value2) {
      addCriterion("PLACA not between", value1, value2, "placa");
      return (Criteria) this;
    }

    public Criteria andMarcaIsNull() {
      addCriterion("MARCA is null");
      return (Criteria) this;
    }

    public Criteria andMarcaIsNotNull() {
      addCriterion("MARCA is not null");
      return (Criteria) this;
    }

    public Criteria andMarcaEqualTo(String value) {
      addCriterion("MARCA =", value, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaNotEqualTo(String value) {
      addCriterion("MARCA <>", value, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaGreaterThan(String value) {
      addCriterion("MARCA >", value, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaGreaterThanOrEqualTo(String value) {
      addCriterion("MARCA >=", value, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaLessThan(String value) {
      addCriterion("MARCA <", value, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaLessThanOrEqualTo(String value) {
      addCriterion("MARCA <=", value, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaIn(List<String> values) {
      addCriterion("MARCA in", values, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaNotIn(List<String> values) {
      addCriterion("MARCA not in", values, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaBetween(String value1, String value2) {
      addCriterion("MARCA between", value1, value2, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaNotBetween(String value1, String value2) {
      addCriterion("MARCA not between", value1, value2, "marca");
      return (Criteria) this;
    }

    public Criteria andModeloIsNull() {
      addCriterion("MODELO is null");
      return (Criteria) this;
    }

    public Criteria andModeloIsNotNull() {
      addCriterion("MODELO is not null");
      return (Criteria) this;
    }

    public Criteria andModeloEqualTo(String value) {
      addCriterion("MODELO =", value, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloNotEqualTo(String value) {
      addCriterion("MODELO <>", value, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloGreaterThan(String value) {
      addCriterion("MODELO >", value, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloGreaterThanOrEqualTo(String value) {
      addCriterion("MODELO >=", value, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloLessThan(String value) {
      addCriterion("MODELO <", value, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloLessThanOrEqualTo(String value) {
      addCriterion("MODELO <=", value, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloIn(List<String> values) {
      addCriterion("MODELO in", values, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloNotIn(List<String> values) {
      addCriterion("MODELO not in", values, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloBetween(String value1, String value2) {
      addCriterion("MODELO between", value1, value2, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloNotBetween(String value1, String value2) {
      addCriterion("MODELO not between", value1, value2, "modelo");
      return (Criteria) this;
    }

    public Criteria andSerieIsNull() {
      addCriterion("SERIE is null");
      return (Criteria) this;
    }

    public Criteria andSerieIsNotNull() {
      addCriterion("SERIE is not null");
      return (Criteria) this;
    }

    public Criteria andSerieEqualTo(String value) {
      addCriterion("SERIE =", value, "serie");
      return (Criteria) this;
    }

    public Criteria andSerieNotEqualTo(String value) {
      addCriterion("SERIE <>", value, "serie");
      return (Criteria) this;
    }

    public Criteria andSerieGreaterThan(String value) {
      addCriterion("SERIE >", value, "serie");
      return (Criteria) this;
    }

    public Criteria andSerieGreaterThanOrEqualTo(String value) {
      addCriterion("SERIE >=", value, "serie");
      return (Criteria) this;
    }

    public Criteria andSerieLessThan(String value) {
      addCriterion("SERIE <", value, "serie");
      return (Criteria) this;
    }

    public Criteria andSerieLessThanOrEqualTo(String value) {
      addCriterion("SERIE <=", value, "serie");
      return (Criteria) this;
    }

    public Criteria andSerieIn(List<String> values) {
      addCriterion("SERIE in", values, "serie");
      return (Criteria) this;
    }

    public Criteria andSerieNotIn(List<String> values) {
      addCriterion("SERIE not in", values, "serie");
      return (Criteria) this;
    }

    public Criteria andSerieBetween(String value1, String value2) {
      addCriterion("SERIE between", value1, value2, "serie");
      return (Criteria) this;
    }

    public Criteria andSerieNotBetween(String value1, String value2) {
      addCriterion("SERIE not between", value1, value2, "serie");
      return (Criteria) this;
    }

    public Criteria andAnioFabricacionIsNull() {
      addCriterion("ANIO_FABRICACION is null");
      return (Criteria) this;
    }

    public Criteria andAnioFabricacionIsNotNull() {
      addCriterion("ANIO_FABRICACION is not null");
      return (Criteria) this;
    }

    public Criteria andAnioFabricacionEqualTo(Short value) {
      addCriterion("ANIO_FABRICACION =", value, "anioFabricacion");
      return (Criteria) this;
    }

    public Criteria andAnioFabricacionNotEqualTo(Short value) {
      addCriterion("ANIO_FABRICACION <>", value, "anioFabricacion");
      return (Criteria) this;
    }

    public Criteria andAnioFabricacionGreaterThan(Short value) {
      addCriterion("ANIO_FABRICACION >", value, "anioFabricacion");
      return (Criteria) this;
    }

    public Criteria andAnioFabricacionGreaterThanOrEqualTo(Short value) {
      addCriterion("ANIO_FABRICACION >=", value, "anioFabricacion");
      return (Criteria) this;
    }

    public Criteria andAnioFabricacionLessThan(Short value) {
      addCriterion("ANIO_FABRICACION <", value, "anioFabricacion");
      return (Criteria) this;
    }

    public Criteria andAnioFabricacionLessThanOrEqualTo(Short value) {
      addCriterion("ANIO_FABRICACION <=", value, "anioFabricacion");
      return (Criteria) this;
    }

    public Criteria andAnioFabricacionIn(List<Short> values) {
      addCriterion("ANIO_FABRICACION in", values, "anioFabricacion");
      return (Criteria) this;
    }

    public Criteria andAnioFabricacionNotIn(List<Short> values) {
      addCriterion("ANIO_FABRICACION not in", values, "anioFabricacion");
      return (Criteria) this;
    }

    public Criteria andAnioFabricacionBetween(Short value1, Short value2) {
      addCriterion("ANIO_FABRICACION between", value1, value2, "anioFabricacion");
      return (Criteria) this;
    }

    public Criteria andAnioFabricacionNotBetween(Short value1, Short value2) {
      addCriterion("ANIO_FABRICACION not between", value1, value2, "anioFabricacion");
      return (Criteria) this;
    }

    public Criteria andUsoIsNull() {
      addCriterion("USO is null");
      return (Criteria) this;
    }

    public Criteria andUsoIsNotNull() {
      addCriterion("USO is not null");
      return (Criteria) this;
    }

    public Criteria andUsoEqualTo(String value) {
      addCriterion("USO =", value, "uso");
      return (Criteria) this;
    }

    public Criteria andUsoNotEqualTo(String value) {
      addCriterion("USO <>", value, "uso");
      return (Criteria) this;
    }

    public Criteria andUsoGreaterThan(String value) {
      addCriterion("USO >", value, "uso");
      return (Criteria) this;
    }

    public Criteria andUsoGreaterThanOrEqualTo(String value) {
      addCriterion("USO >=", value, "uso");
      return (Criteria) this;
    }

    public Criteria andUsoLessThan(String value) {
      addCriterion("USO <", value, "uso");
      return (Criteria) this;
    }

    public Criteria andUsoLessThanOrEqualTo(String value) {
      addCriterion("USO <=", value, "uso");
      return (Criteria) this;
    }

    public Criteria andUsoIn(List<String> values) {
      addCriterion("USO in", values, "uso");
      return (Criteria) this;
    }

    public Criteria andUsoNotIn(List<String> values) {
      addCriterion("USO not in", values, "uso");
      return (Criteria) this;
    }

    public Criteria andUsoBetween(String value1, String value2) {
      addCriterion("USO between", value1, value2, "uso");
      return (Criteria) this;
    }

    public Criteria andUsoNotBetween(String value1, String value2) {
      addCriterion("USO not between", value1, value2, "uso");
      return (Criteria) this;
    }

    public Criteria andCategoriaIsNull() {
      addCriterion("CATEGORIA is null");
      return (Criteria) this;
    }

    public Criteria andCategoriaIsNotNull() {
      addCriterion("CATEGORIA is not null");
      return (Criteria) this;
    }

    public Criteria andCategoriaEqualTo(String value) {
      addCriterion("CATEGORIA =", value, "categoria");
      return (Criteria) this;
    }

    public Criteria andCategoriaNotEqualTo(String value) {
      addCriterion("CATEGORIA <>", value, "categoria");
      return (Criteria) this;
    }

    public Criteria andCategoriaGreaterThan(String value) {
      addCriterion("CATEGORIA >", value, "categoria");
      return (Criteria) this;
    }

    public Criteria andCategoriaGreaterThanOrEqualTo(String value) {
      addCriterion("CATEGORIA >=", value, "categoria");
      return (Criteria) this;
    }

    public Criteria andCategoriaLessThan(String value) {
      addCriterion("CATEGORIA <", value, "categoria");
      return (Criteria) this;
    }

    public Criteria andCategoriaLessThanOrEqualTo(String value) {
      addCriterion("CATEGORIA <=", value, "categoria");
      return (Criteria) this;
    }

    public Criteria andCategoriaIn(List<String> values) {
      addCriterion("CATEGORIA in", values, "categoria");
      return (Criteria) this;
    }

    public Criteria andCategoriaNotIn(List<String> values) {
      addCriterion("CATEGORIA not in", values, "categoria");
      return (Criteria) this;
    }

    public Criteria andCategoriaBetween(String value1, String value2) {
      addCriterion("CATEGORIA between", value1, value2, "categoria");
      return (Criteria) this;
    }

    public Criteria andCategoriaNotBetween(String value1, String value2) {
      addCriterion("CATEGORIA not between", value1, value2, "categoria");
      return (Criteria) this;
    }

    public Criteria andNroAsientosIsNull() {
      addCriterion("NRO_ASIENTOS is null");
      return (Criteria) this;
    }

    public Criteria andNroAsientosIsNotNull() {
      addCriterion("NRO_ASIENTOS is not null");
      return (Criteria) this;
    }

    public Criteria andNroAsientosEqualTo(Short value) {
      addCriterion("NRO_ASIENTOS =", value, "nroAsientos");
      return (Criteria) this;
    }

    public Criteria andNroAsientosNotEqualTo(Short value) {
      addCriterion("NRO_ASIENTOS <>", value, "nroAsientos");
      return (Criteria) this;
    }

    public Criteria andNroAsientosGreaterThan(Short value) {
      addCriterion("NRO_ASIENTOS >", value, "nroAsientos");
      return (Criteria) this;
    }

    public Criteria andNroAsientosGreaterThanOrEqualTo(Short value) {
      addCriterion("NRO_ASIENTOS >=", value, "nroAsientos");
      return (Criteria) this;
    }

    public Criteria andNroAsientosLessThan(Short value) {
      addCriterion("NRO_ASIENTOS <", value, "nroAsientos");
      return (Criteria) this;
    }

    public Criteria andNroAsientosLessThanOrEqualTo(Short value) {
      addCriterion("NRO_ASIENTOS <=", value, "nroAsientos");
      return (Criteria) this;
    }

    public Criteria andNroAsientosIn(List<Short> values) {
      addCriterion("NRO_ASIENTOS in", values, "nroAsientos");
      return (Criteria) this;
    }

    public Criteria andNroAsientosNotIn(List<Short> values) {
      addCriterion("NRO_ASIENTOS not in", values, "nroAsientos");
      return (Criteria) this;
    }

    public Criteria andNroAsientosBetween(Short value1, Short value2) {
      addCriterion("NRO_ASIENTOS between", value1, value2, "nroAsientos");
      return (Criteria) this;
    }

    public Criteria andNroAsientosNotBetween(Short value1, Short value2) {
      addCriterion("NRO_ASIENTOS not between", value1, value2, "nroAsientos");
      return (Criteria) this;
    }

    public Criteria andDepartamentoIsNull() {
      addCriterion("DEPARTAMENTO is null");
      return (Criteria) this;
    }

    public Criteria andDepartamentoIsNotNull() {
      addCriterion("DEPARTAMENTO is not null");
      return (Criteria) this;
    }

    public Criteria andDepartamentoEqualTo(String value) {
      addCriterion("DEPARTAMENTO =", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoNotEqualTo(String value) {
      addCriterion("DEPARTAMENTO <>", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoGreaterThan(String value) {
      addCriterion("DEPARTAMENTO >", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoGreaterThanOrEqualTo(String value) {
      addCriterion("DEPARTAMENTO >=", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoLessThan(String value) {
      addCriterion("DEPARTAMENTO <", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoLessThanOrEqualTo(String value) {
      addCriterion("DEPARTAMENTO <=", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoIn(List<String> values) {
      addCriterion("DEPARTAMENTO in", values, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoNotIn(List<String> values) {
      addCriterion("DEPARTAMENTO not in", values, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoBetween(String value1, String value2) {
      addCriterion("DEPARTAMENTO between", value1, value2, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoNotBetween(String value1, String value2) {
      addCriterion("DEPARTAMENTO not between", value1, value2, "departamento");
      return (Criteria) this;
    }

    public Criteria andPrimaIsNull() {
      addCriterion("PRIMA is null");
      return (Criteria) this;
    }

    public Criteria andPrimaIsNotNull() {
      addCriterion("PRIMA is not null");
      return (Criteria) this;
    }

    public Criteria andPrimaEqualTo(BigDecimal value) {
      addCriterion("PRIMA =", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaNotEqualTo(BigDecimal value) {
      addCriterion("PRIMA <>", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaGreaterThan(BigDecimal value) {
      addCriterion("PRIMA >", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("PRIMA >=", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaLessThan(BigDecimal value) {
      addCriterion("PRIMA <", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaLessThanOrEqualTo(BigDecimal value) {
      addCriterion("PRIMA <=", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaIn(List<BigDecimal> values) {
      addCriterion("PRIMA in", values, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaNotIn(List<BigDecimal> values) {
      addCriterion("PRIMA not in", values, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PRIMA between", value1, value2, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PRIMA not between", value1, value2, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaIsNull() {
      addCriterion("PRIMA_TECNICA is null");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaIsNotNull() {
      addCriterion("PRIMA_TECNICA is not null");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaEqualTo(BigDecimal value) {
      addCriterion("PRIMA_TECNICA =", value, "primaTecnica");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaNotEqualTo(BigDecimal value) {
      addCriterion("PRIMA_TECNICA <>", value, "primaTecnica");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaGreaterThan(BigDecimal value) {
      addCriterion("PRIMA_TECNICA >", value, "primaTecnica");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("PRIMA_TECNICA >=", value, "primaTecnica");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaLessThan(BigDecimal value) {
      addCriterion("PRIMA_TECNICA <", value, "primaTecnica");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaLessThanOrEqualTo(BigDecimal value) {
      addCriterion("PRIMA_TECNICA <=", value, "primaTecnica");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaIn(List<BigDecimal> values) {
      addCriterion("PRIMA_TECNICA in", values, "primaTecnica");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaNotIn(List<BigDecimal> values) {
      addCriterion("PRIMA_TECNICA not in", values, "primaTecnica");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PRIMA_TECNICA between", value1, value2, "primaTecnica");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PRIMA_TECNICA not between", value1, value2, "primaTecnica");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoIsNull() {
      addCriterion("TIP_DOCUMENTO is null");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoIsNotNull() {
      addCriterion("TIP_DOCUMENTO is not null");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoEqualTo(String value) {
      addCriterion("TIP_DOCUMENTO =", value, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoNotEqualTo(String value) {
      addCriterion("TIP_DOCUMENTO <>", value, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoGreaterThan(String value) {
      addCriterion("TIP_DOCUMENTO >", value, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoGreaterThanOrEqualTo(String value) {
      addCriterion("TIP_DOCUMENTO >=", value, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoLessThan(String value) {
      addCriterion("TIP_DOCUMENTO <", value, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoLessThanOrEqualTo(String value) {
      addCriterion("TIP_DOCUMENTO <=", value, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoIn(List<String> values) {
      addCriterion("TIP_DOCUMENTO in", values, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoNotIn(List<String> values) {
      addCriterion("TIP_DOCUMENTO not in", values, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoBetween(String value1, String value2) {
      addCriterion("TIP_DOCUMENTO between", value1, value2, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoNotBetween(String value1, String value2) {
      addCriterion("TIP_DOCUMENTO not between", value1, value2, "tipDocumento");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoIsNull() {
      addCriterion("NRO_DOCUMENTO is null");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoIsNotNull() {
      addCriterion("NRO_DOCUMENTO is not null");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoEqualTo(String value) {
      addCriterion("NRO_DOCUMENTO =", value, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoNotEqualTo(String value) {
      addCriterion("NRO_DOCUMENTO <>", value, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoGreaterThan(String value) {
      addCriterion("NRO_DOCUMENTO >", value, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoGreaterThanOrEqualTo(String value) {
      addCriterion("NRO_DOCUMENTO >=", value, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoLessThan(String value) {
      addCriterion("NRO_DOCUMENTO <", value, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoLessThanOrEqualTo(String value) {
      addCriterion("NRO_DOCUMENTO <=", value, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoIn(List<String> values) {
      addCriterion("NRO_DOCUMENTO in", values, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoNotIn(List<String> values) {
      addCriterion("NRO_DOCUMENTO not in", values, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoBetween(String value1, String value2) {
      addCriterion("NRO_DOCUMENTO between", value1, value2, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoNotBetween(String value1, String value2) {
      addCriterion("NRO_DOCUMENTO not between", value1, value2, "nroDocumento");
      return (Criteria) this;
    }

    public Criteria andNomContratIsNull() {
      addCriterion("NOM_CONTRAT is null");
      return (Criteria) this;
    }

    public Criteria andNomContratIsNotNull() {
      addCriterion("NOM_CONTRAT is not null");
      return (Criteria) this;
    }

    public Criteria andNomContratEqualTo(String value) {
      addCriterion("NOM_CONTRAT =", value, "nomContrat");
      return (Criteria) this;
    }

    public Criteria andNomContratNotEqualTo(String value) {
      addCriterion("NOM_CONTRAT <>", value, "nomContrat");
      return (Criteria) this;
    }

    public Criteria andNomContratGreaterThan(String value) {
      addCriterion("NOM_CONTRAT >", value, "nomContrat");
      return (Criteria) this;
    }

    public Criteria andNomContratGreaterThanOrEqualTo(String value) {
      addCriterion("NOM_CONTRAT >=", value, "nomContrat");
      return (Criteria) this;
    }

    public Criteria andNomContratLessThan(String value) {
      addCriterion("NOM_CONTRAT <", value, "nomContrat");
      return (Criteria) this;
    }

    public Criteria andNomContratLessThanOrEqualTo(String value) {
      addCriterion("NOM_CONTRAT <=", value, "nomContrat");
      return (Criteria) this;
    }

    public Criteria andNomContratIn(List<String> values) {
      addCriterion("NOM_CONTRAT in", values, "nomContrat");
      return (Criteria) this;
    }

    public Criteria andNomContratNotIn(List<String> values) {
      addCriterion("NOM_CONTRAT not in", values, "nomContrat");
      return (Criteria) this;
    }

    public Criteria andNomContratBetween(String value1, String value2) {
      addCriterion("NOM_CONTRAT between", value1, value2, "nomContrat");
      return (Criteria) this;
    }

    public Criteria andNomContratNotBetween(String value1, String value2) {
      addCriterion("NOM_CONTRAT not between", value1, value2, "nomContrat");
      return (Criteria) this;
    }

    public Criteria andApePatcontratIsNull() {
      addCriterion("APE_PATCONTRAT is null");
      return (Criteria) this;
    }

    public Criteria andApePatcontratIsNotNull() {
      addCriterion("APE_PATCONTRAT is not null");
      return (Criteria) this;
    }

    public Criteria andApePatcontratEqualTo(String value) {
      addCriterion("APE_PATCONTRAT =", value, "apePatcontrat");
      return (Criteria) this;
    }

    public Criteria andApePatcontratNotEqualTo(String value) {
      addCriterion("APE_PATCONTRAT <>", value, "apePatcontrat");
      return (Criteria) this;
    }

    public Criteria andApePatcontratGreaterThan(String value) {
      addCriterion("APE_PATCONTRAT >", value, "apePatcontrat");
      return (Criteria) this;
    }

    public Criteria andApePatcontratGreaterThanOrEqualTo(String value) {
      addCriterion("APE_PATCONTRAT >=", value, "apePatcontrat");
      return (Criteria) this;
    }

    public Criteria andApePatcontratLessThan(String value) {
      addCriterion("APE_PATCONTRAT <", value, "apePatcontrat");
      return (Criteria) this;
    }

    public Criteria andApePatcontratLessThanOrEqualTo(String value) {
      addCriterion("APE_PATCONTRAT <=", value, "apePatcontrat");
      return (Criteria) this;
    }

    public Criteria andApePatcontratIn(List<String> values) {
      addCriterion("APE_PATCONTRAT in", values, "apePatcontrat");
      return (Criteria) this;
    }

    public Criteria andApePatcontratNotIn(List<String> values) {
      addCriterion("APE_PATCONTRAT not in", values, "apePatcontrat");
      return (Criteria) this;
    }

    public Criteria andApePatcontratBetween(String value1, String value2) {
      addCriterion("APE_PATCONTRAT between", value1, value2, "apePatcontrat");
      return (Criteria) this;
    }

    public Criteria andApePatcontratNotBetween(String value1, String value2) {
      addCriterion("APE_PATCONTRAT not between", value1, value2, "apePatcontrat");
      return (Criteria) this;
    }

    public Criteria andApeMatcontratIsNull() {
      addCriterion("APE_MATCONTRAT is null");
      return (Criteria) this;
    }

    public Criteria andApeMatcontratIsNotNull() {
      addCriterion("APE_MATCONTRAT is not null");
      return (Criteria) this;
    }

    public Criteria andApeMatcontratEqualTo(String value) {
      addCriterion("APE_MATCONTRAT =", value, "apeMatcontrat");
      return (Criteria) this;
    }

    public Criteria andApeMatcontratNotEqualTo(String value) {
      addCriterion("APE_MATCONTRAT <>", value, "apeMatcontrat");
      return (Criteria) this;
    }

    public Criteria andApeMatcontratGreaterThan(String value) {
      addCriterion("APE_MATCONTRAT >", value, "apeMatcontrat");
      return (Criteria) this;
    }

    public Criteria andApeMatcontratGreaterThanOrEqualTo(String value) {
      addCriterion("APE_MATCONTRAT >=", value, "apeMatcontrat");
      return (Criteria) this;
    }

    public Criteria andApeMatcontratLessThan(String value) {
      addCriterion("APE_MATCONTRAT <", value, "apeMatcontrat");
      return (Criteria) this;
    }

    public Criteria andApeMatcontratLessThanOrEqualTo(String value) {
      addCriterion("APE_MATCONTRAT <=", value, "apeMatcontrat");
      return (Criteria) this;
    }

    public Criteria andApeMatcontratIn(List<String> values) {
      addCriterion("APE_MATCONTRAT in", values, "apeMatcontrat");
      return (Criteria) this;
    }

    public Criteria andApeMatcontratNotIn(List<String> values) {
      addCriterion("APE_MATCONTRAT not in", values, "apeMatcontrat");
      return (Criteria) this;
    }

    public Criteria andApeMatcontratBetween(String value1, String value2) {
      addCriterion("APE_MATCONTRAT between", value1, value2, "apeMatcontrat");
      return (Criteria) this;
    }

    public Criteria andApeMatcontratNotBetween(String value1, String value2) {
      addCriterion("APE_MATCONTRAT not between", value1, value2, "apeMatcontrat");
      return (Criteria) this;
    }

    public Criteria andFecNacimientoIsNull() {
      addCriterion("FEC_NACIMIENTO is null");
      return (Criteria) this;
    }

    public Criteria andFecNacimientoIsNotNull() {
      addCriterion("FEC_NACIMIENTO is not null");
      return (Criteria) this;
    }

    public Criteria andFecNacimientoEqualTo(Date value) {
      addCriterion("FEC_NACIMIENTO =", value, "fecNacimiento");
      return (Criteria) this;
    }

    public Criteria andFecNacimientoNotEqualTo(Date value) {
      addCriterion("FEC_NACIMIENTO <>", value, "fecNacimiento");
      return (Criteria) this;
    }

    public Criteria andFecNacimientoGreaterThan(Date value) {
      addCriterion("FEC_NACIMIENTO >", value, "fecNacimiento");
      return (Criteria) this;
    }

    public Criteria andFecNacimientoGreaterThanOrEqualTo(Date value) {
      addCriterion("FEC_NACIMIENTO >=", value, "fecNacimiento");
      return (Criteria) this;
    }

    public Criteria andFecNacimientoLessThan(Date value) {
      addCriterion("FEC_NACIMIENTO <", value, "fecNacimiento");
      return (Criteria) this;
    }

    public Criteria andFecNacimientoLessThanOrEqualTo(Date value) {
      addCriterion("FEC_NACIMIENTO <=", value, "fecNacimiento");
      return (Criteria) this;
    }

    public Criteria andFecNacimientoIn(List<Date> values) {
      addCriterion("FEC_NACIMIENTO in", values, "fecNacimiento");
      return (Criteria) this;
    }

    public Criteria andFecNacimientoNotIn(List<Date> values) {
      addCriterion("FEC_NACIMIENTO not in", values, "fecNacimiento");
      return (Criteria) this;
    }

    public Criteria andFecNacimientoBetween(Date value1, Date value2) {
      addCriterion("FEC_NACIMIENTO between", value1, value2, "fecNacimiento");
      return (Criteria) this;
    }

    public Criteria andFecNacimientoNotBetween(Date value1, Date value2) {
      addCriterion("FEC_NACIMIENTO not between", value1, value2, "fecNacimiento");
      return (Criteria) this;
    }

    public Criteria andDepContratIsNull() {
      addCriterion("DEP_CONTRAT is null");
      return (Criteria) this;
    }

    public Criteria andDepContratIsNotNull() {
      addCriterion("DEP_CONTRAT is not null");
      return (Criteria) this;
    }

    public Criteria andDepContratEqualTo(String value) {
      addCriterion("DEP_CONTRAT =", value, "depContrat");
      return (Criteria) this;
    }

    public Criteria andDepContratNotEqualTo(String value) {
      addCriterion("DEP_CONTRAT <>", value, "depContrat");
      return (Criteria) this;
    }

    public Criteria andDepContratGreaterThan(String value) {
      addCriterion("DEP_CONTRAT >", value, "depContrat");
      return (Criteria) this;
    }

    public Criteria andDepContratGreaterThanOrEqualTo(String value) {
      addCriterion("DEP_CONTRAT >=", value, "depContrat");
      return (Criteria) this;
    }

    public Criteria andDepContratLessThan(String value) {
      addCriterion("DEP_CONTRAT <", value, "depContrat");
      return (Criteria) this;
    }

    public Criteria andDepContratLessThanOrEqualTo(String value) {
      addCriterion("DEP_CONTRAT <=", value, "depContrat");
      return (Criteria) this;
    }

    public Criteria andDepContratIn(List<String> values) {
      addCriterion("DEP_CONTRAT in", values, "depContrat");
      return (Criteria) this;
    }

    public Criteria andDepContratNotIn(List<String> values) {
      addCriterion("DEP_CONTRAT not in", values, "depContrat");
      return (Criteria) this;
    }

    public Criteria andDepContratBetween(String value1, String value2) {
      addCriterion("DEP_CONTRAT between", value1, value2, "depContrat");
      return (Criteria) this;
    }

    public Criteria andDepContratNotBetween(String value1, String value2) {
      addCriterion("DEP_CONTRAT not between", value1, value2, "depContrat");
      return (Criteria) this;
    }

    public Criteria andProvContratIsNull() {
      addCriterion("PROV_CONTRAT is null");
      return (Criteria) this;
    }

    public Criteria andProvContratIsNotNull() {
      addCriterion("PROV_CONTRAT is not null");
      return (Criteria) this;
    }

    public Criteria andProvContratEqualTo(String value) {
      addCriterion("PROV_CONTRAT =", value, "provContrat");
      return (Criteria) this;
    }

    public Criteria andProvContratNotEqualTo(String value) {
      addCriterion("PROV_CONTRAT <>", value, "provContrat");
      return (Criteria) this;
    }

    public Criteria andProvContratGreaterThan(String value) {
      addCriterion("PROV_CONTRAT >", value, "provContrat");
      return (Criteria) this;
    }

    public Criteria andProvContratGreaterThanOrEqualTo(String value) {
      addCriterion("PROV_CONTRAT >=", value, "provContrat");
      return (Criteria) this;
    }

    public Criteria andProvContratLessThan(String value) {
      addCriterion("PROV_CONTRAT <", value, "provContrat");
      return (Criteria) this;
    }

    public Criteria andProvContratLessThanOrEqualTo(String value) {
      addCriterion("PROV_CONTRAT <=", value, "provContrat");
      return (Criteria) this;
    }

    public Criteria andProvContratIn(List<String> values) {
      addCriterion("PROV_CONTRAT in", values, "provContrat");
      return (Criteria) this;
    }

    public Criteria andProvContratNotIn(List<String> values) {
      addCriterion("PROV_CONTRAT not in", values, "provContrat");
      return (Criteria) this;
    }

    public Criteria andProvContratBetween(String value1, String value2) {
      addCriterion("PROV_CONTRAT between", value1, value2, "provContrat");
      return (Criteria) this;
    }

    public Criteria andProvContratNotBetween(String value1, String value2) {
      addCriterion("PROV_CONTRAT not between", value1, value2, "provContrat");
      return (Criteria) this;
    }

    public Criteria andDistContratIsNull() {
      addCriterion("DIST_CONTRAT is null");
      return (Criteria) this;
    }

    public Criteria andDistContratIsNotNull() {
      addCriterion("DIST_CONTRAT is not null");
      return (Criteria) this;
    }

    public Criteria andDistContratEqualTo(String value) {
      addCriterion("DIST_CONTRAT =", value, "distContrat");
      return (Criteria) this;
    }

    public Criteria andDistContratNotEqualTo(String value) {
      addCriterion("DIST_CONTRAT <>", value, "distContrat");
      return (Criteria) this;
    }

    public Criteria andDistContratGreaterThan(String value) {
      addCriterion("DIST_CONTRAT >", value, "distContrat");
      return (Criteria) this;
    }

    public Criteria andDistContratGreaterThanOrEqualTo(String value) {
      addCriterion("DIST_CONTRAT >=", value, "distContrat");
      return (Criteria) this;
    }

    public Criteria andDistContratLessThan(String value) {
      addCriterion("DIST_CONTRAT <", value, "distContrat");
      return (Criteria) this;
    }

    public Criteria andDistContratLessThanOrEqualTo(String value) {
      addCriterion("DIST_CONTRAT <=", value, "distContrat");
      return (Criteria) this;
    }

    public Criteria andDistContratIn(List<String> values) {
      addCriterion("DIST_CONTRAT in", values, "distContrat");
      return (Criteria) this;
    }

    public Criteria andDistContratNotIn(List<String> values) {
      addCriterion("DIST_CONTRAT not in", values, "distContrat");
      return (Criteria) this;
    }

    public Criteria andDistContratBetween(String value1, String value2) {
      addCriterion("DIST_CONTRAT between", value1, value2, "distContrat");
      return (Criteria) this;
    }

    public Criteria andDistContratNotBetween(String value1, String value2) {
      addCriterion("DIST_CONTRAT not between", value1, value2, "distContrat");
      return (Criteria) this;
    }

    public Criteria andDireccionIsNull() {
      addCriterion("DIRECCION is null");
      return (Criteria) this;
    }

    public Criteria andDireccionIsNotNull() {
      addCriterion("DIRECCION is not null");
      return (Criteria) this;
    }

    public Criteria andDireccionEqualTo(String value) {
      addCriterion("DIRECCION =", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionNotEqualTo(String value) {
      addCriterion("DIRECCION <>", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionGreaterThan(String value) {
      addCriterion("DIRECCION >", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionGreaterThanOrEqualTo(String value) {
      addCriterion("DIRECCION >=", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionLessThan(String value) {
      addCriterion("DIRECCION <", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionLessThanOrEqualTo(String value) {
      addCriterion("DIRECCION <=", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionIn(List<String> values) {
      addCriterion("DIRECCION in", values, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionNotIn(List<String> values) {
      addCriterion("DIRECCION not in", values, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionBetween(String value1, String value2) {
      addCriterion("DIRECCION between", value1, value2, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionNotBetween(String value1, String value2) {
      addCriterion("DIRECCION not between", value1, value2, "direccion");
      return (Criteria) this;
    }

    public Criteria andTelefonoIsNull() {
      addCriterion("TELEFONO is null");
      return (Criteria) this;
    }

    public Criteria andTelefonoIsNotNull() {
      addCriterion("TELEFONO is not null");
      return (Criteria) this;
    }

    public Criteria andTelefonoEqualTo(String value) {
      addCriterion("TELEFONO =", value, "telefono");
      return (Criteria) this;
    }

    public Criteria andTelefonoNotEqualTo(String value) {
      addCriterion("TELEFONO <>", value, "telefono");
      return (Criteria) this;
    }

    public Criteria andTelefonoGreaterThan(String value) {
      addCriterion("TELEFONO >", value, "telefono");
      return (Criteria) this;
    }

    public Criteria andTelefonoGreaterThanOrEqualTo(String value) {
      addCriterion("TELEFONO >=", value, "telefono");
      return (Criteria) this;
    }

    public Criteria andTelefonoLessThan(String value) {
      addCriterion("TELEFONO <", value, "telefono");
      return (Criteria) this;
    }

    public Criteria andTelefonoLessThanOrEqualTo(String value) {
      addCriterion("TELEFONO <=", value, "telefono");
      return (Criteria) this;
    }

    public Criteria andTelefonoIn(List<String> values) {
      addCriterion("TELEFONO in", values, "telefono");
      return (Criteria) this;
    }

    public Criteria andTelefonoNotIn(List<String> values) {
      addCriterion("TELEFONO not in", values, "telefono");
      return (Criteria) this;
    }

    public Criteria andTelefonoBetween(String value1, String value2) {
      addCriterion("TELEFONO between", value1, value2, "telefono");
      return (Criteria) this;
    }

    public Criteria andTelefonoNotBetween(String value1, String value2) {
      addCriterion("TELEFONO not between", value1, value2, "telefono");
      return (Criteria) this;
    }

    public Criteria andFecIniVigIsNull() {
      addCriterion("FEC_INI_VIG is null");
      return (Criteria) this;
    }

    public Criteria andFecIniVigIsNotNull() {
      addCriterion("FEC_INI_VIG is not null");
      return (Criteria) this;
    }

    public Criteria andFecIniVigEqualTo(Date value) {
      addCriterion("FEC_INI_VIG =", value, "fecIniVig");
      return (Criteria) this;
    }

    public Criteria andFecIniVigNotEqualTo(Date value) {
      addCriterion("FEC_INI_VIG <>", value, "fecIniVig");
      return (Criteria) this;
    }

    public Criteria andFecIniVigGreaterThan(Date value) {
      addCriterion("FEC_INI_VIG >", value, "fecIniVig");
      return (Criteria) this;
    }

    public Criteria andFecIniVigGreaterThanOrEqualTo(Date value) {
      addCriterion("FEC_INI_VIG >=", value, "fecIniVig");
      return (Criteria) this;
    }

    public Criteria andFecIniVigLessThan(Date value) {
      addCriterion("FEC_INI_VIG <", value, "fecIniVig");
      return (Criteria) this;
    }

    public Criteria andFecIniVigLessThanOrEqualTo(Date value) {
      addCriterion("FEC_INI_VIG <=", value, "fecIniVig");
      return (Criteria) this;
    }

    public Criteria andFecIniVigIn(List<Date> values) {
      addCriterion("FEC_INI_VIG in", values, "fecIniVig");
      return (Criteria) this;
    }

    public Criteria andFecIniVigNotIn(List<Date> values) {
      addCriterion("FEC_INI_VIG not in", values, "fecIniVig");
      return (Criteria) this;
    }

    public Criteria andFecIniVigBetween(Date value1, Date value2) {
      addCriterion("FEC_INI_VIG between", value1, value2, "fecIniVig");
      return (Criteria) this;
    }

    public Criteria andFecIniVigNotBetween(Date value1, Date value2) {
      addCriterion("FEC_INI_VIG not between", value1, value2, "fecIniVig");
      return (Criteria) this;
    }

    public Criteria andFecFinVigIsNull() {
      addCriterion("FEC_FIN_VIG is null");
      return (Criteria) this;
    }

    public Criteria andFecFinVigIsNotNull() {
      addCriterion("FEC_FIN_VIG is not null");
      return (Criteria) this;
    }

    public Criteria andFecFinVigEqualTo(Date value) {
      addCriterion("FEC_FIN_VIG =", value, "fecFinVig");
      return (Criteria) this;
    }

    public Criteria andFecFinVigNotEqualTo(Date value) {
      addCriterion("FEC_FIN_VIG <>", value, "fecFinVig");
      return (Criteria) this;
    }

    public Criteria andFecFinVigGreaterThan(Date value) {
      addCriterion("FEC_FIN_VIG >", value, "fecFinVig");
      return (Criteria) this;
    }

    public Criteria andFecFinVigGreaterThanOrEqualTo(Date value) {
      addCriterion("FEC_FIN_VIG >=", value, "fecFinVig");
      return (Criteria) this;
    }

    public Criteria andFecFinVigLessThan(Date value) {
      addCriterion("FEC_FIN_VIG <", value, "fecFinVig");
      return (Criteria) this;
    }

    public Criteria andFecFinVigLessThanOrEqualTo(Date value) {
      addCriterion("FEC_FIN_VIG <=", value, "fecFinVig");
      return (Criteria) this;
    }

    public Criteria andFecFinVigIn(List<Date> values) {
      addCriterion("FEC_FIN_VIG in", values, "fecFinVig");
      return (Criteria) this;
    }

    public Criteria andFecFinVigNotIn(List<Date> values) {
      addCriterion("FEC_FIN_VIG not in", values, "fecFinVig");
      return (Criteria) this;
    }

    public Criteria andFecFinVigBetween(Date value1, Date value2) {
      addCriterion("FEC_FIN_VIG between", value1, value2, "fecFinVig");
      return (Criteria) this;
    }

    public Criteria andFecFinVigNotBetween(Date value1, Date value2) {
      addCriterion("FEC_FIN_VIG not between", value1, value2, "fecFinVig");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoemplIsNull() {
      addCriterion("TIP_DOCUMENTOEMPL is null");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoemplIsNotNull() {
      addCriterion("TIP_DOCUMENTOEMPL is not null");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoemplEqualTo(String value) {
      addCriterion("TIP_DOCUMENTOEMPL =", value, "tipDocumentoempl");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoemplNotEqualTo(String value) {
      addCriterion("TIP_DOCUMENTOEMPL <>", value, "tipDocumentoempl");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoemplGreaterThan(String value) {
      addCriterion("TIP_DOCUMENTOEMPL >", value, "tipDocumentoempl");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoemplGreaterThanOrEqualTo(String value) {
      addCriterion("TIP_DOCUMENTOEMPL >=", value, "tipDocumentoempl");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoemplLessThan(String value) {
      addCriterion("TIP_DOCUMENTOEMPL <", value, "tipDocumentoempl");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoemplLessThanOrEqualTo(String value) {
      addCriterion("TIP_DOCUMENTOEMPL <=", value, "tipDocumentoempl");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoemplIn(List<String> values) {
      addCriterion("TIP_DOCUMENTOEMPL in", values, "tipDocumentoempl");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoemplNotIn(List<String> values) {
      addCriterion("TIP_DOCUMENTOEMPL not in", values, "tipDocumentoempl");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoemplBetween(String value1, String value2) {
      addCriterion("TIP_DOCUMENTOEMPL between", value1, value2, "tipDocumentoempl");
      return (Criteria) this;
    }

    public Criteria andTipDocumentoemplNotBetween(String value1, String value2) {
      addCriterion("TIP_DOCUMENTOEMPL not between", value1, value2, "tipDocumentoempl");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoemplIsNull() {
      addCriterion("NRO_DOCUMENTOEMPL is null");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoemplIsNotNull() {
      addCriterion("NRO_DOCUMENTOEMPL is not null");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoemplEqualTo(String value) {
      addCriterion("NRO_DOCUMENTOEMPL =", value, "nroDocumentoempl");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoemplNotEqualTo(String value) {
      addCriterion("NRO_DOCUMENTOEMPL <>", value, "nroDocumentoempl");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoemplGreaterThan(String value) {
      addCriterion("NRO_DOCUMENTOEMPL >", value, "nroDocumentoempl");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoemplGreaterThanOrEqualTo(String value) {
      addCriterion("NRO_DOCUMENTOEMPL >=", value, "nroDocumentoempl");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoemplLessThan(String value) {
      addCriterion("NRO_DOCUMENTOEMPL <", value, "nroDocumentoempl");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoemplLessThanOrEqualTo(String value) {
      addCriterion("NRO_DOCUMENTOEMPL <=", value, "nroDocumentoempl");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoemplIn(List<String> values) {
      addCriterion("NRO_DOCUMENTOEMPL in", values, "nroDocumentoempl");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoemplNotIn(List<String> values) {
      addCriterion("NRO_DOCUMENTOEMPL not in", values, "nroDocumentoempl");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoemplBetween(String value1, String value2) {
      addCriterion("NRO_DOCUMENTOEMPL between", value1, value2, "nroDocumentoempl");
      return (Criteria) this;
    }

    public Criteria andNroDocumentoemplNotBetween(String value1, String value2) {
      addCriterion("NRO_DOCUMENTOEMPL not between", value1, value2, "nroDocumentoempl");
      return (Criteria) this;
    }

    public Criteria andNomEmplIsNull() {
      addCriterion("NOM_EMPL is null");
      return (Criteria) this;
    }

    public Criteria andNomEmplIsNotNull() {
      addCriterion("NOM_EMPL is not null");
      return (Criteria) this;
    }

    public Criteria andNomEmplEqualTo(String value) {
      addCriterion("NOM_EMPL =", value, "nomEmpl");
      return (Criteria) this;
    }

    public Criteria andNomEmplNotEqualTo(String value) {
      addCriterion("NOM_EMPL <>", value, "nomEmpl");
      return (Criteria) this;
    }

    public Criteria andNomEmplGreaterThan(String value) {
      addCriterion("NOM_EMPL >", value, "nomEmpl");
      return (Criteria) this;
    }

    public Criteria andNomEmplGreaterThanOrEqualTo(String value) {
      addCriterion("NOM_EMPL >=", value, "nomEmpl");
      return (Criteria) this;
    }

    public Criteria andNomEmplLessThan(String value) {
      addCriterion("NOM_EMPL <", value, "nomEmpl");
      return (Criteria) this;
    }

    public Criteria andNomEmplLessThanOrEqualTo(String value) {
      addCriterion("NOM_EMPL <=", value, "nomEmpl");
      return (Criteria) this;
    }

    public Criteria andNomEmplIn(List<String> values) {
      addCriterion("NOM_EMPL in", values, "nomEmpl");
      return (Criteria) this;
    }

    public Criteria andNomEmplNotIn(List<String> values) {
      addCriterion("NOM_EMPL not in", values, "nomEmpl");
      return (Criteria) this;
    }

    public Criteria andNomEmplBetween(String value1, String value2) {
      addCriterion("NOM_EMPL between", value1, value2, "nomEmpl");
      return (Criteria) this;
    }

    public Criteria andNomEmplNotBetween(String value1, String value2) {
      addCriterion("NOM_EMPL not between", value1, value2, "nomEmpl");
      return (Criteria) this;
    }

    public Criteria andApeMatemplIsNull() {
      addCriterion("APE_MATEMPL is null");
      return (Criteria) this;
    }

    public Criteria andApeMatemplIsNotNull() {
      addCriterion("APE_MATEMPL is not null");
      return (Criteria) this;
    }

    public Criteria andApeMatemplEqualTo(String value) {
      addCriterion("APE_MATEMPL =", value, "apeMatempl");
      return (Criteria) this;
    }

    public Criteria andApeMatemplNotEqualTo(String value) {
      addCriterion("APE_MATEMPL <>", value, "apeMatempl");
      return (Criteria) this;
    }

    public Criteria andApeMatemplGreaterThan(String value) {
      addCriterion("APE_MATEMPL >", value, "apeMatempl");
      return (Criteria) this;
    }

    public Criteria andApeMatemplGreaterThanOrEqualTo(String value) {
      addCriterion("APE_MATEMPL >=", value, "apeMatempl");
      return (Criteria) this;
    }

    public Criteria andApeMatemplLessThan(String value) {
      addCriterion("APE_MATEMPL <", value, "apeMatempl");
      return (Criteria) this;
    }

    public Criteria andApeMatemplLessThanOrEqualTo(String value) {
      addCriterion("APE_MATEMPL <=", value, "apeMatempl");
      return (Criteria) this;
    }

    public Criteria andApeMatemplIn(List<String> values) {
      addCriterion("APE_MATEMPL in", values, "apeMatempl");
      return (Criteria) this;
    }

    public Criteria andApeMatemplNotIn(List<String> values) {
      addCriterion("APE_MATEMPL not in", values, "apeMatempl");
      return (Criteria) this;
    }

    public Criteria andApeMatemplBetween(String value1, String value2) {
      addCriterion("APE_MATEMPL between", value1, value2, "apeMatempl");
      return (Criteria) this;
    }

    public Criteria andApeMatemplNotBetween(String value1, String value2) {
      addCriterion("APE_MATEMPL not between", value1, value2, "apeMatempl");
      return (Criteria) this;
    }

    public Criteria andApePatemplIsNull() {
      addCriterion("APE_PATEMPL is null");
      return (Criteria) this;
    }

    public Criteria andApePatemplIsNotNull() {
      addCriterion("APE_PATEMPL is not null");
      return (Criteria) this;
    }

    public Criteria andApePatemplEqualTo(String value) {
      addCriterion("APE_PATEMPL =", value, "apePatempl");
      return (Criteria) this;
    }

    public Criteria andApePatemplNotEqualTo(String value) {
      addCriterion("APE_PATEMPL <>", value, "apePatempl");
      return (Criteria) this;
    }

    public Criteria andApePatemplGreaterThan(String value) {
      addCriterion("APE_PATEMPL >", value, "apePatempl");
      return (Criteria) this;
    }

    public Criteria andApePatemplGreaterThanOrEqualTo(String value) {
      addCriterion("APE_PATEMPL >=", value, "apePatempl");
      return (Criteria) this;
    }

    public Criteria andApePatemplLessThan(String value) {
      addCriterion("APE_PATEMPL <", value, "apePatempl");
      return (Criteria) this;
    }

    public Criteria andApePatemplLessThanOrEqualTo(String value) {
      addCriterion("APE_PATEMPL <=", value, "apePatempl");
      return (Criteria) this;
    }

    public Criteria andApePatemplIn(List<String> values) {
      addCriterion("APE_PATEMPL in", values, "apePatempl");
      return (Criteria) this;
    }

    public Criteria andApePatemplNotIn(List<String> values) {
      addCriterion("APE_PATEMPL not in", values, "apePatempl");
      return (Criteria) this;
    }

    public Criteria andApePatemplBetween(String value1, String value2) {
      addCriterion("APE_PATEMPL between", value1, value2, "apePatempl");
      return (Criteria) this;
    }

    public Criteria andApePatemplNotBetween(String value1, String value2) {
      addCriterion("APE_PATEMPL not between", value1, value2, "apePatempl");
      return (Criteria) this;
    }

    public Criteria andFecCreacionIsNull() {
      addCriterion("FEC_CREACION is null");
      return (Criteria) this;
    }

    public Criteria andFecCreacionIsNotNull() {
      addCriterion("FEC_CREACION is not null");
      return (Criteria) this;
    }

    public Criteria andFecCreacionEqualTo(Date value) {
      addCriterion("FEC_CREACION =", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionNotEqualTo(Date value) {
      addCriterion("FEC_CREACION <>", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionGreaterThan(Date value) {
      addCriterion("FEC_CREACION >", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionGreaterThanOrEqualTo(Date value) {
      addCriterion("FEC_CREACION >=", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionLessThan(Date value) {
      addCriterion("FEC_CREACION <", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionLessThanOrEqualTo(Date value) {
      addCriterion("FEC_CREACION <=", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionIn(List<Date> values) {
      addCriterion("FEC_CREACION in", values, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionNotIn(List<Date> values) {
      addCriterion("FEC_CREACION not in", values, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionBetween(Date value1, Date value2) {
      addCriterion("FEC_CREACION between", value1, value2, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionNotBetween(Date value1, Date value2) {
      addCriterion("FEC_CREACION not between", value1, value2, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionIsNull() {
      addCriterion("USU_CREACION is null");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionIsNotNull() {
      addCriterion("USU_CREACION is not null");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionEqualTo(String value) {
      addCriterion("USU_CREACION =", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionNotEqualTo(String value) {
      addCriterion("USU_CREACION <>", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionGreaterThan(String value) {
      addCriterion("USU_CREACION >", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionGreaterThanOrEqualTo(String value) {
      addCriterion("USU_CREACION >=", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionLessThan(String value) {
      addCriterion("USU_CREACION <", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionLessThanOrEqualTo(String value) {
      addCriterion("USU_CREACION <=", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionIn(List<String> values) {
      addCriterion("USU_CREACION in", values, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionNotIn(List<String> values) {
      addCriterion("USU_CREACION not in", values, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionBetween(String value1, String value2) {
      addCriterion("USU_CREACION between", value1, value2, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionNotBetween(String value1, String value2) {
      addCriterion("USU_CREACION not between", value1, value2, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionIsNull() {
      addCriterion("FEC_MODIFICACION is null");
      return (Criteria) this;
    }

    public Criteria andFecModificacionIsNotNull() {
      addCriterion("FEC_MODIFICACION is not null");
      return (Criteria) this;
    }

    public Criteria andFecModificacionEqualTo(Date value) {
      addCriterion("FEC_MODIFICACION =", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionNotEqualTo(Date value) {
      addCriterion("FEC_MODIFICACION <>", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionGreaterThan(Date value) {
      addCriterion("FEC_MODIFICACION >", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionGreaterThanOrEqualTo(Date value) {
      addCriterion("FEC_MODIFICACION >=", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionLessThan(Date value) {
      addCriterion("FEC_MODIFICACION <", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionLessThanOrEqualTo(Date value) {
      addCriterion("FEC_MODIFICACION <=", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionIn(List<Date> values) {
      addCriterion("FEC_MODIFICACION in", values, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionNotIn(List<Date> values) {
      addCriterion("FEC_MODIFICACION not in", values, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionBetween(Date value1, Date value2) {
      addCriterion("FEC_MODIFICACION between", value1, value2, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionNotBetween(Date value1, Date value2) {
      addCriterion("FEC_MODIFICACION not between", value1, value2, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionIsNull() {
      addCriterion("USU_MODIFICACION is null");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionIsNotNull() {
      addCriterion("USU_MODIFICACION is not null");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionEqualTo(String value) {
      addCriterion("USU_MODIFICACION =", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionNotEqualTo(String value) {
      addCriterion("USU_MODIFICACION <>", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionGreaterThan(String value) {
      addCriterion("USU_MODIFICACION >", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionGreaterThanOrEqualTo(String value) {
      addCriterion("USU_MODIFICACION >=", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionLessThan(String value) {
      addCriterion("USU_MODIFICACION <", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionLessThanOrEqualTo(String value) {
      addCriterion("USU_MODIFICACION <=", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionIn(List<String> values) {
      addCriterion("USU_MODIFICACION in", values, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionNotIn(List<String> values) {
      addCriterion("USU_MODIFICACION not in", values, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionBetween(String value1, String value2) {
      addCriterion("USU_MODIFICACION between", value1, value2, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionNotBetween(String value1, String value2) {
      addCriterion("USU_MODIFICACION not between", value1, value2, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andNroEspValoradaIsNull() {
      addCriterion("NRO_ESP_VALORADA is null");
      return (Criteria) this;
    }

    public Criteria andNroEspValoradaIsNotNull() {
      addCriterion("NRO_ESP_VALORADA is not null");
      return (Criteria) this;
    }

    public Criteria andNroEspValoradaEqualTo(String value) {
      addCriterion("NRO_ESP_VALORADA =", value, "nroEspValorada");
      return (Criteria) this;
    }

    public Criteria andNroEspValoradaNotEqualTo(String value) {
      addCriterion("NRO_ESP_VALORADA <>", value, "nroEspValorada");
      return (Criteria) this;
    }

    public Criteria andNroEspValoradaGreaterThan(String value) {
      addCriterion("NRO_ESP_VALORADA >", value, "nroEspValorada");
      return (Criteria) this;
    }

    public Criteria andNroEspValoradaGreaterThanOrEqualTo(String value) {
      addCriterion("NRO_ESP_VALORADA >=", value, "nroEspValorada");
      return (Criteria) this;
    }

    public Criteria andNroEspValoradaLessThan(String value) {
      addCriterion("NRO_ESP_VALORADA <", value, "nroEspValorada");
      return (Criteria) this;
    }

    public Criteria andNroEspValoradaLessThanOrEqualTo(String value) {
      addCriterion("NRO_ESP_VALORADA <=", value, "nroEspValorada");
      return (Criteria) this;
    }

    public Criteria andNroEspValoradaIn(List<String> values) {
      addCriterion("NRO_ESP_VALORADA in", values, "nroEspValorada");
      return (Criteria) this;
    }

    public Criteria andNroEspValoradaNotIn(List<String> values) {
      addCriterion("NRO_ESP_VALORADA not in", values, "nroEspValorada");
      return (Criteria) this;
    }

    public Criteria andNroEspValoradaBetween(String value1, String value2) {
      addCriterion("NRO_ESP_VALORADA between", value1, value2, "nroEspValorada");
      return (Criteria) this;
    }

    public Criteria andNroEspValoradaNotBetween(String value1, String value2) {
      addCriterion("NRO_ESP_VALORADA not between", value1, value2, "nroEspValorada");
      return (Criteria) this;
    }

    public Criteria andEstadoIsNull() {
      addCriterion("ESTADO is null");
      return (Criteria) this;
    }

    public Criteria andEstadoIsNotNull() {
      addCriterion("ESTADO is not null");
      return (Criteria) this;
    }

    public Criteria andEstadoEqualTo(String value) {
      addCriterion("ESTADO =", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoNotEqualTo(String value) {
      addCriterion("ESTADO <>", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoGreaterThan(String value) {
      addCriterion("ESTADO >", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoGreaterThanOrEqualTo(String value) {
      addCriterion("ESTADO >=", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoLessThan(String value) {
      addCriterion("ESTADO <", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoLessThanOrEqualTo(String value) {
      addCriterion("ESTADO <=", value, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoIn(List<String> values) {
      addCriterion("ESTADO in", values, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoNotIn(List<String> values) {
      addCriterion("ESTADO not in", values, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoBetween(String value1, String value2) {
      addCriterion("ESTADO between", value1, value2, "estado");
      return (Criteria) this;
    }

    public Criteria andEstadoNotBetween(String value1, String value2) {
      addCriterion("ESTADO not between", value1, value2, "estado");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoIsNull() {
      addCriterion("NRO_CERTIFICADO is null");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoIsNotNull() {
      addCriterion("NRO_CERTIFICADO is not null");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoEqualTo(String value) {
      addCriterion("NRO_CERTIFICADO =", value, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoNotEqualTo(String value) {
      addCriterion("NRO_CERTIFICADO <>", value, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoGreaterThan(String value) {
      addCriterion("NRO_CERTIFICADO >", value, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoGreaterThanOrEqualTo(String value) {
      addCriterion("NRO_CERTIFICADO >=", value, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoLessThan(String value) {
      addCriterion("NRO_CERTIFICADO <", value, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoLessThanOrEqualTo(String value) {
      addCriterion("NRO_CERTIFICADO <=", value, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoIn(List<String> values) {
      addCriterion("NRO_CERTIFICADO in", values, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoNotIn(List<String> values) {
      addCriterion("NRO_CERTIFICADO not in", values, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoBetween(String value1, String value2) {
      addCriterion("NRO_CERTIFICADO between", value1, value2, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andNroCertificadoNotBetween(String value1, String value2) {
      addCriterion("NRO_CERTIFICADO not between", value1, value2, "nroCertificado");
      return (Criteria) this;
    }

    public Criteria andCodRazonSocialIsNull() {
      addCriterion("COD_RAZON_SOCIAL is null");
      return (Criteria) this;
    }

    public Criteria andCodRazonSocialIsNotNull() {
      addCriterion("COD_RAZON_SOCIAL is not null");
      return (Criteria) this;
    }

    public Criteria andCodRazonSocialEqualTo(String value) {
      addCriterion("COD_RAZON_SOCIAL =", value, "codRazonSocial");
      return (Criteria) this;
    }

    public Criteria andCodRazonSocialNotEqualTo(String value) {
      addCriterion("COD_RAZON_SOCIAL <>", value, "codRazonSocial");
      return (Criteria) this;
    }

    public Criteria andCodRazonSocialGreaterThan(String value) {
      addCriterion("COD_RAZON_SOCIAL >", value, "codRazonSocial");
      return (Criteria) this;
    }

    public Criteria andCodRazonSocialGreaterThanOrEqualTo(String value) {
      addCriterion("COD_RAZON_SOCIAL >=", value, "codRazonSocial");
      return (Criteria) this;
    }

    public Criteria andCodRazonSocialLessThan(String value) {
      addCriterion("COD_RAZON_SOCIAL <", value, "codRazonSocial");
      return (Criteria) this;
    }

    public Criteria andCodRazonSocialLessThanOrEqualTo(String value) {
      addCriterion("COD_RAZON_SOCIAL <=", value, "codRazonSocial");
      return (Criteria) this;
    }

    public Criteria andCodRazonSocialIn(List<String> values) {
      addCriterion("COD_RAZON_SOCIAL in", values, "codRazonSocial");
      return (Criteria) this;
    }

    public Criteria andCodRazonSocialNotIn(List<String> values) {
      addCriterion("COD_RAZON_SOCIAL not in", values, "codRazonSocial");
      return (Criteria) this;
    }

    public Criteria andCodRazonSocialBetween(String value1, String value2) {
      addCriterion("COD_RAZON_SOCIAL between", value1, value2, "codRazonSocial");
      return (Criteria) this;
    }

    public Criteria andCodRazonSocialNotBetween(String value1, String value2) {
      addCriterion("COD_RAZON_SOCIAL not between", value1, value2, "codRazonSocial");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.POLIZA_SOAT_EMPL
   *
   * @mbggenerated do_not_delete_during_merge Wed Sep 24 17:41:29 COT 2014
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.POLIZA_SOAT_EMPL
   *
   * @mbggenerated Wed Sep 24 17:41:29 COT 2014
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}