package com.cardif.satelite.model.soatdirecto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class DireccionPropietarioVehiculoDirectoExample implements Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table USER_SOAT_DIRECPROD.DIRECCION_PROPIETARIO_VEHICULO
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table USER_SOAT_DIRECPROD.DIRECCION_PROPIETARIO_VEHICULO
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table USER_SOAT_DIRECPROD.DIRECCION_PROPIETARIO_VEHICULO
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_SOAT_DIRECPROD.DIRECCION_PROPIETARIO_VEHICULO
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  public DireccionPropietarioVehiculoDirectoExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_SOAT_DIRECPROD.DIRECCION_PROPIETARIO_VEHICULO
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_SOAT_DIRECPROD.DIRECCION_PROPIETARIO_VEHICULO
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_SOAT_DIRECPROD.DIRECCION_PROPIETARIO_VEHICULO
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_SOAT_DIRECPROD.DIRECCION_PROPIETARIO_VEHICULO
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_SOAT_DIRECPROD.DIRECCION_PROPIETARIO_VEHICULO
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_SOAT_DIRECPROD.DIRECCION_PROPIETARIO_VEHICULO
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_SOAT_DIRECPROD.DIRECCION_PROPIETARIO_VEHICULO
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_SOAT_DIRECPROD.DIRECCION_PROPIETARIO_VEHICULO
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_SOAT_DIRECPROD.DIRECCION_PROPIETARIO_VEHICULO
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_SOAT_DIRECPROD.DIRECCION_PROPIETARIO_VEHICULO
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table USER_SOAT_DIRECPROD.DIRECCION_PROPIETARIO_VEHICULO
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andPlacaIsNull() {
      addCriterion("PLACA is null");
      return (Criteria) this;
    }

    public Criteria andPlacaIsNotNull() {
      addCriterion("PLACA is not null");
      return (Criteria) this;
    }

    public Criteria andPlacaEqualTo(String value) {
      addCriterion("PLACA =", value, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaNotEqualTo(String value) {
      addCriterion("PLACA <>", value, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaGreaterThan(String value) {
      addCriterion("PLACA >", value, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaGreaterThanOrEqualTo(String value) {
      addCriterion("PLACA >=", value, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaLessThan(String value) {
      addCriterion("PLACA <", value, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaLessThanOrEqualTo(String value) {
      addCriterion("PLACA <=", value, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaLike(String value) {
      addCriterion("PLACA like", value, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaNotLike(String value) {
      addCriterion("PLACA not like", value, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaIn(List<String> values) {
      addCriterion("PLACA in", values, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaNotIn(List<String> values) {
      addCriterion("PLACA not in", values, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaBetween(String value1, String value2) {
      addCriterion("PLACA between", value1, value2, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaNotBetween(String value1, String value2) {
      addCriterion("PLACA not between", value1, value2, "placa");
      return (Criteria) this;
    }

    public Criteria andVersionIsNull() {
      addCriterion("VERSION is null");
      return (Criteria) this;
    }

    public Criteria andVersionIsNotNull() {
      addCriterion("VERSION is not null");
      return (Criteria) this;
    }

    public Criteria andVersionEqualTo(Long value) {
      addCriterion("VERSION =", value, "version");
      return (Criteria) this;
    }

    public Criteria andVersionNotEqualTo(Long value) {
      addCriterion("VERSION <>", value, "version");
      return (Criteria) this;
    }

    public Criteria andVersionGreaterThan(Long value) {
      addCriterion("VERSION >", value, "version");
      return (Criteria) this;
    }

    public Criteria andVersionGreaterThanOrEqualTo(Long value) {
      addCriterion("VERSION >=", value, "version");
      return (Criteria) this;
    }

    public Criteria andVersionLessThan(Long value) {
      addCriterion("VERSION <", value, "version");
      return (Criteria) this;
    }

    public Criteria andVersionLessThanOrEqualTo(Long value) {
      addCriterion("VERSION <=", value, "version");
      return (Criteria) this;
    }

    public Criteria andVersionIn(List<Long> values) {
      addCriterion("VERSION in", values, "version");
      return (Criteria) this;
    }

    public Criteria andVersionNotIn(List<Long> values) {
      addCriterion("VERSION not in", values, "version");
      return (Criteria) this;
    }

    public Criteria andVersionBetween(Long value1, Long value2) {
      addCriterion("VERSION between", value1, value2, "version");
      return (Criteria) this;
    }

    public Criteria andVersionNotBetween(Long value1, Long value2) {
      addCriterion("VERSION not between", value1, value2, "version");
      return (Criteria) this;
    }

    public Criteria andDireccionIsNull() {
      addCriterion("DIRECCION is null");
      return (Criteria) this;
    }

    public Criteria andDireccionIsNotNull() {
      addCriterion("DIRECCION is not null");
      return (Criteria) this;
    }

    public Criteria andDireccionEqualTo(BigDecimal value) {
      addCriterion("DIRECCION =", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionNotEqualTo(BigDecimal value) {
      addCriterion("DIRECCION <>", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionGreaterThan(BigDecimal value) {
      addCriterion("DIRECCION >", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("DIRECCION >=", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionLessThan(BigDecimal value) {
      addCriterion("DIRECCION <", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionLessThanOrEqualTo(BigDecimal value) {
      addCriterion("DIRECCION <=", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionIn(List<BigDecimal> values) {
      addCriterion("DIRECCION in", values, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionNotIn(List<BigDecimal> values) {
      addCriterion("DIRECCION not in", values, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("DIRECCION between", value1, value2, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("DIRECCION not between", value1, value2, "direccion");
      return (Criteria) this;
    }

    public Criteria andPropietarioIsNull() {
      addCriterion("PROPIETARIO is null");
      return (Criteria) this;
    }

    public Criteria andPropietarioIsNotNull() {
      addCriterion("PROPIETARIO is not null");
      return (Criteria) this;
    }

    public Criteria andPropietarioEqualTo(BigDecimal value) {
      addCriterion("PROPIETARIO =", value, "propietario");
      return (Criteria) this;
    }

    public Criteria andPropietarioNotEqualTo(BigDecimal value) {
      addCriterion("PROPIETARIO <>", value, "propietario");
      return (Criteria) this;
    }

    public Criteria andPropietarioGreaterThan(BigDecimal value) {
      addCriterion("PROPIETARIO >", value, "propietario");
      return (Criteria) this;
    }

    public Criteria andPropietarioGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("PROPIETARIO >=", value, "propietario");
      return (Criteria) this;
    }

    public Criteria andPropietarioLessThan(BigDecimal value) {
      addCriterion("PROPIETARIO <", value, "propietario");
      return (Criteria) this;
    }

    public Criteria andPropietarioLessThanOrEqualTo(BigDecimal value) {
      addCriterion("PROPIETARIO <=", value, "propietario");
      return (Criteria) this;
    }

    public Criteria andPropietarioIn(List<BigDecimal> values) {
      addCriterion("PROPIETARIO in", values, "propietario");
      return (Criteria) this;
    }

    public Criteria andPropietarioNotIn(List<BigDecimal> values) {
      addCriterion("PROPIETARIO not in", values, "propietario");
      return (Criteria) this;
    }

    public Criteria andPropietarioBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PROPIETARIO between", value1, value2, "propietario");
      return (Criteria) this;
    }

    public Criteria andPropietarioNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PROPIETARIO not between", value1, value2, "propietario");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table USER_SOAT_DIRECPROD.DIRECCION_PROPIETARIO_VEHICULO
   *
   * @mbggenerated do_not_delete_during_merge Wed Mar 12 16:22:33 COT 2014
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table USER_SOAT_DIRECPROD.DIRECCION_PROPIETARIO_VEHICULO
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}