package com.cardif.satelite.model.soatdirecto;

import java.io.Serializable;
import java.math.BigDecimal;

public class MarcaVehiculoDirecto implements Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column USER_SOAT_DIRECPROD.MARCA_VEHICULO.ID
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  private BigDecimal id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * USER_SOAT_DIRECPROD.MARCA_VEHICULO.NOMBRE_MARCAVEHICULO
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  private String nombreMarcavehiculo;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column USER_SOAT_DIRECPROD.MARCA_VEHICULO.VERSION
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  private Long version;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column USER_SOAT_DIRECPROD.MARCA_VEHICULO.ID
   *
   * @return the value of USER_SOAT_DIRECPROD.MARCA_VEHICULO.ID
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  public BigDecimal getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column USER_SOAT_DIRECPROD.MARCA_VEHICULO.ID
   *
   * @param id
   *          the value for USER_SOAT_DIRECPROD.MARCA_VEHICULO.ID
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  public void setId(BigDecimal id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column
   * USER_SOAT_DIRECPROD.MARCA_VEHICULO.NOMBRE_MARCAVEHICULO
   *
   * @return the value of USER_SOAT_DIRECPROD.MARCA_VEHICULO.NOMBRE_MARCAVEHICULO
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  public String getNombreMarcavehiculo() {
    return nombreMarcavehiculo;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column
   * USER_SOAT_DIRECPROD.MARCA_VEHICULO.NOMBRE_MARCAVEHICULO
   *
   * @param nombreMarcavehiculo
   *          the value for USER_SOAT_DIRECPROD.MARCA_VEHICULO.NOMBRE_MARCAVEHICULO
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  public void setNombreMarcavehiculo(String nombreMarcavehiculo) {
    this.nombreMarcavehiculo = nombreMarcavehiculo == null ? null : nombreMarcavehiculo.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column USER_SOAT_DIRECPROD.MARCA_VEHICULO.VERSION
   *
   * @return the value of USER_SOAT_DIRECPROD.MARCA_VEHICULO.VERSION
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  public Long getVersion() {
    return version;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column USER_SOAT_DIRECPROD.MARCA_VEHICULO.VERSION
   *
   * @param version
   *          the value for USER_SOAT_DIRECPROD.MARCA_VEHICULO.VERSION
   *
   * @mbggenerated Wed Mar 12 16:22:33 COT 2014
   */
  public void setVersion(Long version) {
    this.version = version;
  }
}