package com.cardif.satelite.configuracion.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import com.cardif.satelite.model.satelite.GenDepartamento;
import com.cardif.satelite.model.satelite.GenDepartamentoExample;

public interface GenDepartamentoMapper {

  final String SELECT_DEPARTAMENTO = "SELECT * FROM GEN_DEPARTAMENTO order by NOMBRE_DEPARTAMENTO";

  @Select(SELECT_DEPARTAMENTO)
  @ResultMap(value = "BaseResultMap")
  List<GenDepartamento> selectDepartamento();

  final String SELECT_DEPTO_PAIS = "SELECT * FROM GEN_DEPARTAMENTO WHERE COD_PAIS = #{codPais} order by NOMBRE_DEPARTAMENTO";

  @Select(SELECT_DEPTO_PAIS)
  @ResultMap(value = "BaseResultMap")
  List<GenDepartamento> selectDepartamentoPais(@Param("codPais") String codPais);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_DEPARTAMENTO
   *
   * @mbggenerated Wed Sep 03 18:53:49 COT 2014
   */
  int countByExample(GenDepartamentoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_DEPARTAMENTO
   *
   * @mbggenerated Wed Sep 03 18:53:49 COT 2014
   */
  int deleteByExample(GenDepartamentoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_DEPARTAMENTO
   *
   * @mbggenerated Wed Sep 03 18:53:49 COT 2014
   */
  int deleteByPrimaryKey(String codDepartamento);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_DEPARTAMENTO
   *
   * @mbggenerated Wed Sep 03 18:53:49 COT 2014
   */
  int insert(GenDepartamento record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_DEPARTAMENTO
   *
   * @mbggenerated Wed Sep 03 18:53:49 COT 2014
   */
  int insertSelective(GenDepartamento record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_DEPARTAMENTO
   *
   * @mbggenerated Wed Sep 03 18:53:49 COT 2014
   */
  List<GenDepartamento> selectByExample(GenDepartamentoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_DEPARTAMENTO
   *
   * @mbggenerated Wed Sep 03 18:53:49 COT 2014
   */
  GenDepartamento selectByPrimaryKey(String codDepartamento);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_DEPARTAMENTO
   *
   * @mbggenerated Wed Sep 03 18:53:49 COT 2014
   */
  int updateByExampleSelective(@Param("record") GenDepartamento record, @Param("example") GenDepartamentoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_DEPARTAMENTO
   *
   * @mbggenerated Wed Sep 03 18:53:49 COT 2014
   */
  int updateByExample(@Param("record") GenDepartamento record, @Param("example") GenDepartamentoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_DEPARTAMENTO
   *
   * @mbggenerated Wed Sep 03 18:53:49 COT 2014
   */
  int updateByPrimaryKeySelective(GenDepartamento record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_DEPARTAMENTO
   *
   * @mbggenerated Wed Sep 03 18:53:49 COT 2014
   */
  int updateByPrimaryKey(GenDepartamento record);
}