package com.cardif.satelite.configuracion.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import com.cardif.satelite.model.satelite.GenProvincia;
import com.cardif.satelite.model.satelite.GenProvinciaExample;

public interface GenProvinciaMapper {
  final String SELECT_PROV = "SELECT * FROM GEN_PROVINCIA " + "WHERE DEPARTAMENTO = #{codDepartamento} order by NOMBRE_PROVINCIA";

  @Select(SELECT_PROV)
  @ResultMap(value = "BaseResultMap")
  List<GenProvincia> selectProvincia(@Param("codDepartamento") String codDepartamento);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_PROVINCIA
   *
   * @mbggenerated Wed Sep 03 18:53:50 COT 2014
   */
  int countByExample(GenProvinciaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_PROVINCIA
   *
   * @mbggenerated Wed Sep 03 18:53:50 COT 2014
   */
  int deleteByExample(GenProvinciaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_PROVINCIA
   *
   * @mbggenerated Wed Sep 03 18:53:50 COT 2014
   */
  int deleteByPrimaryKey(String codProvincia);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_PROVINCIA
   *
   * @mbggenerated Wed Sep 03 18:53:50 COT 2014
   */
  int insert(GenProvincia record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_PROVINCIA
   *
   * @mbggenerated Wed Sep 03 18:53:50 COT 2014
   */
  int insertSelective(GenProvincia record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_PROVINCIA
   *
   * @mbggenerated Wed Sep 03 18:53:50 COT 2014
   */
  List<GenProvincia> selectByExample(GenProvinciaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_PROVINCIA
   *
   * @mbggenerated Wed Sep 03 18:53:50 COT 2014
   */
  GenProvincia selectByPrimaryKey(String codProvincia);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_PROVINCIA
   *
   * @mbggenerated Wed Sep 03 18:53:50 COT 2014
   */
  int updateByExampleSelective(@Param("record") GenProvincia record, @Param("example") GenProvinciaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_PROVINCIA
   *
   * @mbggenerated Wed Sep 03 18:53:50 COT 2014
   */
  int updateByExample(@Param("record") GenProvincia record, @Param("example") GenProvinciaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_PROVINCIA
   *
   * @mbggenerated Wed Sep 03 18:53:50 COT 2014
   */
  int updateByPrimaryKeySelective(GenProvincia record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.GEN_PROVINCIA
   *
   * @mbggenerated Wed Sep 03 18:53:50 COT 2014
   */
  int updateByPrimaryKey(GenProvincia record);
}