package com.cardif.satelite.model.satelite;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CabBasePolizasSoatExample implements Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.CAB_BASE_POLIZAS_SOAT
   *
   * @mbggenerated Thu Jul 17 12:08:59 COT 2014
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.CAB_BASE_POLIZAS_SOAT
   *
   * @mbggenerated Thu Jul 17 12:08:59 COT 2014
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.CAB_BASE_POLIZAS_SOAT
   *
   * @mbggenerated Thu Jul 17 12:08:59 COT 2014
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CAB_BASE_POLIZAS_SOAT
   *
   * @mbggenerated Thu Jul 17 12:08:59 COT 2014
   */
  public CabBasePolizasSoatExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CAB_BASE_POLIZAS_SOAT
   *
   * @mbggenerated Thu Jul 17 12:08:59 COT 2014
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CAB_BASE_POLIZAS_SOAT
   *
   * @mbggenerated Thu Jul 17 12:08:59 COT 2014
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CAB_BASE_POLIZAS_SOAT
   *
   * @mbggenerated Thu Jul 17 12:08:59 COT 2014
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CAB_BASE_POLIZAS_SOAT
   *
   * @mbggenerated Thu Jul 17 12:08:59 COT 2014
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CAB_BASE_POLIZAS_SOAT
   *
   * @mbggenerated Thu Jul 17 12:08:59 COT 2014
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CAB_BASE_POLIZAS_SOAT
   *
   * @mbggenerated Thu Jul 17 12:08:59 COT 2014
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CAB_BASE_POLIZAS_SOAT
   *
   * @mbggenerated Thu Jul 17 12:08:59 COT 2014
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CAB_BASE_POLIZAS_SOAT
   *
   * @mbggenerated Thu Jul 17 12:08:59 COT 2014
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CAB_BASE_POLIZAS_SOAT
   *
   * @mbggenerated Thu Jul 17 12:08:59 COT 2014
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CAB_BASE_POLIZAS_SOAT
   *
   * @mbggenerated Thu Jul 17 12:08:59 COT 2014
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.CAB_BASE_POLIZAS_SOAT
   *
   * @mbggenerated Thu Jul 17 12:08:59 COT 2014
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andSecArchivoIsNull() {
      addCriterion("SEC_ARCHIVO is null");
      return (Criteria) this;
    }

    public Criteria andSecArchivoIsNotNull() {
      addCriterion("SEC_ARCHIVO is not null");
      return (Criteria) this;
    }

    public Criteria andSecArchivoEqualTo(Long value) {
      addCriterion("SEC_ARCHIVO =", value, "secArchivo");
      return (Criteria) this;
    }

    public Criteria andSecArchivoNotEqualTo(Long value) {
      addCriterion("SEC_ARCHIVO <>", value, "secArchivo");
      return (Criteria) this;
    }

    public Criteria andSecArchivoGreaterThan(Long value) {
      addCriterion("SEC_ARCHIVO >", value, "secArchivo");
      return (Criteria) this;
    }

    public Criteria andSecArchivoGreaterThanOrEqualTo(Long value) {
      addCriterion("SEC_ARCHIVO >=", value, "secArchivo");
      return (Criteria) this;
    }

    public Criteria andSecArchivoLessThan(Long value) {
      addCriterion("SEC_ARCHIVO <", value, "secArchivo");
      return (Criteria) this;
    }

    public Criteria andSecArchivoLessThanOrEqualTo(Long value) {
      addCriterion("SEC_ARCHIVO <=", value, "secArchivo");
      return (Criteria) this;
    }

    public Criteria andSecArchivoIn(List<Long> values) {
      addCriterion("SEC_ARCHIVO in", values, "secArchivo");
      return (Criteria) this;
    }

    public Criteria andSecArchivoNotIn(List<Long> values) {
      addCriterion("SEC_ARCHIVO not in", values, "secArchivo");
      return (Criteria) this;
    }

    public Criteria andSecArchivoBetween(Long value1, Long value2) {
      addCriterion("SEC_ARCHIVO between", value1, value2, "secArchivo");
      return (Criteria) this;
    }

    public Criteria andSecArchivoNotBetween(Long value1, Long value2) {
      addCriterion("SEC_ARCHIVO not between", value1, value2, "secArchivo");
      return (Criteria) this;
    }

    public Criteria andProductoIsNull() {
      addCriterion("PRODUCTO is null");
      return (Criteria) this;
    }

    public Criteria andProductoIsNotNull() {
      addCriterion("PRODUCTO is not null");
      return (Criteria) this;
    }

    public Criteria andProductoEqualTo(String value) {
      addCriterion("PRODUCTO =", value, "producto");
      return (Criteria) this;
    }

    public Criteria andProductoNotEqualTo(String value) {
      addCriterion("PRODUCTO <>", value, "producto");
      return (Criteria) this;
    }

    public Criteria andProductoGreaterThan(String value) {
      addCriterion("PRODUCTO >", value, "producto");
      return (Criteria) this;
    }

    public Criteria andProductoGreaterThanOrEqualTo(String value) {
      addCriterion("PRODUCTO >=", value, "producto");
      return (Criteria) this;
    }

    public Criteria andProductoLessThan(String value) {
      addCriterion("PRODUCTO <", value, "producto");
      return (Criteria) this;
    }

    public Criteria andProductoLessThanOrEqualTo(String value) {
      addCriterion("PRODUCTO <=", value, "producto");
      return (Criteria) this;
    }

    public Criteria andProductoIn(List<String> values) {
      addCriterion("PRODUCTO in", values, "producto");
      return (Criteria) this;
    }

    public Criteria andProductoNotIn(List<String> values) {
      addCriterion("PRODUCTO not in", values, "producto");
      return (Criteria) this;
    }

    public Criteria andProductoBetween(String value1, String value2) {
      addCriterion("PRODUCTO between", value1, value2, "producto");
      return (Criteria) this;
    }

    public Criteria andProductoNotBetween(String value1, String value2) {
      addCriterion("PRODUCTO not between", value1, value2, "producto");
      return (Criteria) this;
    }

    public Criteria andFecCargaIsNull() {
      addCriterion("FEC_CARGA is null");
      return (Criteria) this;
    }

    public Criteria andFecCargaIsNotNull() {
      addCriterion("FEC_CARGA is not null");
      return (Criteria) this;
    }

    public Criteria andFecCargaEqualTo(Date value) {
      addCriterion("FEC_CARGA =", value, "fecCarga");
      return (Criteria) this;
    }

    public Criteria andFecCargaNotEqualTo(Date value) {
      addCriterion("FEC_CARGA <>", value, "fecCarga");
      return (Criteria) this;
    }

    public Criteria andFecCargaGreaterThan(Date value) {
      addCriterion("FEC_CARGA >", value, "fecCarga");
      return (Criteria) this;
    }

    public Criteria andFecCargaGreaterThanOrEqualTo(Date value) {
      addCriterion("FEC_CARGA >=", value, "fecCarga");
      return (Criteria) this;
    }

    public Criteria andFecCargaLessThan(Date value) {
      addCriterion("FEC_CARGA <", value, "fecCarga");
      return (Criteria) this;
    }

    public Criteria andFecCargaLessThanOrEqualTo(Date value) {
      addCriterion("FEC_CARGA <=", value, "fecCarga");
      return (Criteria) this;
    }

    public Criteria andFecCargaIn(List<Date> values) {
      addCriterion("FEC_CARGA in", values, "fecCarga");
      return (Criteria) this;
    }

    public Criteria andFecCargaNotIn(List<Date> values) {
      addCriterion("FEC_CARGA not in", values, "fecCarga");
      return (Criteria) this;
    }

    public Criteria andFecCargaBetween(Date value1, Date value2) {
      addCriterion("FEC_CARGA between", value1, value2, "fecCarga");
      return (Criteria) this;
    }

    public Criteria andFecCargaNotBetween(Date value1, Date value2) {
      addCriterion("FEC_CARGA not between", value1, value2, "fecCarga");
      return (Criteria) this;
    }

    public Criteria andNomArchivoIsNull() {
      addCriterion("NOM_ARCHIVO is null");
      return (Criteria) this;
    }

    public Criteria andNomArchivoIsNotNull() {
      addCriterion("NOM_ARCHIVO is not null");
      return (Criteria) this;
    }

    public Criteria andNomArchivoEqualTo(String value) {
      addCriterion("NOM_ARCHIVO =", value, "nomArchivo");
      return (Criteria) this;
    }

    public Criteria andNomArchivoNotEqualTo(String value) {
      addCriterion("NOM_ARCHIVO <>", value, "nomArchivo");
      return (Criteria) this;
    }

    public Criteria andNomArchivoGreaterThan(String value) {
      addCriterion("NOM_ARCHIVO >", value, "nomArchivo");
      return (Criteria) this;
    }

    public Criteria andNomArchivoGreaterThanOrEqualTo(String value) {
      addCriterion("NOM_ARCHIVO >=", value, "nomArchivo");
      return (Criteria) this;
    }

    public Criteria andNomArchivoLessThan(String value) {
      addCriterion("NOM_ARCHIVO <", value, "nomArchivo");
      return (Criteria) this;
    }

    public Criteria andNomArchivoLessThanOrEqualTo(String value) {
      addCriterion("NOM_ARCHIVO <=", value, "nomArchivo");
      return (Criteria) this;
    }

    public Criteria andNomArchivoIn(List<String> values) {
      addCriterion("NOM_ARCHIVO in", values, "nomArchivo");
      return (Criteria) this;
    }

    public Criteria andNomArchivoNotIn(List<String> values) {
      addCriterion("NOM_ARCHIVO not in", values, "nomArchivo");
      return (Criteria) this;
    }

    public Criteria andNomArchivoBetween(String value1, String value2) {
      addCriterion("NOM_ARCHIVO between", value1, value2, "nomArchivo");
      return (Criteria) this;
    }

    public Criteria andNomArchivoNotBetween(String value1, String value2) {
      addCriterion("NOM_ARCHIVO not between", value1, value2, "nomArchivo");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosIsNull() {
      addCriterion("NUM_REGISTROS is null");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosIsNotNull() {
      addCriterion("NUM_REGISTROS is not null");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosEqualTo(Long value) {
      addCriterion("NUM_REGISTROS =", value, "numRegistros");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosNotEqualTo(Long value) {
      addCriterion("NUM_REGISTROS <>", value, "numRegistros");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosGreaterThan(Long value) {
      addCriterion("NUM_REGISTROS >", value, "numRegistros");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosGreaterThanOrEqualTo(Long value) {
      addCriterion("NUM_REGISTROS >=", value, "numRegistros");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosLessThan(Long value) {
      addCriterion("NUM_REGISTROS <", value, "numRegistros");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosLessThanOrEqualTo(Long value) {
      addCriterion("NUM_REGISTROS <=", value, "numRegistros");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosIn(List<Long> values) {
      addCriterion("NUM_REGISTROS in", values, "numRegistros");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosNotIn(List<Long> values) {
      addCriterion("NUM_REGISTROS not in", values, "numRegistros");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosBetween(Long value1, Long value2) {
      addCriterion("NUM_REGISTROS between", value1, value2, "numRegistros");
      return (Criteria) this;
    }

    public Criteria andNumRegistrosNotBetween(Long value1, Long value2) {
      addCriterion("NUM_REGISTROS not between", value1, value2, "numRegistros");
      return (Criteria) this;
    }

    public Criteria andFecCreacionIsNull() {
      addCriterion("FEC_CREACION is null");
      return (Criteria) this;
    }

    public Criteria andFecCreacionIsNotNull() {
      addCriterion("FEC_CREACION is not null");
      return (Criteria) this;
    }

    public Criteria andFecCreacionEqualTo(Date value) {
      addCriterion("FEC_CREACION =", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionNotEqualTo(Date value) {
      addCriterion("FEC_CREACION <>", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionGreaterThan(Date value) {
      addCriterion("FEC_CREACION >", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionGreaterThanOrEqualTo(Date value) {
      addCriterion("FEC_CREACION >=", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionLessThan(Date value) {
      addCriterion("FEC_CREACION <", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionLessThanOrEqualTo(Date value) {
      addCriterion("FEC_CREACION <=", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionIn(List<Date> values) {
      addCriterion("FEC_CREACION in", values, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionNotIn(List<Date> values) {
      addCriterion("FEC_CREACION not in", values, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionBetween(Date value1, Date value2) {
      addCriterion("FEC_CREACION between", value1, value2, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionNotBetween(Date value1, Date value2) {
      addCriterion("FEC_CREACION not between", value1, value2, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionIsNull() {
      addCriterion("USU_CREACION is null");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionIsNotNull() {
      addCriterion("USU_CREACION is not null");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionEqualTo(String value) {
      addCriterion("USU_CREACION =", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionNotEqualTo(String value) {
      addCriterion("USU_CREACION <>", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionGreaterThan(String value) {
      addCriterion("USU_CREACION >", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionGreaterThanOrEqualTo(String value) {
      addCriterion("USU_CREACION >=", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionLessThan(String value) {
      addCriterion("USU_CREACION <", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionLessThanOrEqualTo(String value) {
      addCriterion("USU_CREACION <=", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionIn(List<String> values) {
      addCriterion("USU_CREACION in", values, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionNotIn(List<String> values) {
      addCriterion("USU_CREACION not in", values, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionBetween(String value1, String value2) {
      addCriterion("USU_CREACION between", value1, value2, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionNotBetween(String value1, String value2) {
      addCriterion("USU_CREACION not between", value1, value2, "usuCreacion");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.CAB_BASE_POLIZAS_SOAT
   *
   * @mbggenerated do_not_delete_during_merge Thu Jul 17 12:08:59 COT 2014
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.CAB_BASE_POLIZAS_SOAT
   *
   * @mbggenerated Thu Jul 17 12:08:59 COT 2014
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}