package com.cardif.satelite.model.satelite;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ConciReporteExample implements Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  public ConciReporteExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andPkIsNull() {
      addCriterion("PK is null");
      return (Criteria) this;
    }

    public Criteria andPkIsNotNull() {
      addCriterion("PK is not null");
      return (Criteria) this;
    }

    public Criteria andPkEqualTo(Long value) {
      addCriterion("PK =", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotEqualTo(Long value) {
      addCriterion("PK <>", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThan(Long value) {
      addCriterion("PK >", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkGreaterThanOrEqualTo(Long value) {
      addCriterion("PK >=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThan(Long value) {
      addCriterion("PK <", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkLessThanOrEqualTo(Long value) {
      addCriterion("PK <=", value, "pk");
      return (Criteria) this;
    }

    public Criteria andPkIn(List<Long> values) {
      addCriterion("PK in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotIn(List<Long> values) {
      addCriterion("PK not in", values, "pk");
      return (Criteria) this;
    }

    public Criteria andPkBetween(Long value1, Long value2) {
      addCriterion("PK between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andPkNotBetween(Long value1, Long value2) {
      addCriterion("PK not between", value1, value2, "pk");
      return (Criteria) this;
    }

    public Criteria andLoteIsNull() {
      addCriterion("LOTE is null");
      return (Criteria) this;
    }

    public Criteria andLoteIsNotNull() {
      addCriterion("LOTE is not null");
      return (Criteria) this;
    }

    public Criteria andLoteEqualTo(String value) {
      addCriterion("LOTE =", value, "lote");
      return (Criteria) this;
    }

    public Criteria andLoteNotEqualTo(String value) {
      addCriterion("LOTE <>", value, "lote");
      return (Criteria) this;
    }

    public Criteria andLoteGreaterThan(String value) {
      addCriterion("LOTE >", value, "lote");
      return (Criteria) this;
    }

    public Criteria andLoteGreaterThanOrEqualTo(String value) {
      addCriterion("LOTE >=", value, "lote");
      return (Criteria) this;
    }

    public Criteria andLoteLessThan(String value) {
      addCriterion("LOTE <", value, "lote");
      return (Criteria) this;
    }

    public Criteria andLoteLessThanOrEqualTo(String value) {
      addCriterion("LOTE <=", value, "lote");
      return (Criteria) this;
    }

    public Criteria andLoteIn(List<String> values) {
      addCriterion("LOTE in", values, "lote");
      return (Criteria) this;
    }

    public Criteria andLoteNotIn(List<String> values) {
      addCriterion("LOTE not in", values, "lote");
      return (Criteria) this;
    }

    public Criteria andLoteBetween(String value1, String value2) {
      addCriterion("LOTE between", value1, value2, "lote");
      return (Criteria) this;
    }

    public Criteria andLoteNotBetween(String value1, String value2) {
      addCriterion("LOTE not between", value1, value2, "lote");
      return (Criteria) this;
    }

    public Criteria andPlacaIsNull() {
      addCriterion("PLACA is null");
      return (Criteria) this;
    }

    public Criteria andPlacaIsNotNull() {
      addCriterion("PLACA is not null");
      return (Criteria) this;
    }

    public Criteria andPlacaEqualTo(String value) {
      addCriterion("PLACA =", value, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaNotEqualTo(String value) {
      addCriterion("PLACA <>", value, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaGreaterThan(String value) {
      addCriterion("PLACA >", value, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaGreaterThanOrEqualTo(String value) {
      addCriterion("PLACA >=", value, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaLessThan(String value) {
      addCriterion("PLACA <", value, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaLessThanOrEqualTo(String value) {
      addCriterion("PLACA <=", value, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaIn(List<String> values) {
      addCriterion("PLACA in", values, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaNotIn(List<String> values) {
      addCriterion("PLACA not in", values, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaBetween(String value1, String value2) {
      addCriterion("PLACA between", value1, value2, "placa");
      return (Criteria) this;
    }

    public Criteria andPlacaNotBetween(String value1, String value2) {
      addCriterion("PLACA not between", value1, value2, "placa");
      return (Criteria) this;
    }

    public Criteria andClaseIsNull() {
      addCriterion("CLASE is null");
      return (Criteria) this;
    }

    public Criteria andClaseIsNotNull() {
      addCriterion("CLASE is not null");
      return (Criteria) this;
    }

    public Criteria andClaseEqualTo(String value) {
      addCriterion("CLASE =", value, "clase");
      return (Criteria) this;
    }

    public Criteria andClaseNotEqualTo(String value) {
      addCriterion("CLASE <>", value, "clase");
      return (Criteria) this;
    }

    public Criteria andClaseGreaterThan(String value) {
      addCriterion("CLASE >", value, "clase");
      return (Criteria) this;
    }

    public Criteria andClaseGreaterThanOrEqualTo(String value) {
      addCriterion("CLASE >=", value, "clase");
      return (Criteria) this;
    }

    public Criteria andClaseLessThan(String value) {
      addCriterion("CLASE <", value, "clase");
      return (Criteria) this;
    }

    public Criteria andClaseLessThanOrEqualTo(String value) {
      addCriterion("CLASE <=", value, "clase");
      return (Criteria) this;
    }

    public Criteria andClaseIn(List<String> values) {
      addCriterion("CLASE in", values, "clase");
      return (Criteria) this;
    }

    public Criteria andClaseNotIn(List<String> values) {
      addCriterion("CLASE not in", values, "clase");
      return (Criteria) this;
    }

    public Criteria andClaseBetween(String value1, String value2) {
      addCriterion("CLASE between", value1, value2, "clase");
      return (Criteria) this;
    }

    public Criteria andClaseNotBetween(String value1, String value2) {
      addCriterion("CLASE not between", value1, value2, "clase");
      return (Criteria) this;
    }

    public Criteria andMarcaIsNull() {
      addCriterion("MARCA is null");
      return (Criteria) this;
    }

    public Criteria andMarcaIsNotNull() {
      addCriterion("MARCA is not null");
      return (Criteria) this;
    }

    public Criteria andMarcaEqualTo(String value) {
      addCriterion("MARCA =", value, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaNotEqualTo(String value) {
      addCriterion("MARCA <>", value, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaGreaterThan(String value) {
      addCriterion("MARCA >", value, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaGreaterThanOrEqualTo(String value) {
      addCriterion("MARCA >=", value, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaLessThan(String value) {
      addCriterion("MARCA <", value, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaLessThanOrEqualTo(String value) {
      addCriterion("MARCA <=", value, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaIn(List<String> values) {
      addCriterion("MARCA in", values, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaNotIn(List<String> values) {
      addCriterion("MARCA not in", values, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaBetween(String value1, String value2) {
      addCriterion("MARCA between", value1, value2, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaNotBetween(String value1, String value2) {
      addCriterion("MARCA not between", value1, value2, "marca");
      return (Criteria) this;
    }

    public Criteria andNumAsientosIsNull() {
      addCriterion("NUM_ASIENTOS is null");
      return (Criteria) this;
    }

    public Criteria andNumAsientosIsNotNull() {
      addCriterion("NUM_ASIENTOS is not null");
      return (Criteria) this;
    }

    public Criteria andNumAsientosEqualTo(Short value) {
      addCriterion("NUM_ASIENTOS =", value, "numAsientos");
      return (Criteria) this;
    }

    public Criteria andNumAsientosNotEqualTo(Short value) {
      addCriterion("NUM_ASIENTOS <>", value, "numAsientos");
      return (Criteria) this;
    }

    public Criteria andNumAsientosGreaterThan(Short value) {
      addCriterion("NUM_ASIENTOS >", value, "numAsientos");
      return (Criteria) this;
    }

    public Criteria andNumAsientosGreaterThanOrEqualTo(Short value) {
      addCriterion("NUM_ASIENTOS >=", value, "numAsientos");
      return (Criteria) this;
    }

    public Criteria andNumAsientosLessThan(Short value) {
      addCriterion("NUM_ASIENTOS <", value, "numAsientos");
      return (Criteria) this;
    }

    public Criteria andNumAsientosLessThanOrEqualTo(Short value) {
      addCriterion("NUM_ASIENTOS <=", value, "numAsientos");
      return (Criteria) this;
    }

    public Criteria andNumAsientosIn(List<Short> values) {
      addCriterion("NUM_ASIENTOS in", values, "numAsientos");
      return (Criteria) this;
    }

    public Criteria andNumAsientosNotIn(List<Short> values) {
      addCriterion("NUM_ASIENTOS not in", values, "numAsientos");
      return (Criteria) this;
    }

    public Criteria andNumAsientosBetween(Short value1, Short value2) {
      addCriterion("NUM_ASIENTOS between", value1, value2, "numAsientos");
      return (Criteria) this;
    }

    public Criteria andNumAsientosNotBetween(Short value1, Short value2) {
      addCriterion("NUM_ASIENTOS not between", value1, value2, "numAsientos");
      return (Criteria) this;
    }

    public Criteria andModeloIsNull() {
      addCriterion("MODELO is null");
      return (Criteria) this;
    }

    public Criteria andModeloIsNotNull() {
      addCriterion("MODELO is not null");
      return (Criteria) this;
    }

    public Criteria andModeloEqualTo(String value) {
      addCriterion("MODELO =", value, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloNotEqualTo(String value) {
      addCriterion("MODELO <>", value, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloGreaterThan(String value) {
      addCriterion("MODELO >", value, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloGreaterThanOrEqualTo(String value) {
      addCriterion("MODELO >=", value, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloLessThan(String value) {
      addCriterion("MODELO <", value, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloLessThanOrEqualTo(String value) {
      addCriterion("MODELO <=", value, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloIn(List<String> values) {
      addCriterion("MODELO in", values, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloNotIn(List<String> values) {
      addCriterion("MODELO not in", values, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloBetween(String value1, String value2) {
      addCriterion("MODELO between", value1, value2, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloNotBetween(String value1, String value2) {
      addCriterion("MODELO not between", value1, value2, "modelo");
      return (Criteria) this;
    }

    public Criteria andUsoVehiculoIsNull() {
      addCriterion("USO_VEHICULO is null");
      return (Criteria) this;
    }

    public Criteria andUsoVehiculoIsNotNull() {
      addCriterion("USO_VEHICULO is not null");
      return (Criteria) this;
    }

    public Criteria andUsoVehiculoEqualTo(String value) {
      addCriterion("USO_VEHICULO =", value, "usoVehiculo");
      return (Criteria) this;
    }

    public Criteria andUsoVehiculoNotEqualTo(String value) {
      addCriterion("USO_VEHICULO <>", value, "usoVehiculo");
      return (Criteria) this;
    }

    public Criteria andUsoVehiculoGreaterThan(String value) {
      addCriterion("USO_VEHICULO >", value, "usoVehiculo");
      return (Criteria) this;
    }

    public Criteria andUsoVehiculoGreaterThanOrEqualTo(String value) {
      addCriterion("USO_VEHICULO >=", value, "usoVehiculo");
      return (Criteria) this;
    }

    public Criteria andUsoVehiculoLessThan(String value) {
      addCriterion("USO_VEHICULO <", value, "usoVehiculo");
      return (Criteria) this;
    }

    public Criteria andUsoVehiculoLessThanOrEqualTo(String value) {
      addCriterion("USO_VEHICULO <=", value, "usoVehiculo");
      return (Criteria) this;
    }

    public Criteria andUsoVehiculoIn(List<String> values) {
      addCriterion("USO_VEHICULO in", values, "usoVehiculo");
      return (Criteria) this;
    }

    public Criteria andUsoVehiculoNotIn(List<String> values) {
      addCriterion("USO_VEHICULO not in", values, "usoVehiculo");
      return (Criteria) this;
    }

    public Criteria andUsoVehiculoBetween(String value1, String value2) {
      addCriterion("USO_VEHICULO between", value1, value2, "usoVehiculo");
      return (Criteria) this;
    }

    public Criteria andUsoVehiculoNotBetween(String value1, String value2) {
      addCriterion("USO_VEHICULO not between", value1, value2, "usoVehiculo");
      return (Criteria) this;
    }

    public Criteria andPrimaIsNull() {
      addCriterion("PRIMA is null");
      return (Criteria) this;
    }

    public Criteria andPrimaIsNotNull() {
      addCriterion("PRIMA is not null");
      return (Criteria) this;
    }

    public Criteria andPrimaEqualTo(BigDecimal value) {
      addCriterion("PRIMA =", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaNotEqualTo(BigDecimal value) {
      addCriterion("PRIMA <>", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaGreaterThan(BigDecimal value) {
      addCriterion("PRIMA >", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("PRIMA >=", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaLessThan(BigDecimal value) {
      addCriterion("PRIMA <", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaLessThanOrEqualTo(BigDecimal value) {
      addCriterion("PRIMA <=", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaIn(List<BigDecimal> values) {
      addCriterion("PRIMA in", values, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaNotIn(List<BigDecimal> values) {
      addCriterion("PRIMA not in", values, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PRIMA between", value1, value2, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PRIMA not between", value1, value2, "prima");
      return (Criteria) this;
    }

    public Criteria andFecVentaIsNull() {
      addCriterion("FEC_VENTA is null");
      return (Criteria) this;
    }

    public Criteria andFecVentaIsNotNull() {
      addCriterion("FEC_VENTA is not null");
      return (Criteria) this;
    }

    public Criteria andFecVentaEqualTo(Date value) {
      addCriterion("FEC_VENTA =", value, "fecVenta");
      return (Criteria) this;
    }

    public Criteria andFecVentaNotEqualTo(Date value) {
      addCriterion("FEC_VENTA <>", value, "fecVenta");
      return (Criteria) this;
    }

    public Criteria andFecVentaGreaterThan(Date value) {
      addCriterion("FEC_VENTA >", value, "fecVenta");
      return (Criteria) this;
    }

    public Criteria andFecVentaGreaterThanOrEqualTo(Date value) {
      addCriterion("FEC_VENTA >=", value, "fecVenta");
      return (Criteria) this;
    }

    public Criteria andFecVentaLessThan(Date value) {
      addCriterion("FEC_VENTA <", value, "fecVenta");
      return (Criteria) this;
    }

    public Criteria andFecVentaLessThanOrEqualTo(Date value) {
      addCriterion("FEC_VENTA <=", value, "fecVenta");
      return (Criteria) this;
    }

    public Criteria andFecVentaIn(List<Date> values) {
      addCriterion("FEC_VENTA in", values, "fecVenta");
      return (Criteria) this;
    }

    public Criteria andFecVentaNotIn(List<Date> values) {
      addCriterion("FEC_VENTA not in", values, "fecVenta");
      return (Criteria) this;
    }

    public Criteria andFecVentaBetween(Date value1, Date value2) {
      addCriterion("FEC_VENTA between", value1, value2, "fecVenta");
      return (Criteria) this;
    }

    public Criteria andFecVentaNotBetween(Date value1, Date value2) {
      addCriterion("FEC_VENTA not between", value1, value2, "fecVenta");
      return (Criteria) this;
    }

    public Criteria andTarifDepartamentoIsNull() {
      addCriterion("TARIF_DEPARTAMENTO is null");
      return (Criteria) this;
    }

    public Criteria andTarifDepartamentoIsNotNull() {
      addCriterion("TARIF_DEPARTAMENTO is not null");
      return (Criteria) this;
    }

    public Criteria andTarifDepartamentoEqualTo(String value) {
      addCriterion("TARIF_DEPARTAMENTO =", value, "tarifDepartamento");
      return (Criteria) this;
    }

    public Criteria andTarifDepartamentoNotEqualTo(String value) {
      addCriterion("TARIF_DEPARTAMENTO <>", value, "tarifDepartamento");
      return (Criteria) this;
    }

    public Criteria andTarifDepartamentoGreaterThan(String value) {
      addCriterion("TARIF_DEPARTAMENTO >", value, "tarifDepartamento");
      return (Criteria) this;
    }

    public Criteria andTarifDepartamentoGreaterThanOrEqualTo(String value) {
      addCriterion("TARIF_DEPARTAMENTO >=", value, "tarifDepartamento");
      return (Criteria) this;
    }

    public Criteria andTarifDepartamentoLessThan(String value) {
      addCriterion("TARIF_DEPARTAMENTO <", value, "tarifDepartamento");
      return (Criteria) this;
    }

    public Criteria andTarifDepartamentoLessThanOrEqualTo(String value) {
      addCriterion("TARIF_DEPARTAMENTO <=", value, "tarifDepartamento");
      return (Criteria) this;
    }

    public Criteria andTarifDepartamentoIn(List<String> values) {
      addCriterion("TARIF_DEPARTAMENTO in", values, "tarifDepartamento");
      return (Criteria) this;
    }

    public Criteria andTarifDepartamentoNotIn(List<String> values) {
      addCriterion("TARIF_DEPARTAMENTO not in", values, "tarifDepartamento");
      return (Criteria) this;
    }

    public Criteria andTarifDepartamentoBetween(String value1, String value2) {
      addCriterion("TARIF_DEPARTAMENTO between", value1, value2, "tarifDepartamento");
      return (Criteria) this;
    }

    public Criteria andTarifDepartamentoNotBetween(String value1, String value2) {
      addCriterion("TARIF_DEPARTAMENTO not between", value1, value2, "tarifDepartamento");
      return (Criteria) this;
    }

    public Criteria andSubProductoIsNull() {
      addCriterion("SUB_PRODUCTO is null");
      return (Criteria) this;
    }

    public Criteria andSubProductoIsNotNull() {
      addCriterion("SUB_PRODUCTO is not null");
      return (Criteria) this;
    }

    public Criteria andSubProductoEqualTo(String value) {
      addCriterion("SUB_PRODUCTO =", value, "subProducto");
      return (Criteria) this;
    }

    public Criteria andSubProductoNotEqualTo(String value) {
      addCriterion("SUB_PRODUCTO <>", value, "subProducto");
      return (Criteria) this;
    }

    public Criteria andSubProductoGreaterThan(String value) {
      addCriterion("SUB_PRODUCTO >", value, "subProducto");
      return (Criteria) this;
    }

    public Criteria andSubProductoGreaterThanOrEqualTo(String value) {
      addCriterion("SUB_PRODUCTO >=", value, "subProducto");
      return (Criteria) this;
    }

    public Criteria andSubProductoLessThan(String value) {
      addCriterion("SUB_PRODUCTO <", value, "subProducto");
      return (Criteria) this;
    }

    public Criteria andSubProductoLessThanOrEqualTo(String value) {
      addCriterion("SUB_PRODUCTO <=", value, "subProducto");
      return (Criteria) this;
    }

    public Criteria andSubProductoIn(List<String> values) {
      addCriterion("SUB_PRODUCTO in", values, "subProducto");
      return (Criteria) this;
    }

    public Criteria andSubProductoNotIn(List<String> values) {
      addCriterion("SUB_PRODUCTO not in", values, "subProducto");
      return (Criteria) this;
    }

    public Criteria andSubProductoBetween(String value1, String value2) {
      addCriterion("SUB_PRODUCTO between", value1, value2, "subProducto");
      return (Criteria) this;
    }

    public Criteria andSubProductoNotBetween(String value1, String value2) {
      addCriterion("SUB_PRODUCTO not between", value1, value2, "subProducto");
      return (Criteria) this;
    }

    public Criteria andMedioPagoIsNull() {
      addCriterion("MEDIO_PAGO is null");
      return (Criteria) this;
    }

    public Criteria andMedioPagoIsNotNull() {
      addCriterion("MEDIO_PAGO is not null");
      return (Criteria) this;
    }

    public Criteria andMedioPagoEqualTo(String value) {
      addCriterion("MEDIO_PAGO =", value, "medioPago");
      return (Criteria) this;
    }

    public Criteria andMedioPagoNotEqualTo(String value) {
      addCriterion("MEDIO_PAGO <>", value, "medioPago");
      return (Criteria) this;
    }

    public Criteria andMedioPagoGreaterThan(String value) {
      addCriterion("MEDIO_PAGO >", value, "medioPago");
      return (Criteria) this;
    }

    public Criteria andMedioPagoGreaterThanOrEqualTo(String value) {
      addCriterion("MEDIO_PAGO >=", value, "medioPago");
      return (Criteria) this;
    }

    public Criteria andMedioPagoLessThan(String value) {
      addCriterion("MEDIO_PAGO <", value, "medioPago");
      return (Criteria) this;
    }

    public Criteria andMedioPagoLessThanOrEqualTo(String value) {
      addCriterion("MEDIO_PAGO <=", value, "medioPago");
      return (Criteria) this;
    }

    public Criteria andMedioPagoIn(List<String> values) {
      addCriterion("MEDIO_PAGO in", values, "medioPago");
      return (Criteria) this;
    }

    public Criteria andMedioPagoNotIn(List<String> values) {
      addCriterion("MEDIO_PAGO not in", values, "medioPago");
      return (Criteria) this;
    }

    public Criteria andMedioPagoBetween(String value1, String value2) {
      addCriterion("MEDIO_PAGO between", value1, value2, "medioPago");
      return (Criteria) this;
    }

    public Criteria andMedioPagoNotBetween(String value1, String value2) {
      addCriterion("MEDIO_PAGO not between", value1, value2, "medioPago");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaMasterIsNull() {
      addCriterion("PRIMA_TECNICA_MASTER is null");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaMasterIsNotNull() {
      addCriterion("PRIMA_TECNICA_MASTER is not null");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaMasterEqualTo(BigDecimal value) {
      addCriterion("PRIMA_TECNICA_MASTER =", value, "primaTecnicaMaster");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaMasterNotEqualTo(BigDecimal value) {
      addCriterion("PRIMA_TECNICA_MASTER <>", value, "primaTecnicaMaster");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaMasterGreaterThan(BigDecimal value) {
      addCriterion("PRIMA_TECNICA_MASTER >", value, "primaTecnicaMaster");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaMasterGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("PRIMA_TECNICA_MASTER >=", value, "primaTecnicaMaster");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaMasterLessThan(BigDecimal value) {
      addCriterion("PRIMA_TECNICA_MASTER <", value, "primaTecnicaMaster");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaMasterLessThanOrEqualTo(BigDecimal value) {
      addCriterion("PRIMA_TECNICA_MASTER <=", value, "primaTecnicaMaster");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaMasterIn(List<BigDecimal> values) {
      addCriterion("PRIMA_TECNICA_MASTER in", values, "primaTecnicaMaster");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaMasterNotIn(List<BigDecimal> values) {
      addCriterion("PRIMA_TECNICA_MASTER not in", values, "primaTecnicaMaster");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaMasterBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PRIMA_TECNICA_MASTER between", value1, value2, "primaTecnicaMaster");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaMasterNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PRIMA_TECNICA_MASTER not between", value1, value2, "primaTecnicaMaster");
      return (Criteria) this;
    }

    public Criteria andPrimaPublicaMasterIsNull() {
      addCriterion("PRIMA_PUBLICA_MASTER is null");
      return (Criteria) this;
    }

    public Criteria andPrimaPublicaMasterIsNotNull() {
      addCriterion("PRIMA_PUBLICA_MASTER is not null");
      return (Criteria) this;
    }

    public Criteria andPrimaPublicaMasterEqualTo(BigDecimal value) {
      addCriterion("PRIMA_PUBLICA_MASTER =", value, "primaPublicaMaster");
      return (Criteria) this;
    }

    public Criteria andPrimaPublicaMasterNotEqualTo(BigDecimal value) {
      addCriterion("PRIMA_PUBLICA_MASTER <>", value, "primaPublicaMaster");
      return (Criteria) this;
    }

    public Criteria andPrimaPublicaMasterGreaterThan(BigDecimal value) {
      addCriterion("PRIMA_PUBLICA_MASTER >", value, "primaPublicaMaster");
      return (Criteria) this;
    }

    public Criteria andPrimaPublicaMasterGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("PRIMA_PUBLICA_MASTER >=", value, "primaPublicaMaster");
      return (Criteria) this;
    }

    public Criteria andPrimaPublicaMasterLessThan(BigDecimal value) {
      addCriterion("PRIMA_PUBLICA_MASTER <", value, "primaPublicaMaster");
      return (Criteria) this;
    }

    public Criteria andPrimaPublicaMasterLessThanOrEqualTo(BigDecimal value) {
      addCriterion("PRIMA_PUBLICA_MASTER <=", value, "primaPublicaMaster");
      return (Criteria) this;
    }

    public Criteria andPrimaPublicaMasterIn(List<BigDecimal> values) {
      addCriterion("PRIMA_PUBLICA_MASTER in", values, "primaPublicaMaster");
      return (Criteria) this;
    }

    public Criteria andPrimaPublicaMasterNotIn(List<BigDecimal> values) {
      addCriterion("PRIMA_PUBLICA_MASTER not in", values, "primaPublicaMaster");
      return (Criteria) this;
    }

    public Criteria andPrimaPublicaMasterBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PRIMA_PUBLICA_MASTER between", value1, value2, "primaPublicaMaster");
      return (Criteria) this;
    }

    public Criteria andPrimaPublicaMasterNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PRIMA_PUBLICA_MASTER not between", value1, value2, "primaPublicaMaster");
      return (Criteria) this;
    }

    public Criteria andIgvIsNull() {
      addCriterion("IGV is null");
      return (Criteria) this;
    }

    public Criteria andIgvIsNotNull() {
      addCriterion("IGV is not null");
      return (Criteria) this;
    }

    public Criteria andIgvEqualTo(BigDecimal value) {
      addCriterion("IGV =", value, "igv");
      return (Criteria) this;
    }

    public Criteria andIgvNotEqualTo(BigDecimal value) {
      addCriterion("IGV <>", value, "igv");
      return (Criteria) this;
    }

    public Criteria andIgvGreaterThan(BigDecimal value) {
      addCriterion("IGV >", value, "igv");
      return (Criteria) this;
    }

    public Criteria andIgvGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("IGV >=", value, "igv");
      return (Criteria) this;
    }

    public Criteria andIgvLessThan(BigDecimal value) {
      addCriterion("IGV <", value, "igv");
      return (Criteria) this;
    }

    public Criteria andIgvLessThanOrEqualTo(BigDecimal value) {
      addCriterion("IGV <=", value, "igv");
      return (Criteria) this;
    }

    public Criteria andIgvIn(List<BigDecimal> values) {
      addCriterion("IGV in", values, "igv");
      return (Criteria) this;
    }

    public Criteria andIgvNotIn(List<BigDecimal> values) {
      addCriterion("IGV not in", values, "igv");
      return (Criteria) this;
    }

    public Criteria andIgvBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("IGV between", value1, value2, "igv");
      return (Criteria) this;
    }

    public Criteria andIgvNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("IGV not between", value1, value2, "igv");
      return (Criteria) this;
    }

    public Criteria andDeIsNull() {
      addCriterion("DE is null");
      return (Criteria) this;
    }

    public Criteria andDeIsNotNull() {
      addCriterion("DE is not null");
      return (Criteria) this;
    }

    public Criteria andDeEqualTo(BigDecimal value) {
      addCriterion("DE =", value, "de");
      return (Criteria) this;
    }

    public Criteria andDeNotEqualTo(BigDecimal value) {
      addCriterion("DE <>", value, "de");
      return (Criteria) this;
    }

    public Criteria andDeGreaterThan(BigDecimal value) {
      addCriterion("DE >", value, "de");
      return (Criteria) this;
    }

    public Criteria andDeGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("DE >=", value, "de");
      return (Criteria) this;
    }

    public Criteria andDeLessThan(BigDecimal value) {
      addCriterion("DE <", value, "de");
      return (Criteria) this;
    }

    public Criteria andDeLessThanOrEqualTo(BigDecimal value) {
      addCriterion("DE <=", value, "de");
      return (Criteria) this;
    }

    public Criteria andDeIn(List<BigDecimal> values) {
      addCriterion("DE in", values, "de");
      return (Criteria) this;
    }

    public Criteria andDeNotIn(List<BigDecimal> values) {
      addCriterion("DE not in", values, "de");
      return (Criteria) this;
    }

    public Criteria andDeBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("DE between", value1, value2, "de");
      return (Criteria) this;
    }

    public Criteria andDeNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("DE not between", value1, value2, "de");
      return (Criteria) this;
    }

    public Criteria andFondoCompensacionIsNull() {
      addCriterion("FONDO_COMPENSACION is null");
      return (Criteria) this;
    }

    public Criteria andFondoCompensacionIsNotNull() {
      addCriterion("FONDO_COMPENSACION is not null");
      return (Criteria) this;
    }

    public Criteria andFondoCompensacionEqualTo(BigDecimal value) {
      addCriterion("FONDO_COMPENSACION =", value, "fondoCompensacion");
      return (Criteria) this;
    }

    public Criteria andFondoCompensacionNotEqualTo(BigDecimal value) {
      addCriterion("FONDO_COMPENSACION <>", value, "fondoCompensacion");
      return (Criteria) this;
    }

    public Criteria andFondoCompensacionGreaterThan(BigDecimal value) {
      addCriterion("FONDO_COMPENSACION >", value, "fondoCompensacion");
      return (Criteria) this;
    }

    public Criteria andFondoCompensacionGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("FONDO_COMPENSACION >=", value, "fondoCompensacion");
      return (Criteria) this;
    }

    public Criteria andFondoCompensacionLessThan(BigDecimal value) {
      addCriterion("FONDO_COMPENSACION <", value, "fondoCompensacion");
      return (Criteria) this;
    }

    public Criteria andFondoCompensacionLessThanOrEqualTo(BigDecimal value) {
      addCriterion("FONDO_COMPENSACION <=", value, "fondoCompensacion");
      return (Criteria) this;
    }

    public Criteria andFondoCompensacionIn(List<BigDecimal> values) {
      addCriterion("FONDO_COMPENSACION in", values, "fondoCompensacion");
      return (Criteria) this;
    }

    public Criteria andFondoCompensacionNotIn(List<BigDecimal> values) {
      addCriterion("FONDO_COMPENSACION not in", values, "fondoCompensacion");
      return (Criteria) this;
    }

    public Criteria andFondoCompensacionBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("FONDO_COMPENSACION between", value1, value2, "fondoCompensacion");
      return (Criteria) this;
    }

    public Criteria andFondoCompensacionNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("FONDO_COMPENSACION not between", value1, value2, "fondoCompensacion");
      return (Criteria) this;
    }

    public Criteria andComisionCobranzaIsNull() {
      addCriterion("COMISION_COBRANZA is null");
      return (Criteria) this;
    }

    public Criteria andComisionCobranzaIsNotNull() {
      addCriterion("COMISION_COBRANZA is not null");
      return (Criteria) this;
    }

    public Criteria andComisionCobranzaEqualTo(BigDecimal value) {
      addCriterion("COMISION_COBRANZA =", value, "comisionCobranza");
      return (Criteria) this;
    }

    public Criteria andComisionCobranzaNotEqualTo(BigDecimal value) {
      addCriterion("COMISION_COBRANZA <>", value, "comisionCobranza");
      return (Criteria) this;
    }

    public Criteria andComisionCobranzaGreaterThan(BigDecimal value) {
      addCriterion("COMISION_COBRANZA >", value, "comisionCobranza");
      return (Criteria) this;
    }

    public Criteria andComisionCobranzaGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("COMISION_COBRANZA >=", value, "comisionCobranza");
      return (Criteria) this;
    }

    public Criteria andComisionCobranzaLessThan(BigDecimal value) {
      addCriterion("COMISION_COBRANZA <", value, "comisionCobranza");
      return (Criteria) this;
    }

    public Criteria andComisionCobranzaLessThanOrEqualTo(BigDecimal value) {
      addCriterion("COMISION_COBRANZA <=", value, "comisionCobranza");
      return (Criteria) this;
    }

    public Criteria andComisionCobranzaIn(List<BigDecimal> values) {
      addCriterion("COMISION_COBRANZA in", values, "comisionCobranza");
      return (Criteria) this;
    }

    public Criteria andComisionCobranzaNotIn(List<BigDecimal> values) {
      addCriterion("COMISION_COBRANZA not in", values, "comisionCobranza");
      return (Criteria) this;
    }

    public Criteria andComisionCobranzaBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("COMISION_COBRANZA between", value1, value2, "comisionCobranza");
      return (Criteria) this;
    }

    public Criteria andComisionCobranzaNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("COMISION_COBRANZA not between", value1, value2, "comisionCobranza");
      return (Criteria) this;
    }

    public Criteria andComisionSocioIsNull() {
      addCriterion("COMISION_SOCIO is null");
      return (Criteria) this;
    }

    public Criteria andComisionSocioIsNotNull() {
      addCriterion("COMISION_SOCIO is not null");
      return (Criteria) this;
    }

    public Criteria andComisionSocioEqualTo(BigDecimal value) {
      addCriterion("COMISION_SOCIO =", value, "comisionSocio");
      return (Criteria) this;
    }

    public Criteria andComisionSocioNotEqualTo(BigDecimal value) {
      addCriterion("COMISION_SOCIO <>", value, "comisionSocio");
      return (Criteria) this;
    }

    public Criteria andComisionSocioGreaterThan(BigDecimal value) {
      addCriterion("COMISION_SOCIO >", value, "comisionSocio");
      return (Criteria) this;
    }

    public Criteria andComisionSocioGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("COMISION_SOCIO >=", value, "comisionSocio");
      return (Criteria) this;
    }

    public Criteria andComisionSocioLessThan(BigDecimal value) {
      addCriterion("COMISION_SOCIO <", value, "comisionSocio");
      return (Criteria) this;
    }

    public Criteria andComisionSocioLessThanOrEqualTo(BigDecimal value) {
      addCriterion("COMISION_SOCIO <=", value, "comisionSocio");
      return (Criteria) this;
    }

    public Criteria andComisionSocioIn(List<BigDecimal> values) {
      addCriterion("COMISION_SOCIO in", values, "comisionSocio");
      return (Criteria) this;
    }

    public Criteria andComisionSocioNotIn(List<BigDecimal> values) {
      addCriterion("COMISION_SOCIO not in", values, "comisionSocio");
      return (Criteria) this;
    }

    public Criteria andComisionSocioBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("COMISION_SOCIO between", value1, value2, "comisionSocio");
      return (Criteria) this;
    }

    public Criteria andComisionSocioNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("COMISION_SOCIO not between", value1, value2, "comisionSocio");
      return (Criteria) this;
    }

    public Criteria andFondoTelemarketingIsNull() {
      addCriterion("FONDO_TELEMARKETING is null");
      return (Criteria) this;
    }

    public Criteria andFondoTelemarketingIsNotNull() {
      addCriterion("FONDO_TELEMARKETING is not null");
      return (Criteria) this;
    }

    public Criteria andFondoTelemarketingEqualTo(BigDecimal value) {
      addCriterion("FONDO_TELEMARKETING =", value, "fondoTelemarketing");
      return (Criteria) this;
    }

    public Criteria andFondoTelemarketingNotEqualTo(BigDecimal value) {
      addCriterion("FONDO_TELEMARKETING <>", value, "fondoTelemarketing");
      return (Criteria) this;
    }

    public Criteria andFondoTelemarketingGreaterThan(BigDecimal value) {
      addCriterion("FONDO_TELEMARKETING >", value, "fondoTelemarketing");
      return (Criteria) this;
    }

    public Criteria andFondoTelemarketingGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("FONDO_TELEMARKETING >=", value, "fondoTelemarketing");
      return (Criteria) this;
    }

    public Criteria andFondoTelemarketingLessThan(BigDecimal value) {
      addCriterion("FONDO_TELEMARKETING <", value, "fondoTelemarketing");
      return (Criteria) this;
    }

    public Criteria andFondoTelemarketingLessThanOrEqualTo(BigDecimal value) {
      addCriterion("FONDO_TELEMARKETING <=", value, "fondoTelemarketing");
      return (Criteria) this;
    }

    public Criteria andFondoTelemarketingIn(List<BigDecimal> values) {
      addCriterion("FONDO_TELEMARKETING in", values, "fondoTelemarketing");
      return (Criteria) this;
    }

    public Criteria andFondoTelemarketingNotIn(List<BigDecimal> values) {
      addCriterion("FONDO_TELEMARKETING not in", values, "fondoTelemarketing");
      return (Criteria) this;
    }

    public Criteria andFondoTelemarketingBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("FONDO_TELEMARKETING between", value1, value2, "fondoTelemarketing");
      return (Criteria) this;
    }

    public Criteria andFondoTelemarketingNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("FONDO_TELEMARKETING not between", value1, value2, "fondoTelemarketing");
      return (Criteria) this;
    }

    public Criteria andComisionBrokerIsNull() {
      addCriterion("COMISION_BROKER is null");
      return (Criteria) this;
    }

    public Criteria andComisionBrokerIsNotNull() {
      addCriterion("COMISION_BROKER is not null");
      return (Criteria) this;
    }

    public Criteria andComisionBrokerEqualTo(BigDecimal value) {
      addCriterion("COMISION_BROKER =", value, "comisionBroker");
      return (Criteria) this;
    }

    public Criteria andComisionBrokerNotEqualTo(BigDecimal value) {
      addCriterion("COMISION_BROKER <>", value, "comisionBroker");
      return (Criteria) this;
    }

    public Criteria andComisionBrokerGreaterThan(BigDecimal value) {
      addCriterion("COMISION_BROKER >", value, "comisionBroker");
      return (Criteria) this;
    }

    public Criteria andComisionBrokerGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("COMISION_BROKER >=", value, "comisionBroker");
      return (Criteria) this;
    }

    public Criteria andComisionBrokerLessThan(BigDecimal value) {
      addCriterion("COMISION_BROKER <", value, "comisionBroker");
      return (Criteria) this;
    }

    public Criteria andComisionBrokerLessThanOrEqualTo(BigDecimal value) {
      addCriterion("COMISION_BROKER <=", value, "comisionBroker");
      return (Criteria) this;
    }

    public Criteria andComisionBrokerIn(List<BigDecimal> values) {
      addCriterion("COMISION_BROKER in", values, "comisionBroker");
      return (Criteria) this;
    }

    public Criteria andComisionBrokerNotIn(List<BigDecimal> values) {
      addCriterion("COMISION_BROKER not in", values, "comisionBroker");
      return (Criteria) this;
    }

    public Criteria andComisionBrokerBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("COMISION_BROKER between", value1, value2, "comisionBroker");
      return (Criteria) this;
    }

    public Criteria andComisionBrokerNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("COMISION_BROKER not between", value1, value2, "comisionBroker");
      return (Criteria) this;
    }

    public Criteria andDondePagoIsNull() {
      addCriterion("DONDE_PAGO is null");
      return (Criteria) this;
    }

    public Criteria andDondePagoIsNotNull() {
      addCriterion("DONDE_PAGO is not null");
      return (Criteria) this;
    }

    public Criteria andDondePagoEqualTo(String value) {
      addCriterion("DONDE_PAGO =", value, "dondePago");
      return (Criteria) this;
    }

    public Criteria andDondePagoNotEqualTo(String value) {
      addCriterion("DONDE_PAGO <>", value, "dondePago");
      return (Criteria) this;
    }

    public Criteria andDondePagoGreaterThan(String value) {
      addCriterion("DONDE_PAGO >", value, "dondePago");
      return (Criteria) this;
    }

    public Criteria andDondePagoGreaterThanOrEqualTo(String value) {
      addCriterion("DONDE_PAGO >=", value, "dondePago");
      return (Criteria) this;
    }

    public Criteria andDondePagoLessThan(String value) {
      addCriterion("DONDE_PAGO <", value, "dondePago");
      return (Criteria) this;
    }

    public Criteria andDondePagoLessThanOrEqualTo(String value) {
      addCriterion("DONDE_PAGO <=", value, "dondePago");
      return (Criteria) this;
    }

    public Criteria andDondePagoIn(List<String> values) {
      addCriterion("DONDE_PAGO in", values, "dondePago");
      return (Criteria) this;
    }

    public Criteria andDondePagoNotIn(List<String> values) {
      addCriterion("DONDE_PAGO not in", values, "dondePago");
      return (Criteria) this;
    }

    public Criteria andDondePagoBetween(String value1, String value2) {
      addCriterion("DONDE_PAGO between", value1, value2, "dondePago");
      return (Criteria) this;
    }

    public Criteria andDondePagoNotBetween(String value1, String value2) {
      addCriterion("DONDE_PAGO not between", value1, value2, "dondePago");
      return (Criteria) this;
    }

    public Criteria andObservacionesIsNull() {
      addCriterion("OBSERVACIONES is null");
      return (Criteria) this;
    }

    public Criteria andObservacionesIsNotNull() {
      addCriterion("OBSERVACIONES is not null");
      return (Criteria) this;
    }

    public Criteria andObservacionesEqualTo(String value) {
      addCriterion("OBSERVACIONES =", value, "observaciones");
      return (Criteria) this;
    }

    public Criteria andObservacionesNotEqualTo(String value) {
      addCriterion("OBSERVACIONES <>", value, "observaciones");
      return (Criteria) this;
    }

    public Criteria andObservacionesGreaterThan(String value) {
      addCriterion("OBSERVACIONES >", value, "observaciones");
      return (Criteria) this;
    }

    public Criteria andObservacionesGreaterThanOrEqualTo(String value) {
      addCriterion("OBSERVACIONES >=", value, "observaciones");
      return (Criteria) this;
    }

    public Criteria andObservacionesLessThan(String value) {
      addCriterion("OBSERVACIONES <", value, "observaciones");
      return (Criteria) this;
    }

    public Criteria andObservacionesLessThanOrEqualTo(String value) {
      addCriterion("OBSERVACIONES <=", value, "observaciones");
      return (Criteria) this;
    }

    public Criteria andObservacionesIn(List<String> values) {
      addCriterion("OBSERVACIONES in", values, "observaciones");
      return (Criteria) this;
    }

    public Criteria andObservacionesNotIn(List<String> values) {
      addCriterion("OBSERVACIONES not in", values, "observaciones");
      return (Criteria) this;
    }

    public Criteria andObservacionesBetween(String value1, String value2) {
      addCriterion("OBSERVACIONES between", value1, value2, "observaciones");
      return (Criteria) this;
    }

    public Criteria andObservacionesNotBetween(String value1, String value2) {
      addCriterion("OBSERVACIONES not between", value1, value2, "observaciones");
      return (Criteria) this;
    }

    public Criteria andSecArchivoIsNull() {
      addCriterion("SEC_ARCHIVO is null");
      return (Criteria) this;
    }

    public Criteria andSecArchivoIsNotNull() {
      addCriterion("SEC_ARCHIVO is not null");
      return (Criteria) this;
    }

    public Criteria andSecArchivoEqualTo(Long value) {
      addCriterion("SEC_ARCHIVO =", value, "secArchivo");
      return (Criteria) this;
    }

    public Criteria andSecArchivoNotEqualTo(Long value) {
      addCriterion("SEC_ARCHIVO <>", value, "secArchivo");
      return (Criteria) this;
    }

    public Criteria andSecArchivoGreaterThan(Long value) {
      addCriterion("SEC_ARCHIVO >", value, "secArchivo");
      return (Criteria) this;
    }

    public Criteria andSecArchivoGreaterThanOrEqualTo(Long value) {
      addCriterion("SEC_ARCHIVO >=", value, "secArchivo");
      return (Criteria) this;
    }

    public Criteria andSecArchivoLessThan(Long value) {
      addCriterion("SEC_ARCHIVO <", value, "secArchivo");
      return (Criteria) this;
    }

    public Criteria andSecArchivoLessThanOrEqualTo(Long value) {
      addCriterion("SEC_ARCHIVO <=", value, "secArchivo");
      return (Criteria) this;
    }

    public Criteria andSecArchivoIn(List<Long> values) {
      addCriterion("SEC_ARCHIVO in", values, "secArchivo");
      return (Criteria) this;
    }

    public Criteria andSecArchivoNotIn(List<Long> values) {
      addCriterion("SEC_ARCHIVO not in", values, "secArchivo");
      return (Criteria) this;
    }

    public Criteria andSecArchivoBetween(Long value1, Long value2) {
      addCriterion("SEC_ARCHIVO between", value1, value2, "secArchivo");
      return (Criteria) this;
    }

    public Criteria andSecArchivoNotBetween(Long value1, Long value2) {
      addCriterion("SEC_ARCHIVO not between", value1, value2, "secArchivo");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated do_not_delete_during_merge Mon Jul 21 21:23:55 COT 2014
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}