package com.cardif.satelite.model.satelite;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MasterPrecioSoatExample implements Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.MASTER_PRECIOS_SOAT
   *
   * @mbggenerated Mon Jul 07 10:52:45 COT 2014
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.MASTER_PRECIOS_SOAT
   *
   * @mbggenerated Mon Jul 07 10:52:45 COT 2014
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.MASTER_PRECIOS_SOAT
   *
   * @mbggenerated Mon Jul 07 10:52:45 COT 2014
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MASTER_PRECIOS_SOAT
   *
   * @mbggenerated Mon Jul 07 10:52:45 COT 2014
   */
  public MasterPrecioSoatExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MASTER_PRECIOS_SOAT
   *
   * @mbggenerated Mon Jul 07 10:52:45 COT 2014
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MASTER_PRECIOS_SOAT
   *
   * @mbggenerated Mon Jul 07 10:52:45 COT 2014
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MASTER_PRECIOS_SOAT
   *
   * @mbggenerated Mon Jul 07 10:52:45 COT 2014
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MASTER_PRECIOS_SOAT
   *
   * @mbggenerated Mon Jul 07 10:52:45 COT 2014
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MASTER_PRECIOS_SOAT
   *
   * @mbggenerated Mon Jul 07 10:52:45 COT 2014
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MASTER_PRECIOS_SOAT
   *
   * @mbggenerated Mon Jul 07 10:52:45 COT 2014
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MASTER_PRECIOS_SOAT
   *
   * @mbggenerated Mon Jul 07 10:52:45 COT 2014
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MASTER_PRECIOS_SOAT
   *
   * @mbggenerated Mon Jul 07 10:52:45 COT 2014
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MASTER_PRECIOS_SOAT
   *
   * @mbggenerated Mon Jul 07 10:52:45 COT 2014
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MASTER_PRECIOS_SOAT
   *
   * @mbggenerated Mon Jul 07 10:52:45 COT 2014
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.MASTER_PRECIOS_SOAT
   *
   * @mbggenerated Mon Jul 07 10:52:45 COT 2014
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andCodSocioIsNull() {
      addCriterion("COD_SOCIO is null");
      return (Criteria) this;
    }

    public Criteria andCodSocioIsNotNull() {
      addCriterion("COD_SOCIO is not null");
      return (Criteria) this;
    }

    public Criteria andCodSocioEqualTo(String value) {
      addCriterion("COD_SOCIO =", value, "codSocio");
      return (Criteria) this;
    }

    public Criteria andCodSocioNotEqualTo(String value) {
      addCriterion("COD_SOCIO <>", value, "codSocio");
      return (Criteria) this;
    }

    public Criteria andCodSocioGreaterThan(String value) {
      addCriterion("COD_SOCIO >", value, "codSocio");
      return (Criteria) this;
    }

    public Criteria andCodSocioGreaterThanOrEqualTo(String value) {
      addCriterion("COD_SOCIO >=", value, "codSocio");
      return (Criteria) this;
    }

    public Criteria andCodSocioLessThan(String value) {
      addCriterion("COD_SOCIO <", value, "codSocio");
      return (Criteria) this;
    }

    public Criteria andCodSocioLessThanOrEqualTo(String value) {
      addCriterion("COD_SOCIO <=", value, "codSocio");
      return (Criteria) this;
    }

    public Criteria andCodSocioIn(List<String> values) {
      addCriterion("COD_SOCIO in", values, "codSocio");
      return (Criteria) this;
    }

    public Criteria andCodSocioNotIn(List<String> values) {
      addCriterion("COD_SOCIO not in", values, "codSocio");
      return (Criteria) this;
    }

    public Criteria andCodSocioBetween(String value1, String value2) {
      addCriterion("COD_SOCIO between", value1, value2, "codSocio");
      return (Criteria) this;
    }

    public Criteria andCodSocioNotBetween(String value1, String value2) {
      addCriterion("COD_SOCIO not between", value1, value2, "codSocio");
      return (Criteria) this;
    }

    public Criteria andCodMasterIsNull() {
      addCriterion("COD_MASTER is null");
      return (Criteria) this;
    }

    public Criteria andCodMasterIsNotNull() {
      addCriterion("COD_MASTER is not null");
      return (Criteria) this;
    }

    public Criteria andCodMasterEqualTo(String value) {
      addCriterion("COD_MASTER =", value, "codMaster");
      return (Criteria) this;
    }

    public Criteria andCodMasterNotEqualTo(String value) {
      addCriterion("COD_MASTER <>", value, "codMaster");
      return (Criteria) this;
    }

    public Criteria andCodMasterGreaterThan(String value) {
      addCriterion("COD_MASTER >", value, "codMaster");
      return (Criteria) this;
    }

    public Criteria andCodMasterGreaterThanOrEqualTo(String value) {
      addCriterion("COD_MASTER >=", value, "codMaster");
      return (Criteria) this;
    }

    public Criteria andCodMasterLessThan(String value) {
      addCriterion("COD_MASTER <", value, "codMaster");
      return (Criteria) this;
    }

    public Criteria andCodMasterLessThanOrEqualTo(String value) {
      addCriterion("COD_MASTER <=", value, "codMaster");
      return (Criteria) this;
    }

    public Criteria andCodMasterIn(List<String> values) {
      addCriterion("COD_MASTER in", values, "codMaster");
      return (Criteria) this;
    }

    public Criteria andCodMasterNotIn(List<String> values) {
      addCriterion("COD_MASTER not in", values, "codMaster");
      return (Criteria) this;
    }

    public Criteria andCodMasterBetween(String value1, String value2) {
      addCriterion("COD_MASTER between", value1, value2, "codMaster");
      return (Criteria) this;
    }

    public Criteria andCodMasterNotBetween(String value1, String value2) {
      addCriterion("COD_MASTER not between", value1, value2, "codMaster");
      return (Criteria) this;
    }

    public Criteria andCanalIsNull() {
      addCriterion("CANAL is null");
      return (Criteria) this;
    }

    public Criteria andCanalIsNotNull() {
      addCriterion("CANAL is not null");
      return (Criteria) this;
    }

    public Criteria andCanalEqualTo(String value) {
      addCriterion("CANAL =", value, "canal");
      return (Criteria) this;
    }

    public Criteria andCanalNotEqualTo(String value) {
      addCriterion("CANAL <>", value, "canal");
      return (Criteria) this;
    }

    public Criteria andCanalGreaterThan(String value) {
      addCriterion("CANAL >", value, "canal");
      return (Criteria) this;
    }

    public Criteria andCanalGreaterThanOrEqualTo(String value) {
      addCriterion("CANAL >=", value, "canal");
      return (Criteria) this;
    }

    public Criteria andCanalLessThan(String value) {
      addCriterion("CANAL <", value, "canal");
      return (Criteria) this;
    }

    public Criteria andCanalLessThanOrEqualTo(String value) {
      addCriterion("CANAL <=", value, "canal");
      return (Criteria) this;
    }

    public Criteria andCanalIn(List<String> values) {
      addCriterion("CANAL in", values, "canal");
      return (Criteria) this;
    }

    public Criteria andCanalNotIn(List<String> values) {
      addCriterion("CANAL not in", values, "canal");
      return (Criteria) this;
    }

    public Criteria andCanalBetween(String value1, String value2) {
      addCriterion("CANAL between", value1, value2, "canal");
      return (Criteria) this;
    }

    public Criteria andCanalNotBetween(String value1, String value2) {
      addCriterion("CANAL not between", value1, value2, "canal");
      return (Criteria) this;
    }

    public Criteria andMedioPagoIsNull() {
      addCriterion("MEDIO_PAGO is null");
      return (Criteria) this;
    }

    public Criteria andMedioPagoIsNotNull() {
      addCriterion("MEDIO_PAGO is not null");
      return (Criteria) this;
    }

    public Criteria andMedioPagoEqualTo(String value) {
      addCriterion("MEDIO_PAGO =", value, "medioPago");
      return (Criteria) this;
    }

    public Criteria andMedioPagoNotEqualTo(String value) {
      addCriterion("MEDIO_PAGO <>", value, "medioPago");
      return (Criteria) this;
    }

    public Criteria andMedioPagoGreaterThan(String value) {
      addCriterion("MEDIO_PAGO >", value, "medioPago");
      return (Criteria) this;
    }

    public Criteria andMedioPagoGreaterThanOrEqualTo(String value) {
      addCriterion("MEDIO_PAGO >=", value, "medioPago");
      return (Criteria) this;
    }

    public Criteria andMedioPagoLessThan(String value) {
      addCriterion("MEDIO_PAGO <", value, "medioPago");
      return (Criteria) this;
    }

    public Criteria andMedioPagoLessThanOrEqualTo(String value) {
      addCriterion("MEDIO_PAGO <=", value, "medioPago");
      return (Criteria) this;
    }

    public Criteria andMedioPagoIn(List<String> values) {
      addCriterion("MEDIO_PAGO in", values, "medioPago");
      return (Criteria) this;
    }

    public Criteria andMedioPagoNotIn(List<String> values) {
      addCriterion("MEDIO_PAGO not in", values, "medioPago");
      return (Criteria) this;
    }

    public Criteria andMedioPagoBetween(String value1, String value2) {
      addCriterion("MEDIO_PAGO between", value1, value2, "medioPago");
      return (Criteria) this;
    }

    public Criteria andMedioPagoNotBetween(String value1, String value2) {
      addCriterion("MEDIO_PAGO not between", value1, value2, "medioPago");
      return (Criteria) this;
    }

    public Criteria andDepartamentoIsNull() {
      addCriterion("DEPARTAMENTO is null");
      return (Criteria) this;
    }

    public Criteria andDepartamentoIsNotNull() {
      addCriterion("DEPARTAMENTO is not null");
      return (Criteria) this;
    }

    public Criteria andDepartamentoEqualTo(String value) {
      addCriterion("DEPARTAMENTO =", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoNotEqualTo(String value) {
      addCriterion("DEPARTAMENTO <>", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoGreaterThan(String value) {
      addCriterion("DEPARTAMENTO >", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoGreaterThanOrEqualTo(String value) {
      addCriterion("DEPARTAMENTO >=", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoLessThan(String value) {
      addCriterion("DEPARTAMENTO <", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoLessThanOrEqualTo(String value) {
      addCriterion("DEPARTAMENTO <=", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoIn(List<String> values) {
      addCriterion("DEPARTAMENTO in", values, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoNotIn(List<String> values) {
      addCriterion("DEPARTAMENTO not in", values, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoBetween(String value1, String value2) {
      addCriterion("DEPARTAMENTO between", value1, value2, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoNotBetween(String value1, String value2) {
      addCriterion("DEPARTAMENTO not between", value1, value2, "departamento");
      return (Criteria) this;
    }

    public Criteria andUsoIsNull() {
      addCriterion("USO is null");
      return (Criteria) this;
    }

    public Criteria andUsoIsNotNull() {
      addCriterion("USO is not null");
      return (Criteria) this;
    }

    public Criteria andUsoEqualTo(String value) {
      addCriterion("USO =", value, "uso");
      return (Criteria) this;
    }

    public Criteria andUsoNotEqualTo(String value) {
      addCriterion("USO <>", value, "uso");
      return (Criteria) this;
    }

    public Criteria andUsoGreaterThan(String value) {
      addCriterion("USO >", value, "uso");
      return (Criteria) this;
    }

    public Criteria andUsoGreaterThanOrEqualTo(String value) {
      addCriterion("USO >=", value, "uso");
      return (Criteria) this;
    }

    public Criteria andUsoLessThan(String value) {
      addCriterion("USO <", value, "uso");
      return (Criteria) this;
    }

    public Criteria andUsoLessThanOrEqualTo(String value) {
      addCriterion("USO <=", value, "uso");
      return (Criteria) this;
    }

    public Criteria andUsoIn(List<String> values) {
      addCriterion("USO in", values, "uso");
      return (Criteria) this;
    }

    public Criteria andUsoNotIn(List<String> values) {
      addCriterion("USO not in", values, "uso");
      return (Criteria) this;
    }

    public Criteria andUsoBetween(String value1, String value2) {
      addCriterion("USO between", value1, value2, "uso");
      return (Criteria) this;
    }

    public Criteria andUsoNotBetween(String value1, String value2) {
      addCriterion("USO not between", value1, value2, "uso");
      return (Criteria) this;
    }

    public Criteria andCategoriaIsNull() {
      addCriterion("CATEGORIA is null");
      return (Criteria) this;
    }

    public Criteria andCategoriaIsNotNull() {
      addCriterion("CATEGORIA is not null");
      return (Criteria) this;
    }

    public Criteria andCategoriaEqualTo(String value) {
      addCriterion("CATEGORIA =", value, "categoria");
      return (Criteria) this;
    }

    public Criteria andCategoriaNotEqualTo(String value) {
      addCriterion("CATEGORIA <>", value, "categoria");
      return (Criteria) this;
    }

    public Criteria andCategoriaGreaterThan(String value) {
      addCriterion("CATEGORIA >", value, "categoria");
      return (Criteria) this;
    }

    public Criteria andCategoriaGreaterThanOrEqualTo(String value) {
      addCriterion("CATEGORIA >=", value, "categoria");
      return (Criteria) this;
    }

    public Criteria andCategoriaLessThan(String value) {
      addCriterion("CATEGORIA <", value, "categoria");
      return (Criteria) this;
    }

    public Criteria andCategoriaLessThanOrEqualTo(String value) {
      addCriterion("CATEGORIA <=", value, "categoria");
      return (Criteria) this;
    }

    public Criteria andCategoriaIn(List<String> values) {
      addCriterion("CATEGORIA in", values, "categoria");
      return (Criteria) this;
    }

    public Criteria andCategoriaNotIn(List<String> values) {
      addCriterion("CATEGORIA not in", values, "categoria");
      return (Criteria) this;
    }

    public Criteria andCategoriaBetween(String value1, String value2) {
      addCriterion("CATEGORIA between", value1, value2, "categoria");
      return (Criteria) this;
    }

    public Criteria andCategoriaNotBetween(String value1, String value2) {
      addCriterion("CATEGORIA not between", value1, value2, "categoria");
      return (Criteria) this;
    }

    public Criteria andNroAsientosIsNull() {
      addCriterion("NRO_ASIENTOS is null");
      return (Criteria) this;
    }

    public Criteria andNroAsientosIsNotNull() {
      addCriterion("NRO_ASIENTOS is not null");
      return (Criteria) this;
    }

    public Criteria andNroAsientosEqualTo(Short value) {
      addCriterion("NRO_ASIENTOS =", value, "nroAsientos");
      return (Criteria) this;
    }

    public Criteria andNroAsientosNotEqualTo(Short value) {
      addCriterion("NRO_ASIENTOS <>", value, "nroAsientos");
      return (Criteria) this;
    }

    public Criteria andNroAsientosGreaterThan(Short value) {
      addCriterion("NRO_ASIENTOS >", value, "nroAsientos");
      return (Criteria) this;
    }

    public Criteria andNroAsientosGreaterThanOrEqualTo(Short value) {
      addCriterion("NRO_ASIENTOS >=", value, "nroAsientos");
      return (Criteria) this;
    }

    public Criteria andNroAsientosLessThan(Short value) {
      addCriterion("NRO_ASIENTOS <", value, "nroAsientos");
      return (Criteria) this;
    }

    public Criteria andNroAsientosLessThanOrEqualTo(Short value) {
      addCriterion("NRO_ASIENTOS <=", value, "nroAsientos");
      return (Criteria) this;
    }

    public Criteria andNroAsientosIn(List<Short> values) {
      addCriterion("NRO_ASIENTOS in", values, "nroAsientos");
      return (Criteria) this;
    }

    public Criteria andNroAsientosNotIn(List<Short> values) {
      addCriterion("NRO_ASIENTOS not in", values, "nroAsientos");
      return (Criteria) this;
    }

    public Criteria andNroAsientosBetween(Short value1, Short value2) {
      addCriterion("NRO_ASIENTOS between", value1, value2, "nroAsientos");
      return (Criteria) this;
    }

    public Criteria andNroAsientosNotBetween(Short value1, Short value2) {
      addCriterion("NRO_ASIENTOS not between", value1, value2, "nroAsientos");
      return (Criteria) this;
    }

    public Criteria andMarcaIsNull() {
      addCriterion("MARCA is null");
      return (Criteria) this;
    }

    public Criteria andMarcaIsNotNull() {
      addCriterion("MARCA is not null");
      return (Criteria) this;
    }

    public Criteria andMarcaEqualTo(String value) {
      addCriterion("MARCA =", value, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaNotEqualTo(String value) {
      addCriterion("MARCA <>", value, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaGreaterThan(String value) {
      addCriterion("MARCA >", value, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaGreaterThanOrEqualTo(String value) {
      addCriterion("MARCA >=", value, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaLessThan(String value) {
      addCriterion("MARCA <", value, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaLessThanOrEqualTo(String value) {
      addCriterion("MARCA <=", value, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaIn(List<String> values) {
      addCriterion("MARCA in", values, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaNotIn(List<String> values) {
      addCriterion("MARCA not in", values, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaBetween(String value1, String value2) {
      addCriterion("MARCA between", value1, value2, "marca");
      return (Criteria) this;
    }

    public Criteria andMarcaNotBetween(String value1, String value2) {
      addCriterion("MARCA not between", value1, value2, "marca");
      return (Criteria) this;
    }

    public Criteria andModeloIsNull() {
      addCriterion("MODELO is null");
      return (Criteria) this;
    }

    public Criteria andModeloIsNotNull() {
      addCriterion("MODELO is not null");
      return (Criteria) this;
    }

    public Criteria andModeloEqualTo(String value) {
      addCriterion("MODELO =", value, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloNotEqualTo(String value) {
      addCriterion("MODELO <>", value, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloGreaterThan(String value) {
      addCriterion("MODELO >", value, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloGreaterThanOrEqualTo(String value) {
      addCriterion("MODELO >=", value, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloLessThan(String value) {
      addCriterion("MODELO <", value, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloLessThanOrEqualTo(String value) {
      addCriterion("MODELO <=", value, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloIn(List<String> values) {
      addCriterion("MODELO in", values, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloNotIn(List<String> values) {
      addCriterion("MODELO not in", values, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloBetween(String value1, String value2) {
      addCriterion("MODELO between", value1, value2, "modelo");
      return (Criteria) this;
    }

    public Criteria andModeloNotBetween(String value1, String value2) {
      addCriterion("MODELO not between", value1, value2, "modelo");
      return (Criteria) this;
    }

    public Criteria andPrimaIsNull() {
      addCriterion("PRIMA is null");
      return (Criteria) this;
    }

    public Criteria andPrimaIsNotNull() {
      addCriterion("PRIMA is not null");
      return (Criteria) this;
    }

    public Criteria andPrimaEqualTo(BigDecimal value) {
      addCriterion("PRIMA =", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaNotEqualTo(BigDecimal value) {
      addCriterion("PRIMA <>", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaGreaterThan(BigDecimal value) {
      addCriterion("PRIMA >", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("PRIMA >=", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaLessThan(BigDecimal value) {
      addCriterion("PRIMA <", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaLessThanOrEqualTo(BigDecimal value) {
      addCriterion("PRIMA <=", value, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaIn(List<BigDecimal> values) {
      addCriterion("PRIMA in", values, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaNotIn(List<BigDecimal> values) {
      addCriterion("PRIMA not in", values, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PRIMA between", value1, value2, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PRIMA not between", value1, value2, "prima");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaIsNull() {
      addCriterion("PRIMA_TECNICA is null");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaIsNotNull() {
      addCriterion("PRIMA_TECNICA is not null");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaEqualTo(BigDecimal value) {
      addCriterion("PRIMA_TECNICA =", value, "primaTecnica");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaNotEqualTo(BigDecimal value) {
      addCriterion("PRIMA_TECNICA <>", value, "primaTecnica");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaGreaterThan(BigDecimal value) {
      addCriterion("PRIMA_TECNICA >", value, "primaTecnica");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("PRIMA_TECNICA >=", value, "primaTecnica");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaLessThan(BigDecimal value) {
      addCriterion("PRIMA_TECNICA <", value, "primaTecnica");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaLessThanOrEqualTo(BigDecimal value) {
      addCriterion("PRIMA_TECNICA <=", value, "primaTecnica");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaIn(List<BigDecimal> values) {
      addCriterion("PRIMA_TECNICA in", values, "primaTecnica");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaNotIn(List<BigDecimal> values) {
      addCriterion("PRIMA_TECNICA not in", values, "primaTecnica");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PRIMA_TECNICA between", value1, value2, "primaTecnica");
      return (Criteria) this;
    }

    public Criteria andPrimaTecnicaNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PRIMA_TECNICA not between", value1, value2, "primaTecnica");
      return (Criteria) this;
    }

    public Criteria andExcluidoIsNull() {
      addCriterion("EXCLUIDO is null");
      return (Criteria) this;
    }

    public Criteria andExcluidoIsNotNull() {
      addCriterion("EXCLUIDO is not null");
      return (Criteria) this;
    }

    public Criteria andExcluidoEqualTo(Short value) {
      addCriterion("EXCLUIDO =", value, "excluido");
      return (Criteria) this;
    }

    public Criteria andExcluidoNotEqualTo(Short value) {
      addCriterion("EXCLUIDO <>", value, "excluido");
      return (Criteria) this;
    }

    public Criteria andExcluidoGreaterThan(Short value) {
      addCriterion("EXCLUIDO >", value, "excluido");
      return (Criteria) this;
    }

    public Criteria andExcluidoGreaterThanOrEqualTo(Short value) {
      addCriterion("EXCLUIDO >=", value, "excluido");
      return (Criteria) this;
    }

    public Criteria andExcluidoLessThan(Short value) {
      addCriterion("EXCLUIDO <", value, "excluido");
      return (Criteria) this;
    }

    public Criteria andExcluidoLessThanOrEqualTo(Short value) {
      addCriterion("EXCLUIDO <=", value, "excluido");
      return (Criteria) this;
    }

    public Criteria andExcluidoIn(List<Short> values) {
      addCriterion("EXCLUIDO in", values, "excluido");
      return (Criteria) this;
    }

    public Criteria andExcluidoNotIn(List<Short> values) {
      addCriterion("EXCLUIDO not in", values, "excluido");
      return (Criteria) this;
    }

    public Criteria andExcluidoBetween(Short value1, Short value2) {
      addCriterion("EXCLUIDO between", value1, value2, "excluido");
      return (Criteria) this;
    }

    public Criteria andExcluidoNotBetween(Short value1, Short value2) {
      addCriterion("EXCLUIDO not between", value1, value2, "excluido");
      return (Criteria) this;
    }

    public Criteria andIgvIsNull() {
      addCriterion("IGV is null");
      return (Criteria) this;
    }

    public Criteria andIgvIsNotNull() {
      addCriterion("IGV is not null");
      return (Criteria) this;
    }

    public Criteria andIgvEqualTo(BigDecimal value) {
      addCriterion("IGV =", value, "igv");
      return (Criteria) this;
    }

    public Criteria andIgvNotEqualTo(BigDecimal value) {
      addCriterion("IGV <>", value, "igv");
      return (Criteria) this;
    }

    public Criteria andIgvGreaterThan(BigDecimal value) {
      addCriterion("IGV >", value, "igv");
      return (Criteria) this;
    }

    public Criteria andIgvGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("IGV >=", value, "igv");
      return (Criteria) this;
    }

    public Criteria andIgvLessThan(BigDecimal value) {
      addCriterion("IGV <", value, "igv");
      return (Criteria) this;
    }

    public Criteria andIgvLessThanOrEqualTo(BigDecimal value) {
      addCriterion("IGV <=", value, "igv");
      return (Criteria) this;
    }

    public Criteria andIgvIn(List<BigDecimal> values) {
      addCriterion("IGV in", values, "igv");
      return (Criteria) this;
    }

    public Criteria andIgvNotIn(List<BigDecimal> values) {
      addCriterion("IGV not in", values, "igv");
      return (Criteria) this;
    }

    public Criteria andIgvBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("IGV between", value1, value2, "igv");
      return (Criteria) this;
    }

    public Criteria andIgvNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("IGV not between", value1, value2, "igv");
      return (Criteria) this;
    }

    public Criteria andDeIsNull() {
      addCriterion("DE is null");
      return (Criteria) this;
    }

    public Criteria andDeIsNotNull() {
      addCriterion("DE is not null");
      return (Criteria) this;
    }

    public Criteria andDeEqualTo(BigDecimal value) {
      addCriterion("DE =", value, "de");
      return (Criteria) this;
    }

    public Criteria andDeNotEqualTo(BigDecimal value) {
      addCriterion("DE <>", value, "de");
      return (Criteria) this;
    }

    public Criteria andDeGreaterThan(BigDecimal value) {
      addCriterion("DE >", value, "de");
      return (Criteria) this;
    }

    public Criteria andDeGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("DE >=", value, "de");
      return (Criteria) this;
    }

    public Criteria andDeLessThan(BigDecimal value) {
      addCriterion("DE <", value, "de");
      return (Criteria) this;
    }

    public Criteria andDeLessThanOrEqualTo(BigDecimal value) {
      addCriterion("DE <=", value, "de");
      return (Criteria) this;
    }

    public Criteria andDeIn(List<BigDecimal> values) {
      addCriterion("DE in", values, "de");
      return (Criteria) this;
    }

    public Criteria andDeNotIn(List<BigDecimal> values) {
      addCriterion("DE not in", values, "de");
      return (Criteria) this;
    }

    public Criteria andDeBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("DE between", value1, value2, "de");
      return (Criteria) this;
    }

    public Criteria andDeNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("DE not between", value1, value2, "de");
      return (Criteria) this;
    }

    public Criteria andFndCompIsNull() {
      addCriterion("FND_COMP is null");
      return (Criteria) this;
    }

    public Criteria andFndCompIsNotNull() {
      addCriterion("FND_COMP is not null");
      return (Criteria) this;
    }

    public Criteria andFndCompEqualTo(BigDecimal value) {
      addCriterion("FND_COMP =", value, "fndComp");
      return (Criteria) this;
    }

    public Criteria andFndCompNotEqualTo(BigDecimal value) {
      addCriterion("FND_COMP <>", value, "fndComp");
      return (Criteria) this;
    }

    public Criteria andFndCompGreaterThan(BigDecimal value) {
      addCriterion("FND_COMP >", value, "fndComp");
      return (Criteria) this;
    }

    public Criteria andFndCompGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("FND_COMP >=", value, "fndComp");
      return (Criteria) this;
    }

    public Criteria andFndCompLessThan(BigDecimal value) {
      addCriterion("FND_COMP <", value, "fndComp");
      return (Criteria) this;
    }

    public Criteria andFndCompLessThanOrEqualTo(BigDecimal value) {
      addCriterion("FND_COMP <=", value, "fndComp");
      return (Criteria) this;
    }

    public Criteria andFndCompIn(List<BigDecimal> values) {
      addCriterion("FND_COMP in", values, "fndComp");
      return (Criteria) this;
    }

    public Criteria andFndCompNotIn(List<BigDecimal> values) {
      addCriterion("FND_COMP not in", values, "fndComp");
      return (Criteria) this;
    }

    public Criteria andFndCompBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("FND_COMP between", value1, value2, "fndComp");
      return (Criteria) this;
    }

    public Criteria andFndCompNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("FND_COMP not between", value1, value2, "fndComp");
      return (Criteria) this;
    }

    public Criteria andComCobranzaIsNull() {
      addCriterion("COM_COBRANZA is null");
      return (Criteria) this;
    }

    public Criteria andComCobranzaIsNotNull() {
      addCriterion("COM_COBRANZA is not null");
      return (Criteria) this;
    }

    public Criteria andComCobranzaEqualTo(BigDecimal value) {
      addCriterion("COM_COBRANZA =", value, "comCobranza");
      return (Criteria) this;
    }

    public Criteria andComCobranzaNotEqualTo(BigDecimal value) {
      addCriterion("COM_COBRANZA <>", value, "comCobranza");
      return (Criteria) this;
    }

    public Criteria andComCobranzaGreaterThan(BigDecimal value) {
      addCriterion("COM_COBRANZA >", value, "comCobranza");
      return (Criteria) this;
    }

    public Criteria andComCobranzaGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("COM_COBRANZA >=", value, "comCobranza");
      return (Criteria) this;
    }

    public Criteria andComCobranzaLessThan(BigDecimal value) {
      addCriterion("COM_COBRANZA <", value, "comCobranza");
      return (Criteria) this;
    }

    public Criteria andComCobranzaLessThanOrEqualTo(BigDecimal value) {
      addCriterion("COM_COBRANZA <=", value, "comCobranza");
      return (Criteria) this;
    }

    public Criteria andComCobranzaIn(List<BigDecimal> values) {
      addCriterion("COM_COBRANZA in", values, "comCobranza");
      return (Criteria) this;
    }

    public Criteria andComCobranzaNotIn(List<BigDecimal> values) {
      addCriterion("COM_COBRANZA not in", values, "comCobranza");
      return (Criteria) this;
    }

    public Criteria andComCobranzaBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("COM_COBRANZA between", value1, value2, "comCobranza");
      return (Criteria) this;
    }

    public Criteria andComCobranzaNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("COM_COBRANZA not between", value1, value2, "comCobranza");
      return (Criteria) this;
    }

    public Criteria andComSocioIsNull() {
      addCriterion("COM_SOCIO is null");
      return (Criteria) this;
    }

    public Criteria andComSocioIsNotNull() {
      addCriterion("COM_SOCIO is not null");
      return (Criteria) this;
    }

    public Criteria andComSocioEqualTo(BigDecimal value) {
      addCriterion("COM_SOCIO =", value, "comSocio");
      return (Criteria) this;
    }

    public Criteria andComSocioNotEqualTo(BigDecimal value) {
      addCriterion("COM_SOCIO <>", value, "comSocio");
      return (Criteria) this;
    }

    public Criteria andComSocioGreaterThan(BigDecimal value) {
      addCriterion("COM_SOCIO >", value, "comSocio");
      return (Criteria) this;
    }

    public Criteria andComSocioGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("COM_SOCIO >=", value, "comSocio");
      return (Criteria) this;
    }

    public Criteria andComSocioLessThan(BigDecimal value) {
      addCriterion("COM_SOCIO <", value, "comSocio");
      return (Criteria) this;
    }

    public Criteria andComSocioLessThanOrEqualTo(BigDecimal value) {
      addCriterion("COM_SOCIO <=", value, "comSocio");
      return (Criteria) this;
    }

    public Criteria andComSocioIn(List<BigDecimal> values) {
      addCriterion("COM_SOCIO in", values, "comSocio");
      return (Criteria) this;
    }

    public Criteria andComSocioNotIn(List<BigDecimal> values) {
      addCriterion("COM_SOCIO not in", values, "comSocio");
      return (Criteria) this;
    }

    public Criteria andComSocioBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("COM_SOCIO between", value1, value2, "comSocio");
      return (Criteria) this;
    }

    public Criteria andComSocioNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("COM_SOCIO not between", value1, value2, "comSocio");
      return (Criteria) this;
    }

    public Criteria andFdoTlmkIsNull() {
      addCriterion("FDO_TLMK is null");
      return (Criteria) this;
    }

    public Criteria andFdoTlmkIsNotNull() {
      addCriterion("FDO_TLMK is not null");
      return (Criteria) this;
    }

    public Criteria andFdoTlmkEqualTo(BigDecimal value) {
      addCriterion("FDO_TLMK =", value, "fdoTlmk");
      return (Criteria) this;
    }

    public Criteria andFdoTlmkNotEqualTo(BigDecimal value) {
      addCriterion("FDO_TLMK <>", value, "fdoTlmk");
      return (Criteria) this;
    }

    public Criteria andFdoTlmkGreaterThan(BigDecimal value) {
      addCriterion("FDO_TLMK >", value, "fdoTlmk");
      return (Criteria) this;
    }

    public Criteria andFdoTlmkGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("FDO_TLMK >=", value, "fdoTlmk");
      return (Criteria) this;
    }

    public Criteria andFdoTlmkLessThan(BigDecimal value) {
      addCriterion("FDO_TLMK <", value, "fdoTlmk");
      return (Criteria) this;
    }

    public Criteria andFdoTlmkLessThanOrEqualTo(BigDecimal value) {
      addCriterion("FDO_TLMK <=", value, "fdoTlmk");
      return (Criteria) this;
    }

    public Criteria andFdoTlmkIn(List<BigDecimal> values) {
      addCriterion("FDO_TLMK in", values, "fdoTlmk");
      return (Criteria) this;
    }

    public Criteria andFdoTlmkNotIn(List<BigDecimal> values) {
      addCriterion("FDO_TLMK not in", values, "fdoTlmk");
      return (Criteria) this;
    }

    public Criteria andFdoTlmkBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("FDO_TLMK between", value1, value2, "fdoTlmk");
      return (Criteria) this;
    }

    public Criteria andFdoTlmkNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("FDO_TLMK not between", value1, value2, "fdoTlmk");
      return (Criteria) this;
    }

    public Criteria andComBrokerIsNull() {
      addCriterion("COM_BROKER is null");
      return (Criteria) this;
    }

    public Criteria andComBrokerIsNotNull() {
      addCriterion("COM_BROKER is not null");
      return (Criteria) this;
    }

    public Criteria andComBrokerEqualTo(BigDecimal value) {
      addCriterion("COM_BROKER =", value, "comBroker");
      return (Criteria) this;
    }

    public Criteria andComBrokerNotEqualTo(BigDecimal value) {
      addCriterion("COM_BROKER <>", value, "comBroker");
      return (Criteria) this;
    }

    public Criteria andComBrokerGreaterThan(BigDecimal value) {
      addCriterion("COM_BROKER >", value, "comBroker");
      return (Criteria) this;
    }

    public Criteria andComBrokerGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("COM_BROKER >=", value, "comBroker");
      return (Criteria) this;
    }

    public Criteria andComBrokerLessThan(BigDecimal value) {
      addCriterion("COM_BROKER <", value, "comBroker");
      return (Criteria) this;
    }

    public Criteria andComBrokerLessThanOrEqualTo(BigDecimal value) {
      addCriterion("COM_BROKER <=", value, "comBroker");
      return (Criteria) this;
    }

    public Criteria andComBrokerIn(List<BigDecimal> values) {
      addCriterion("COM_BROKER in", values, "comBroker");
      return (Criteria) this;
    }

    public Criteria andComBrokerNotIn(List<BigDecimal> values) {
      addCriterion("COM_BROKER not in", values, "comBroker");
      return (Criteria) this;
    }

    public Criteria andComBrokerBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("COM_BROKER between", value1, value2, "comBroker");
      return (Criteria) this;
    }

    public Criteria andComBrokerNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("COM_BROKER not between", value1, value2, "comBroker");
      return (Criteria) this;
    }

    public Criteria andFecValidezIsNull() {
      addCriterion("FEC_VALIDEZ is null");
      return (Criteria) this;
    }

    public Criteria andFecValidezIsNotNull() {
      addCriterion("FEC_VALIDEZ is not null");
      return (Criteria) this;
    }

    public Criteria andFecValidezEqualTo(Date value) {
      addCriterion("FEC_VALIDEZ =", value, "fecValidez");
      return (Criteria) this;
    }

    public Criteria andFecValidezNotEqualTo(Date value) {
      addCriterion("FEC_VALIDEZ <>", value, "fecValidez");
      return (Criteria) this;
    }

    public Criteria andFecValidezGreaterThan(Date value) {
      addCriterion("FEC_VALIDEZ >", value, "fecValidez");
      return (Criteria) this;
    }

    public Criteria andFecValidezGreaterThanOrEqualTo(Date value) {
      addCriterion("FEC_VALIDEZ >=", value, "fecValidez");
      return (Criteria) this;
    }

    public Criteria andFecValidezLessThan(Date value) {
      addCriterion("FEC_VALIDEZ <", value, "fecValidez");
      return (Criteria) this;
    }

    public Criteria andFecValidezLessThanOrEqualTo(Date value) {
      addCriterion("FEC_VALIDEZ <=", value, "fecValidez");
      return (Criteria) this;
    }

    public Criteria andFecValidezIn(List<Date> values) {
      addCriterion("FEC_VALIDEZ in", values, "fecValidez");
      return (Criteria) this;
    }

    public Criteria andFecValidezNotIn(List<Date> values) {
      addCriterion("FEC_VALIDEZ not in", values, "fecValidez");
      return (Criteria) this;
    }

    public Criteria andFecValidezBetween(Date value1, Date value2) {
      addCriterion("FEC_VALIDEZ between", value1, value2, "fecValidez");
      return (Criteria) this;
    }

    public Criteria andFecValidezNotBetween(Date value1, Date value2) {
      addCriterion("FEC_VALIDEZ not between", value1, value2, "fecValidez");
      return (Criteria) this;
    }

    public Criteria andFecCreacionIsNull() {
      addCriterion("FEC_CREACION is null");
      return (Criteria) this;
    }

    public Criteria andFecCreacionIsNotNull() {
      addCriterion("FEC_CREACION is not null");
      return (Criteria) this;
    }

    public Criteria andFecCreacionEqualTo(Date value) {
      addCriterion("FEC_CREACION =", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionNotEqualTo(Date value) {
      addCriterion("FEC_CREACION <>", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionGreaterThan(Date value) {
      addCriterion("FEC_CREACION >", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionGreaterThanOrEqualTo(Date value) {
      addCriterion("FEC_CREACION >=", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionLessThan(Date value) {
      addCriterion("FEC_CREACION <", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionLessThanOrEqualTo(Date value) {
      addCriterion("FEC_CREACION <=", value, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionIn(List<Date> values) {
      addCriterion("FEC_CREACION in", values, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionNotIn(List<Date> values) {
      addCriterion("FEC_CREACION not in", values, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionBetween(Date value1, Date value2) {
      addCriterion("FEC_CREACION between", value1, value2, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andFecCreacionNotBetween(Date value1, Date value2) {
      addCriterion("FEC_CREACION not between", value1, value2, "fecCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionIsNull() {
      addCriterion("USU_CREACION is null");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionIsNotNull() {
      addCriterion("USU_CREACION is not null");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionEqualTo(String value) {
      addCriterion("USU_CREACION =", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionNotEqualTo(String value) {
      addCriterion("USU_CREACION <>", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionGreaterThan(String value) {
      addCriterion("USU_CREACION >", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionGreaterThanOrEqualTo(String value) {
      addCriterion("USU_CREACION >=", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionLessThan(String value) {
      addCriterion("USU_CREACION <", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionLessThanOrEqualTo(String value) {
      addCriterion("USU_CREACION <=", value, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionIn(List<String> values) {
      addCriterion("USU_CREACION in", values, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionNotIn(List<String> values) {
      addCriterion("USU_CREACION not in", values, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionBetween(String value1, String value2) {
      addCriterion("USU_CREACION between", value1, value2, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andUsuCreacionNotBetween(String value1, String value2) {
      addCriterion("USU_CREACION not between", value1, value2, "usuCreacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionIsNull() {
      addCriterion("FEC_MODIFICACION is null");
      return (Criteria) this;
    }

    public Criteria andFecModificacionIsNotNull() {
      addCriterion("FEC_MODIFICACION is not null");
      return (Criteria) this;
    }

    public Criteria andFecModificacionEqualTo(Date value) {
      addCriterion("FEC_MODIFICACION =", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionNotEqualTo(Date value) {
      addCriterion("FEC_MODIFICACION <>", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionGreaterThan(Date value) {
      addCriterion("FEC_MODIFICACION >", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionGreaterThanOrEqualTo(Date value) {
      addCriterion("FEC_MODIFICACION >=", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionLessThan(Date value) {
      addCriterion("FEC_MODIFICACION <", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionLessThanOrEqualTo(Date value) {
      addCriterion("FEC_MODIFICACION <=", value, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionIn(List<Date> values) {
      addCriterion("FEC_MODIFICACION in", values, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionNotIn(List<Date> values) {
      addCriterion("FEC_MODIFICACION not in", values, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionBetween(Date value1, Date value2) {
      addCriterion("FEC_MODIFICACION between", value1, value2, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andFecModificacionNotBetween(Date value1, Date value2) {
      addCriterion("FEC_MODIFICACION not between", value1, value2, "fecModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionIsNull() {
      addCriterion("USU_MODIFICACION is null");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionIsNotNull() {
      addCriterion("USU_MODIFICACION is not null");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionEqualTo(String value) {
      addCriterion("USU_MODIFICACION =", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionNotEqualTo(String value) {
      addCriterion("USU_MODIFICACION <>", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionGreaterThan(String value) {
      addCriterion("USU_MODIFICACION >", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionGreaterThanOrEqualTo(String value) {
      addCriterion("USU_MODIFICACION >=", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionLessThan(String value) {
      addCriterion("USU_MODIFICACION <", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionLessThanOrEqualTo(String value) {
      addCriterion("USU_MODIFICACION <=", value, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionIn(List<String> values) {
      addCriterion("USU_MODIFICACION in", values, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionNotIn(List<String> values) {
      addCriterion("USU_MODIFICACION not in", values, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionBetween(String value1, String value2) {
      addCriterion("USU_MODIFICACION between", value1, value2, "usuModificacion");
      return (Criteria) this;
    }

    public Criteria andUsuModificacionNotBetween(String value1, String value2) {
      addCriterion("USU_MODIFICACION not between", value1, value2, "usuModificacion");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.MASTER_PRECIOS_SOAT
   *
   * @mbggenerated do_not_delete_during_merge Mon Jul 07 10:52:45 COT 2014
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.MASTER_PRECIOS_SOAT
   *
   * @mbggenerated Mon Jul 07 10:52:45 COT 2014
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}