package com.cardif.satelite.model.upload;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ClienteExample implements Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table UPLOAD.CLIENTE
   *
   * @mbggenerated Wed Feb 05 22:03:14 COT 2014
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table UPLOAD.CLIENTE
   *
   * @mbggenerated Wed Feb 05 22:03:14 COT 2014
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table UPLOAD.CLIENTE
   *
   * @mbggenerated Wed Feb 05 22:03:14 COT 2014
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table UPLOAD.CLIENTE
   *
   * @mbggenerated Wed Feb 05 22:03:14 COT 2014
   */
  public ClienteExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table UPLOAD.CLIENTE
   *
   * @mbggenerated Wed Feb 05 22:03:14 COT 2014
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table UPLOAD.CLIENTE
   *
   * @mbggenerated Wed Feb 05 22:03:14 COT 2014
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table UPLOAD.CLIENTE
   *
   * @mbggenerated Wed Feb 05 22:03:14 COT 2014
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table UPLOAD.CLIENTE
   *
   * @mbggenerated Wed Feb 05 22:03:14 COT 2014
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table UPLOAD.CLIENTE
   *
   * @mbggenerated Wed Feb 05 22:03:14 COT 2014
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table UPLOAD.CLIENTE
   *
   * @mbggenerated Wed Feb 05 22:03:14 COT 2014
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table UPLOAD.CLIENTE
   *
   * @mbggenerated Wed Feb 05 22:03:14 COT 2014
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table UPLOAD.CLIENTE
   *
   * @mbggenerated Wed Feb 05 22:03:14 COT 2014
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table UPLOAD.CLIENTE
   *
   * @mbggenerated Wed Feb 05 22:03:14 COT 2014
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table UPLOAD.CLIENTE
   *
   * @mbggenerated Wed Feb 05 22:03:14 COT 2014
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table UPLOAD.CLIENTE
   *
   * @mbggenerated Wed Feb 05 22:03:14 COT 2014
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    protected void addCriterionForJDBCDate(String condition, Date value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      addCriterion(condition, new java.sql.Date(value.getTime()), property);
    }

    protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
      if (values == null || values.size() == 0) {
        throw new RuntimeException("Value list for " + property + " cannot be null or empty");
      }
      List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
      Iterator<Date> iter = values.iterator();
      while (iter.hasNext()) {
        dateList.add(new java.sql.Date(iter.next().getTime()));
      }
      addCriterion(condition, dateList, property);
    }

    protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
    }

    public Criteria andPersonaIdIsNull() {
      addCriterion("PERSONA_ID is null");
      return (Criteria) this;
    }

    public Criteria andPersonaIdIsNotNull() {
      addCriterion("PERSONA_ID is not null");
      return (Criteria) this;
    }

    public Criteria andPersonaIdEqualTo(Long value) {
      addCriterion("PERSONA_ID =", value, "personaId");
      return (Criteria) this;
    }

    public Criteria andPersonaIdNotEqualTo(Long value) {
      addCriterion("PERSONA_ID <>", value, "personaId");
      return (Criteria) this;
    }

    public Criteria andPersonaIdGreaterThan(Long value) {
      addCriterion("PERSONA_ID >", value, "personaId");
      return (Criteria) this;
    }

    public Criteria andPersonaIdGreaterThanOrEqualTo(Long value) {
      addCriterion("PERSONA_ID >=", value, "personaId");
      return (Criteria) this;
    }

    public Criteria andPersonaIdLessThan(Long value) {
      addCriterion("PERSONA_ID <", value, "personaId");
      return (Criteria) this;
    }

    public Criteria andPersonaIdLessThanOrEqualTo(Long value) {
      addCriterion("PERSONA_ID <=", value, "personaId");
      return (Criteria) this;
    }

    public Criteria andPersonaIdIn(List<Long> values) {
      addCriterion("PERSONA_ID in", values, "personaId");
      return (Criteria) this;
    }

    public Criteria andPersonaIdNotIn(List<Long> values) {
      addCriterion("PERSONA_ID not in", values, "personaId");
      return (Criteria) this;
    }

    public Criteria andPersonaIdBetween(Long value1, Long value2) {
      addCriterion("PERSONA_ID between", value1, value2, "personaId");
      return (Criteria) this;
    }

    public Criteria andPersonaIdNotBetween(Long value1, Long value2) {
      addCriterion("PERSONA_ID not between", value1, value2, "personaId");
      return (Criteria) this;
    }

    public Criteria andSocioIdIsNull() {
      addCriterion("SOCIO_ID is null");
      return (Criteria) this;
    }

    public Criteria andSocioIdIsNotNull() {
      addCriterion("SOCIO_ID is not null");
      return (Criteria) this;
    }

    public Criteria andSocioIdEqualTo(Long value) {
      addCriterion("SOCIO_ID =", value, "socioId");
      return (Criteria) this;
    }

    public Criteria andSocioIdNotEqualTo(Long value) {
      addCriterion("SOCIO_ID <>", value, "socioId");
      return (Criteria) this;
    }

    public Criteria andSocioIdGreaterThan(Long value) {
      addCriterion("SOCIO_ID >", value, "socioId");
      return (Criteria) this;
    }

    public Criteria andSocioIdGreaterThanOrEqualTo(Long value) {
      addCriterion("SOCIO_ID >=", value, "socioId");
      return (Criteria) this;
    }

    public Criteria andSocioIdLessThan(Long value) {
      addCriterion("SOCIO_ID <", value, "socioId");
      return (Criteria) this;
    }

    public Criteria andSocioIdLessThanOrEqualTo(Long value) {
      addCriterion("SOCIO_ID <=", value, "socioId");
      return (Criteria) this;
    }

    public Criteria andSocioIdIn(List<Long> values) {
      addCriterion("SOCIO_ID in", values, "socioId");
      return (Criteria) this;
    }

    public Criteria andSocioIdNotIn(List<Long> values) {
      addCriterion("SOCIO_ID not in", values, "socioId");
      return (Criteria) this;
    }

    public Criteria andSocioIdBetween(Long value1, Long value2) {
      addCriterion("SOCIO_ID between", value1, value2, "socioId");
      return (Criteria) this;
    }

    public Criteria andSocioIdNotBetween(Long value1, Long value2) {
      addCriterion("SOCIO_ID not between", value1, value2, "socioId");
      return (Criteria) this;
    }

    public Criteria andTipoDocIsNull() {
      addCriterion("TIPO_DOC is null");
      return (Criteria) this;
    }

    public Criteria andTipoDocIsNotNull() {
      addCriterion("TIPO_DOC is not null");
      return (Criteria) this;
    }

    public Criteria andTipoDocEqualTo(String value) {
      addCriterion("TIPO_DOC =", value, "tipoDoc");
      return (Criteria) this;
    }

    public Criteria andTipoDocNotEqualTo(String value) {
      addCriterion("TIPO_DOC <>", value, "tipoDoc");
      return (Criteria) this;
    }

    public Criteria andTipoDocGreaterThan(String value) {
      addCriterion("TIPO_DOC >", value, "tipoDoc");
      return (Criteria) this;
    }

    public Criteria andTipoDocGreaterThanOrEqualTo(String value) {
      addCriterion("TIPO_DOC >=", value, "tipoDoc");
      return (Criteria) this;
    }

    public Criteria andTipoDocLessThan(String value) {
      addCriterion("TIPO_DOC <", value, "tipoDoc");
      return (Criteria) this;
    }

    public Criteria andTipoDocLessThanOrEqualTo(String value) {
      addCriterion("TIPO_DOC <=", value, "tipoDoc");
      return (Criteria) this;
    }

    public Criteria andTipoDocLike(String value) {
      addCriterion("TIPO_DOC like", value, "tipoDoc");
      return (Criteria) this;
    }

    public Criteria andTipoDocNotLike(String value) {
      addCriterion("TIPO_DOC not like", value, "tipoDoc");
      return (Criteria) this;
    }

    public Criteria andTipoDocIn(List<String> values) {
      addCriterion("TIPO_DOC in", values, "tipoDoc");
      return (Criteria) this;
    }

    public Criteria andTipoDocNotIn(List<String> values) {
      addCriterion("TIPO_DOC not in", values, "tipoDoc");
      return (Criteria) this;
    }

    public Criteria andTipoDocBetween(String value1, String value2) {
      addCriterion("TIPO_DOC between", value1, value2, "tipoDoc");
      return (Criteria) this;
    }

    public Criteria andTipoDocNotBetween(String value1, String value2) {
      addCriterion("TIPO_DOC not between", value1, value2, "tipoDoc");
      return (Criteria) this;
    }

    public Criteria andNumeroDocIsNull() {
      addCriterion("NUMERO_DOC is null");
      return (Criteria) this;
    }

    public Criteria andNumeroDocIsNotNull() {
      addCriterion("NUMERO_DOC is not null");
      return (Criteria) this;
    }

    public Criteria andNumeroDocEqualTo(String value) {
      addCriterion("NUMERO_DOC =", value, "numeroDoc");
      return (Criteria) this;
    }

    public Criteria andNumeroDocNotEqualTo(String value) {
      addCriterion("NUMERO_DOC <>", value, "numeroDoc");
      return (Criteria) this;
    }

    public Criteria andNumeroDocGreaterThan(String value) {
      addCriterion("NUMERO_DOC >", value, "numeroDoc");
      return (Criteria) this;
    }

    public Criteria andNumeroDocGreaterThanOrEqualTo(String value) {
      addCriterion("NUMERO_DOC >=", value, "numeroDoc");
      return (Criteria) this;
    }

    public Criteria andNumeroDocLessThan(String value) {
      addCriterion("NUMERO_DOC <", value, "numeroDoc");
      return (Criteria) this;
    }

    public Criteria andNumeroDocLessThanOrEqualTo(String value) {
      addCriterion("NUMERO_DOC <=", value, "numeroDoc");
      return (Criteria) this;
    }

    public Criteria andNumeroDocLike(String value) {
      addCriterion("NUMERO_DOC like", value, "numeroDoc");
      return (Criteria) this;
    }

    public Criteria andNumeroDocNotLike(String value) {
      addCriterion("NUMERO_DOC not like", value, "numeroDoc");
      return (Criteria) this;
    }

    public Criteria andNumeroDocIn(List<String> values) {
      addCriterion("NUMERO_DOC in", values, "numeroDoc");
      return (Criteria) this;
    }

    public Criteria andNumeroDocNotIn(List<String> values) {
      addCriterion("NUMERO_DOC not in", values, "numeroDoc");
      return (Criteria) this;
    }

    public Criteria andNumeroDocBetween(String value1, String value2) {
      addCriterion("NUMERO_DOC between", value1, value2, "numeroDoc");
      return (Criteria) this;
    }

    public Criteria andNumeroDocNotBetween(String value1, String value2) {
      addCriterion("NUMERO_DOC not between", value1, value2, "numeroDoc");
      return (Criteria) this;
    }

    public Criteria andNombreCompletoIsNull() {
      addCriterion("NOMBRE_COMPLETO is null");
      return (Criteria) this;
    }

    public Criteria andNombreCompletoIsNotNull() {
      addCriterion("NOMBRE_COMPLETO is not null");
      return (Criteria) this;
    }

    public Criteria andNombreCompletoEqualTo(String value) {
      addCriterion("NOMBRE_COMPLETO =", value, "nombreCompleto");
      return (Criteria) this;
    }

    public Criteria andNombreCompletoNotEqualTo(String value) {
      addCriterion("NOMBRE_COMPLETO <>", value, "nombreCompleto");
      return (Criteria) this;
    }

    public Criteria andNombreCompletoGreaterThan(String value) {
      addCriterion("NOMBRE_COMPLETO >", value, "nombreCompleto");
      return (Criteria) this;
    }

    public Criteria andNombreCompletoGreaterThanOrEqualTo(String value) {
      addCriterion("NOMBRE_COMPLETO >=", value, "nombreCompleto");
      return (Criteria) this;
    }

    public Criteria andNombreCompletoLessThan(String value) {
      addCriterion("NOMBRE_COMPLETO <", value, "nombreCompleto");
      return (Criteria) this;
    }

    public Criteria andNombreCompletoLessThanOrEqualTo(String value) {
      addCriterion("NOMBRE_COMPLETO <=", value, "nombreCompleto");
      return (Criteria) this;
    }

    public Criteria andNombreCompletoLike(String value) {
      addCriterion("NOMBRE_COMPLETO like", value, "nombreCompleto");
      return (Criteria) this;
    }

    public Criteria andNombreCompletoNotLike(String value) {
      addCriterion("NOMBRE_COMPLETO not like", value, "nombreCompleto");
      return (Criteria) this;
    }

    public Criteria andNombreCompletoIn(List<String> values) {
      addCriterion("NOMBRE_COMPLETO in", values, "nombreCompleto");
      return (Criteria) this;
    }

    public Criteria andNombreCompletoNotIn(List<String> values) {
      addCriterion("NOMBRE_COMPLETO not in", values, "nombreCompleto");
      return (Criteria) this;
    }

    public Criteria andNombreCompletoBetween(String value1, String value2) {
      addCriterion("NOMBRE_COMPLETO between", value1, value2, "nombreCompleto");
      return (Criteria) this;
    }

    public Criteria andNombreCompletoNotBetween(String value1, String value2) {
      addCriterion("NOMBRE_COMPLETO not between", value1, value2, "nombreCompleto");
      return (Criteria) this;
    }

    public Criteria andFechaNacIsNull() {
      addCriterion("FECHA_NAC is null");
      return (Criteria) this;
    }

    public Criteria andFechaNacIsNotNull() {
      addCriterion("FECHA_NAC is not null");
      return (Criteria) this;
    }

    public Criteria andFechaNacEqualTo(Date value) {
      addCriterionForJDBCDate("FECHA_NAC =", value, "fechaNac");
      return (Criteria) this;
    }

    public Criteria andFechaNacNotEqualTo(Date value) {
      addCriterionForJDBCDate("FECHA_NAC <>", value, "fechaNac");
      return (Criteria) this;
    }

    public Criteria andFechaNacGreaterThan(Date value) {
      addCriterionForJDBCDate("FECHA_NAC >", value, "fechaNac");
      return (Criteria) this;
    }

    public Criteria andFechaNacGreaterThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("FECHA_NAC >=", value, "fechaNac");
      return (Criteria) this;
    }

    public Criteria andFechaNacLessThan(Date value) {
      addCriterionForJDBCDate("FECHA_NAC <", value, "fechaNac");
      return (Criteria) this;
    }

    public Criteria andFechaNacLessThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("FECHA_NAC <=", value, "fechaNac");
      return (Criteria) this;
    }

    public Criteria andFechaNacIn(List<Date> values) {
      addCriterionForJDBCDate("FECHA_NAC in", values, "fechaNac");
      return (Criteria) this;
    }

    public Criteria andFechaNacNotIn(List<Date> values) {
      addCriterionForJDBCDate("FECHA_NAC not in", values, "fechaNac");
      return (Criteria) this;
    }

    public Criteria andFechaNacBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("FECHA_NAC between", value1, value2, "fechaNac");
      return (Criteria) this;
    }

    public Criteria andFechaNacNotBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("FECHA_NAC not between", value1, value2, "fechaNac");
      return (Criteria) this;
    }

    public Criteria andEdadIsNull() {
      addCriterion("EDAD is null");
      return (Criteria) this;
    }

    public Criteria andEdadIsNotNull() {
      addCriterion("EDAD is not null");
      return (Criteria) this;
    }

    public Criteria andEdadEqualTo(Short value) {
      addCriterion("EDAD =", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadNotEqualTo(Short value) {
      addCriterion("EDAD <>", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadGreaterThan(Short value) {
      addCriterion("EDAD >", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadGreaterThanOrEqualTo(Short value) {
      addCriterion("EDAD >=", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadLessThan(Short value) {
      addCriterion("EDAD <", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadLessThanOrEqualTo(Short value) {
      addCriterion("EDAD <=", value, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadIn(List<Short> values) {
      addCriterion("EDAD in", values, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadNotIn(List<Short> values) {
      addCriterion("EDAD not in", values, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadBetween(Short value1, Short value2) {
      addCriterion("EDAD between", value1, value2, "edad");
      return (Criteria) this;
    }

    public Criteria andEdadNotBetween(Short value1, Short value2) {
      addCriterion("EDAD not between", value1, value2, "edad");
      return (Criteria) this;
    }

    public Criteria andRangoEdadIsNull() {
      addCriterion("RANGO_EDAD is null");
      return (Criteria) this;
    }

    public Criteria andRangoEdadIsNotNull() {
      addCriterion("RANGO_EDAD is not null");
      return (Criteria) this;
    }

    public Criteria andRangoEdadEqualTo(String value) {
      addCriterion("RANGO_EDAD =", value, "rangoEdad");
      return (Criteria) this;
    }

    public Criteria andRangoEdadNotEqualTo(String value) {
      addCriterion("RANGO_EDAD <>", value, "rangoEdad");
      return (Criteria) this;
    }

    public Criteria andRangoEdadGreaterThan(String value) {
      addCriterion("RANGO_EDAD >", value, "rangoEdad");
      return (Criteria) this;
    }

    public Criteria andRangoEdadGreaterThanOrEqualTo(String value) {
      addCriterion("RANGO_EDAD >=", value, "rangoEdad");
      return (Criteria) this;
    }

    public Criteria andRangoEdadLessThan(String value) {
      addCriterion("RANGO_EDAD <", value, "rangoEdad");
      return (Criteria) this;
    }

    public Criteria andRangoEdadLessThanOrEqualTo(String value) {
      addCriterion("RANGO_EDAD <=", value, "rangoEdad");
      return (Criteria) this;
    }

    public Criteria andRangoEdadLike(String value) {
      addCriterion("RANGO_EDAD like", value, "rangoEdad");
      return (Criteria) this;
    }

    public Criteria andRangoEdadNotLike(String value) {
      addCriterion("RANGO_EDAD not like", value, "rangoEdad");
      return (Criteria) this;
    }

    public Criteria andRangoEdadIn(List<String> values) {
      addCriterion("RANGO_EDAD in", values, "rangoEdad");
      return (Criteria) this;
    }

    public Criteria andRangoEdadNotIn(List<String> values) {
      addCriterion("RANGO_EDAD not in", values, "rangoEdad");
      return (Criteria) this;
    }

    public Criteria andRangoEdadBetween(String value1, String value2) {
      addCriterion("RANGO_EDAD between", value1, value2, "rangoEdad");
      return (Criteria) this;
    }

    public Criteria andRangoEdadNotBetween(String value1, String value2) {
      addCriterion("RANGO_EDAD not between", value1, value2, "rangoEdad");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilIsNull() {
      addCriterion("ESTADO_CIVIL is null");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilIsNotNull() {
      addCriterion("ESTADO_CIVIL is not null");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilEqualTo(String value) {
      addCriterion("ESTADO_CIVIL =", value, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilNotEqualTo(String value) {
      addCriterion("ESTADO_CIVIL <>", value, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilGreaterThan(String value) {
      addCriterion("ESTADO_CIVIL >", value, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilGreaterThanOrEqualTo(String value) {
      addCriterion("ESTADO_CIVIL >=", value, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilLessThan(String value) {
      addCriterion("ESTADO_CIVIL <", value, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilLessThanOrEqualTo(String value) {
      addCriterion("ESTADO_CIVIL <=", value, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilLike(String value) {
      addCriterion("ESTADO_CIVIL like", value, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilNotLike(String value) {
      addCriterion("ESTADO_CIVIL not like", value, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilIn(List<String> values) {
      addCriterion("ESTADO_CIVIL in", values, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilNotIn(List<String> values) {
      addCriterion("ESTADO_CIVIL not in", values, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilBetween(String value1, String value2) {
      addCriterion("ESTADO_CIVIL between", value1, value2, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andEstadoCivilNotBetween(String value1, String value2) {
      addCriterion("ESTADO_CIVIL not between", value1, value2, "estadoCivil");
      return (Criteria) this;
    }

    public Criteria andDepartamentoIsNull() {
      addCriterion("DEPARTAMENTO is null");
      return (Criteria) this;
    }

    public Criteria andDepartamentoIsNotNull() {
      addCriterion("DEPARTAMENTO is not null");
      return (Criteria) this;
    }

    public Criteria andDepartamentoEqualTo(String value) {
      addCriterion("DEPARTAMENTO =", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoNotEqualTo(String value) {
      addCriterion("DEPARTAMENTO <>", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoGreaterThan(String value) {
      addCriterion("DEPARTAMENTO >", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoGreaterThanOrEqualTo(String value) {
      addCriterion("DEPARTAMENTO >=", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoLessThan(String value) {
      addCriterion("DEPARTAMENTO <", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoLessThanOrEqualTo(String value) {
      addCriterion("DEPARTAMENTO <=", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoLike(String value) {
      addCriterion("DEPARTAMENTO like", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoNotLike(String value) {
      addCriterion("DEPARTAMENTO not like", value, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoIn(List<String> values) {
      addCriterion("DEPARTAMENTO in", values, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoNotIn(List<String> values) {
      addCriterion("DEPARTAMENTO not in", values, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoBetween(String value1, String value2) {
      addCriterion("DEPARTAMENTO between", value1, value2, "departamento");
      return (Criteria) this;
    }

    public Criteria andDepartamentoNotBetween(String value1, String value2) {
      addCriterion("DEPARTAMENTO not between", value1, value2, "departamento");
      return (Criteria) this;
    }

    public Criteria andProvinciaIsNull() {
      addCriterion("PROVINCIA is null");
      return (Criteria) this;
    }

    public Criteria andProvinciaIsNotNull() {
      addCriterion("PROVINCIA is not null");
      return (Criteria) this;
    }

    public Criteria andProvinciaEqualTo(String value) {
      addCriterion("PROVINCIA =", value, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaNotEqualTo(String value) {
      addCriterion("PROVINCIA <>", value, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaGreaterThan(String value) {
      addCriterion("PROVINCIA >", value, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaGreaterThanOrEqualTo(String value) {
      addCriterion("PROVINCIA >=", value, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaLessThan(String value) {
      addCriterion("PROVINCIA <", value, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaLessThanOrEqualTo(String value) {
      addCriterion("PROVINCIA <=", value, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaLike(String value) {
      addCriterion("PROVINCIA like", value, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaNotLike(String value) {
      addCriterion("PROVINCIA not like", value, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaIn(List<String> values) {
      addCriterion("PROVINCIA in", values, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaNotIn(List<String> values) {
      addCriterion("PROVINCIA not in", values, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaBetween(String value1, String value2) {
      addCriterion("PROVINCIA between", value1, value2, "provincia");
      return (Criteria) this;
    }

    public Criteria andProvinciaNotBetween(String value1, String value2) {
      addCriterion("PROVINCIA not between", value1, value2, "provincia");
      return (Criteria) this;
    }

    public Criteria andDistritoIsNull() {
      addCriterion("DISTRITO is null");
      return (Criteria) this;
    }

    public Criteria andDistritoIsNotNull() {
      addCriterion("DISTRITO is not null");
      return (Criteria) this;
    }

    public Criteria andDistritoEqualTo(String value) {
      addCriterion("DISTRITO =", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoNotEqualTo(String value) {
      addCriterion("DISTRITO <>", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoGreaterThan(String value) {
      addCriterion("DISTRITO >", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoGreaterThanOrEqualTo(String value) {
      addCriterion("DISTRITO >=", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoLessThan(String value) {
      addCriterion("DISTRITO <", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoLessThanOrEqualTo(String value) {
      addCriterion("DISTRITO <=", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoLike(String value) {
      addCriterion("DISTRITO like", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoNotLike(String value) {
      addCriterion("DISTRITO not like", value, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoIn(List<String> values) {
      addCriterion("DISTRITO in", values, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoNotIn(List<String> values) {
      addCriterion("DISTRITO not in", values, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoBetween(String value1, String value2) {
      addCriterion("DISTRITO between", value1, value2, "distrito");
      return (Criteria) this;
    }

    public Criteria andDistritoNotBetween(String value1, String value2) {
      addCriterion("DISTRITO not between", value1, value2, "distrito");
      return (Criteria) this;
    }

    public Criteria andDireccionIsNull() {
      addCriterion("DIRECCION is null");
      return (Criteria) this;
    }

    public Criteria andDireccionIsNotNull() {
      addCriterion("DIRECCION is not null");
      return (Criteria) this;
    }

    public Criteria andDireccionEqualTo(String value) {
      addCriterion("DIRECCION =", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionNotEqualTo(String value) {
      addCriterion("DIRECCION <>", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionGreaterThan(String value) {
      addCriterion("DIRECCION >", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionGreaterThanOrEqualTo(String value) {
      addCriterion("DIRECCION >=", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionLessThan(String value) {
      addCriterion("DIRECCION <", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionLessThanOrEqualTo(String value) {
      addCriterion("DIRECCION <=", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionLike(String value) {
      addCriterion("DIRECCION like", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionNotLike(String value) {
      addCriterion("DIRECCION not like", value, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionIn(List<String> values) {
      addCriterion("DIRECCION in", values, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionNotIn(List<String> values) {
      addCriterion("DIRECCION not in", values, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionBetween(String value1, String value2) {
      addCriterion("DIRECCION between", value1, value2, "direccion");
      return (Criteria) this;
    }

    public Criteria andDireccionNotBetween(String value1, String value2) {
      addCriterion("DIRECCION not between", value1, value2, "direccion");
      return (Criteria) this;
    }

    public Criteria andTelefono1IsNull() {
      addCriterion("TELEFONO_1 is null");
      return (Criteria) this;
    }

    public Criteria andTelefono1IsNotNull() {
      addCriterion("TELEFONO_1 is not null");
      return (Criteria) this;
    }

    public Criteria andTelefono1EqualTo(String value) {
      addCriterion("TELEFONO_1 =", value, "telefono1");
      return (Criteria) this;
    }

    public Criteria andTelefono1NotEqualTo(String value) {
      addCriterion("TELEFONO_1 <>", value, "telefono1");
      return (Criteria) this;
    }

    public Criteria andTelefono1GreaterThan(String value) {
      addCriterion("TELEFONO_1 >", value, "telefono1");
      return (Criteria) this;
    }

    public Criteria andTelefono1GreaterThanOrEqualTo(String value) {
      addCriterion("TELEFONO_1 >=", value, "telefono1");
      return (Criteria) this;
    }

    public Criteria andTelefono1LessThan(String value) {
      addCriterion("TELEFONO_1 <", value, "telefono1");
      return (Criteria) this;
    }

    public Criteria andTelefono1LessThanOrEqualTo(String value) {
      addCriterion("TELEFONO_1 <=", value, "telefono1");
      return (Criteria) this;
    }

    public Criteria andTelefono1Like(String value) {
      addCriterion("TELEFONO_1 like", value, "telefono1");
      return (Criteria) this;
    }

    public Criteria andTelefono1NotLike(String value) {
      addCriterion("TELEFONO_1 not like", value, "telefono1");
      return (Criteria) this;
    }

    public Criteria andTelefono1In(List<String> values) {
      addCriterion("TELEFONO_1 in", values, "telefono1");
      return (Criteria) this;
    }

    public Criteria andTelefono1NotIn(List<String> values) {
      addCriterion("TELEFONO_1 not in", values, "telefono1");
      return (Criteria) this;
    }

    public Criteria andTelefono1Between(String value1, String value2) {
      addCriterion("TELEFONO_1 between", value1, value2, "telefono1");
      return (Criteria) this;
    }

    public Criteria andTelefono1NotBetween(String value1, String value2) {
      addCriterion("TELEFONO_1 not between", value1, value2, "telefono1");
      return (Criteria) this;
    }

    public Criteria andTelefono2IsNull() {
      addCriterion("TELEFONO_2 is null");
      return (Criteria) this;
    }

    public Criteria andTelefono2IsNotNull() {
      addCriterion("TELEFONO_2 is not null");
      return (Criteria) this;
    }

    public Criteria andTelefono2EqualTo(String value) {
      addCriterion("TELEFONO_2 =", value, "telefono2");
      return (Criteria) this;
    }

    public Criteria andTelefono2NotEqualTo(String value) {
      addCriterion("TELEFONO_2 <>", value, "telefono2");
      return (Criteria) this;
    }

    public Criteria andTelefono2GreaterThan(String value) {
      addCriterion("TELEFONO_2 >", value, "telefono2");
      return (Criteria) this;
    }

    public Criteria andTelefono2GreaterThanOrEqualTo(String value) {
      addCriterion("TELEFONO_2 >=", value, "telefono2");
      return (Criteria) this;
    }

    public Criteria andTelefono2LessThan(String value) {
      addCriterion("TELEFONO_2 <", value, "telefono2");
      return (Criteria) this;
    }

    public Criteria andTelefono2LessThanOrEqualTo(String value) {
      addCriterion("TELEFONO_2 <=", value, "telefono2");
      return (Criteria) this;
    }

    public Criteria andTelefono2Like(String value) {
      addCriterion("TELEFONO_2 like", value, "telefono2");
      return (Criteria) this;
    }

    public Criteria andTelefono2NotLike(String value) {
      addCriterion("TELEFONO_2 not like", value, "telefono2");
      return (Criteria) this;
    }

    public Criteria andTelefono2In(List<String> values) {
      addCriterion("TELEFONO_2 in", values, "telefono2");
      return (Criteria) this;
    }

    public Criteria andTelefono2NotIn(List<String> values) {
      addCriterion("TELEFONO_2 not in", values, "telefono2");
      return (Criteria) this;
    }

    public Criteria andTelefono2Between(String value1, String value2) {
      addCriterion("TELEFONO_2 between", value1, value2, "telefono2");
      return (Criteria) this;
    }

    public Criteria andTelefono2NotBetween(String value1, String value2) {
      addCriterion("TELEFONO_2 not between", value1, value2, "telefono2");
      return (Criteria) this;
    }

    public Criteria andTelefono3IsNull() {
      addCriterion("TELEFONO_3 is null");
      return (Criteria) this;
    }

    public Criteria andTelefono3IsNotNull() {
      addCriterion("TELEFONO_3 is not null");
      return (Criteria) this;
    }

    public Criteria andTelefono3EqualTo(String value) {
      addCriterion("TELEFONO_3 =", value, "telefono3");
      return (Criteria) this;
    }

    public Criteria andTelefono3NotEqualTo(String value) {
      addCriterion("TELEFONO_3 <>", value, "telefono3");
      return (Criteria) this;
    }

    public Criteria andTelefono3GreaterThan(String value) {
      addCriterion("TELEFONO_3 >", value, "telefono3");
      return (Criteria) this;
    }

    public Criteria andTelefono3GreaterThanOrEqualTo(String value) {
      addCriterion("TELEFONO_3 >=", value, "telefono3");
      return (Criteria) this;
    }

    public Criteria andTelefono3LessThan(String value) {
      addCriterion("TELEFONO_3 <", value, "telefono3");
      return (Criteria) this;
    }

    public Criteria andTelefono3LessThanOrEqualTo(String value) {
      addCriterion("TELEFONO_3 <=", value, "telefono3");
      return (Criteria) this;
    }

    public Criteria andTelefono3Like(String value) {
      addCriterion("TELEFONO_3 like", value, "telefono3");
      return (Criteria) this;
    }

    public Criteria andTelefono3NotLike(String value) {
      addCriterion("TELEFONO_3 not like", value, "telefono3");
      return (Criteria) this;
    }

    public Criteria andTelefono3In(List<String> values) {
      addCriterion("TELEFONO_3 in", values, "telefono3");
      return (Criteria) this;
    }

    public Criteria andTelefono3NotIn(List<String> values) {
      addCriterion("TELEFONO_3 not in", values, "telefono3");
      return (Criteria) this;
    }

    public Criteria andTelefono3Between(String value1, String value2) {
      addCriterion("TELEFONO_3 between", value1, value2, "telefono3");
      return (Criteria) this;
    }

    public Criteria andTelefono3NotBetween(String value1, String value2) {
      addCriterion("TELEFONO_3 not between", value1, value2, "telefono3");
      return (Criteria) this;
    }

    public Criteria andTelefono4IsNull() {
      addCriterion("TELEFONO_4 is null");
      return (Criteria) this;
    }

    public Criteria andTelefono4IsNotNull() {
      addCriterion("TELEFONO_4 is not null");
      return (Criteria) this;
    }

    public Criteria andTelefono4EqualTo(String value) {
      addCriterion("TELEFONO_4 =", value, "telefono4");
      return (Criteria) this;
    }

    public Criteria andTelefono4NotEqualTo(String value) {
      addCriterion("TELEFONO_4 <>", value, "telefono4");
      return (Criteria) this;
    }

    public Criteria andTelefono4GreaterThan(String value) {
      addCriterion("TELEFONO_4 >", value, "telefono4");
      return (Criteria) this;
    }

    public Criteria andTelefono4GreaterThanOrEqualTo(String value) {
      addCriterion("TELEFONO_4 >=", value, "telefono4");
      return (Criteria) this;
    }

    public Criteria andTelefono4LessThan(String value) {
      addCriterion("TELEFONO_4 <", value, "telefono4");
      return (Criteria) this;
    }

    public Criteria andTelefono4LessThanOrEqualTo(String value) {
      addCriterion("TELEFONO_4 <=", value, "telefono4");
      return (Criteria) this;
    }

    public Criteria andTelefono4Like(String value) {
      addCriterion("TELEFONO_4 like", value, "telefono4");
      return (Criteria) this;
    }

    public Criteria andTelefono4NotLike(String value) {
      addCriterion("TELEFONO_4 not like", value, "telefono4");
      return (Criteria) this;
    }

    public Criteria andTelefono4In(List<String> values) {
      addCriterion("TELEFONO_4 in", values, "telefono4");
      return (Criteria) this;
    }

    public Criteria andTelefono4NotIn(List<String> values) {
      addCriterion("TELEFONO_4 not in", values, "telefono4");
      return (Criteria) this;
    }

    public Criteria andTelefono4Between(String value1, String value2) {
      addCriterion("TELEFONO_4 between", value1, value2, "telefono4");
      return (Criteria) this;
    }

    public Criteria andTelefono4NotBetween(String value1, String value2) {
      addCriterion("TELEFONO_4 not between", value1, value2, "telefono4");
      return (Criteria) this;
    }

    public Criteria andTelefono5IsNull() {
      addCriterion("TELEFONO_5 is null");
      return (Criteria) this;
    }

    public Criteria andTelefono5IsNotNull() {
      addCriterion("TELEFONO_5 is not null");
      return (Criteria) this;
    }

    public Criteria andTelefono5EqualTo(String value) {
      addCriterion("TELEFONO_5 =", value, "telefono5");
      return (Criteria) this;
    }

    public Criteria andTelefono5NotEqualTo(String value) {
      addCriterion("TELEFONO_5 <>", value, "telefono5");
      return (Criteria) this;
    }

    public Criteria andTelefono5GreaterThan(String value) {
      addCriterion("TELEFONO_5 >", value, "telefono5");
      return (Criteria) this;
    }

    public Criteria andTelefono5GreaterThanOrEqualTo(String value) {
      addCriterion("TELEFONO_5 >=", value, "telefono5");
      return (Criteria) this;
    }

    public Criteria andTelefono5LessThan(String value) {
      addCriterion("TELEFONO_5 <", value, "telefono5");
      return (Criteria) this;
    }

    public Criteria andTelefono5LessThanOrEqualTo(String value) {
      addCriterion("TELEFONO_5 <=", value, "telefono5");
      return (Criteria) this;
    }

    public Criteria andTelefono5Like(String value) {
      addCriterion("TELEFONO_5 like", value, "telefono5");
      return (Criteria) this;
    }

    public Criteria andTelefono5NotLike(String value) {
      addCriterion("TELEFONO_5 not like", value, "telefono5");
      return (Criteria) this;
    }

    public Criteria andTelefono5In(List<String> values) {
      addCriterion("TELEFONO_5 in", values, "telefono5");
      return (Criteria) this;
    }

    public Criteria andTelefono5NotIn(List<String> values) {
      addCriterion("TELEFONO_5 not in", values, "telefono5");
      return (Criteria) this;
    }

    public Criteria andTelefono5Between(String value1, String value2) {
      addCriterion("TELEFONO_5 between", value1, value2, "telefono5");
      return (Criteria) this;
    }

    public Criteria andTelefono5NotBetween(String value1, String value2) {
      addCriterion("TELEFONO_5 not between", value1, value2, "telefono5");
      return (Criteria) this;
    }

    public Criteria andTelefono6IsNull() {
      addCriterion("TELEFONO_6 is null");
      return (Criteria) this;
    }

    public Criteria andTelefono6IsNotNull() {
      addCriterion("TELEFONO_6 is not null");
      return (Criteria) this;
    }

    public Criteria andTelefono6EqualTo(String value) {
      addCriterion("TELEFONO_6 =", value, "telefono6");
      return (Criteria) this;
    }

    public Criteria andTelefono6NotEqualTo(String value) {
      addCriterion("TELEFONO_6 <>", value, "telefono6");
      return (Criteria) this;
    }

    public Criteria andTelefono6GreaterThan(String value) {
      addCriterion("TELEFONO_6 >", value, "telefono6");
      return (Criteria) this;
    }

    public Criteria andTelefono6GreaterThanOrEqualTo(String value) {
      addCriterion("TELEFONO_6 >=", value, "telefono6");
      return (Criteria) this;
    }

    public Criteria andTelefono6LessThan(String value) {
      addCriterion("TELEFONO_6 <", value, "telefono6");
      return (Criteria) this;
    }

    public Criteria andTelefono6LessThanOrEqualTo(String value) {
      addCriterion("TELEFONO_6 <=", value, "telefono6");
      return (Criteria) this;
    }

    public Criteria andTelefono6Like(String value) {
      addCriterion("TELEFONO_6 like", value, "telefono6");
      return (Criteria) this;
    }

    public Criteria andTelefono6NotLike(String value) {
      addCriterion("TELEFONO_6 not like", value, "telefono6");
      return (Criteria) this;
    }

    public Criteria andTelefono6In(List<String> values) {
      addCriterion("TELEFONO_6 in", values, "telefono6");
      return (Criteria) this;
    }

    public Criteria andTelefono6NotIn(List<String> values) {
      addCriterion("TELEFONO_6 not in", values, "telefono6");
      return (Criteria) this;
    }

    public Criteria andTelefono6Between(String value1, String value2) {
      addCriterion("TELEFONO_6 between", value1, value2, "telefono6");
      return (Criteria) this;
    }

    public Criteria andTelefono6NotBetween(String value1, String value2) {
      addCriterion("TELEFONO_6 not between", value1, value2, "telefono6");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo1IsNull() {
      addCriterion("TLF_TRABAJO_1 is null");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo1IsNotNull() {
      addCriterion("TLF_TRABAJO_1 is not null");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo1EqualTo(String value) {
      addCriterion("TLF_TRABAJO_1 =", value, "tlfTrabajo1");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo1NotEqualTo(String value) {
      addCriterion("TLF_TRABAJO_1 <>", value, "tlfTrabajo1");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo1GreaterThan(String value) {
      addCriterion("TLF_TRABAJO_1 >", value, "tlfTrabajo1");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo1GreaterThanOrEqualTo(String value) {
      addCriterion("TLF_TRABAJO_1 >=", value, "tlfTrabajo1");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo1LessThan(String value) {
      addCriterion("TLF_TRABAJO_1 <", value, "tlfTrabajo1");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo1LessThanOrEqualTo(String value) {
      addCriterion("TLF_TRABAJO_1 <=", value, "tlfTrabajo1");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo1Like(String value) {
      addCriterion("TLF_TRABAJO_1 like", value, "tlfTrabajo1");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo1NotLike(String value) {
      addCriterion("TLF_TRABAJO_1 not like", value, "tlfTrabajo1");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo1In(List<String> values) {
      addCriterion("TLF_TRABAJO_1 in", values, "tlfTrabajo1");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo1NotIn(List<String> values) {
      addCriterion("TLF_TRABAJO_1 not in", values, "tlfTrabajo1");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo1Between(String value1, String value2) {
      addCriterion("TLF_TRABAJO_1 between", value1, value2, "tlfTrabajo1");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo1NotBetween(String value1, String value2) {
      addCriterion("TLF_TRABAJO_1 not between", value1, value2, "tlfTrabajo1");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo2IsNull() {
      addCriterion("TLF_TRABAJO_2 is null");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo2IsNotNull() {
      addCriterion("TLF_TRABAJO_2 is not null");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo2EqualTo(String value) {
      addCriterion("TLF_TRABAJO_2 =", value, "tlfTrabajo2");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo2NotEqualTo(String value) {
      addCriterion("TLF_TRABAJO_2 <>", value, "tlfTrabajo2");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo2GreaterThan(String value) {
      addCriterion("TLF_TRABAJO_2 >", value, "tlfTrabajo2");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo2GreaterThanOrEqualTo(String value) {
      addCriterion("TLF_TRABAJO_2 >=", value, "tlfTrabajo2");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo2LessThan(String value) {
      addCriterion("TLF_TRABAJO_2 <", value, "tlfTrabajo2");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo2LessThanOrEqualTo(String value) {
      addCriterion("TLF_TRABAJO_2 <=", value, "tlfTrabajo2");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo2Like(String value) {
      addCriterion("TLF_TRABAJO_2 like", value, "tlfTrabajo2");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo2NotLike(String value) {
      addCriterion("TLF_TRABAJO_2 not like", value, "tlfTrabajo2");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo2In(List<String> values) {
      addCriterion("TLF_TRABAJO_2 in", values, "tlfTrabajo2");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo2NotIn(List<String> values) {
      addCriterion("TLF_TRABAJO_2 not in", values, "tlfTrabajo2");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo2Between(String value1, String value2) {
      addCriterion("TLF_TRABAJO_2 between", value1, value2, "tlfTrabajo2");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo2NotBetween(String value1, String value2) {
      addCriterion("TLF_TRABAJO_2 not between", value1, value2, "tlfTrabajo2");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo3IsNull() {
      addCriterion("TLF_TRABAJO_3 is null");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo3IsNotNull() {
      addCriterion("TLF_TRABAJO_3 is not null");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo3EqualTo(String value) {
      addCriterion("TLF_TRABAJO_3 =", value, "tlfTrabajo3");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo3NotEqualTo(String value) {
      addCriterion("TLF_TRABAJO_3 <>", value, "tlfTrabajo3");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo3GreaterThan(String value) {
      addCriterion("TLF_TRABAJO_3 >", value, "tlfTrabajo3");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo3GreaterThanOrEqualTo(String value) {
      addCriterion("TLF_TRABAJO_3 >=", value, "tlfTrabajo3");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo3LessThan(String value) {
      addCriterion("TLF_TRABAJO_3 <", value, "tlfTrabajo3");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo3LessThanOrEqualTo(String value) {
      addCriterion("TLF_TRABAJO_3 <=", value, "tlfTrabajo3");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo3Like(String value) {
      addCriterion("TLF_TRABAJO_3 like", value, "tlfTrabajo3");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo3NotLike(String value) {
      addCriterion("TLF_TRABAJO_3 not like", value, "tlfTrabajo3");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo3In(List<String> values) {
      addCriterion("TLF_TRABAJO_3 in", values, "tlfTrabajo3");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo3NotIn(List<String> values) {
      addCriterion("TLF_TRABAJO_3 not in", values, "tlfTrabajo3");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo3Between(String value1, String value2) {
      addCriterion("TLF_TRABAJO_3 between", value1, value2, "tlfTrabajo3");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo3NotBetween(String value1, String value2) {
      addCriterion("TLF_TRABAJO_3 not between", value1, value2, "tlfTrabajo3");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo4IsNull() {
      addCriterion("TLF_TRABAJO_4 is null");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo4IsNotNull() {
      addCriterion("TLF_TRABAJO_4 is not null");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo4EqualTo(String value) {
      addCriterion("TLF_TRABAJO_4 =", value, "tlfTrabajo4");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo4NotEqualTo(String value) {
      addCriterion("TLF_TRABAJO_4 <>", value, "tlfTrabajo4");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo4GreaterThan(String value) {
      addCriterion("TLF_TRABAJO_4 >", value, "tlfTrabajo4");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo4GreaterThanOrEqualTo(String value) {
      addCriterion("TLF_TRABAJO_4 >=", value, "tlfTrabajo4");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo4LessThan(String value) {
      addCriterion("TLF_TRABAJO_4 <", value, "tlfTrabajo4");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo4LessThanOrEqualTo(String value) {
      addCriterion("TLF_TRABAJO_4 <=", value, "tlfTrabajo4");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo4Like(String value) {
      addCriterion("TLF_TRABAJO_4 like", value, "tlfTrabajo4");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo4NotLike(String value) {
      addCriterion("TLF_TRABAJO_4 not like", value, "tlfTrabajo4");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo4In(List<String> values) {
      addCriterion("TLF_TRABAJO_4 in", values, "tlfTrabajo4");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo4NotIn(List<String> values) {
      addCriterion("TLF_TRABAJO_4 not in", values, "tlfTrabajo4");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo4Between(String value1, String value2) {
      addCriterion("TLF_TRABAJO_4 between", value1, value2, "tlfTrabajo4");
      return (Criteria) this;
    }

    public Criteria andTlfTrabajo4NotBetween(String value1, String value2) {
      addCriterion("TLF_TRABAJO_4 not between", value1, value2, "tlfTrabajo4");
      return (Criteria) this;
    }

    public Criteria andTlfContactoIsNull() {
      addCriterion("TLF_CONTACTO is null");
      return (Criteria) this;
    }

    public Criteria andTlfContactoIsNotNull() {
      addCriterion("TLF_CONTACTO is not null");
      return (Criteria) this;
    }

    public Criteria andTlfContactoEqualTo(String value) {
      addCriterion("TLF_CONTACTO =", value, "tlfContacto");
      return (Criteria) this;
    }

    public Criteria andTlfContactoNotEqualTo(String value) {
      addCriterion("TLF_CONTACTO <>", value, "tlfContacto");
      return (Criteria) this;
    }

    public Criteria andTlfContactoGreaterThan(String value) {
      addCriterion("TLF_CONTACTO >", value, "tlfContacto");
      return (Criteria) this;
    }

    public Criteria andTlfContactoGreaterThanOrEqualTo(String value) {
      addCriterion("TLF_CONTACTO >=", value, "tlfContacto");
      return (Criteria) this;
    }

    public Criteria andTlfContactoLessThan(String value) {
      addCriterion("TLF_CONTACTO <", value, "tlfContacto");
      return (Criteria) this;
    }

    public Criteria andTlfContactoLessThanOrEqualTo(String value) {
      addCriterion("TLF_CONTACTO <=", value, "tlfContacto");
      return (Criteria) this;
    }

    public Criteria andTlfContactoLike(String value) {
      addCriterion("TLF_CONTACTO like", value, "tlfContacto");
      return (Criteria) this;
    }

    public Criteria andTlfContactoNotLike(String value) {
      addCriterion("TLF_CONTACTO not like", value, "tlfContacto");
      return (Criteria) this;
    }

    public Criteria andTlfContactoIn(List<String> values) {
      addCriterion("TLF_CONTACTO in", values, "tlfContacto");
      return (Criteria) this;
    }

    public Criteria andTlfContactoNotIn(List<String> values) {
      addCriterion("TLF_CONTACTO not in", values, "tlfContacto");
      return (Criteria) this;
    }

    public Criteria andTlfContactoBetween(String value1, String value2) {
      addCriterion("TLF_CONTACTO between", value1, value2, "tlfContacto");
      return (Criteria) this;
    }

    public Criteria andTlfContactoNotBetween(String value1, String value2) {
      addCriterion("TLF_CONTACTO not between", value1, value2, "tlfContacto");
      return (Criteria) this;
    }

    public Criteria andBancoIsNull() {
      addCriterion("BANCO is null");
      return (Criteria) this;
    }

    public Criteria andBancoIsNotNull() {
      addCriterion("BANCO is not null");
      return (Criteria) this;
    }

    public Criteria andBancoEqualTo(String value) {
      addCriterion("BANCO =", value, "banco");
      return (Criteria) this;
    }

    public Criteria andBancoNotEqualTo(String value) {
      addCriterion("BANCO <>", value, "banco");
      return (Criteria) this;
    }

    public Criteria andBancoGreaterThan(String value) {
      addCriterion("BANCO >", value, "banco");
      return (Criteria) this;
    }

    public Criteria andBancoGreaterThanOrEqualTo(String value) {
      addCriterion("BANCO >=", value, "banco");
      return (Criteria) this;
    }

    public Criteria andBancoLessThan(String value) {
      addCriterion("BANCO <", value, "banco");
      return (Criteria) this;
    }

    public Criteria andBancoLessThanOrEqualTo(String value) {
      addCriterion("BANCO <=", value, "banco");
      return (Criteria) this;
    }

    public Criteria andBancoLike(String value) {
      addCriterion("BANCO like", value, "banco");
      return (Criteria) this;
    }

    public Criteria andBancoNotLike(String value) {
      addCriterion("BANCO not like", value, "banco");
      return (Criteria) this;
    }

    public Criteria andBancoIn(List<String> values) {
      addCriterion("BANCO in", values, "banco");
      return (Criteria) this;
    }

    public Criteria andBancoNotIn(List<String> values) {
      addCriterion("BANCO not in", values, "banco");
      return (Criteria) this;
    }

    public Criteria andBancoBetween(String value1, String value2) {
      addCriterion("BANCO between", value1, value2, "banco");
      return (Criteria) this;
    }

    public Criteria andBancoNotBetween(String value1, String value2) {
      addCriterion("BANCO not between", value1, value2, "banco");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaIsNull() {
      addCriterion("NRO_TARJETA is null");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaIsNotNull() {
      addCriterion("NRO_TARJETA is not null");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaEqualTo(String value) {
      addCriterion("NRO_TARJETA =", value, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaNotEqualTo(String value) {
      addCriterion("NRO_TARJETA <>", value, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaGreaterThan(String value) {
      addCriterion("NRO_TARJETA >", value, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaGreaterThanOrEqualTo(String value) {
      addCriterion("NRO_TARJETA >=", value, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaLessThan(String value) {
      addCriterion("NRO_TARJETA <", value, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaLessThanOrEqualTo(String value) {
      addCriterion("NRO_TARJETA <=", value, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaLike(String value) {
      addCriterion("NRO_TARJETA like", value, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaNotLike(String value) {
      addCriterion("NRO_TARJETA not like", value, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaIn(List<String> values) {
      addCriterion("NRO_TARJETA in", values, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaNotIn(List<String> values) {
      addCriterion("NRO_TARJETA not in", values, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaBetween(String value1, String value2) {
      addCriterion("NRO_TARJETA between", value1, value2, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andNroTarjetaNotBetween(String value1, String value2) {
      addCriterion("NRO_TARJETA not between", value1, value2, "nroTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaIsNull() {
      addCriterion("TIPO_TARJETA is null");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaIsNotNull() {
      addCriterion("TIPO_TARJETA is not null");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaEqualTo(String value) {
      addCriterion("TIPO_TARJETA =", value, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaNotEqualTo(String value) {
      addCriterion("TIPO_TARJETA <>", value, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaGreaterThan(String value) {
      addCriterion("TIPO_TARJETA >", value, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaGreaterThanOrEqualTo(String value) {
      addCriterion("TIPO_TARJETA >=", value, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaLessThan(String value) {
      addCriterion("TIPO_TARJETA <", value, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaLessThanOrEqualTo(String value) {
      addCriterion("TIPO_TARJETA <=", value, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaLike(String value) {
      addCriterion("TIPO_TARJETA like", value, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaNotLike(String value) {
      addCriterion("TIPO_TARJETA not like", value, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaIn(List<String> values) {
      addCriterion("TIPO_TARJETA in", values, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaNotIn(List<String> values) {
      addCriterion("TIPO_TARJETA not in", values, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaBetween(String value1, String value2) {
      addCriterion("TIPO_TARJETA between", value1, value2, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andTipoTarjetaNotBetween(String value1, String value2) {
      addCriterion("TIPO_TARJETA not between", value1, value2, "tipoTarjeta");
      return (Criteria) this;
    }

    public Criteria andFechaVencIsNull() {
      addCriterion("FECHA_VENC is null");
      return (Criteria) this;
    }

    public Criteria andFechaVencIsNotNull() {
      addCriterion("FECHA_VENC is not null");
      return (Criteria) this;
    }

    public Criteria andFechaVencEqualTo(Date value) {
      addCriterionForJDBCDate("FECHA_VENC =", value, "fechaVenc");
      return (Criteria) this;
    }

    public Criteria andFechaVencNotEqualTo(Date value) {
      addCriterionForJDBCDate("FECHA_VENC <>", value, "fechaVenc");
      return (Criteria) this;
    }

    public Criteria andFechaVencGreaterThan(Date value) {
      addCriterionForJDBCDate("FECHA_VENC >", value, "fechaVenc");
      return (Criteria) this;
    }

    public Criteria andFechaVencGreaterThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("FECHA_VENC >=", value, "fechaVenc");
      return (Criteria) this;
    }

    public Criteria andFechaVencLessThan(Date value) {
      addCriterionForJDBCDate("FECHA_VENC <", value, "fechaVenc");
      return (Criteria) this;
    }

    public Criteria andFechaVencLessThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("FECHA_VENC <=", value, "fechaVenc");
      return (Criteria) this;
    }

    public Criteria andFechaVencIn(List<Date> values) {
      addCriterionForJDBCDate("FECHA_VENC in", values, "fechaVenc");
      return (Criteria) this;
    }

    public Criteria andFechaVencNotIn(List<Date> values) {
      addCriterionForJDBCDate("FECHA_VENC not in", values, "fechaVenc");
      return (Criteria) this;
    }

    public Criteria andFechaVencBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("FECHA_VENC between", value1, value2, "fechaVenc");
      return (Criteria) this;
    }

    public Criteria andFechaVencNotBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("FECHA_VENC not between", value1, value2, "fechaVenc");
      return (Criteria) this;
    }

    public Criteria andClienteThIsNull() {
      addCriterion("CLIENTE_TH is null");
      return (Criteria) this;
    }

    public Criteria andClienteThIsNotNull() {
      addCriterion("CLIENTE_TH is not null");
      return (Criteria) this;
    }

    public Criteria andClienteThEqualTo(String value) {
      addCriterion("CLIENTE_TH =", value, "clienteTh");
      return (Criteria) this;
    }

    public Criteria andClienteThNotEqualTo(String value) {
      addCriterion("CLIENTE_TH <>", value, "clienteTh");
      return (Criteria) this;
    }

    public Criteria andClienteThGreaterThan(String value) {
      addCriterion("CLIENTE_TH >", value, "clienteTh");
      return (Criteria) this;
    }

    public Criteria andClienteThGreaterThanOrEqualTo(String value) {
      addCriterion("CLIENTE_TH >=", value, "clienteTh");
      return (Criteria) this;
    }

    public Criteria andClienteThLessThan(String value) {
      addCriterion("CLIENTE_TH <", value, "clienteTh");
      return (Criteria) this;
    }

    public Criteria andClienteThLessThanOrEqualTo(String value) {
      addCriterion("CLIENTE_TH <=", value, "clienteTh");
      return (Criteria) this;
    }

    public Criteria andClienteThLike(String value) {
      addCriterion("CLIENTE_TH like", value, "clienteTh");
      return (Criteria) this;
    }

    public Criteria andClienteThNotLike(String value) {
      addCriterion("CLIENTE_TH not like", value, "clienteTh");
      return (Criteria) this;
    }

    public Criteria andClienteThIn(List<String> values) {
      addCriterion("CLIENTE_TH in", values, "clienteTh");
      return (Criteria) this;
    }

    public Criteria andClienteThNotIn(List<String> values) {
      addCriterion("CLIENTE_TH not in", values, "clienteTh");
      return (Criteria) this;
    }

    public Criteria andClienteThBetween(String value1, String value2) {
      addCriterion("CLIENTE_TH between", value1, value2, "clienteTh");
      return (Criteria) this;
    }

    public Criteria andClienteThNotBetween(String value1, String value2) {
      addCriterion("CLIENTE_TH not between", value1, value2, "clienteTh");
      return (Criteria) this;
    }

    public Criteria andCodigoCampanaIsNull() {
      addCriterion("CODIGO_CAMPANA is null");
      return (Criteria) this;
    }

    public Criteria andCodigoCampanaIsNotNull() {
      addCriterion("CODIGO_CAMPANA is not null");
      return (Criteria) this;
    }

    public Criteria andCodigoCampanaEqualTo(String value) {
      addCriterion("CODIGO_CAMPANA =", value, "codigoCampana");
      return (Criteria) this;
    }

    public Criteria andCodigoCampanaNotEqualTo(String value) {
      addCriterion("CODIGO_CAMPANA <>", value, "codigoCampana");
      return (Criteria) this;
    }

    public Criteria andCodigoCampanaGreaterThan(String value) {
      addCriterion("CODIGO_CAMPANA >", value, "codigoCampana");
      return (Criteria) this;
    }

    public Criteria andCodigoCampanaGreaterThanOrEqualTo(String value) {
      addCriterion("CODIGO_CAMPANA >=", value, "codigoCampana");
      return (Criteria) this;
    }

    public Criteria andCodigoCampanaLessThan(String value) {
      addCriterion("CODIGO_CAMPANA <", value, "codigoCampana");
      return (Criteria) this;
    }

    public Criteria andCodigoCampanaLessThanOrEqualTo(String value) {
      addCriterion("CODIGO_CAMPANA <=", value, "codigoCampana");
      return (Criteria) this;
    }

    public Criteria andCodigoCampanaLike(String value) {
      addCriterion("CODIGO_CAMPANA like", value, "codigoCampana");
      return (Criteria) this;
    }

    public Criteria andCodigoCampanaNotLike(String value) {
      addCriterion("CODIGO_CAMPANA not like", value, "codigoCampana");
      return (Criteria) this;
    }

    public Criteria andCodigoCampanaIn(List<String> values) {
      addCriterion("CODIGO_CAMPANA in", values, "codigoCampana");
      return (Criteria) this;
    }

    public Criteria andCodigoCampanaNotIn(List<String> values) {
      addCriterion("CODIGO_CAMPANA not in", values, "codigoCampana");
      return (Criteria) this;
    }

    public Criteria andCodigoCampanaBetween(String value1, String value2) {
      addCriterion("CODIGO_CAMPANA between", value1, value2, "codigoCampana");
      return (Criteria) this;
    }

    public Criteria andCodigoCampanaNotBetween(String value1, String value2) {
      addCriterion("CODIGO_CAMPANA not between", value1, value2, "codigoCampana");
      return (Criteria) this;
    }

    public Criteria andMarca1IsNull() {
      addCriterion("MARCA_1 is null");
      return (Criteria) this;
    }

    public Criteria andMarca1IsNotNull() {
      addCriterion("MARCA_1 is not null");
      return (Criteria) this;
    }

    public Criteria andMarca1EqualTo(String value) {
      addCriterion("MARCA_1 =", value, "marca1");
      return (Criteria) this;
    }

    public Criteria andMarca1NotEqualTo(String value) {
      addCriterion("MARCA_1 <>", value, "marca1");
      return (Criteria) this;
    }

    public Criteria andMarca1GreaterThan(String value) {
      addCriterion("MARCA_1 >", value, "marca1");
      return (Criteria) this;
    }

    public Criteria andMarca1GreaterThanOrEqualTo(String value) {
      addCriterion("MARCA_1 >=", value, "marca1");
      return (Criteria) this;
    }

    public Criteria andMarca1LessThan(String value) {
      addCriterion("MARCA_1 <", value, "marca1");
      return (Criteria) this;
    }

    public Criteria andMarca1LessThanOrEqualTo(String value) {
      addCriterion("MARCA_1 <=", value, "marca1");
      return (Criteria) this;
    }

    public Criteria andMarca1Like(String value) {
      addCriterion("MARCA_1 like", value, "marca1");
      return (Criteria) this;
    }

    public Criteria andMarca1NotLike(String value) {
      addCriterion("MARCA_1 not like", value, "marca1");
      return (Criteria) this;
    }

    public Criteria andMarca1In(List<String> values) {
      addCriterion("MARCA_1 in", values, "marca1");
      return (Criteria) this;
    }

    public Criteria andMarca1NotIn(List<String> values) {
      addCriterion("MARCA_1 not in", values, "marca1");
      return (Criteria) this;
    }

    public Criteria andMarca1Between(String value1, String value2) {
      addCriterion("MARCA_1 between", value1, value2, "marca1");
      return (Criteria) this;
    }

    public Criteria andMarca1NotBetween(String value1, String value2) {
      addCriterion("MARCA_1 not between", value1, value2, "marca1");
      return (Criteria) this;
    }

    public Criteria andMarca2IsNull() {
      addCriterion("MARCA_2 is null");
      return (Criteria) this;
    }

    public Criteria andMarca2IsNotNull() {
      addCriterion("MARCA_2 is not null");
      return (Criteria) this;
    }

    public Criteria andMarca2EqualTo(String value) {
      addCriterion("MARCA_2 =", value, "marca2");
      return (Criteria) this;
    }

    public Criteria andMarca2NotEqualTo(String value) {
      addCriterion("MARCA_2 <>", value, "marca2");
      return (Criteria) this;
    }

    public Criteria andMarca2GreaterThan(String value) {
      addCriterion("MARCA_2 >", value, "marca2");
      return (Criteria) this;
    }

    public Criteria andMarca2GreaterThanOrEqualTo(String value) {
      addCriterion("MARCA_2 >=", value, "marca2");
      return (Criteria) this;
    }

    public Criteria andMarca2LessThan(String value) {
      addCriterion("MARCA_2 <", value, "marca2");
      return (Criteria) this;
    }

    public Criteria andMarca2LessThanOrEqualTo(String value) {
      addCriterion("MARCA_2 <=", value, "marca2");
      return (Criteria) this;
    }

    public Criteria andMarca2Like(String value) {
      addCriterion("MARCA_2 like", value, "marca2");
      return (Criteria) this;
    }

    public Criteria andMarca2NotLike(String value) {
      addCriterion("MARCA_2 not like", value, "marca2");
      return (Criteria) this;
    }

    public Criteria andMarca2In(List<String> values) {
      addCriterion("MARCA_2 in", values, "marca2");
      return (Criteria) this;
    }

    public Criteria andMarca2NotIn(List<String> values) {
      addCriterion("MARCA_2 not in", values, "marca2");
      return (Criteria) this;
    }

    public Criteria andMarca2Between(String value1, String value2) {
      addCriterion("MARCA_2 between", value1, value2, "marca2");
      return (Criteria) this;
    }

    public Criteria andMarca2NotBetween(String value1, String value2) {
      addCriterion("MARCA_2 not between", value1, value2, "marca2");
      return (Criteria) this;
    }

    public Criteria andNseIsNull() {
      addCriterion("NSE is null");
      return (Criteria) this;
    }

    public Criteria andNseIsNotNull() {
      addCriterion("NSE is not null");
      return (Criteria) this;
    }

    public Criteria andNseEqualTo(String value) {
      addCriterion("NSE =", value, "nse");
      return (Criteria) this;
    }

    public Criteria andNseNotEqualTo(String value) {
      addCriterion("NSE <>", value, "nse");
      return (Criteria) this;
    }

    public Criteria andNseGreaterThan(String value) {
      addCriterion("NSE >", value, "nse");
      return (Criteria) this;
    }

    public Criteria andNseGreaterThanOrEqualTo(String value) {
      addCriterion("NSE >=", value, "nse");
      return (Criteria) this;
    }

    public Criteria andNseLessThan(String value) {
      addCriterion("NSE <", value, "nse");
      return (Criteria) this;
    }

    public Criteria andNseLessThanOrEqualTo(String value) {
      addCriterion("NSE <=", value, "nse");
      return (Criteria) this;
    }

    public Criteria andNseLike(String value) {
      addCriterion("NSE like", value, "nse");
      return (Criteria) this;
    }

    public Criteria andNseNotLike(String value) {
      addCriterion("NSE not like", value, "nse");
      return (Criteria) this;
    }

    public Criteria andNseIn(List<String> values) {
      addCriterion("NSE in", values, "nse");
      return (Criteria) this;
    }

    public Criteria andNseNotIn(List<String> values) {
      addCriterion("NSE not in", values, "nse");
      return (Criteria) this;
    }

    public Criteria andNseBetween(String value1, String value2) {
      addCriterion("NSE between", value1, value2, "nse");
      return (Criteria) this;
    }

    public Criteria andNseNotBetween(String value1, String value2) {
      addCriterion("NSE not between", value1, value2, "nse");
      return (Criteria) this;
    }

    public Criteria andTargetIsNull() {
      addCriterion("TARGET is null");
      return (Criteria) this;
    }

    public Criteria andTargetIsNotNull() {
      addCriterion("TARGET is not null");
      return (Criteria) this;
    }

    public Criteria andTargetEqualTo(String value) {
      addCriterion("TARGET =", value, "target");
      return (Criteria) this;
    }

    public Criteria andTargetNotEqualTo(String value) {
      addCriterion("TARGET <>", value, "target");
      return (Criteria) this;
    }

    public Criteria andTargetGreaterThan(String value) {
      addCriterion("TARGET >", value, "target");
      return (Criteria) this;
    }

    public Criteria andTargetGreaterThanOrEqualTo(String value) {
      addCriterion("TARGET >=", value, "target");
      return (Criteria) this;
    }

    public Criteria andTargetLessThan(String value) {
      addCriterion("TARGET <", value, "target");
      return (Criteria) this;
    }

    public Criteria andTargetLessThanOrEqualTo(String value) {
      addCriterion("TARGET <=", value, "target");
      return (Criteria) this;
    }

    public Criteria andTargetLike(String value) {
      addCriterion("TARGET like", value, "target");
      return (Criteria) this;
    }

    public Criteria andTargetNotLike(String value) {
      addCriterion("TARGET not like", value, "target");
      return (Criteria) this;
    }

    public Criteria andTargetIn(List<String> values) {
      addCriterion("TARGET in", values, "target");
      return (Criteria) this;
    }

    public Criteria andTargetNotIn(List<String> values) {
      addCriterion("TARGET not in", values, "target");
      return (Criteria) this;
    }

    public Criteria andTargetBetween(String value1, String value2) {
      addCriterion("TARGET between", value1, value2, "target");
      return (Criteria) this;
    }

    public Criteria andTargetNotBetween(String value1, String value2) {
      addCriterion("TARGET not between", value1, value2, "target");
      return (Criteria) this;
    }

    public Criteria andFechaCreacionIsNull() {
      addCriterion("FECHA_CREACION is null");
      return (Criteria) this;
    }

    public Criteria andFechaCreacionIsNotNull() {
      addCriterion("FECHA_CREACION is not null");
      return (Criteria) this;
    }

    public Criteria andFechaCreacionEqualTo(Date value) {
      addCriterionForJDBCDate("FECHA_CREACION =", value, "fechaCreacion");
      return (Criteria) this;
    }

    public Criteria andFechaCreacionNotEqualTo(Date value) {
      addCriterionForJDBCDate("FECHA_CREACION <>", value, "fechaCreacion");
      return (Criteria) this;
    }

    public Criteria andFechaCreacionGreaterThan(Date value) {
      addCriterionForJDBCDate("FECHA_CREACION >", value, "fechaCreacion");
      return (Criteria) this;
    }

    public Criteria andFechaCreacionGreaterThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("FECHA_CREACION >=", value, "fechaCreacion");
      return (Criteria) this;
    }

    public Criteria andFechaCreacionLessThan(Date value) {
      addCriterionForJDBCDate("FECHA_CREACION <", value, "fechaCreacion");
      return (Criteria) this;
    }

    public Criteria andFechaCreacionLessThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("FECHA_CREACION <=", value, "fechaCreacion");
      return (Criteria) this;
    }

    public Criteria andFechaCreacionIn(List<Date> values) {
      addCriterionForJDBCDate("FECHA_CREACION in", values, "fechaCreacion");
      return (Criteria) this;
    }

    public Criteria andFechaCreacionNotIn(List<Date> values) {
      addCriterionForJDBCDate("FECHA_CREACION not in", values, "fechaCreacion");
      return (Criteria) this;
    }

    public Criteria andFechaCreacionBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("FECHA_CREACION between", value1, value2, "fechaCreacion");
      return (Criteria) this;
    }

    public Criteria andFechaCreacionNotBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("FECHA_CREACION not between", value1, value2, "fechaCreacion");
      return (Criteria) this;
    }

    public Criteria andUsrCreacionIsNull() {
      addCriterion("USR_CREACION is null");
      return (Criteria) this;
    }

    public Criteria andUsrCreacionIsNotNull() {
      addCriterion("USR_CREACION is not null");
      return (Criteria) this;
    }

    public Criteria andUsrCreacionEqualTo(String value) {
      addCriterion("USR_CREACION =", value, "usrCreacion");
      return (Criteria) this;
    }

    public Criteria andUsrCreacionNotEqualTo(String value) {
      addCriterion("USR_CREACION <>", value, "usrCreacion");
      return (Criteria) this;
    }

    public Criteria andUsrCreacionGreaterThan(String value) {
      addCriterion("USR_CREACION >", value, "usrCreacion");
      return (Criteria) this;
    }

    public Criteria andUsrCreacionGreaterThanOrEqualTo(String value) {
      addCriterion("USR_CREACION >=", value, "usrCreacion");
      return (Criteria) this;
    }

    public Criteria andUsrCreacionLessThan(String value) {
      addCriterion("USR_CREACION <", value, "usrCreacion");
      return (Criteria) this;
    }

    public Criteria andUsrCreacionLessThanOrEqualTo(String value) {
      addCriterion("USR_CREACION <=", value, "usrCreacion");
      return (Criteria) this;
    }

    public Criteria andUsrCreacionLike(String value) {
      addCriterion("USR_CREACION like", value, "usrCreacion");
      return (Criteria) this;
    }

    public Criteria andUsrCreacionNotLike(String value) {
      addCriterion("USR_CREACION not like", value, "usrCreacion");
      return (Criteria) this;
    }

    public Criteria andUsrCreacionIn(List<String> values) {
      addCriterion("USR_CREACION in", values, "usrCreacion");
      return (Criteria) this;
    }

    public Criteria andUsrCreacionNotIn(List<String> values) {
      addCriterion("USR_CREACION not in", values, "usrCreacion");
      return (Criteria) this;
    }

    public Criteria andUsrCreacionBetween(String value1, String value2) {
      addCriterion("USR_CREACION between", value1, value2, "usrCreacion");
      return (Criteria) this;
    }

    public Criteria andUsrCreacionNotBetween(String value1, String value2) {
      addCriterion("USR_CREACION not between", value1, value2, "usrCreacion");
      return (Criteria) this;
    }

    public Criteria andFechaModifIsNull() {
      addCriterion("FECHA_MODIF is null");
      return (Criteria) this;
    }

    public Criteria andFechaModifIsNotNull() {
      addCriterion("FECHA_MODIF is not null");
      return (Criteria) this;
    }

    public Criteria andFechaModifEqualTo(Date value) {
      addCriterionForJDBCDate("FECHA_MODIF =", value, "fechaModif");
      return (Criteria) this;
    }

    public Criteria andFechaModifNotEqualTo(Date value) {
      addCriterionForJDBCDate("FECHA_MODIF <>", value, "fechaModif");
      return (Criteria) this;
    }

    public Criteria andFechaModifGreaterThan(Date value) {
      addCriterionForJDBCDate("FECHA_MODIF >", value, "fechaModif");
      return (Criteria) this;
    }

    public Criteria andFechaModifGreaterThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("FECHA_MODIF >=", value, "fechaModif");
      return (Criteria) this;
    }

    public Criteria andFechaModifLessThan(Date value) {
      addCriterionForJDBCDate("FECHA_MODIF <", value, "fechaModif");
      return (Criteria) this;
    }

    public Criteria andFechaModifLessThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("FECHA_MODIF <=", value, "fechaModif");
      return (Criteria) this;
    }

    public Criteria andFechaModifIn(List<Date> values) {
      addCriterionForJDBCDate("FECHA_MODIF in", values, "fechaModif");
      return (Criteria) this;
    }

    public Criteria andFechaModifNotIn(List<Date> values) {
      addCriterionForJDBCDate("FECHA_MODIF not in", values, "fechaModif");
      return (Criteria) this;
    }

    public Criteria andFechaModifBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("FECHA_MODIF between", value1, value2, "fechaModif");
      return (Criteria) this;
    }

    public Criteria andFechaModifNotBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("FECHA_MODIF not between", value1, value2, "fechaModif");
      return (Criteria) this;
    }

    public Criteria andUsrModifIsNull() {
      addCriterion("USR_MODIF is null");
      return (Criteria) this;
    }

    public Criteria andUsrModifIsNotNull() {
      addCriterion("USR_MODIF is not null");
      return (Criteria) this;
    }

    public Criteria andUsrModifEqualTo(String value) {
      addCriterion("USR_MODIF =", value, "usrModif");
      return (Criteria) this;
    }

    public Criteria andUsrModifNotEqualTo(String value) {
      addCriterion("USR_MODIF <>", value, "usrModif");
      return (Criteria) this;
    }

    public Criteria andUsrModifGreaterThan(String value) {
      addCriterion("USR_MODIF >", value, "usrModif");
      return (Criteria) this;
    }

    public Criteria andUsrModifGreaterThanOrEqualTo(String value) {
      addCriterion("USR_MODIF >=", value, "usrModif");
      return (Criteria) this;
    }

    public Criteria andUsrModifLessThan(String value) {
      addCriterion("USR_MODIF <", value, "usrModif");
      return (Criteria) this;
    }

    public Criteria andUsrModifLessThanOrEqualTo(String value) {
      addCriterion("USR_MODIF <=", value, "usrModif");
      return (Criteria) this;
    }

    public Criteria andUsrModifLike(String value) {
      addCriterion("USR_MODIF like", value, "usrModif");
      return (Criteria) this;
    }

    public Criteria andUsrModifNotLike(String value) {
      addCriterion("USR_MODIF not like", value, "usrModif");
      return (Criteria) this;
    }

    public Criteria andUsrModifIn(List<String> values) {
      addCriterion("USR_MODIF in", values, "usrModif");
      return (Criteria) this;
    }

    public Criteria andUsrModifNotIn(List<String> values) {
      addCriterion("USR_MODIF not in", values, "usrModif");
      return (Criteria) this;
    }

    public Criteria andUsrModifBetween(String value1, String value2) {
      addCriterion("USR_MODIF between", value1, value2, "usrModif");
      return (Criteria) this;
    }

    public Criteria andUsrModifNotBetween(String value1, String value2) {
      addCriterion("USR_MODIF not between", value1, value2, "usrModif");
      return (Criteria) this;
    }

    public Criteria andTelefono7IsNull() {
      addCriterion("TELEFONO_7 is null");
      return (Criteria) this;
    }

    public Criteria andTelefono7IsNotNull() {
      addCriterion("TELEFONO_7 is not null");
      return (Criteria) this;
    }

    public Criteria andTelefono7EqualTo(String value) {
      addCriterion("TELEFONO_7 =", value, "telefono7");
      return (Criteria) this;
    }

    public Criteria andTelefono7NotEqualTo(String value) {
      addCriterion("TELEFONO_7 <>", value, "telefono7");
      return (Criteria) this;
    }

    public Criteria andTelefono7GreaterThan(String value) {
      addCriterion("TELEFONO_7 >", value, "telefono7");
      return (Criteria) this;
    }

    public Criteria andTelefono7GreaterThanOrEqualTo(String value) {
      addCriterion("TELEFONO_7 >=", value, "telefono7");
      return (Criteria) this;
    }

    public Criteria andTelefono7LessThan(String value) {
      addCriterion("TELEFONO_7 <", value, "telefono7");
      return (Criteria) this;
    }

    public Criteria andTelefono7LessThanOrEqualTo(String value) {
      addCriterion("TELEFONO_7 <=", value, "telefono7");
      return (Criteria) this;
    }

    public Criteria andTelefono7Like(String value) {
      addCriterion("TELEFONO_7 like", value, "telefono7");
      return (Criteria) this;
    }

    public Criteria andTelefono7NotLike(String value) {
      addCriterion("TELEFONO_7 not like", value, "telefono7");
      return (Criteria) this;
    }

    public Criteria andTelefono7In(List<String> values) {
      addCriterion("TELEFONO_7 in", values, "telefono7");
      return (Criteria) this;
    }

    public Criteria andTelefono7NotIn(List<String> values) {
      addCriterion("TELEFONO_7 not in", values, "telefono7");
      return (Criteria) this;
    }

    public Criteria andTelefono7Between(String value1, String value2) {
      addCriterion("TELEFONO_7 between", value1, value2, "telefono7");
      return (Criteria) this;
    }

    public Criteria andTelefono7NotBetween(String value1, String value2) {
      addCriterion("TELEFONO_7 not between", value1, value2, "telefono7");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberIsNull() {
      addCriterion("SEQUENCE_FILE_NUMBER is null");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberIsNotNull() {
      addCriterion("SEQUENCE_FILE_NUMBER is not null");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberEqualTo(BigDecimal value) {
      addCriterion("SEQUENCE_FILE_NUMBER =", value, "sequenceFileNumber");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberNotEqualTo(BigDecimal value) {
      addCriterion("SEQUENCE_FILE_NUMBER <>", value, "sequenceFileNumber");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberGreaterThan(BigDecimal value) {
      addCriterion("SEQUENCE_FILE_NUMBER >", value, "sequenceFileNumber");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("SEQUENCE_FILE_NUMBER >=", value, "sequenceFileNumber");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberLessThan(BigDecimal value) {
      addCriterion("SEQUENCE_FILE_NUMBER <", value, "sequenceFileNumber");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberLessThanOrEqualTo(BigDecimal value) {
      addCriterion("SEQUENCE_FILE_NUMBER <=", value, "sequenceFileNumber");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberIn(List<BigDecimal> values) {
      addCriterion("SEQUENCE_FILE_NUMBER in", values, "sequenceFileNumber");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberNotIn(List<BigDecimal> values) {
      addCriterion("SEQUENCE_FILE_NUMBER not in", values, "sequenceFileNumber");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("SEQUENCE_FILE_NUMBER between", value1, value2, "sequenceFileNumber");
      return (Criteria) this;
    }

    public Criteria andSequenceFileNumberNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("SEQUENCE_FILE_NUMBER not between", value1, value2, "sequenceFileNumber");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table UPLOAD.CLIENTE
   *
   * @mbggenerated do_not_delete_during_merge Wed Feb 05 22:03:14 COT 2014
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table UPLOAD.CLIENTE
   *
   * @mbggenerated Wed Feb 05 22:03:14 COT 2014
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}