//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.23 at 04:50:30 PM COT 
//

package com.cardif.sunsystems.mapeo.supplier;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the com.prov package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML
 * content can consist of schema derived interfaces and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.prov
   * 
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link SSC }
   * 
   */
  public SSC createSSC() {
    return new SSC();
  }

  /**
   * Create an instance of {@link SSC.User }
   * 
   */
  public SSC.User createSSCUser() {
    return new SSC.User();
  }

  /**
   * Create an instance of {@link SSC.SunSystemsContext }
   * 
   */
  public SSC.SunSystemsContext createSSCSunSystemsContext() {
    return new SSC.SunSystemsContext();
  }

  /**
   * Create an instance of {@link SSC.Payload }
   * 
   */
  public SSC.Payload createSSCPayload() {
    return new SSC.Payload();
  }

  /**
   * Create an instance of {@link SSC.Payload.Supplier }
   * 
   */
  public SSC.Payload.Supplier createSSCPayloadSupplier() {
    return new SSC.Payload.Supplier();
  }

  /**
   * Create an instance of {@link SSC.Payload.Supplier.BankDetails }
   * 
   */
  public SSC.Payload.Supplier.BankDetails createSSCPayloadSupplierBankDetails() {
    return new SSC.Payload.Supplier.BankDetails();
  }

//  /**
//   * Create an instance of {@link SSC.Payload.Supplier.SupplierAddress }
//   * 
//   */
//  public SSC.Payload.Supplier.SupplierAddress createSSCPayloadSupplierSupplierAddress() {
//    return new SSC.Payload.Supplier.SupplierAddress();
//  }

}
