package com.cardif.sunsystems.mapeo.journal;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2014.12.04 at 03:04:21 PM COT 
//

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="User">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SunSystemsContext">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BusinessUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BudgetCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Payload">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Ledger">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Line" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="AccountCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="AccountingPeriod" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                       &lt;element name="AnalysisCode1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="AnalysisCode2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="AnalysisCode3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="AnalysisCode4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="AnalysisCode5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="AnalysisCode6" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="AnalysisCode7" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="AnalysisCode8" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="AnalysisCode9" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="AnalysisCode10" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Base2ReportingAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="BaseAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="JournalNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="TransactionAmount" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="TransactionDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="TransactionReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="JournalLineNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="AmountTips" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="FlagPayment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="TransactionImport" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="TransactionPen" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="TransactionEuros" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="DiferencePen" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="DiferenceEuros" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="NroCheque" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="NroConstancia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="RefCtaBancoProvision" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="RefCtaBancoComision" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="LossGain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="LastCorrelative" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Accounts">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="LookupCode" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="DetailLad">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="GeneralDescription1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="GeneralDescription2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="GeneralDescription3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "user", "sunSystemsContext", "payload" })
@XmlRootElement(name = "SSC")
public class SSC {

  @XmlElement(name = "User", required = true)
  protected SSC.User user;
  @XmlElement(name = "SunSystemsContext", required = true)
  protected SSC.SunSystemsContext sunSystemsContext;
  @XmlElement(name = "Payload", required = true)
  protected SSC.Payload payload;

  /**
   * Gets the value of the user property.
   * 
   * @return possible object is {@link SSC.User }
   * 
   */
  public SSC.User getUser() {
    return user;
  }

  /**
   * Sets the value of the user property.
   * 
   * @param value
   *          allowed object is {@link SSC.User }
   * 
   */
  public void setUser(SSC.User value) {
    this.user = value;
  }

  /**
   * Gets the value of the sunSystemsContext property.
   * 
   * @return possible object is {@link SSC.SunSystemsContext }
   * 
   */
  public SSC.SunSystemsContext getSunSystemsContext() {
    return sunSystemsContext;
  }

  /**
   * Sets the value of the sunSystemsContext property.
   * 
   * @param value
   *          allowed object is {@link SSC.SunSystemsContext }
   * 
   */
  public void setSunSystemsContext(SSC.SunSystemsContext value) {
    this.sunSystemsContext = value;
  }

  /**
   * Gets the value of the payload property.
   * 
   * @return possible object is {@link SSC.Payload }
   * 
   */
  public SSC.Payload getPayload() {
    return payload;
  }

  /**
   * Sets the value of the payload property.
   * 
   * @param value
   *          allowed object is {@link SSC.Payload }
   * 
   */
  public void setPayload(SSC.Payload value) {
    this.payload = value;
  }

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="Ledger">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                 &lt;sequence>
   *                   &lt;element name="Line" maxOccurs="unbounded" minOccurs="0">
   *                     &lt;complexType>
   *                       &lt;complexContent>
   *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                           &lt;sequence>
   *                             &lt;element name="AccountCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="AccountingPeriod" type="{http://www.w3.org/2001/XMLSchema}short"/>
   *                             &lt;element name="AnalysisCode1" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="AnalysisCode2" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="AnalysisCode3" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="AnalysisCode4" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="AnalysisCode5" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="AnalysisCode6" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="AnalysisCode7" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="AnalysisCode8" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="AnalysisCode9" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="AnalysisCode10" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="Base2ReportingAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="BaseAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="JournalNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
   *                             &lt;element name="TransactionAmount" type="{http://www.w3.org/2001/XMLSchema}float"/>
   *                             &lt;element name="TransactionDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="TransactionReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="JournalLineNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="AmountTips" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="FlagPayment" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="TransactionImport" type="{http://www.w3.org/2001/XMLSchema}float"/>
   *                             &lt;element name="TransactionPen" type="{http://www.w3.org/2001/XMLSchema}float"/>
   *                             &lt;element name="TransactionEuros" type="{http://www.w3.org/2001/XMLSchema}float"/>
   *                             &lt;element name="DiferencePen" type="{http://www.w3.org/2001/XMLSchema}float"/>
   *                             &lt;element name="DiferenceEuros" type="{http://www.w3.org/2001/XMLSchema}float"/>
   *                             &lt;element name="NroCheque" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="NroConstancia" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="RefCtaBancoProvision" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="RefCtaBancoComision" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="LossGain" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="LastCorrelative" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="Accounts">
   *                               &lt;complexType>
   *                                 &lt;complexContent>
   *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                                     &lt;sequence>
   *                                       &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                                       &lt;element name="LookupCode" type="{http://www.w3.org/2001/XMLSchema}long"/>
   *                                     &lt;/sequence>
   *                                   &lt;/restriction>
   *                                 &lt;/complexContent>
   *                               &lt;/complexType>
   *                             &lt;/element>
   *                             &lt;element name="DetailLad">
   *                               &lt;complexType>
   *                                 &lt;complexContent>
   *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                                     &lt;sequence>
   *                                        &lt;element name="GeneralDescription1" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                                        &lt;element name="GeneralDescription2" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                                        &lt;element name="GeneralDescription3" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                                      &lt;/sequence>
   *                                    &lt;/restriction>
   *                                  &lt;/complexContent>
   *                                &lt;/complexType>
   *                              &lt;/element>
   *                           &lt;/sequence>
   *                         &lt;/restriction>
   *                       &lt;/complexContent>
   *                     &lt;/complexType>
   *                   &lt;/element>
   *                 &lt;/sequence>
   *               &lt;/restriction>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "ledger" })
  public static class Payload {

    @XmlElement(name = "Ledger", required = true)
    protected SSC.Payload.Ledger ledger;

    /**
     * Gets the value of the ledger property.
     * 
     * @return possible object is {@link SSC.Payload.Ledger }
     * 
     */
    public SSC.Payload.Ledger getLedger() {
      return ledger;
    }

    /**
     * Sets the value of the ledger property.
     * 
     * @param value
     *          allowed object is {@link SSC.Payload.Ledger }
     * 
     */
    public void setLedger(SSC.Payload.Ledger value) {
      this.ledger = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Line" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AccountCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AccountingPeriod" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="AnalysisCode1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AnalysisCode2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AnalysisCode3" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AnalysisCode4" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AnalysisCode5" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AnalysisCode6" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AnalysisCode7" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AnalysisCode8" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AnalysisCode9" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AnalysisCode10" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Base2ReportingAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="BaseAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="JournalNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="TransactionAmount" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="TransactionDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="TransactionReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="JournalLineNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AmountTips" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="FlagPayment" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="TransactionImport" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="TransactionPen" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="TransactionEuros" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="DiferencePen" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="DiferenceEuros" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="NroCheque" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="NroConstancia" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="RefCtaBancoProvision" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="RefCtaBancoComision" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="LossGain" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="LastCorrelative" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Accounts">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="LookupCode" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="DetailLad">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="GeneralDescription1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="GeneralDescription2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="GeneralDescription3" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "line" })
    public static class Ledger {

      @XmlElement(name = "Line")
      protected List<SSC.Payload.Ledger.Line> line;

      /**
       * Gets the value of the line property.
       * 
       * <p>
       * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be
       * present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the line property.
       * 
       * <p>
       * For example, to add a new item, do as follows:
       * 
       * <pre>
       * getLine().add(newItem);
       * </pre>
       * 
       * 
       * <p>
       * Objects of the following type(s) are allowed in the list {@link SSC.Payload.Ledger.Line }
       * 
       * 
       */
      public List<SSC.Payload.Ledger.Line> getLine() {
        if (line == null) {
          line = new ArrayList<SSC.Payload.Ledger.Line>();
        }
        return this.line;
      }

      /**
       * <p>
       * Java class for anonymous complex type.
       * 
       * <p>
       * The following schema fragment specifies the expected content contained within this class.
       * 
       * <pre>
       * &lt;complexType>
       *   &lt;complexContent>
       *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *       &lt;sequence>
       *         &lt;element name="AccountCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="AccountingPeriod" type="{http://www.w3.org/2001/XMLSchema}short"/>
       *         &lt;element name="AnalysisCode1" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="AnalysisCode2" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="AnalysisCode3" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="AnalysisCode4" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="AnalysisCode5" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="AnalysisCode6" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="AnalysisCode7" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="AnalysisCode8" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="AnalysisCode9" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="AnalysisCode10" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="Base2ReportingAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="BaseAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="DebitCredit" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="JournalLineNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="JournalNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
       *         &lt;element name="JournalType" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="LinkReference2" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="TransactionAmount" type="{http://www.w3.org/2001/XMLSchema}float"/>
       *         &lt;element name="TransactionDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="TransactionReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="AmountTips" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="FlagPayment" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="TransactionImport" type="{http://www.w3.org/2001/XMLSchema}float"/>
       *         &lt;element name="TransactionPen" type="{http://www.w3.org/2001/XMLSchema}float"/>
       *         &lt;element name="TransactionEuros" type="{http://www.w3.org/2001/XMLSchema}float"/>
       *         &lt;element name="DiferencePen" type="{http://www.w3.org/2001/XMLSchema}float"/>
       *         &lt;element name="DiferenceEuros" type="{http://www.w3.org/2001/XMLSchema}float"/>
       *         &lt;element name="NroCheque" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="NroConstancia" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="RefCtaBancoProvision" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="RefCtaBancoComision" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="LossGain" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="LastCorrelative" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="Accounts">
       *           &lt;complexType>
       *             &lt;complexContent>
       *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *                 &lt;sequence>
       *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *                   &lt;element name="LookupCode" type="{http://www.w3.org/2001/XMLSchema}long"/>
       *                 &lt;/sequence>
       *               &lt;/restriction>
       *             &lt;/complexContent>
       *           &lt;/complexType>
       *         &lt;/element>
       *         &lt;element name="DetailLad">
       *           &lt;complexType>
       *             &lt;complexContent>
       *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *                 &lt;sequence>
       *                   &lt;element name="GeneralDescription1" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *                   &lt;element name="GeneralDescription2" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *                   &lt;element name="GeneralDescription3" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *                 &lt;/sequence>
       *               &lt;/restriction>
       *             &lt;/complexContent>
       *           &lt;/complexType>
       *         &lt;/element>
       *       &lt;/sequence>
       *     &lt;/restriction>
       *   &lt;/complexContent>
       * &lt;/complexType>
       * </pre>
       * 
       * 
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "",
          propOrder = { "accountCode", "accountingPeriod", "analysisCode1", "analysisCode2", "analysisCode3", "analysisCode4", "analysisCode5", "analysisCode6", "analysisCode7", "analysisCode8",
              "analysisCode9", "analysisCode10", "base2ReportingAmount", "baseAmount", "currencyCode", "debitCredit", "description", "journalLineNumber", "journalNumber", "journalType", "linkReference2", "transactionAmount", "transactionDate",
              "transactionReference", "amountTips", "flagPayment", "transactionImport", "transactionPen", "transactionEuros", "diferencePen", "diferenceEuros", "nroCheque",
              "nroConstancia", "refCtaBancoProvision", "refCtaBancoComision", "lossGain", "lastCorrelative", "accounts", "detailLad" })
      public static class Line {

        @XmlElement(name = "AccountCode", required = true)
        protected String accountCode;
        @XmlElement(name = "AccountingPeriod")
        protected short accountingPeriod;
        @XmlElement(name = "AnalysisCode1", required = true)
        protected String analysisCode1;
        @XmlElement(name = "AnalysisCode2", required = true)
        protected String analysisCode2;
        @XmlElement(name = "AnalysisCode3", required = true)
        protected String analysisCode3;
        @XmlElement(name = "AnalysisCode4", required = true)
        protected String analysisCode4;
        @XmlElement(name = "AnalysisCode5", required = true)
        protected String analysisCode5;
        @XmlElement(name = "AnalysisCode6", required = true)
        protected String analysisCode6;
        @XmlElement(name = "AnalysisCode7", required = true)
        protected String analysisCode7;
        @XmlElement(name = "AnalysisCode8", required = true)
        protected String analysisCode8;
        @XmlElement(name = "AnalysisCode9", required = true)
        protected String analysisCode9;
        @XmlElement(name = "AnalysisCode10", required = true)
        protected String analysisCode10;
        @XmlElement(name = "Base2ReportingAmount")
        protected String base2ReportingAmount;
        @XmlElement(name = "BaseAmount")
        protected String baseAmount;
        @XmlElement(name = "CurrencyCode", required = true)
        protected String currencyCode;
        @XmlElement(name = "DebitCredit", required = true)
        protected String debitCredit;
        @XmlElement(name = "Description", required = true)
        protected String description;
        @XmlElement(name = "JournalLineNumber", required = true)
        protected String journalLineNumber;
        @XmlElement(name = "JournalNumber")
        protected int journalNumber;
        @XmlElement(name = "JournalType")
        protected String journalType;
        @XmlElement(name = "LinkReference2")
        protected String linkReference2;
        @XmlElement(name = "TransactionAmount")
        protected float transactionAmount;
        @XmlElement(name = "TransactionDate")
        protected String transactionDate;
        @XmlElement(name = "TransactionReference", required = true)
        protected String transactionReference;
        @XmlElement(name = "AmountTips", required = true)
        protected String amountTips;
        @XmlElement(name = "FlagPayment", required = true)
        protected String flagPayment;
        @XmlElement(name = "TransactionImport")
        protected float transactionImport;
        @XmlElement(name = "TransactionPen")
        protected float transactionPen;
        @XmlElement(name = "TransactionEuros")
        protected float transactionEuros;
        @XmlElement(name = "DiferencePen")
        protected float diferencePen;
        @XmlElement(name = "DiferenceEuros")
        protected float diferenceEuros;
        @XmlElement(name = "NroCheque", required = true)
        protected String nroCheque;
        @XmlElement(name = "NroConstancia", required = true)
        protected String nroConstancia;
        @XmlElement(name = "RefCtaBancoProvision", required = true)
        protected String refCtaBancoProvision;
        @XmlElement(name = "RefCtaBancoComision", required = true)
        protected String refCtaBancoComision;
        @XmlElement(name = "LossGain", required = true)
        protected String lossGain;
        @XmlElement(name = "LastCorrelative", required = true)
        protected String lastCorrelative;
        @XmlElement(name = "Accounts", required = true)
        protected SSC.Payload.Ledger.Line.Accounts accounts;
        @XmlElement(name = "DetailLad", required = true)
        protected SSC.Payload.Ledger.Line.DetailLad detailLad;
        
        
        /**
         * Gets the value of the accountCode property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getAccountCode() {
          return accountCode;
        }

        /**
         * Sets the value of the accountCode property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setAccountCode(String value) {
          this.accountCode = value;
        }

        /**
         * Gets the value of the accountingPeriod property.
         * 
         */
        public short getAccountingPeriod() {
          return accountingPeriod;
        }

        /**
         * Sets the value of the accountingPeriod property.
         * 
         */
        public void setAccountingPeriod(short value) {
          this.accountingPeriod = value;
        }

        /**
         * Gets the value of the analysisCode1 property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getAnalysisCode1() {
          return analysisCode1;
        }

        /**
         * Sets the value of the analysisCode1 property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setAnalysisCode1(String value) {
          this.analysisCode1 = value;
        }

        /**
         * Gets the value of the analysisCode2 property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getAnalysisCode2() {
          return analysisCode2;
        }

        /**
         * Sets the value of the analysisCode2 property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setAnalysisCode2(String value) {
          this.analysisCode2 = value;
        }

        /**
         * Gets the value of the analysisCode3 property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getAnalysisCode3() {
          return analysisCode3;
        }

        /**
         * Sets the value of the analysisCode3 property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setAnalysisCode3(String value) {
          this.analysisCode3 = value;
        }

        /**
         * Gets the value of the analysisCode4 property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getAnalysisCode4() {
          return analysisCode4;
        }

        /**
         * Sets the value of the analysisCode4 property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setAnalysisCode4(String value) {
          this.analysisCode4 = value;
        }

        /**
         * Gets the value of the analysisCode5 property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getAnalysisCode5() {
          return analysisCode5;
        }

        /**
         * Sets the value of the analysisCode5 property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setAnalysisCode5(String value) {
          this.analysisCode5 = value;
        }

        /**
         * Gets the value of the analysisCode6 property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getAnalysisCode6() {
          return analysisCode6;
        }

        /**
         * Sets the value of the analysisCode6 property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setAnalysisCode6(String value) {
          this.analysisCode6 = value;
        }

        /**
         * Gets the value of the analysisCode7 property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getAnalysisCode7() {
          return analysisCode7;
        }

        /**
         * Sets the value of the analysisCode7 property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setAnalysisCode7(String value) {
          this.analysisCode7 = value;
        }

        /**
         * Gets the value of the analysisCode8 property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getAnalysisCode8() {
          return analysisCode8;
        }

        /**
         * Sets the value of the analysisCode8 property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setAnalysisCode8(String value) {
          this.analysisCode8 = value;
        }

        /**
         * Gets the value of the analysisCode9 property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getAnalysisCode9() {
          return analysisCode9;
        }

        /**
         * Sets the value of the analysisCode9 property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setAnalysisCode9(String value) {
          this.analysisCode9 = value;
        }

        /**
         * Gets the value of the analysisCode10 property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getAnalysisCode10() {
          return analysisCode10;
        }

        /**
         * Sets the value of the analysisCode10 property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setAnalysisCode10(String value) {
          this.analysisCode10 = value;
        }

        /**
         * Gets the value of the base2ReportingAmount property.
         * 
         */
        public String getBase2ReportingAmount() {
          return base2ReportingAmount;
        }

        /**
         * Sets the value of the base2ReportingAmount property.
         * 
         */
        public void setBase2ReportingAmount(String value) {
          this.base2ReportingAmount = value;
        }

        /**
         * Gets the value of the baseAmount property.
         * 
         */
        public String getBaseAmount() {
          return baseAmount;
        }

        /**
         * Sets the value of the baseAmount property.
         * 
         */
        public void setBaseAmount(String value) {
          this.baseAmount = value;
        }

        /**
         * Gets the value of the currencyCode property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getCurrencyCode() {
          return currencyCode;
        }

        /**
         * Sets the value of the currencyCode property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setCurrencyCode(String value) {
          this.currencyCode = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return possible object is {@link String }
         * 
         */

        public String getDebitCredit() {
          return debitCredit;
        }
        
        /**
         * Sets the value of the currencyCode property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setDebitCredit(String debitCredit) {
          this.debitCredit = debitCredit;
        }
        
        public String getDescription() {
          return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setDescription(String value) {
          this.description = value;
        }
        
        /**
         * Gets the value of the journalNumber property.
         * 
         */
        public int getJournalNumber() {
          return journalNumber;
        }

        /**
         * Sets the value of the journalNumber property.
         * 
         */
        public void setJournalNumber(int value) {
          this.journalNumber = value;
        }
        
        public String getJournalType() {
          return journalType;
        }

        public void setJournalType(String journalType) {
          this.journalType = journalType;
        }

        public String getLinkReference2() {
          return linkReference2;
        }

        public void setLinkReference2(String linkReference2) {
          this.linkReference2 = linkReference2;
        }

        /**
         * Gets the value of the transactionAmount property.
         * 
         */
        public float getTransactionAmount() {
          return transactionAmount;
        }

        /**
         * Sets the value of the transactionAmount property.
         * 
         */
        public void setTransactionAmount(float value) {
          this.transactionAmount = value;
        }

        /**
         * Gets the value of the transactionDate property.
         * 
         */
        public String getTransactionDate() {
          return transactionDate;
        }

        /**
         * Sets the value of the transactionDate property.
         * 
         */
        public void setTransactionDate(String value) {
          this.transactionDate = value;
        }

        /**
         * Gets the value of the transactionReference property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getTransactionReference() {
          return transactionReference;
        }

        /**
         * Sets the value of the transactionReference property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setTransactionReference(String value) {
          this.transactionReference = value;
        }

        /**
         * Gets the value of the journalLineNumber property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getJournalLineNumber() {
          return journalLineNumber;
        }

        /**
         * Sets the value of the journalLineNumber property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setJournalLineNumber(String value) {
          this.journalLineNumber = value;
        }

        /**
         * Gets the value of the amountTips property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getAmountTips() {
          return amountTips;
        }

        /**
         * Sets the value of the amountTips property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setAmountTips(String value) {
          this.amountTips = value;
        }

        /**
         * Gets the value of the flagPayment property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getFlagPayment() {
          return flagPayment;
        }

        /**
         * Sets the value of the flagPayment property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setFlagPayment(String value) {
          this.flagPayment = value;
        }

        /**
         * Gets the value of the transactionImport property.
         * 
         */
        public float getTransactionImport() {
          return transactionImport;
        }

        /**
         * Sets the value of the transactionImport property.
         * 
         */
        public void setTransactionImport(float value) {
          this.transactionImport = value;
        }

        /**
         * Gets the value of the transactionPen property.
         * 
         */
        public float getTransactionPen() {
          return transactionPen;
        }

        /**
         * Sets the value of the transactionPen property.
         * 
         */
        public void setTransactionPen(float value) {
          this.transactionPen = value;
        }

        /**
         * Gets the value of the transactionEuros property.
         * 
         */
        public float getTransactionEuros() {
          return transactionEuros;
        }

        /**
         * Sets the value of the transactionEuros property.
         * 
         */
        public void setTransactionEuros(float value) {
          this.transactionEuros = value;
        }

        /**
         * Gets the value of the diferencePen property.
         * 
         */
        public float getDiferencePen() {
          return diferencePen;
        }

        /**
         * Sets the value of the diferencePen property.
         * 
         */
        public void setDiferencePen(float value) {
          this.diferencePen = value;
        }

        /**
         * Gets the value of the diferenceEuros property.
         * 
         */
        public float getDiferenceEuros() {
          return diferenceEuros;
        }

        /**
         * Sets the value of the diferenceEuros property.
         * 
         */
        public void setDiferenceEuros(float value) {
          this.diferenceEuros = value;
        }

        /**
         * Gets the value of the nroCheque property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getNroCheque() {
          return nroCheque;
        }

        /**
         * Sets the value of the nroCheque property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setNroCheque(String value) {
          this.nroCheque = value;
        }

        /**
         * Gets the value of the nroConstancia property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getNroConstancia() {
          return nroConstancia;
        }

        /**
         * Sets the value of the nroConstancia property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setNroConstancia(String value) {
          this.nroConstancia = value;
        }

        /**
         * Gets the value of the refCtaBancoProvision property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getRefCtaBancoProvision() {
          return refCtaBancoProvision;
        }

        /**
         * Sets the value of the refCtaBancoProvision property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setRefCtaBancoProvision(String value) {
          this.refCtaBancoProvision = value;
        }

        /**
         * Gets the value of the refCtaBancoComision property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getRefCtaBancoComision() {
          return refCtaBancoComision;
        }

        /**
         * Sets the value of the refCtaBancoComision property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setRefCtaBancoComision(String value) {
          this.refCtaBancoComision = value;
        }

        /**
         * Gets the value of the lossGain property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getLossGain() {
          return lossGain;
        }

        /**
         * Sets the value of the lossGain property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setLossGain(String value) {
          this.lossGain = value;
        }

        /**
         * Gets the value of the lastCorrelative property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getLastCorrelative() {
          return lastCorrelative;
        }

        /**
         * Sets the value of the lastCorrelative property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setLastCorrelative(String value) {
          this.lastCorrelative = value;
        }

        /**
         * Gets the value of the accounts property.
         * 
         * @return possible object is {@link SSC.Payload.Ledger.Line.Accounts }
         * 
         */
        public SSC.Payload.Ledger.Line.Accounts getAccounts() {
          return accounts;
        }

        /**
         * Sets the value of the accounts property.
         * 
         * @param value
         *          allowed object is {@link SSC.Payload.Ledger.Line.Accounts }
         * 
         */
        public void setAccounts(SSC.Payload.Ledger.Line.Accounts value) {
          this.accounts = value;
        }
        
        

        /**
         * Gets the value of the accounts property.
         * 
         * @return possible object is {@link SSC.Payload.Ledger.Line.Accounts }
         * 
         */
        public SSC.Payload.Ledger.Line.DetailLad getDetailLad() {
          return detailLad;
        }

        /**
         * Sets the value of the accounts property.
         * 
         * @param value
         *          allowed object is {@link SSC.Payload.Ledger.Line.Accounts }
         * 
         */
        public void setDetailLad(SSC.Payload.Ledger.Line.DetailLad value) {
          this.detailLad = value;
        }
        
        
        
        

        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="LookupCode" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "description", "lookupCode", "longDescription" })
        public static class Accounts {

          @XmlElement(name = "Description", required = true)
          protected String description;
          @XmlElement(name = "LookupCode")
          protected String lookupCode;
          @XmlElement(name = "LongDescription", required = true)
          protected String longDescription;

          /**
           * Gets the value of the description property.
           * 
           * @return possible object is {@link String }
           * 
           */
          public String getDescription() {
            return description;
          }

          /**
           * Sets the value of the description property.
           * 
           * @param value
           *          allowed object is {@link String }
           * 
           */
          public void setDescription(String value) {
            this.description = value;
          }

          /**
           * Gets the value of the lookupCode property.
           * 
           */
          public String getLookupCode() {
            return lookupCode;
          }

          /**
           * Sets the value of the lookupCode property.
           * 
           */
          public void setLookupCode(String value) {
            this.lookupCode = value;
          }

          public String getLongDescription() {
            return longDescription;
          }

          public void setLongDescription(String longDescription) {
            this.longDescription = longDescription;
          }

        }
        
        
        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="GeneralDescription1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="GeneralDescription2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="GeneralDescription3" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "generalDescription1", "generalDescription2", "generalDescription3" })
        public static class DetailLad {

          @XmlElement(name = "GeneralDescription1")
          protected String generalDescription1;
          @XmlElement(name = "GeneralDescription2")
          protected String generalDescription2;
          @XmlElement(name = "GeneralDescription3")
          protected String generalDescription3;

          /**
           * Gets the value of the generalDescription1 property.
           * 
           * @return possible object is {@link String }
           * 
           */
          public String getGeneralDescription1() {
            return generalDescription1;
          }

          /**
           * Sets the value of the generalDescription1 property.
           * 
           * @param value
           *          allowed object is {@link String }
           * 
           */
          public void setGeneralDescription1(String value) {
            this.generalDescription1 = value;
          }

          /**
           * Gets the value of the lookupCode property.
           * 
           */
          public String getGeneralDescription2() {
            return generalDescription2;
          }

          /**
           * Sets the value of the lookupCode property.
           * 
           */
          public void setGeneralDescription2(String value) {
            this.generalDescription2 = value;
          }
          
          /**
           * Gets the value of the lookupCode property.
           * 
           */
          public String getGeneralDescription3() {
            return generalDescription3;
          }

          /**
           * Sets the value of the lookupCode property.
           * 
           */
          public void setGeneralDescription3(String value) {
            this.generalDescription3 = value;
          }

        }
        
      }

    }

  }

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="BusinessUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="BudgetCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "businessUnit", "budgetCode" })
  public static class SunSystemsContext {

    @XmlElement(name = "BusinessUnit", required = true)
    protected String businessUnit;
    @XmlElement(name = "BudgetCode", required = true)
    protected String budgetCode;

    /**
     * Gets the value of the businessUnit property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBusinessUnit() {
      return businessUnit;
    }

    /**
     * Sets the value of the businessUnit property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setBusinessUnit(String value) {
      this.businessUnit = value;
    }

    /**
     * Gets the value of the budgetCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBudgetCode() {
      return budgetCode;
    }

    /**
     * Sets the value of the budgetCode property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setBudgetCode(String value) {
      this.budgetCode = value;
    }

  }

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "name" })
  public static class User {

    @XmlElement(name = "Name", required = true)
    protected String name;

    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName() {
      return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setName(String value) {
      this.name = value;
    }

  }

}
