package com.cardif.satelite.suscripcion.dao;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.cardif.satelite.model.satelite.ConciCabTramaDiaria;
import com.cardif.satelite.model.satelite.ConciCabTramaDiariaExample;
import com.cardif.satelite.suscripcion.bean.FormatoObservaciones;
import com.cardif.satelite.util.SateliteConstants;

public interface ConciCabTramaDiariaMapper {
  
  final String SELECT_CAB_BASE_POLIZAS =  "SELECT SEC_ARCHIVO, PRODUCTO, FEC_CARGA, NOMBRE_ARCHIVO, NRO_REGISTROS, FEC_CREACION, USU_CREACION, TIPO_CARGA , RUTA_ARCHIVO ,ESTADO_CONSOLIDADO ,ESTADO "
    		+ " FROM TRAMA_DIARIA  where (producto = NVL(#{producto,jdbcType=NVARCHAR},producto) ) AND FLAG_TRAMA = '"+ SateliteConstants.FLAG_TRAMA_DIARIA +"' order by fec_carga desc ";
   
  final String UPDATE_NRO_REGISTROS = " UPDATE DETALLE_TRAMA_DIARIA set num_registros=#{cantRegistros,jdbcType=NUMERIC} " + "where sec_archivo=#{codSecuencia} AND FLAG_TRAMA = '"+ SateliteConstants.FLAG_TRAMA_DIARIA +"'" ;

  final String UPDATE_SECUENCIA = " UPDATE DETALLE_TRAMA_DIARIA " + "SET SEC_ARCHIVO = #{codSecuencia,jdbcType=NUMERIC} " + "WHERE SEC_ARCHIVO = 999999 AND FLAG_TRAMA = '"+ SateliteConstants.FLAG_TRAMA_DIARIA+"'" ;

  final String SELECT_CORRELATIVO =" SELECT CORRELATIVO FROM TRAMA_DIARIA WHERE SEC_ARCHIVO = (SELECT MAX(SEC_ARCHIVO) FROM TRAMA_DIARIA WHERE PRODUCTO = #{producto}) ";
  
  final String SELECT_Id_TRAMA =" SELECT MAX(SEC_ARCHIVO) FROM TRAMA_DIARIA WHERE ESTADO_CONSOLIDADO = 'PENDIENTE' AND ESTADO =" + SateliteConstants.ESTADO_REGISTRO_INACTIVO +" AND FLAG_TRAMA = #{flag_trama}";
  
  final String SELECT_TRAMA_OBSERVADOS=" SELECT * FROM DETALLE_TRAMA_DIARIA_TEMPORAL ";
  
  final String DELETE_X_ARCHIVO = " DELETE FROM DETALLE_TRAMA_DIARIA WHERE "
  							   +  " SEC_ARCHIVO = (SELECT TD.SEC_ARCHIVO FROM TRAMA_DIARIA TD WHERE TD.ESTADO_CONSOLIDADO IN('procesado','pendiente') "
  							   +  " AND TD.SEC_ARCHIVO =  #{secArchivo,jdbcType=NUMERIC})";
 
  @Select(UPDATE_NRO_REGISTROS)
  @ResultMap(value = "BaseResultMap")
  ConciCabTramaDiaria actualizaRegistros(@Param("codSecuencia") Long codSecuencia, @Param("cantRegistros") Long cantRegistros);

  @Select(SELECT_CAB_BASE_POLIZAS)
  @ResultMap("BaseResultMap")
  List<ConciCabTramaDiaria> listaArchivos(@Param("producto") String producto);

  final String SELECT_MAX_SEC = "select max(sec_archivo) from dbo.CONCI_CAB_TRAMA_DIARIA " + "where producto=#{producto}";

  @Select(SELECT_MAX_SEC)
  Long obtener(@Param("producto") String producto);

  @Update(UPDATE_SECUENCIA)
  int actualizaTramaDiaria(@Param("codSecuencia") Long codSecuencia);
  
  @Select(SELECT_CORRELATIVO)
  public String selectCorrelativo( @Param("producto") String flagTrama);
  
  @Select(SELECT_Id_TRAMA)
  public Long selectIdTrama(@Param("flag_trama") String flagTrama);
  
//  final String SELECT_Id_TRAMA_DIARIA="SELECT #{columms} FROM DETALLE_TRAMA_DIARIA_TEMPORAL";
//  @Select(SELECT_Id_TRAMA_DIARIA)
  List<HashMap<String, Object>> selectTramaTemporal(@Param("columms") String columms);
  
  List<FormatoObservaciones> selectTramaObservaciones();
  
  @Delete(DELETE_X_ARCHIVO) 
  int  deletePorSecuencia(@Param("secArchivo") Long codSecuencia);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_DIARIA
   *
   * @mbggenerated Tue Jul 22 17:31:19 COT 2014
   */
  int countByExample(ConciCabTramaDiariaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_DIARIA
   *
   * @mbggenerated Tue Jul 22 17:31:19 COT 2014
   */
  int deleteByExample(ConciCabTramaDiariaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_DIARIA
   *
   * @mbggenerated Tue Jul 22 17:31:19 COT 2014
   */
  int deleteByPrimaryKey(Long secArchivo);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_DIARIA
   *
   * @mbggenerated Tue Jul 22 17:31:19 COT 2014
   */
  int insert(ConciCabTramaDiaria record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_DIARIA
   *
   * @mbggenerated Tue Jul 22 17:31:19 COT 2014
   */
  int insertSelective(ConciCabTramaDiaria record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_DIARIA
   *
   * @mbggenerated Tue Jul 22 17:31:19 COT 2014
   */
  List<ConciCabTramaDiaria> selectByExample(ConciCabTramaDiariaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_DIARIA
   *
   * @mbggenerated Tue Jul 22 17:31:19 COT 2014
   */
  ConciCabTramaDiaria selectByPrimaryKey(Long secArchivo);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_DIARIA
   *
   * @mbggenerated Tue Jul 22 17:31:19 COT 2014
   */
  int updateByExampleSelective(@Param("record") ConciCabTramaDiaria record, @Param("example") ConciCabTramaDiariaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_DIARIA
   *
   * @mbggenerated Tue Jul 22 17:31:19 COT 2014
   */
  int updateByExample(@Param("record") ConciCabTramaDiaria record, @Param("example") ConciCabTramaDiariaExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_DIARIA
   *
   * @mbggenerated Tue Jul 22 17:31:19 COT 2014
   */
  int updateByPrimaryKeySelective(ConciCabTramaDiaria record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_DIARIA
   *
   * @mbggenerated Tue Jul 22 17:31:19 COT 2014
   */
  int updateByPrimaryKey(ConciCabTramaDiaria record);



}