package com.cardif.satelite.suscripcion.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.mapping.StatementType;

import com.cardif.satelite.model.satelite.ConciReporte;
import com.cardif.satelite.model.satelite.ConciReporteExample;

public interface ConciReporteMapper {

  final String INSERT_REPORTE_CONCILIACION = "INSERT INTO CONCI_REPORTE " + "SELECT DET.LOTE, DET.PLACA, DET.TIP_VEHICULO AS CLASE, " + "UPPER(DET.MARCA) MARCA, DET.NUM_ASIENTOS, "
      + "UPPER(DET.MOD_IMPRESION) MODELO, DET.USO_VEHICULO, " + "DET.PRIMA_BRUTA AS PRIMA, DET.FEC_VENTA, 0 AS TARIF_DEPARTAMENTO, " + "DET.SUB_PRODUCTO, DET.DS_MEDPAG AS MEDIO_PAGO, "
      + "MPS.PRIMA_TECNICA AS PRIMA_TECNICA_MASTER, " + "MPS.PRIMA AS PRIMA_PUBLICA_MASTER, MPS.IGV, MPS.DE, " + "MPS.FND_COMP AS FONDO_COMPENSACION, " + "MPS.COM_COBRANZA AS COMISION_COBRANZA, "
      + "MPS.COM_SOCIO AS COMISION_SOCIO, " + "MPS.FDO_TLMK AS FONDO_TELEMARKETING, " + "MPS.COM_BROKER AS COMISION_BROKER, DET.DONDE_PAGO, " + "CASE " + "WHEN MPS.EXCLUIDO = 1 "
      + "THEN 'VEHICULO EXCLUIDO' " + "WHEN DET.PRIMA_BRUTA <> ISNULL(MPS.PRIMA, 0) " + "THEN 'PRIMA SOCIO DIFERENTE AL MASTER' " + "ELSE 'OK' "
      + "END AS OBSERVACIONES, #{secuencia,jdbcType=NUMERIC} AS SEC_ARCHIVO " + "FROM CONCI_CAB_TRAMA_MENSUAL CAB " + "LEFT JOIN CONCI_TRAMA_MENSUAL DET " + "ON DET.SEC_ARCHIVO = CAB.SEC_ARCHIVO "
      + "LEFT JOIN CONCI_MASTER_PRECIOS_SOAT MPS " + "ON MPS.COD_SOCIO = CAB.SOCIO " + "AND MPS.FEC_VALIDEZ = (SELECT MAX(FEC_VALIDEZ) " + "FROM CONCI_MASTER_PRECIOS_SOAT "
      + "WHERE COD_SOCIO = CAB.SOCIO " + "AND FEC_VALIDEZ < DATEADD(DAY, -1, DATEADD(MONTH, 1, " + "CONVERT(DATETIME, CAST(CAB.PERIODO AS VARCHAR(6)) + '01', 112)))) "
      + "AND MPS.CATEGORIA = UPPER(DET.TIP_VEHICULO) " + "AND MPS.USO = UPPER(DET.USO_VEHICULO) " + "AND MPS.DEPARTAMENTO IN (UPPER(DET.DEPARTAMENTO), '.TODOS') "
      + "AND MPS.MARCA IN (UPPER(DET.MARCA), '.TODOS') " + "AND MPS.MODELO IN (UPPER(DET.MOD_IMPRESION), '.TODOS') " + "AND MPS.CANAL IN (UPPER(DET.CANAL_VENTA), '.TODOS') "
      + "AND MPS.MEDIO_PAGO IN (UPPER(DET.DS_MEDPAG), '.TODOS') " + "WHERE CAB.PERIODO = #{periodo,jdbcType=NUMERIC} " + "AND CAB.PRODUCTO = #{producto,jdbcType=VARCHAR}";

  final String DELETE_BY_SECARCHIVO = "DELETE CONCI_REPORTE " + "WHERE SEC_ARCHIVO = #{secuencia,jdbcType=NUMERIC}";

  final String SELECT_REPORTE_CONCILIACION = "SELECT DET.LOTE, DET.PLACA, DET.CLASE, " + "DET.MARCA, DET.NUM_ASIENTOS, DET.MODELO, " + "DET.USO_VEHICULO, DET.PRIMA, DET.FEC_VENTA, "
      + "DET.TARIF_DEPARTAMENTO, DET.SUB_PRODUCTO, DET.MEDIO_PAGO, " + "DET.PRIMA_TECNICA_MASTER, DET.PRIMA_PUBLICA_MASTER, DET.IGV, " + "DET.DE, DET.FONDO_COMPENSACION, DET.COMISION_COBRANZA, "
      + "DET.COMISION_SOCIO, DET.FONDO_TELEMARKETING, DET.COMISION_BROKER, " + "DET.DONDE_PAGO, DET.OBSERVACIONES " + "FROM CONCI_CAB_REPORTE CAB, CONCI_REPORTE DET "
      + "WHERE DET.SEC_ARCHIVO = CAB.SEC_ARCHIVO " + "AND CAB.PERIODO = #{periodo,jdbcType=NUMERIC} " + "AND CAB.PRODUCTO = #{producto,jdbcType=VARCHAR}";

  // @Insert(INSERT_REPORTE_CONCILIACION)
  // int insertaListaReporte(@Param("periodo") Integer periodo,
  // @Param("producto") String producto, @Param("secuencia") Long secuencia);

  @Insert(value = "{CALL SP_CONCILIACION_SOAT_SECOND(#{periodo, mode=IN, jdbcType=NUMERIC},#{producto, mode=IN, jdbcType=VARCHAR},#{secuencia, mode=IN, jdbcType=NUMERIC})}")
  @Options(statementType = StatementType.CALLABLE)
  int insertaListaReporte(@Param("periodo") Integer periodo, @Param("producto") String producto, @Param("secuencia") Long secuencia);

  @Delete(DELETE_BY_SECARCHIVO)
  int deleteBySecArchivo(@Param("secuencia") Long secuencia);

  @Select(SELECT_REPORTE_CONCILIACION)
  @ResultMap(value = "BaseResultMap")
  List<ConciReporte> listaReporteConciliacion(@Param("periodo") Integer periodo, @Param("producto") String producto);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  int countByExample(ConciReporteExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  int deleteByExample(ConciReporteExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  int deleteByPrimaryKey(Long pk);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  int insert(ConciReporte record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  int insertSelective(ConciReporte record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  List<ConciReporte> selectByExample(ConciReporteExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  ConciReporte selectByPrimaryKey(Long pk);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  int updateByExampleSelective(@Param("record") ConciReporte record, @Param("example") ConciReporteExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  int updateByExample(@Param("record") ConciReporte record, @Param("example") ConciReporteExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  int updateByPrimaryKeySelective(ConciReporte record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_REPORTE
   *
   * @mbggenerated Mon Jul 21 21:23:55 COT 2014
   */
  int updateByPrimaryKey(ConciReporte record);
}