package com.cardif.satelite.suscripcion.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.cardif.satelite.model.satelite.ConciCabTramaMensual;
import com.cardif.satelite.model.satelite.ConciCabTramaMensualExample;
import com.cardif.satelite.util.SateliteConstants;

public interface ConciCabTramaMensualMapper {

  final String SELECT_CONCI_CAB_MENSUAL = "SELECT  SEC_ARCHIVO,  PRODUCTO,  NOMBRE_ARCHIVO, NRO_REGISTROS, FEC_CARGA, TIPO_CARGA, FEC_CREACION, USU_CREACION,  RUTA_ARCHIVO,"
  		+ "  ESTADO_CONSOLIDADO, CORRELATIVO,  ESTADO  FROM TRAMA_DIARIA " + "WHERE PRODUCTO = #{producto,jdbcType=VARCHAR} AND FLAG_TRAMA = '"+ SateliteConstants.FLAG_TRAMA_MENSUAL + "'  ORDER BY FEC_CREACION DESC";

  final String SELECT_MAX_SEC = "SELECT MAX(SEC_ARCHIVO) " + "FROM TRAMA_DIARIA " + "WHERE PRODUCTO = #{producto, jdbcType=VARCHAR} AND FLAG_TRAMA = "+ SateliteConstants.FLAG_TRAMA_MENSUAL;

  final String UPDATE_NRO_REGISTROS = "UPDATE TRAMA_DIARIA " + "SET NUM_REGISTROS = #{cantRegistros,jdbcType=NUMERIC} " + "WHERE SEC_ARCHIVO = #{codSecuencia,jdbcType=NUMERIC} AND FLAG_TRAMA = "+ SateliteConstants.FLAG_TRAMA_MENSUAL;

  final String UPDATE_ESTADO = "UPDATE TRAMA_DIARIA " + "SET ESTADO = 'CONCILIADO' " + "WHERE PERIODO = #{periodo,jdbcType=NUMERIC} " + "AND PRODUCTO = #{producto,jdbcType=VARCHAR} AND FLAG_TRAMA = "+ SateliteConstants.FLAG_TRAMA_MENSUAL;

  final String UPDATE_SECUENCIA = "UPDATE TRAMA_DIARIA " + "SET SEC_ARCHIVO = #{codSecuencia,jdbcType=NUMERIC} " + "WHERE SEC_ARCHIVO = 999999 AND FLAG_TRAMA = "+ SateliteConstants.FLAG_TRAMA_MENSUAL;

  @Select(SELECT_CONCI_CAB_MENSUAL)
  @ResultMap("BaseResultMap")
  List<ConciCabTramaMensual> listaArchivos(@Param("producto") String producto);

  @Select(SELECT_MAX_SEC)
  Long obtener(@Param("producto") String producto);

  @Update(UPDATE_NRO_REGISTROS)
  int actualizaRegistros(@Param("codSecuencia") Long codSecuencia, @Param("cantRegistros") Long cantRegistros);

  @Update(UPDATE_SECUENCIA)
  int actualizaTramaMensual(@Param("codSecuencia") Long codSecuencia);

  @Update(UPDATE_ESTADO)
  int actualizaEstado(@Param("periodo") Integer periodo, @Param("producto") String producto);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_MENSUAL
   *
   * @mbggenerated Mon Jul 21 15:00:28 COT 2014
   */
  int countByExample(ConciCabTramaMensualExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_MENSUAL
   *
   * @mbggenerated Mon Jul 21 15:00:28 COT 2014
   */
  int deleteByExample(ConciCabTramaMensualExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_MENSUAL
   *
   * @mbggenerated Mon Jul 21 15:00:28 COT 2014
   */
  int deleteByPrimaryKey(Long secArchivo);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_MENSUAL
   *
   * @mbggenerated Mon Jul 21 15:00:28 COT 2014
   */
  int insert(ConciCabTramaMensual record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_MENSUAL
   *
   * @mbggenerated Mon Jul 21 15:00:28 COT 2014
   */
  int insertSelective(ConciCabTramaMensual record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_MENSUAL
   *
   * @mbggenerated Mon Jul 21 15:00:28 COT 2014
   */
  List<ConciCabTramaMensual> selectByExample(ConciCabTramaMensualExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_MENSUAL
   *
   * @mbggenerated Mon Jul 21 15:00:28 COT 2014
   */
  ConciCabTramaMensual selectByPrimaryKey(Long secArchivo);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_MENSUAL
   *
   * @mbggenerated Mon Jul 21 15:00:28 COT 2014
   */
  int updateByExampleSelective(@Param("record") ConciCabTramaMensual record, @Param("example") ConciCabTramaMensualExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_MENSUAL
   *
   * @mbggenerated Mon Jul 21 15:00:28 COT 2014
   */
  int updateByExample(@Param("record") ConciCabTramaMensual record, @Param("example") ConciCabTramaMensualExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_MENSUAL
   *
   * @mbggenerated Mon Jul 21 15:00:28 COT 2014
   */
  int updateByPrimaryKeySelective(ConciCabTramaMensual record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CONCI_CAB_TRAMA_MENSUAL
   *
   * @mbggenerated Mon Jul 21 15:00:28 COT 2014
   */
  int updateByPrimaryKey(ConciCabTramaMensual record);
}