package com.cardif.satelite.suscripcion.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.cardif.satelite.model.MigRegVentas;
import com.cardif.satelite.model.MigRegVentasExample;

public interface MigRegVentasMapper {

  final String SELECT_PERIODO = "select count(*) " + "from mig_reg_ventas " + "where periodo = #{periodo}";

  @Select(SELECT_PERIODO)
  int verificarPeriodo(@Param("periodo") int periodo);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MIG_REG_VENTAS
   *
   * @mbggenerated Thu Aug 08 17:31:07 COT 2013
   */
  int countByExample(MigRegVentasExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MIG_REG_VENTAS
   *
   * @mbggenerated Thu Aug 08 17:31:07 COT 2013
   */
  int deleteByExample(MigRegVentasExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MIG_REG_VENTAS
   *
   * @mbggenerated Thu Aug 08 17:31:07 COT 2013
   */
  int deleteByPrimaryKey(Long pk);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MIG_REG_VENTAS
   *
   * @mbggenerated Thu Aug 08 17:31:07 COT 2013
   */
  int insert(MigRegVentas record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MIG_REG_VENTAS
   *
   * @mbggenerated Thu Aug 08 17:31:07 COT 2013
   */
  int insertSelective(MigRegVentas record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MIG_REG_VENTAS
   *
   * @mbggenerated Thu Aug 08 17:31:07 COT 2013
   */
  List<MigRegVentas> selectByExample(MigRegVentasExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MIG_REG_VENTAS
   *
   * @mbggenerated Thu Aug 08 17:31:07 COT 2013
   */
  MigRegVentas selectByPrimaryKey(Long pk);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MIG_REG_VENTAS
   *
   * @mbggenerated Thu Aug 08 17:31:07 COT 2013
   */
  int updateByExampleSelective(@Param("record") MigRegVentas record, @Param("example") MigRegVentasExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MIG_REG_VENTAS
   *
   * @mbggenerated Thu Aug 08 17:31:07 COT 2013
   */
  int updateByExample(@Param("record") MigRegVentas record, @Param("example") MigRegVentasExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MIG_REG_VENTAS
   *
   * @mbggenerated Thu Aug 08 17:31:07 COT 2013
   */
  int updateByPrimaryKeySelective(MigRegVentas record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.MIG_REG_VENTAS
   *
   * @mbggenerated Thu Aug 08 17:31:07 COT 2013
   */
  int updateByPrimaryKey(MigRegVentas record);
}