package com.cardif.satelite.suscripcion.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import com.cardif.satelite.model.Socio;
	

public interface SocioTramaMapper {

  final String LISTAR_SOCIOS = "SELECT ID,  RUC_SOCIO,  NOMBRE_SOCIO,  ABREVIATURA,  FECHA_CONTRATO,  GRUPO_COMERCIO,  ESTADO FROM SOCIO ";
  final String LISTAR_SOCIOS_BY_RUC_RAZONSOCIAL = " SELECT ID,  RUC_SOCIO,  NOMBRE_SOCIO,  ABREVIATURA, TO_CHAR(FECHA_CONTRATO, 'dd/MM/yyyy') FECHA_CONTRATO, GRUPO_COMERCIO, ESTADO FROM SOCIO "
					           + " WHERE  (RUC_SOCIO LIKE '%' || #{ruc,jdbcType=VARCHAR} || '%') AND (UPPER(NOMBRE_SOCIO) LIKE UPPER('%' || #{razonSocial,jdbcType=VARCHAR} || '%')) ORDER BY ID DESC";
  //Query botòn Buscar 					
  final String LISTAR_SOCIOS_BY_RUC_RAZONSOCIAL_all ="SELECT ID,  RUC_SOCIO,  NOMBRE_SOCIO,  ABREVIATURA,  FECHA_CONTRATO, GRUPO_COMERCIO, ESTADO FROM SOCIO ORDER BY NOMBRE_SOCIO ASC";
  @Select(LISTAR_SOCIOS)
  @ResultMap(value = "BaseResultMap")
  List<Socio> listaSocios();
  
  final String LISTAR_SOCIOS_BY_RUC = " SELECT RUC_SOCIO FROM SOCIO "
          + " WHERE  (RUC_SOCIO LIKE '%' || #{ruc,jdbcType=VARCHAR} || '%') AND ROWNUM <= 1";
  
  @Select(LISTAR_SOCIOS_BY_RUC_RAZONSOCIAL)
  @ResultMap(value = "BaseResultMap")
  List<Socio> listaSocioByRucRazonSocial(@Param("ruc") String ruc, @Param("razonSocial") String razonSocial );
  
  @Select(LISTAR_SOCIOS_BY_RUC_RAZONSOCIAL_all)
  @ResultMap(value = "BaseResultMap")
  List<Socio> listaSocioByRucRazonSocialAll();
  
  
  @Select(LISTAR_SOCIOS_BY_RUC)
  @ResultMap(value = "BaseResultMap")
  public Socio listaSocioByRuc(@Param("ruc") String ruc);
  
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_VENTAS_SUCURSAL.SOCIO
   *
   * @mbggenerated Fri Sep 05 15:00:58 COT 2014
   */
//  int countByExample(SocioExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_VENTAS_SUCURSAL.SOCIO
   *
   * @mbggenerated Fri Sep 05 15:00:58 COT 2014
   */
//  int deleteByExample(SocioExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_VENTAS_SUCURSAL.SOCIO
   *
   * @mbggenerated Fri Sep 05 15:00:58 COT 2014
   */
  int deleteByPrimaryKey(String codSocio);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_VENTAS_SUCURSAL.SOCIO
   *
   * @mbggenerated Fri Sep 05 15:00:58 COT 2014
   */
  int insert(Socio record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_VENTAS_SUCURSAL.SOCIO
   *
   * @mbggenerated Fri Sep 05 15:00:58 COT 2014
   */
  int insertSelective(Socio record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_VENTAS_SUCURSAL.SOCIO
   *
   * @mbggenerated Fri Sep 05 15:00:58 COT 2014
   */
//  List<Socio> selectByExample(SocioExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_VENTAS_SUCURSAL.SOCIO
   *
   * @mbggenerated Fri Sep 05 15:00:58 COT 2014
   */
  Socio selectByPrimaryKey(String codSocio);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_VENTAS_SUCURSAL.SOCIO
   *
   * @mbggenerated Fri Sep 05 15:00:58 COT 2014
   */
//  int updateByExampleSelective(@Param("record") Socio record, @Param("example") SocioExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_VENTAS_SUCURSAL.SOCIO
   *
   * @mbggenerated Fri Sep 05 15:00:58 COT 2014
   */
//  int updateByExample(@Param("record") Socio record, @Param("example") SocioExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_VENTAS_SUCURSAL.SOCIO
   *
   * @mbggenerated Fri Sep 05 15:00:58 COT 2014
   */
  int updateByPrimaryKeySelective(Socio record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_VENTAS_SUCURSAL.SOCIO
   *
   * @mbggenerated Fri Sep 05 15:00:58 COT 2014
   */
  int updateByPrimaryKey(Socio record);
}