package com.cardif.satelite.suscripcion.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import com.cardif.satelite.model.SusTramaInterbank;
import com.cardif.satelite.model.SusTramaInterbankExample;
import com.cardif.satelite.model.SusTramaInterbankKey;

public interface SusTramaInterbankMapper {
  final String LISTA_DOCUMENTO = "SELECT * FROM dbo.SUS_TRAMA_INTERBANK";

  @Select(LISTA_DOCUMENTO)
  @ResultMap(value = "BaseResultMap")
  List<SusTramaInterbank> listar();

  final String COD_TRAMA = "SELECT * FROM dbo.SUS_TRAMA_INTERBANK" + " WHERE COD_TRAMA=#{periodo} ";

  @Select(COD_TRAMA)
  @ResultMap(value = "BaseResultMap")
  List<SusTramaInterbank> listarPorPK(@Param("periodo") long periodo);

  final String LISTARENVIADOS = "SELECT * FROM SUS_TRAMA_INTERBANK WHERE COD_TRAMA = #{codTrama}";

  @Select(LISTARENVIADOS)
  @ResultMap(value = "BaseResultMap")
  List<SusTramaInterbank> listaReporteAnul(@Param("codTrama") Long codTrama);

  final String ACTUALIZARREGISTROSMULTIMES = " UPDATE dbo.SUS_TRAMA_INTERBANK SET  ESTADO_DOCUMENTO='CON DEVOLUCION' WHERE  COD_TRAMA=#{cod_trama} AND NRO_CERTIFICADO==#{nro_certificado} ";

  @Select(ACTUALIZARREGISTROSMULTIMES)
  @ResultMap(value = "BaseResultMap")
  SusTramaInterbank actualizarRegistrosMultiMes(@Param("cod_trama") long periodo, @Param("nro_certificado") String nro_certificado);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  int countByExample(SusTramaInterbankExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  int deleteByExample(SusTramaInterbankExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  int deleteByPrimaryKey(SusTramaInterbankKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  int insert(SusTramaInterbank record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  int insertSelective(SusTramaInterbank record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  List<SusTramaInterbank> selectByExample(SusTramaInterbankExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  SusTramaInterbank selectByPrimaryKey(SusTramaInterbankKey key);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  int updateByExampleSelective(@Param("record") SusTramaInterbank record, @Param("example") SusTramaInterbankExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  int updateByExample(@Param("record") SusTramaInterbank record, @Param("example") SusTramaInterbankExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  int updateByPrimaryKeySelective(SusTramaInterbank record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SUS_TRAMA_INTERBANK
   *
   * @mbggenerated Mon Jun 23 12:11:49 COT 2014
   */
  int updateByPrimaryKey(SusTramaInterbank record);
}