package com.cardif.satelite.telemarketing.dao;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import com.cardif.satelite.model.datamart.OdsPolizaHm;
import com.cardif.satelite.model.datamart.OdsPolizaHmExample;

/**
 * @class ConsultaTelemarketingService
 * @usuario jhurtado
 * @fecha_creacion 31-01-2014
 * @ticket T022163
 * @descripcion: Obtener codigo de producto
 * 
 */
public interface OdsPolizaHmMapper {

  // final String SELECT_COD_PRODUCTO =
  // "SELECT COD_PRODUCTO FROM ODS_POLIZA_HM WHERE COD_SOCIO = #{codSocio} AND ROWNUM < 2";
  final String SELECT_COD_PRODUCTO = "SELECT DISTINCT COD_PRODUCTO FROM ODS_POLIZA_HM WHERE COD_SOCIO = #{codSocio}";

  @Select(SELECT_COD_PRODUCTO)
  @ResultMap(value = "BaseResultMap")
  List<OdsPolizaHm> selectCodProducto(@Param("codSocio") BigDecimal codSocio);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_DM_ODS.ODS_POLIZA_HM
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  int countByExample(OdsPolizaHmExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_DM_ODS.ODS_POLIZA_HM
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  int deleteByExample(OdsPolizaHmExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_DM_ODS.ODS_POLIZA_HM
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  int insert(OdsPolizaHm record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_DM_ODS.ODS_POLIZA_HM
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  int insertSelective(OdsPolizaHm record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_DM_ODS.ODS_POLIZA_HM
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  List<OdsPolizaHm> selectByExample(OdsPolizaHmExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_DM_ODS.ODS_POLIZA_HM
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  int updateByExampleSelective(@Param("record") OdsPolizaHm record, @Param("example") OdsPolizaHmExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table USER_DM_ODS.ODS_POLIZA_HM
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  int updateByExample(@Param("record") OdsPolizaHm record, @Param("example") OdsPolizaHmExample example);
}