package com.cardif.satelite.telemarketing.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import com.cardif.satelite.model.TlmkBaseRP;
import com.cardif.satelite.model.TlmkBaseRPExample;

public interface TlmkBaseRPMapper {

  final String SELECT_MAX_COD_BASE_RP = "SELECT MAX(COD_BASE) FROM TLMK_BASE_RP";

  final String SELECT_COD_BASE = "SELECT * FROM TLMK_BASE_RP WHERE COD_BASE = #{codBase}" + " AND ESTADO = #{estado}";

  final String SELECT_CLIENTES_PROCESADOS = "SELECT COUNT(*) FROM TLMK_BASE_RP " + "WHERE ESTADO = #{estado} AND COD_BASE = #{codBase}";

  @Select(SELECT_MAX_COD_BASE_RP)
  int selectMaxCodBaseRP();

  @Select(SELECT_COD_BASE)
  @ResultMap("BaseResultMap")
  List<TlmkBaseRP> selectBase(@Param("codBase") Long codBase, @Param("estado") String estado);

  @Select(SELECT_CLIENTES_PROCESADOS)
  int selectClientesProcesados(@Param("codBase") Long codBase, @Param("estado") String estado);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  int countByExample(TlmkBaseRPExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  int deleteByExample(TlmkBaseRPExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  int deleteByPrimaryKey(Long pk);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  int insert(TlmkBaseRP record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  int insertSelective(TlmkBaseRP record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  List<TlmkBaseRP> selectByExample(TlmkBaseRPExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  TlmkBaseRP selectByPrimaryKey(Long pk);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  int updateByExampleSelective(@Param("record") TlmkBaseRP record, @Param("example") TlmkBaseRPExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  int updateByExample(@Param("record") TlmkBaseRP record, @Param("example") TlmkBaseRPExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  int updateByPrimaryKeySelective(TlmkBaseRP record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_RP
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  int updateByPrimaryKey(TlmkBaseRP record);
}
