package com.cardif.satelite.telemarketing.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import com.cardif.satelite.model.TlmkLayoutSocioCardif;
import com.cardif.satelite.model.TlmkLayoutSocioCardifExample;

public interface TlmkLayoutSocioCardifMapper {

  final String LISTAR_LAYOUT_CARDIF = "SELECT * FROM TLMK_LAYOUT_SOCIO_CARDIF " + "WHERE COD_SOCIO = #{codSocio} ORDER BY NUM_SECU";

  @Select(LISTAR_LAYOUT_CARDIF)
  @ResultMap("BaseResultMap")
  List<TlmkLayoutSocioCardif> selectLayout(@Param("codSocio") String codSocio);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_LAYOUT_SOCIO_CARDIF
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  int countByExample(TlmkLayoutSocioCardifExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_LAYOUT_SOCIO_CARDIF
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  int deleteByExample(TlmkLayoutSocioCardifExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_LAYOUT_SOCIO_CARDIF
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  int insert(TlmkLayoutSocioCardif record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_LAYOUT_SOCIO_CARDIF
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  int insertSelective(TlmkLayoutSocioCardif record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_LAYOUT_SOCIO_CARDIF
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  List<TlmkLayoutSocioCardif> selectByExample(TlmkLayoutSocioCardifExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_LAYOUT_SOCIO_CARDIF
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  int updateByExampleSelective(@Param("record") TlmkLayoutSocioCardif record, @Param("example") TlmkLayoutSocioCardifExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_LAYOUT_SOCIO_CARDIF
   *
   * @mbggenerated Wed Jan 22 12:45:18 COT 2014
   */
  int updateByExample(@Param("record") TlmkLayoutSocioCardif record, @Param("example") TlmkLayoutSocioCardifExample example);
}