package com.cardif.satelite.telemarketing.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.cardif.satelite.model.Layout;
import com.cardif.satelite.model.TlmkBaseCabecera;
import com.cardif.satelite.model.TlmkBaseCabeceraExample;

public interface TlmkBaseCabeceraMapper {
  final String SELECT_MAX_COD_BASE = "SELECT MAX(COD_BASE) FROM TLMK_BASE_CABECERA WHERE COD_SOCIO = #{codSocio}";

  final String SELECT_ESTADO = "SELECT ESTADO FROM TLMK_BASE_CABECERA WHERE COD_BASE = #{codBase}";

  final String UPDATE_COLUMNAS = "UPDATE DETALLE_TRAMA_LAYOUT  SET COLUMNA_TABLA = #{columnaTabla} WHERE COLUMNA_EXCEL = #{columnaExcel}  AND ID_PRODUCTO =  #{idcanal}  ";
  
  @Select(SELECT_MAX_COD_BASE)
  int selectMaxCodBase(@Param("codSocio") String codSocio);

  @Select(SELECT_ESTADO)
  String selectEstado(@Param("codBase") Long codBase);

  final String SELECT_SOCIO = "SELECT * FROM TLMK_BASE_CABECERA WHERE COD_SOCIO = #{codSocio}";

  @Select(SELECT_SOCIO)
  @ResultMap(value = "BaseResultMap")
  List<TlmkBaseCabecera> selectSocio(@Param("codSocio") String codSocio);

  @Update(UPDATE_COLUMNAS)
  void UpdateByLayoutNombreColumna(Layout layout);
  
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  int countByExample(TlmkBaseCabeceraExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  int deleteByExample(TlmkBaseCabeceraExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  int deleteByPrimaryKey(Long codBase);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  int insert(TlmkBaseCabecera record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  int insertSelective(TlmkBaseCabecera record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  List<TlmkBaseCabecera> selectByExample(TlmkBaseCabeceraExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  TlmkBaseCabecera selectByPrimaryKey(Long codBase);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  int updateByExampleSelective(@Param("record") TlmkBaseCabecera record, @Param("example") TlmkBaseCabeceraExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  int updateByExample(@Param("record") TlmkBaseCabecera record, @Param("example") TlmkBaseCabeceraExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  int updateByPrimaryKeySelective(TlmkBaseCabecera record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.TLMK_BASE_CABECERA
   *
   * @mbggenerated Thu May 29 11:16:51 COT 2014
   */
  int updateByPrimaryKey(TlmkBaseCabecera record);


}