package com.cardif.satelite.siniestro.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import com.cardif.satelite.model.SiniDesgravamen;
import com.cardif.satelite.model.SiniDesgravamenExample;

public interface SiniDesgravamenMapper {

  final String LISTA_SINI_DESGRAVAMEN = "SELECT * FROM dbo.SINI_DESGRAVAMEN" + " WHERE NRO_SINIESTRO=#{nroSiniestro} ";

  @Select(LISTA_SINI_DESGRAVAMEN)
  @ResultMap(value = "BaseResultMap")
  SiniDesgravamen listar(@Param("nroSiniestro") String nroSiniestro);

  final String LISTA_SINI_DESGRAVAMEN_TODOS = "SELECT * FROM dbo.SINI_DESGRAVAMEN";

  @Select(LISTA_SINI_DESGRAVAMEN_TODOS)
  @ResultMap(value = "BaseResultMap")
  List<SiniDesgravamen> listarT();

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_DESGRAVAMEN
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  int countByExample(SiniDesgravamenExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_DESGRAVAMEN
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  int deleteByExample(SiniDesgravamenExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_DESGRAVAMEN
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  int deleteByPrimaryKey(String nroSiniestro);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_DESGRAVAMEN
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  int insert(SiniDesgravamen record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_DESGRAVAMEN
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  int insertSelective(SiniDesgravamen record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_DESGRAVAMEN
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  List<SiniDesgravamen> selectByExample(SiniDesgravamenExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_DESGRAVAMEN
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  SiniDesgravamen selectByPrimaryKey(String nroSiniestro);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_DESGRAVAMEN
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  int updateByExampleSelective(@Param("record") SiniDesgravamen record, @Param("example") SiniDesgravamenExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_DESGRAVAMEN
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  int updateByExample(@Param("record") SiniDesgravamen record, @Param("example") SiniDesgravamenExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_DESGRAVAMEN
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  int updateByPrimaryKeySelective(SiniDesgravamen record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_DESGRAVAMEN
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  int updateByPrimaryKey(SiniDesgravamen record);

  int selectBinTarjeta(String subStringNumeroTarjeta);

}