package com.cardif.satelite.siniestro.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import com.cardif.satelite.model.SiniRentaHosp;
import com.cardif.satelite.model.SiniRentaHospExample;

public interface SiniRentaHospMapper {

  final String LISTA_SINI_RENTA_HOSP = "SELECT * FROM dbo.SINI_RENTA_HOSP" + " WHERE NRO_SINIESTRO=#{nroSiniestro} ";

  @Select(LISTA_SINI_RENTA_HOSP)
  @ResultMap(value = "BaseResultMap")
  SiniRentaHosp listar(@Param("nroSiniestro") String nroSiniestro);

  final String LISTA_SINI_RENTA_HOSP_TODOS = "SELECT * FROM dbo.SINI_RENTA_HOSP";

  @Select(LISTA_SINI_RENTA_HOSP_TODOS)
  @ResultMap(value = "BaseResultMap")
  List<SiniRentaHosp> listarT();

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_RENTA_HOSP
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  int countByExample(SiniRentaHospExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_RENTA_HOSP
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  int deleteByExample(SiniRentaHospExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_RENTA_HOSP
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  int deleteByPrimaryKey(String nroSiniestro);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_RENTA_HOSP
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  int insert(SiniRentaHosp record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_RENTA_HOSP
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  int insertSelective(SiniRentaHosp record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_RENTA_HOSP
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  List<SiniRentaHosp> selectByExample(SiniRentaHospExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_RENTA_HOSP
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  SiniRentaHosp selectByPrimaryKey(String nroSiniestro);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_RENTA_HOSP
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  int updateByExampleSelective(@Param("record") SiniRentaHosp record, @Param("example") SiniRentaHospExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_RENTA_HOSP
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  int updateByExample(@Param("record") SiniRentaHosp record, @Param("example") SiniRentaHospExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_RENTA_HOSP
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  int updateByPrimaryKeySelective(SiniRentaHosp record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.SINI_RENTA_HOSP
   *
   * @mbggenerated Mon Jul 21 17:21:12 COT 2014
   */
  int updateByPrimaryKey(SiniRentaHosp record);
}