package com.cardif.satelite.model.soat;

import java.io.Serializable;

public class Provincia implements Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column USER_SOAT.PROVINCIA.COD_PROVINCIA
   *
   * @mbggenerated Tue Nov 05 11:46:17 COT 2013
   */
  private String codProvincia;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column USER_SOAT.PROVINCIA.NOMBRE_PROVINCIA
   *
   * @mbggenerated Tue Nov 05 11:46:17 COT 2013
   */
  private String nombreProvincia;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column USER_SOAT.PROVINCIA.VERSION
   *
   * @mbggenerated Tue Nov 05 11:46:17 COT 2013
   */
  private Long version;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column USER_SOAT.PROVINCIA.DEPARTAMENTO
   *
   * @mbggenerated Tue Nov 05 11:46:17 COT 2013
   */
  private String departamento;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column USER_SOAT.PROVINCIA.COD_PROVINCIA
   *
   * @return the value of USER_SOAT.PROVINCIA.COD_PROVINCIA
   *
   * @mbggenerated Tue Nov 05 11:46:17 COT 2013
   */
  public String getCodProvincia() {
    return codProvincia;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column USER_SOAT.PROVINCIA.COD_PROVINCIA
   *
   * @param codProvincia
   *          the value for USER_SOAT.PROVINCIA.COD_PROVINCIA
   *
   * @mbggenerated Tue Nov 05 11:46:17 COT 2013
   */
  public void setCodProvincia(String codProvincia) {
    this.codProvincia = codProvincia == null ? null : codProvincia.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column USER_SOAT.PROVINCIA.NOMBRE_PROVINCIA
   *
   * @return the value of USER_SOAT.PROVINCIA.NOMBRE_PROVINCIA
   *
   * @mbggenerated Tue Nov 05 11:46:17 COT 2013
   */
  public String getNombreProvincia() {
    return nombreProvincia;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column USER_SOAT.PROVINCIA.NOMBRE_PROVINCIA
   *
   * @param nombreProvincia
   *          the value for USER_SOAT.PROVINCIA.NOMBRE_PROVINCIA
   *
   * @mbggenerated Tue Nov 05 11:46:17 COT 2013
   */
  public void setNombreProvincia(String nombreProvincia) {
    this.nombreProvincia = nombreProvincia == null ? null : nombreProvincia.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column USER_SOAT.PROVINCIA.VERSION
   *
   * @return the value of USER_SOAT.PROVINCIA.VERSION
   *
   * @mbggenerated Tue Nov 05 11:46:17 COT 2013
   */
  public Long getVersion() {
    return version;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column USER_SOAT.PROVINCIA.VERSION
   *
   * @param version
   *          the value for USER_SOAT.PROVINCIA.VERSION
   *
   * @mbggenerated Tue Nov 05 11:46:17 COT 2013
   */
  public void setVersion(Long version) {
    this.version = version;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column USER_SOAT.PROVINCIA.DEPARTAMENTO
   *
   * @return the value of USER_SOAT.PROVINCIA.DEPARTAMENTO
   *
   * @mbggenerated Tue Nov 05 11:46:17 COT 2013
   */
  public String getDepartamento() {
    return departamento;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column USER_SOAT.PROVINCIA.DEPARTAMENTO
   *
   * @param departamento
   *          the value for USER_SOAT.PROVINCIA.DEPARTAMENTO
   *
   * @mbggenerated Tue Nov 05 11:46:17 COT 2013
   */
  public void setDepartamento(String departamento) {
    this.departamento = departamento == null ? null : departamento.trim();
  }
}