package com.cardif.satelite.model.acsele;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class OpenItemReferenceExample implements Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table BRAXTS_CFG.OPENITEMREFERENCE
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table BRAXTS_CFG.OPENITEMREFERENCE
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table BRAXTS_CFG.OPENITEMREFERENCE
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEMREFERENCE
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  public OpenItemReferenceExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEMREFERENCE
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEMREFERENCE
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEMREFERENCE
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEMREFERENCE
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEMREFERENCE
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEMREFERENCE
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEMREFERENCE
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEMREFERENCE
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEMREFERENCE
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEMREFERENCE
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table BRAXTS_CFG.OPENITEMREFERENCE
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andOpenitemreferenceidIsNull() {
      addCriterion("OPENITEMREFERENCEID is null");
      return (Criteria) this;
    }

    public Criteria andOpenitemreferenceidIsNotNull() {
      addCriterion("OPENITEMREFERENCEID is not null");
      return (Criteria) this;
    }

    public Criteria andOpenitemreferenceidEqualTo(BigDecimal value) {
      addCriterion("OPENITEMREFERENCEID =", value, "openitemreferenceid");
      return (Criteria) this;
    }

    public Criteria andOpenitemreferenceidNotEqualTo(BigDecimal value) {
      addCriterion("OPENITEMREFERENCEID <>", value, "openitemreferenceid");
      return (Criteria) this;
    }

    public Criteria andOpenitemreferenceidGreaterThan(BigDecimal value) {
      addCriterion("OPENITEMREFERENCEID >", value, "openitemreferenceid");
      return (Criteria) this;
    }

    public Criteria andOpenitemreferenceidGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("OPENITEMREFERENCEID >=", value, "openitemreferenceid");
      return (Criteria) this;
    }

    public Criteria andOpenitemreferenceidLessThan(BigDecimal value) {
      addCriterion("OPENITEMREFERENCEID <", value, "openitemreferenceid");
      return (Criteria) this;
    }

    public Criteria andOpenitemreferenceidLessThanOrEqualTo(BigDecimal value) {
      addCriterion("OPENITEMREFERENCEID <=", value, "openitemreferenceid");
      return (Criteria) this;
    }

    public Criteria andOpenitemreferenceidIn(List<BigDecimal> values) {
      addCriterion("OPENITEMREFERENCEID in", values, "openitemreferenceid");
      return (Criteria) this;
    }

    public Criteria andOpenitemreferenceidNotIn(List<BigDecimal> values) {
      addCriterion("OPENITEMREFERENCEID not in", values, "openitemreferenceid");
      return (Criteria) this;
    }

    public Criteria andOpenitemreferenceidBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("OPENITEMREFERENCEID between", value1, value2, "openitemreferenceid");
      return (Criteria) this;
    }

    public Criteria andOpenitemreferenceidNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("OPENITEMREFERENCEID not between", value1, value2, "openitemreferenceid");
      return (Criteria) this;
    }

    public Criteria andOpenitemidIsNull() {
      addCriterion("OPENITEMID is null");
      return (Criteria) this;
    }

    public Criteria andOpenitemidIsNotNull() {
      addCriterion("OPENITEMID is not null");
      return (Criteria) this;
    }

    public Criteria andOpenitemidEqualTo(BigDecimal value) {
      addCriterion("OPENITEMID =", value, "openitemid");
      return (Criteria) this;
    }

    public Criteria andOpenitemidNotEqualTo(BigDecimal value) {
      addCriterion("OPENITEMID <>", value, "openitemid");
      return (Criteria) this;
    }

    public Criteria andOpenitemidGreaterThan(BigDecimal value) {
      addCriterion("OPENITEMID >", value, "openitemid");
      return (Criteria) this;
    }

    public Criteria andOpenitemidGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("OPENITEMID >=", value, "openitemid");
      return (Criteria) this;
    }

    public Criteria andOpenitemidLessThan(BigDecimal value) {
      addCriterion("OPENITEMID <", value, "openitemid");
      return (Criteria) this;
    }

    public Criteria andOpenitemidLessThanOrEqualTo(BigDecimal value) {
      addCriterion("OPENITEMID <=", value, "openitemid");
      return (Criteria) this;
    }

    public Criteria andOpenitemidIn(List<BigDecimal> values) {
      addCriterion("OPENITEMID in", values, "openitemid");
      return (Criteria) this;
    }

    public Criteria andOpenitemidNotIn(List<BigDecimal> values) {
      addCriterion("OPENITEMID not in", values, "openitemid");
      return (Criteria) this;
    }

    public Criteria andOpenitemidBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("OPENITEMID between", value1, value2, "openitemid");
      return (Criteria) this;
    }

    public Criteria andOpenitemidNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("OPENITEMID not between", value1, value2, "openitemid");
      return (Criteria) this;
    }

    public Criteria andPolicyidIsNull() {
      addCriterion("POLICYID is null");
      return (Criteria) this;
    }

    public Criteria andPolicyidIsNotNull() {
      addCriterion("POLICYID is not null");
      return (Criteria) this;
    }

    public Criteria andPolicyidEqualTo(BigDecimal value) {
      addCriterion("POLICYID =", value, "policyid");
      return (Criteria) this;
    }

    public Criteria andPolicyidNotEqualTo(BigDecimal value) {
      addCriterion("POLICYID <>", value, "policyid");
      return (Criteria) this;
    }

    public Criteria andPolicyidGreaterThan(BigDecimal value) {
      addCriterion("POLICYID >", value, "policyid");
      return (Criteria) this;
    }

    public Criteria andPolicyidGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("POLICYID >=", value, "policyid");
      return (Criteria) this;
    }

    public Criteria andPolicyidLessThan(BigDecimal value) {
      addCriterion("POLICYID <", value, "policyid");
      return (Criteria) this;
    }

    public Criteria andPolicyidLessThanOrEqualTo(BigDecimal value) {
      addCriterion("POLICYID <=", value, "policyid");
      return (Criteria) this;
    }

    public Criteria andPolicyidIn(List<BigDecimal> values) {
      addCriterion("POLICYID in", values, "policyid");
      return (Criteria) this;
    }

    public Criteria andPolicyidNotIn(List<BigDecimal> values) {
      addCriterion("POLICYID not in", values, "policyid");
      return (Criteria) this;
    }

    public Criteria andPolicyidBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("POLICYID between", value1, value2, "policyid");
      return (Criteria) this;
    }

    public Criteria andPolicyidNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("POLICYID not between", value1, value2, "policyid");
      return (Criteria) this;
    }

    public Criteria andRiskunitidIsNull() {
      addCriterion("RISKUNITID is null");
      return (Criteria) this;
    }

    public Criteria andRiskunitidIsNotNull() {
      addCriterion("RISKUNITID is not null");
      return (Criteria) this;
    }

    public Criteria andRiskunitidEqualTo(BigDecimal value) {
      addCriterion("RISKUNITID =", value, "riskunitid");
      return (Criteria) this;
    }

    public Criteria andRiskunitidNotEqualTo(BigDecimal value) {
      addCriterion("RISKUNITID <>", value, "riskunitid");
      return (Criteria) this;
    }

    public Criteria andRiskunitidGreaterThan(BigDecimal value) {
      addCriterion("RISKUNITID >", value, "riskunitid");
      return (Criteria) this;
    }

    public Criteria andRiskunitidGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("RISKUNITID >=", value, "riskunitid");
      return (Criteria) this;
    }

    public Criteria andRiskunitidLessThan(BigDecimal value) {
      addCriterion("RISKUNITID <", value, "riskunitid");
      return (Criteria) this;
    }

    public Criteria andRiskunitidLessThanOrEqualTo(BigDecimal value) {
      addCriterion("RISKUNITID <=", value, "riskunitid");
      return (Criteria) this;
    }

    public Criteria andRiskunitidIn(List<BigDecimal> values) {
      addCriterion("RISKUNITID in", values, "riskunitid");
      return (Criteria) this;
    }

    public Criteria andRiskunitidNotIn(List<BigDecimal> values) {
      addCriterion("RISKUNITID not in", values, "riskunitid");
      return (Criteria) this;
    }

    public Criteria andRiskunitidBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("RISKUNITID between", value1, value2, "riskunitid");
      return (Criteria) this;
    }

    public Criteria andRiskunitidNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("RISKUNITID not between", value1, value2, "riskunitid");
      return (Criteria) this;
    }

    public Criteria andReferenceIsNull() {
      addCriterion("REFERENCE is null");
      return (Criteria) this;
    }

    public Criteria andReferenceIsNotNull() {
      addCriterion("REFERENCE is not null");
      return (Criteria) this;
    }

    public Criteria andReferenceEqualTo(BigDecimal value) {
      addCriterion("REFERENCE =", value, "reference");
      return (Criteria) this;
    }

    public Criteria andReferenceNotEqualTo(BigDecimal value) {
      addCriterion("REFERENCE <>", value, "reference");
      return (Criteria) this;
    }

    public Criteria andReferenceGreaterThan(BigDecimal value) {
      addCriterion("REFERENCE >", value, "reference");
      return (Criteria) this;
    }

    public Criteria andReferenceGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("REFERENCE >=", value, "reference");
      return (Criteria) this;
    }

    public Criteria andReferenceLessThan(BigDecimal value) {
      addCriterion("REFERENCE <", value, "reference");
      return (Criteria) this;
    }

    public Criteria andReferenceLessThanOrEqualTo(BigDecimal value) {
      addCriterion("REFERENCE <=", value, "reference");
      return (Criteria) this;
    }

    public Criteria andReferenceIn(List<BigDecimal> values) {
      addCriterion("REFERENCE in", values, "reference");
      return (Criteria) this;
    }

    public Criteria andReferenceNotIn(List<BigDecimal> values) {
      addCriterion("REFERENCE not in", values, "reference");
      return (Criteria) this;
    }

    public Criteria andReferenceBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("REFERENCE between", value1, value2, "reference");
      return (Criteria) this;
    }

    public Criteria andReferenceNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("REFERENCE not between", value1, value2, "reference");
      return (Criteria) this;
    }

    public Criteria andAdditionalreferenceIsNull() {
      addCriterion("ADDITIONALREFERENCE is null");
      return (Criteria) this;
    }

    public Criteria andAdditionalreferenceIsNotNull() {
      addCriterion("ADDITIONALREFERENCE is not null");
      return (Criteria) this;
    }

    public Criteria andAdditionalreferenceEqualTo(BigDecimal value) {
      addCriterion("ADDITIONALREFERENCE =", value, "additionalreference");
      return (Criteria) this;
    }

    public Criteria andAdditionalreferenceNotEqualTo(BigDecimal value) {
      addCriterion("ADDITIONALREFERENCE <>", value, "additionalreference");
      return (Criteria) this;
    }

    public Criteria andAdditionalreferenceGreaterThan(BigDecimal value) {
      addCriterion("ADDITIONALREFERENCE >", value, "additionalreference");
      return (Criteria) this;
    }

    public Criteria andAdditionalreferenceGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("ADDITIONALREFERENCE >=", value, "additionalreference");
      return (Criteria) this;
    }

    public Criteria andAdditionalreferenceLessThan(BigDecimal value) {
      addCriterion("ADDITIONALREFERENCE <", value, "additionalreference");
      return (Criteria) this;
    }

    public Criteria andAdditionalreferenceLessThanOrEqualTo(BigDecimal value) {
      addCriterion("ADDITIONALREFERENCE <=", value, "additionalreference");
      return (Criteria) this;
    }

    public Criteria andAdditionalreferenceIn(List<BigDecimal> values) {
      addCriterion("ADDITIONALREFERENCE in", values, "additionalreference");
      return (Criteria) this;
    }

    public Criteria andAdditionalreferenceNotIn(List<BigDecimal> values) {
      addCriterion("ADDITIONALREFERENCE not in", values, "additionalreference");
      return (Criteria) this;
    }

    public Criteria andAdditionalreferenceBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("ADDITIONALREFERENCE between", value1, value2, "additionalreference");
      return (Criteria) this;
    }

    public Criteria andAdditionalreferenceNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("ADDITIONALREFERENCE not between", value1, value2, "additionalreference");
      return (Criteria) this;
    }

    public Criteria andPaymentsequenceIsNull() {
      addCriterion("PAYMENTSEQUENCE is null");
      return (Criteria) this;
    }

    public Criteria andPaymentsequenceIsNotNull() {
      addCriterion("PAYMENTSEQUENCE is not null");
      return (Criteria) this;
    }

    public Criteria andPaymentsequenceEqualTo(String value) {
      addCriterion("PAYMENTSEQUENCE =", value, "paymentsequence");
      return (Criteria) this;
    }

    public Criteria andPaymentsequenceNotEqualTo(String value) {
      addCriterion("PAYMENTSEQUENCE <>", value, "paymentsequence");
      return (Criteria) this;
    }

    public Criteria andPaymentsequenceGreaterThan(String value) {
      addCriterion("PAYMENTSEQUENCE >", value, "paymentsequence");
      return (Criteria) this;
    }

    public Criteria andPaymentsequenceGreaterThanOrEqualTo(String value) {
      addCriterion("PAYMENTSEQUENCE >=", value, "paymentsequence");
      return (Criteria) this;
    }

    public Criteria andPaymentsequenceLessThan(String value) {
      addCriterion("PAYMENTSEQUENCE <", value, "paymentsequence");
      return (Criteria) this;
    }

    public Criteria andPaymentsequenceLessThanOrEqualTo(String value) {
      addCriterion("PAYMENTSEQUENCE <=", value, "paymentsequence");
      return (Criteria) this;
    }

    public Criteria andPaymentsequenceLike(String value) {
      addCriterion("PAYMENTSEQUENCE like", value, "paymentsequence");
      return (Criteria) this;
    }

    public Criteria andPaymentsequenceNotLike(String value) {
      addCriterion("PAYMENTSEQUENCE not like", value, "paymentsequence");
      return (Criteria) this;
    }

    public Criteria andPaymentsequenceIn(List<String> values) {
      addCriterion("PAYMENTSEQUENCE in", values, "paymentsequence");
      return (Criteria) this;
    }

    public Criteria andPaymentsequenceNotIn(List<String> values) {
      addCriterion("PAYMENTSEQUENCE not in", values, "paymentsequence");
      return (Criteria) this;
    }

    public Criteria andPaymentsequenceBetween(String value1, String value2) {
      addCriterion("PAYMENTSEQUENCE between", value1, value2, "paymentsequence");
      return (Criteria) this;
    }

    public Criteria andPaymentsequenceNotBetween(String value1, String value2) {
      addCriterion("PAYMENTSEQUENCE not between", value1, value2, "paymentsequence");
      return (Criteria) this;
    }

    public Criteria andOprPolicynumberIsNull() {
      addCriterion("OPR_POLICYNUMBER is null");
      return (Criteria) this;
    }

    public Criteria andOprPolicynumberIsNotNull() {
      addCriterion("OPR_POLICYNUMBER is not null");
      return (Criteria) this;
    }

    public Criteria andOprPolicynumberEqualTo(String value) {
      addCriterion("OPR_POLICYNUMBER =", value, "oprPolicynumber");
      return (Criteria) this;
    }

    public Criteria andOprPolicynumberNotEqualTo(String value) {
      addCriterion("OPR_POLICYNUMBER <>", value, "oprPolicynumber");
      return (Criteria) this;
    }

    public Criteria andOprPolicynumberGreaterThan(String value) {
      addCriterion("OPR_POLICYNUMBER >", value, "oprPolicynumber");
      return (Criteria) this;
    }

    public Criteria andOprPolicynumberGreaterThanOrEqualTo(String value) {
      addCriterion("OPR_POLICYNUMBER >=", value, "oprPolicynumber");
      return (Criteria) this;
    }

    public Criteria andOprPolicynumberLessThan(String value) {
      addCriterion("OPR_POLICYNUMBER <", value, "oprPolicynumber");
      return (Criteria) this;
    }

    public Criteria andOprPolicynumberLessThanOrEqualTo(String value) {
      addCriterion("OPR_POLICYNUMBER <=", value, "oprPolicynumber");
      return (Criteria) this;
    }

    public Criteria andOprPolicynumberLike(String value) {
      addCriterion("OPR_POLICYNUMBER like", value, "oprPolicynumber");
      return (Criteria) this;
    }

    public Criteria andOprPolicynumberNotLike(String value) {
      addCriterion("OPR_POLICYNUMBER not like", value, "oprPolicynumber");
      return (Criteria) this;
    }

    public Criteria andOprPolicynumberIn(List<String> values) {
      addCriterion("OPR_POLICYNUMBER in", values, "oprPolicynumber");
      return (Criteria) this;
    }

    public Criteria andOprPolicynumberNotIn(List<String> values) {
      addCriterion("OPR_POLICYNUMBER not in", values, "oprPolicynumber");
      return (Criteria) this;
    }

    public Criteria andOprPolicynumberBetween(String value1, String value2) {
      addCriterion("OPR_POLICYNUMBER between", value1, value2, "oprPolicynumber");
      return (Criteria) this;
    }

    public Criteria andOprPolicynumberNotBetween(String value1, String value2) {
      addCriterion("OPR_POLICYNUMBER not between", value1, value2, "oprPolicynumber");
      return (Criteria) this;
    }

    public Criteria andOprRiskunitnumberIsNull() {
      addCriterion("OPR_RISKUNITNUMBER is null");
      return (Criteria) this;
    }

    public Criteria andOprRiskunitnumberIsNotNull() {
      addCriterion("OPR_RISKUNITNUMBER is not null");
      return (Criteria) this;
    }

    public Criteria andOprRiskunitnumberEqualTo(String value) {
      addCriterion("OPR_RISKUNITNUMBER =", value, "oprRiskunitnumber");
      return (Criteria) this;
    }

    public Criteria andOprRiskunitnumberNotEqualTo(String value) {
      addCriterion("OPR_RISKUNITNUMBER <>", value, "oprRiskunitnumber");
      return (Criteria) this;
    }

    public Criteria andOprRiskunitnumberGreaterThan(String value) {
      addCriterion("OPR_RISKUNITNUMBER >", value, "oprRiskunitnumber");
      return (Criteria) this;
    }

    public Criteria andOprRiskunitnumberGreaterThanOrEqualTo(String value) {
      addCriterion("OPR_RISKUNITNUMBER >=", value, "oprRiskunitnumber");
      return (Criteria) this;
    }

    public Criteria andOprRiskunitnumberLessThan(String value) {
      addCriterion("OPR_RISKUNITNUMBER <", value, "oprRiskunitnumber");
      return (Criteria) this;
    }

    public Criteria andOprRiskunitnumberLessThanOrEqualTo(String value) {
      addCriterion("OPR_RISKUNITNUMBER <=", value, "oprRiskunitnumber");
      return (Criteria) this;
    }

    public Criteria andOprRiskunitnumberLike(String value) {
      addCriterion("OPR_RISKUNITNUMBER like", value, "oprRiskunitnumber");
      return (Criteria) this;
    }

    public Criteria andOprRiskunitnumberNotLike(String value) {
      addCriterion("OPR_RISKUNITNUMBER not like", value, "oprRiskunitnumber");
      return (Criteria) this;
    }

    public Criteria andOprRiskunitnumberIn(List<String> values) {
      addCriterion("OPR_RISKUNITNUMBER in", values, "oprRiskunitnumber");
      return (Criteria) this;
    }

    public Criteria andOprRiskunitnumberNotIn(List<String> values) {
      addCriterion("OPR_RISKUNITNUMBER not in", values, "oprRiskunitnumber");
      return (Criteria) this;
    }

    public Criteria andOprRiskunitnumberBetween(String value1, String value2) {
      addCriterion("OPR_RISKUNITNUMBER between", value1, value2, "oprRiskunitnumber");
      return (Criteria) this;
    }

    public Criteria andOprRiskunitnumberNotBetween(String value1, String value2) {
      addCriterion("OPR_RISKUNITNUMBER not between", value1, value2, "oprRiskunitnumber");
      return (Criteria) this;
    }

    public Criteria andOprClaimnumberIsNull() {
      addCriterion("OPR_CLAIMNUMBER is null");
      return (Criteria) this;
    }

    public Criteria andOprClaimnumberIsNotNull() {
      addCriterion("OPR_CLAIMNUMBER is not null");
      return (Criteria) this;
    }

    public Criteria andOprClaimnumberEqualTo(String value) {
      addCriterion("OPR_CLAIMNUMBER =", value, "oprClaimnumber");
      return (Criteria) this;
    }

    public Criteria andOprClaimnumberNotEqualTo(String value) {
      addCriterion("OPR_CLAIMNUMBER <>", value, "oprClaimnumber");
      return (Criteria) this;
    }

    public Criteria andOprClaimnumberGreaterThan(String value) {
      addCriterion("OPR_CLAIMNUMBER >", value, "oprClaimnumber");
      return (Criteria) this;
    }

    public Criteria andOprClaimnumberGreaterThanOrEqualTo(String value) {
      addCriterion("OPR_CLAIMNUMBER >=", value, "oprClaimnumber");
      return (Criteria) this;
    }

    public Criteria andOprClaimnumberLessThan(String value) {
      addCriterion("OPR_CLAIMNUMBER <", value, "oprClaimnumber");
      return (Criteria) this;
    }

    public Criteria andOprClaimnumberLessThanOrEqualTo(String value) {
      addCriterion("OPR_CLAIMNUMBER <=", value, "oprClaimnumber");
      return (Criteria) this;
    }

    public Criteria andOprClaimnumberLike(String value) {
      addCriterion("OPR_CLAIMNUMBER like", value, "oprClaimnumber");
      return (Criteria) this;
    }

    public Criteria andOprClaimnumberNotLike(String value) {
      addCriterion("OPR_CLAIMNUMBER not like", value, "oprClaimnumber");
      return (Criteria) this;
    }

    public Criteria andOprClaimnumberIn(List<String> values) {
      addCriterion("OPR_CLAIMNUMBER in", values, "oprClaimnumber");
      return (Criteria) this;
    }

    public Criteria andOprClaimnumberNotIn(List<String> values) {
      addCriterion("OPR_CLAIMNUMBER not in", values, "oprClaimnumber");
      return (Criteria) this;
    }

    public Criteria andOprClaimnumberBetween(String value1, String value2) {
      addCriterion("OPR_CLAIMNUMBER between", value1, value2, "oprClaimnumber");
      return (Criteria) this;
    }

    public Criteria andOprClaimnumberNotBetween(String value1, String value2) {
      addCriterion("OPR_CLAIMNUMBER not between", value1, value2, "oprClaimnumber");
      return (Criteria) this;
    }

    public Criteria andOprRecoverynumberIsNull() {
      addCriterion("OPR_RECOVERYNUMBER is null");
      return (Criteria) this;
    }

    public Criteria andOprRecoverynumberIsNotNull() {
      addCriterion("OPR_RECOVERYNUMBER is not null");
      return (Criteria) this;
    }

    public Criteria andOprRecoverynumberEqualTo(String value) {
      addCriterion("OPR_RECOVERYNUMBER =", value, "oprRecoverynumber");
      return (Criteria) this;
    }

    public Criteria andOprRecoverynumberNotEqualTo(String value) {
      addCriterion("OPR_RECOVERYNUMBER <>", value, "oprRecoverynumber");
      return (Criteria) this;
    }

    public Criteria andOprRecoverynumberGreaterThan(String value) {
      addCriterion("OPR_RECOVERYNUMBER >", value, "oprRecoverynumber");
      return (Criteria) this;
    }

    public Criteria andOprRecoverynumberGreaterThanOrEqualTo(String value) {
      addCriterion("OPR_RECOVERYNUMBER >=", value, "oprRecoverynumber");
      return (Criteria) this;
    }

    public Criteria andOprRecoverynumberLessThan(String value) {
      addCriterion("OPR_RECOVERYNUMBER <", value, "oprRecoverynumber");
      return (Criteria) this;
    }

    public Criteria andOprRecoverynumberLessThanOrEqualTo(String value) {
      addCriterion("OPR_RECOVERYNUMBER <=", value, "oprRecoverynumber");
      return (Criteria) this;
    }

    public Criteria andOprRecoverynumberLike(String value) {
      addCriterion("OPR_RECOVERYNUMBER like", value, "oprRecoverynumber");
      return (Criteria) this;
    }

    public Criteria andOprRecoverynumberNotLike(String value) {
      addCriterion("OPR_RECOVERYNUMBER not like", value, "oprRecoverynumber");
      return (Criteria) this;
    }

    public Criteria andOprRecoverynumberIn(List<String> values) {
      addCriterion("OPR_RECOVERYNUMBER in", values, "oprRecoverynumber");
      return (Criteria) this;
    }

    public Criteria andOprRecoverynumberNotIn(List<String> values) {
      addCriterion("OPR_RECOVERYNUMBER not in", values, "oprRecoverynumber");
      return (Criteria) this;
    }

    public Criteria andOprRecoverynumberBetween(String value1, String value2) {
      addCriterion("OPR_RECOVERYNUMBER between", value1, value2, "oprRecoverynumber");
      return (Criteria) this;
    }

    public Criteria andOprRecoverynumberNotBetween(String value1, String value2) {
      addCriterion("OPR_RECOVERYNUMBER not between", value1, value2, "oprRecoverynumber");
      return (Criteria) this;
    }

    public Criteria andOprAggregationcodeIsNull() {
      addCriterion("OPR_AGGREGATIONCODE is null");
      return (Criteria) this;
    }

    public Criteria andOprAggregationcodeIsNotNull() {
      addCriterion("OPR_AGGREGATIONCODE is not null");
      return (Criteria) this;
    }

    public Criteria andOprAggregationcodeEqualTo(String value) {
      addCriterion("OPR_AGGREGATIONCODE =", value, "oprAggregationcode");
      return (Criteria) this;
    }

    public Criteria andOprAggregationcodeNotEqualTo(String value) {
      addCriterion("OPR_AGGREGATIONCODE <>", value, "oprAggregationcode");
      return (Criteria) this;
    }

    public Criteria andOprAggregationcodeGreaterThan(String value) {
      addCriterion("OPR_AGGREGATIONCODE >", value, "oprAggregationcode");
      return (Criteria) this;
    }

    public Criteria andOprAggregationcodeGreaterThanOrEqualTo(String value) {
      addCriterion("OPR_AGGREGATIONCODE >=", value, "oprAggregationcode");
      return (Criteria) this;
    }

    public Criteria andOprAggregationcodeLessThan(String value) {
      addCriterion("OPR_AGGREGATIONCODE <", value, "oprAggregationcode");
      return (Criteria) this;
    }

    public Criteria andOprAggregationcodeLessThanOrEqualTo(String value) {
      addCriterion("OPR_AGGREGATIONCODE <=", value, "oprAggregationcode");
      return (Criteria) this;
    }

    public Criteria andOprAggregationcodeLike(String value) {
      addCriterion("OPR_AGGREGATIONCODE like", value, "oprAggregationcode");
      return (Criteria) this;
    }

    public Criteria andOprAggregationcodeNotLike(String value) {
      addCriterion("OPR_AGGREGATIONCODE not like", value, "oprAggregationcode");
      return (Criteria) this;
    }

    public Criteria andOprAggregationcodeIn(List<String> values) {
      addCriterion("OPR_AGGREGATIONCODE in", values, "oprAggregationcode");
      return (Criteria) this;
    }

    public Criteria andOprAggregationcodeNotIn(List<String> values) {
      addCriterion("OPR_AGGREGATIONCODE not in", values, "oprAggregationcode");
      return (Criteria) this;
    }

    public Criteria andOprAggregationcodeBetween(String value1, String value2) {
      addCriterion("OPR_AGGREGATIONCODE between", value1, value2, "oprAggregationcode");
      return (Criteria) this;
    }

    public Criteria andOprAggregationcodeNotBetween(String value1, String value2) {
      addCriterion("OPR_AGGREGATIONCODE not between", value1, value2, "oprAggregationcode");
      return (Criteria) this;
    }

    public Criteria andPorIdIsNull() {
      addCriterion("POR_ID is null");
      return (Criteria) this;
    }

    public Criteria andPorIdIsNotNull() {
      addCriterion("POR_ID is not null");
      return (Criteria) this;
    }

    public Criteria andPorIdEqualTo(BigDecimal value) {
      addCriterion("POR_ID =", value, "porId");
      return (Criteria) this;
    }

    public Criteria andPorIdNotEqualTo(BigDecimal value) {
      addCriterion("POR_ID <>", value, "porId");
      return (Criteria) this;
    }

    public Criteria andPorIdGreaterThan(BigDecimal value) {
      addCriterion("POR_ID >", value, "porId");
      return (Criteria) this;
    }

    public Criteria andPorIdGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("POR_ID >=", value, "porId");
      return (Criteria) this;
    }

    public Criteria andPorIdLessThan(BigDecimal value) {
      addCriterion("POR_ID <", value, "porId");
      return (Criteria) this;
    }

    public Criteria andPorIdLessThanOrEqualTo(BigDecimal value) {
      addCriterion("POR_ID <=", value, "porId");
      return (Criteria) this;
    }

    public Criteria andPorIdIn(List<BigDecimal> values) {
      addCriterion("POR_ID in", values, "porId");
      return (Criteria) this;
    }

    public Criteria andPorIdNotIn(List<BigDecimal> values) {
      addCriterion("POR_ID not in", values, "porId");
      return (Criteria) this;
    }

    public Criteria andPorIdBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("POR_ID between", value1, value2, "porId");
      return (Criteria) this;
    }

    public Criteria andPorIdNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("POR_ID not between", value1, value2, "porId");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table BRAXTS_CFG.OPENITEMREFERENCE
   *
   * @mbggenerated do_not_delete_during_merge Tue Jun 17 15:34:18 COT 2014
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table BRAXTS_CFG.OPENITEMREFERENCE
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}