package com.cardif.satelite.model.datamart;

import java.io.Serializable;

public class OdsSocioMm implements Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column USER_DM_ODS.ODS_SOCIO_MM.COD_SOCIO
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  private String codSocio;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column USER_DM_ODS.ODS_SOCIO_MM.NBR_SOCIO
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  private String nbrSocio;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column USER_DM_ODS.ODS_SOCIO_MM.RUC
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  private String ruc;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column USER_DM_ODS.ODS_SOCIO_MM.INDUSTRIA
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  private String industria;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column USER_DM_ODS.ODS_SOCIO_MM.DIR_SOCIO
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  private String dirSocio;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column USER_DM_ODS.ODS_SOCIO_MM.COD_SOCIO
   *
   * @return the value of USER_DM_ODS.ODS_SOCIO_MM.COD_SOCIO
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  public String getCodSocio() {
    return codSocio;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column USER_DM_ODS.ODS_SOCIO_MM.COD_SOCIO
   *
   * @param codSocio
   *          the value for USER_DM_ODS.ODS_SOCIO_MM.COD_SOCIO
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  public void setCodSocio(String codSocio) {
    this.codSocio = codSocio == null ? null : codSocio.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column USER_DM_ODS.ODS_SOCIO_MM.NBR_SOCIO
   *
   * @return the value of USER_DM_ODS.ODS_SOCIO_MM.NBR_SOCIO
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  public String getNbrSocio() {
    return nbrSocio;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column USER_DM_ODS.ODS_SOCIO_MM.NBR_SOCIO
   *
   * @param nbrSocio
   *          the value for USER_DM_ODS.ODS_SOCIO_MM.NBR_SOCIO
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  public void setNbrSocio(String nbrSocio) {
    this.nbrSocio = nbrSocio == null ? null : nbrSocio.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column USER_DM_ODS.ODS_SOCIO_MM.RUC
   *
   * @return the value of USER_DM_ODS.ODS_SOCIO_MM.RUC
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  public String getRuc() {
    return ruc;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column USER_DM_ODS.ODS_SOCIO_MM.RUC
   *
   * @param ruc
   *          the value for USER_DM_ODS.ODS_SOCIO_MM.RUC
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  public void setRuc(String ruc) {
    this.ruc = ruc == null ? null : ruc.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column USER_DM_ODS.ODS_SOCIO_MM.INDUSTRIA
   *
   * @return the value of USER_DM_ODS.ODS_SOCIO_MM.INDUSTRIA
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  public String getIndustria() {
    return industria;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column USER_DM_ODS.ODS_SOCIO_MM.INDUSTRIA
   *
   * @param industria
   *          the value for USER_DM_ODS.ODS_SOCIO_MM.INDUSTRIA
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  public void setIndustria(String industria) {
    this.industria = industria == null ? null : industria.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column USER_DM_ODS.ODS_SOCIO_MM.DIR_SOCIO
   *
   * @return the value of USER_DM_ODS.ODS_SOCIO_MM.DIR_SOCIO
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  public String getDirSocio() {
    return dirSocio;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column USER_DM_ODS.ODS_SOCIO_MM.DIR_SOCIO
   *
   * @param dirSocio
   *          the value for USER_DM_ODS.ODS_SOCIO_MM.DIR_SOCIO
   *
   * @mbggenerated Tue Feb 04 14:23:56 COT 2014
   */
  public void setDirSocio(String dirSocio) {
    this.dirSocio = dirSocio == null ? null : dirSocio.trim();
  }
}