package com.cardif.satelite.acsele.dao;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import com.cardif.satelite.acsele.bean.ConsultaOpenItem;
import com.cardif.satelite.model.acsele.OpenItem;
import com.cardif.satelite.model.acsele.OpenItemExample;

public interface OpenItemMapper {

  final String LISTA_OPENITEM = " SELECT * FROM OPENITEM " + " WHERE OPENITEMID IN (SELECT OPENITEMID "
      + " FROM openitemreference WHERE opr_policynumber = #{nroCertificado})AND DTY_ID = 513 AND STATUS = 'applied' and opm_substatus = 'TotallyPaid' ORDER BY DOCDATE DESC";

  final String LISTA_OPENITEM_POLICYID = " SELECT DISTINCT POL.POLICYCOMMERCIALNBINPUT AS NUM_POLIZA,  " + "  DECODE(OP.DTY_ID, 513, 'Cuota emitida', 534, 'Cuota pagada', 535, 'Devolucion') AS TIPO, "
      + "  OP.DOCDATE AS FECHA, " + "  OP.DUEDATE AS FEC_VENC, " + "  ROUND(OP.AMOUNT,2) AS MONTO,  " + "  CUR.CCY_ISOCODE AS MONEDA " + "  FROM BRAXTS_CFG.CCOPTPPOLICY POL  "
      + "  INNER JOIN BRAXTS_CFG.AGREGATEDPOLICY APOL  " + "  ON POL.STATIC = APOL.AGREGATEDPOLICYID  " + "  INNER JOIN BRAXTS_CFG.POLICYDCO PDCO  "
      + "  ON APOL.AGREGATEDPOLICYID = PDCO.AGREGATEDOBJECTID  " + "  INNER JOIN BRAXTS_CFG.OPENITEMREFERENCE OPR ON PDCO.AGREGATEDOBJECTID = OPR.POLICYID  "
      + "  INNER JOIN BRAXTS_CFG.OPENITEM OP ON OPR.OPENITEMID = OP.OPENITEMID  " + "  INNER JOIN CURRENCY CUR " + "  ON OP.CURRENCYID = CUR.CURRENCYID " + "  WHERE PDCO.STATUS = 2  "
      + "  AND (OP.DTY_ID IS NULL OR OP.DTY_ID = 513 OR OP.DTY_ID = 535 OR OP.DTY_ID = 534)  " + "  AND POL.STATIC = #{idPoliza} " + "  ORDER BY OP.DOCDATE DESC ";

  @Select(LISTA_OPENITEM)
  @ResultMap(value = "BaseResultMap")
  List<OpenItem> listar(@Param("nroCertificado") String nroCertificado);

  @Select(LISTA_OPENITEM_POLICYID)
  @ResultMap(value = "ConsultaResultMap")
  List<ConsultaOpenItem> selectListaOpenItems(@Param("idPoliza") BigDecimal idPoliza);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEM
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  int countByExample(OpenItemExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEM
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  int deleteByExample(OpenItemExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEM
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  int deleteByPrimaryKey(BigDecimal openitemid);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEM
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  int insert(OpenItem record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEM
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  int insertSelective(OpenItem record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEM
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  List<OpenItem> selectByExample(OpenItemExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEM
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  OpenItem selectByPrimaryKey(BigDecimal openitemid);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEM
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  int updateByExampleSelective(@Param("record") OpenItem record, @Param("example") OpenItemExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEM
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  int updateByExample(@Param("record") OpenItem record, @Param("example") OpenItemExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEM
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  int updateByPrimaryKeySelective(OpenItem record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table BRAXTS_CFG.OPENITEM
   *
   * @mbggenerated Tue Jun 17 15:34:18 COT 2014
   */
  int updateByPrimaryKey(OpenItem record);
}